### ISSUE TITLE
ProgressDialog invisible on Theme_HoloEverywhereLight_Sherlock 

### ISSUE THREAD

**Issue by ghost** [Prototik/HoloEverywhere#10]
The progress indicator on a ProgressDialog is invisible when using Theme_HoloEverywhereLight_Sherlock on an older device (Emulator:2.2, ADP1:1.6).

For now i use a ContextThemeWrapper with Theme_HoloEverywhereDark_Sherlock, but that doesn't look to nice...

But many thanks anyway for this very usefull project!

**Comment by Prototik** [comment]
890515f23ce744fc6957be19e9bef98c6367af80
