### ISSUE TITLE
Null Pointer Exception on Start of Demo + ForceCloses on Spinner/List Settings

### ISSUE THREAD

**Issue by MFlisar** [Prototik/HoloEverywhere#100]
I'm using a Sony Xperia Sola 2.3.7

I get a Null Pointer Exception on App start...  Because the Transaction in SHoloDemoActivity is null.
I fixed the error with following code adjustments... I replaced the lines 39 and 40 in SHoloDemoActivity...  So I can start the app at least..

```
if (ft == null)
    ft = getSupportFragmentManager().beginTransaction().disallowAddToBackStack();

ft.replace(android.R.id.content, fragment);
ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE);
ft.commit();
```

But now, Spinner and List Settings force close the app... The Spinner produces following error:

```
Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x12
```

The same happens to me when trying to create a AlertDialog with a list...

**Comment by Prototik** [comment]
FT: you compile HE demo with standart abs, should use fork.
Lisr: duplicate #98, already fixed

**Comment by MFlisar** [comment]
The Example in the other post is working... But I don't know what you want to tell me... Don't know what you mean with "standard abs".... I tried the last dev version, because the changes you postet in the other post are not yet in the branch, but that doesn't help either... Maybe you can explain what you mean...

**Comment by Prototik** [comment]
Standart ABS - from Jake repo. You should use fork from Christophe repo. When will be release 4.2.0 ABS - we are don't need to fork more.

**Comment by MFlisar** [comment]
Oh, ok. Thank you
