### ISSUE TITLE
OptionsMenu spinner without checkbox

### ISSUE THREAD

**Issue by 2mas29** [Prototik/HoloEverywhere#104]
Hi, I'm trying to create a actionbar with a spinner, but it shows the items with a checkbox. What am I doing wrong? I Don't want the checkboxes shown.

<item
android:id="@+id/menu_spinner"
android:actionViewClass="android.widget.Spinner"
android:showAsAction="always"/>

@Override
public boolean onCreateOptionsMenu(Menu menu) {
    getSupportMenuInflater().inflate(R.menu.spinner_menu, menu);
    Spinner spinner = (Spinner) menu.findItem( R.id.menu_spinner ).getActionView();
    spinner.setAdapter(ArrayAdapter.createFromResource(this, R.array.locations, android.R.layout. simple_spinner_dropdown_item));
        return true;
}

**Comment by Prototik** [comment]
android.R.layout.simple_spinner_dropdown_item - CheckedTextView, use another layout.
