### ISSUE TITLE
NumberPickerPreference

### ISSUE THREAD

**Issue by saik0** [Prototik/HoloEverywhere#105]
Do you guys want to implement a NumberPickerPreference or prefer to keep it strictly backport?

I ask because I'm using one I've created in my project, would not mind it swimming upstream.

**Comment by saik0** [comment]
@Prototik I noticed you assigned it to yourself, I was asking if you want me to send a pull request with my own implementation or if this project should stay a strict AOSP backport only. I would not be surprised if one day there exists such a class in AOSP, not that we should not do it, just that we should do it very carefully.

**Comment by Prototik** [comment]
It's will be custom impl. If you have good numberpickerpreference - you may send pull request, of course. But not fact, what it will be accepted:)

**Comment by saik0** [comment]
OK. I will modify what I've got and send a PR soon. I will use com.WazaBe.HoloEverywhere.external namespace for anything not ported from AOSP, we should also prefix class names with something but HoloEverywhereNumberPickerPreference just sounds ridiculous. Thoughts?

**Comment by Prototik** [comment]
No.
Use default preference package. And name then as NumberPickerPreference.

**Comment by saik0** [comment]
The problem with this is if there is a NumberPickerPreference in AOSP in the future it will have a different implementation. Then porting the upstream one into HoloEverywhere breaks user's existing code. I still think we should use a different namespace and class names so we can deprecate gracefully.

**Comment by Prototik** [comment]
When NPP in AOSP will be created - we a port new NPP with save compat. Only standart preference package.
