### ISSUE TITLE
Spinner => Strange scrolling behaviour + missing items

### ISSUE THREAD

**Issue by MFlisar** [Prototik/HoloEverywhere#109]
Since you changed the spinner to DropDown mode, scrolling does not work proberly... The list is always jumping back to the area where the current item is if you scroll more than once...

Second. using the spinner in a AlertDialog sometimes leads to missing items... If the Dialog also contains a Edit Text, the spinner contains all items only if I click into the Edit Text and the on screen keyboard is displayed, but after ending edit mode of Edit Text, the spinner data is again not complete...

My only workaround is, since before API 11 spinner mode in XML does not work, removing the Spinner from layout after inflating the layout and replace it with a new spinner, that set's the spinner mode to Dialog Mode in Constructor...

So by the way, is there another solution to set spinner mode?

**Comment by Prototik** [comment]
@prom85 spinner mode in XML does not work?
So do not lie.
You may change style with override spinner mode for all spinners, or only one spinner in layout:

```
<style name="MySpinner" parent="@style/Holo.Spinner">
  <item name="spinnerMode">dialog</item>
</style>
```

```
<Spinner ...
holo:spinnerMode="dialog" />
```

**Comment by MFlisar** [comment]
Ok, that's true, I don't know why it didn't work, I tried it more than once that way :-/

**Comment by Prototik** [comment]
Perhaps you used android:spinnerMode, which Spinner of HE does not work.
