### ISSUE TITLE
Using FragmentActivity & MapActivity with HE

### ISSUE THREAD

**Issue by tverona** [Prototik/HoloEverywhere#114]
Hello,

This is not necessarily an issue - more of a usage question: I am currently using FragmentActivity (for the LoaderManager) as well as MapActivity in my app. My understanding is that we need to derive from HE's implementation of S*Activity. However, I did not find the corresponding implementations for FragmentActivity & MapActivity. Is this something that is missing from HE or do I not need to worry about it? Also, my understanding is that my Application class also needs to derive from HE's Application class. Is this correct?

Finally, for my own understanding, what is the purpose of implementing the HE-specific class hierarchies for Activity/Fragment? Is it to enable loading the Roboto fonts for TextViews?

BTW, this is a great project! Thank you very much!

Cheers,
Tomer

**Comment by Prototik** [comment]
(S)Activity/(S)ListActivity/(S)ExpandableListActivity/(S)PreferenceActivity a = ...;
Log.v("TAG", (a instanceof FragmentActivity) + "");

> true

Well, MapActivity... I will be think :)
