### ISSUE TITLE
Prototik leave?

### ISSUE THREAD

**Issue by Prototik** [Prototik/HoloEverywhere#119]
Hi, my brothers! This is my appeal to you.
I have some sad news. I will have to suspend developing HE. This is due to personal problems, but I will try to solve them. I will be absent a month, maybe more. Although maybe I will come back in a couple of days, but it hardly. I hope the community will not forget me and HoloEverywhere overall. Well, I hope Christophe don't forget me ;) I'm not sure that I can check my email ...

А, хер с ним, я вообще не знаю, что может дать 16-и летний подросток этому проекту, но статистика меня добивает канеш :) Пойду немного печень помучаю, заканало меня это дело...

**Comment by indieboyalex** [comment]
You will be sorely missed. Hope it's nothing serious.

**Comment by ChristopheVersieux** [comment]
As the main contributor to the lib, you will never be forgotten ;-)

I really hope these problems are not too serious and you will be able to get over it!

Once again, thanks a lot and good luck.

**Comment by kevsmt** [comment]
Thanks alot for the hard work! ;)

**Comment by ghost** [comment]
@Prototik Thanks for everything. Get back soon.

**Comment by CiTuX** [comment]
Thanks for your good work, I hope you can solve your problems soon.

**Comment by Prototik** [comment]
I come back! :)

**Comment by StenaviN** [comment]
Glad to hear!

```
~ Sent from HTC Desire ~
```

10.10.2012 12:28 пользователь "Sergey" notifications@github.com написал:
