### ISSUE TITLE
InflateException when adding ShareActionProvider

### ISSUE THREAD

**Issue by bondjpf** [Prototik/HoloEverywhere#123]
When I add this line to my xml menu I have an InflateException:   android:actionProviderClass="com.actionbarsherlock.widget.ShareActionProvider"

Menu:

<menu 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:holo="http://schemas.android.com/apk/res-auto">

```
<item android:id="@+id/menu_share"
    android:showAsAction="always"
    android:title="@string/share_subject"
    android:icon="@drawable/ic_social_share_light"
    android:actionProviderClass="com.actionbarsherlock.widget.ShareActionProvider"
    />
```

</menu>

Code:

```
@Override
public boolean onCreateOptionsMenu(Menu menu) {
    super.onCreateOptionsMenu(menu); 

    MenuInflater inflater = getSupportMenuInflater();

    inflater.inflate(R.menu.share_action_provider_light, menu);
    MenuItem actionItem = menu.findItem(R.id.menu_share);
    ShareActionProvider actionProvider = (ShareActionProvider) actionItem.getActionProvider();
    actionProvider.setShareHistoryFileName(ShareActionProvider.DEFAULT_SHARE_HISTORY_FILE_NAME);
    actionProvider.setOnShareTargetSelectedListener(this);

    Intent shareIntent = new Intent(Intent.ACTION_SEND);
    shareIntent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET);
    shareIntent.setType("text/plain");
    shareIntent.putExtra(Intent.EXTRA_TEXT,getString(R.string.listening)+" "+ descr+
        " "+getString(R.string.using)+" "+
            Html.fromHtml(getResources().getString(R.string.app_link))+" "+
        getString(R.string.android));
    shareIntent.putExtra(Intent.EXTRA_SUBJECT,getString(R.string.share_subject));

    actionProvider.setShareIntent(shareIntent);

    return true;
}
```

This is my logcat:

10-05 15:40:12.449: E/AndroidRuntime(1746): FATAL EXCEPTION: main
10-05 15:40:12.449: E/AndroidRuntime(1746): android.view.InflateException: Binary XML file line #26: Error inflating class <unknown>
10-05 15:40:12.449: E/AndroidRuntime(1746):     at android.view.LayoutInflater.createView(LayoutInflater.java:606)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at com.WazaBe.HoloEverywhere.LayoutInflater.onCreateView(LayoutInflater.java:143)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:653)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:678)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at com.actionbarsherlock.widget.ActivityChooserView.<init>(ActivityChooserView.java:229)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at com.actionbarsherlock.widget.ActivityChooserView.<init>(ActivityChooserView.java:202)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at com.actionbarsherlock.widget.ActivityChooserView.<init>(ActivityChooserView.java:192)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at com.actionbarsherlock.widget.ShareActionProvider.onCreateActionView(ShareActionProvider.java:164)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at com.actionbarsherlock.internal.view.ActionProviderWrapper.onCreateActionView(ActionProviderWrapper.java:23)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at com.android.internal.view.menu.MenuItemImpl.getActionView(MenuItemImpl.java:574)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at com.android.internal.view.menu.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:154)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at com.android.internal.view.menu.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:403)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at com.android.internal.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1043)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at com.android.internal.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:87)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at com.android.internal.view.menu.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:187)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at com.android.internal.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:244)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at com.android.internal.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:941)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at com.android.internal.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:964)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:431)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at com.android.internal.policy.impl.PhoneWindow.invalidatePanelMenu(PhoneWindow.java:739)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:2833)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at android.os.Handler.handleCallback(Handler.java:605)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at android.os.Handler.dispatchMessage(Handler.java:92)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at android.os.Looper.loop(Looper.java:137)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at android.app.ActivityThread.main(ActivityThread.java:4575)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at java.lang.reflect.Method.invokeNative(Native Method)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at java.lang.reflect.Method.invoke(Method.java:511)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at dalvik.system.NativeStart.main(Native Method)
10-05 15:40:12.449: E/AndroidRuntime(1746): Caused by: java.lang.reflect.InvocationTargetException
10-05 15:40:12.449: E/AndroidRuntime(1746):     at java.lang.reflect.Constructor.constructNative(Native Method)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at android.view.LayoutInflater.createView(LayoutInflater.java:586)
10-05 15:40:12.449: E/AndroidRuntime(1746):     ... 32 more
10-05 15:40:12.449: E/AndroidRuntime(1746): Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f01000f a=-1}
10-05 15:40:12.449: E/AndroidRuntime(1746):     at android.content.res.Resources.loadDrawable(Resources.java:1957)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at android.view.View.<init>(View.java:2785)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at android.view.ViewGroup.<init>(ViewGroup.java:385)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at android.widget.FrameLayout.<init>(FrameLayout.java:99)
10-05 15:40:12.449: E/AndroidRuntime(1746):     at android.widget.FrameLayout.<init>(FrameLayout.java:95)
10-05 15:40:12.449: E/AndroidRuntime(1746):     ... 35 more

**Comment by Prototik** [comment]
See #603 bug in ABS tracker

**Comment by paulnicholson** [comment]
This seems to be an issue with HoloEverywhere, we were getting this exception with the Holo.Theme.Sherlock theme until we switched to the base ABS theme.
