### ISSUE TITLE
Preference Screen

### ISSUE THREAD

**Issue by ghost** [Prototik/HoloEverywhere#124]
I am having a problem converting my Preferences Screen to HoloEverywhere.  I have updated my source with the following imports:
import com.WazaBe.HoloEverywhere.preference.EditTextPreference;
import com.WazaBe.HoloEverywhere.preference.Preference;
import com.WazaBe.HoloEverywhere.preference.Preference.OnPreferenceChangeListener;
import com.WazaBe.HoloEverywhere.preference.Preference.OnPreferenceClickListener;
import com.WazaBe.HoloEverywhere.preference.PreferenceManager;
import com.WazaBe.HoloEverywhere.preference.PreferenceScreen;
import com.WazaBe.HoloEverywhere.widget.EditText;

My Activity is defined as:
public class PrefsGeneralActivity extends com.WazaBe.HoloEverywhere.sherlock.SPreferenceActivity

However, when running, I get the following crash:
10-05 12:21:07.072: E/AndroidRuntime(14176): java.lang.RuntimeException: Unable to start activity ComponentInfo{app.Appstervan/app.Appstervan.PrefsGeneralActivity}: java.lang.ClassCastException: android.widget.ListView
10-05 12:21:07.072: E/AndroidRuntime(14176):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1872)
10-05 12:21:07.072: E/AndroidRuntime(14176):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1893)
10-05 12:21:07.072: E/AndroidRuntime(14176):    at android.app.ActivityThread.access$1500(ActivityThread.java:135)
10-05 12:21:07.072: E/AndroidRuntime(14176):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1054)
10-05 12:21:07.072: E/AndroidRuntime(14176):    at android.os.Handler.dispatchMessage(Handler.java:99)
10-05 12:21:07.072: E/AndroidRuntime(14176):    at android.os.Looper.loop(Looper.java:150)
10-05 12:21:07.072: E/AndroidRuntime(14176):    at android.app.ActivityThread.main(ActivityThread.java:4385)
10-05 12:21:07.072: E/AndroidRuntime(14176):    at java.lang.reflect.Method.invokeNative(Native Method)
10-05 12:21:07.072: E/AndroidRuntime(14176):    at java.lang.reflect.Method.invoke(Method.java:507)
10-05 12:21:07.072: E/AndroidRuntime(14176):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
10-05 12:21:07.072: E/AndroidRuntime(14176):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
10-05 12:21:07.072: E/AndroidRuntime(14176):    at dalvik.system.NativeStart.main(Native Method)
10-05 12:21:07.072: E/AndroidRuntime(14176): Caused by: java.lang.ClassCastException: android.widget.ListView
10-05 12:21:07.072: E/AndroidRuntime(14176):    at com.WazaBe.HoloEverywhere.app.ListActivity.onContentChanged(ListActivity.java:62)
10-05 12:21:07.072: E/AndroidRuntime(14176):    at com.WazaBe.HoloEverywhere.preference.PreferenceActivity.onContentChanged(PreferenceActivity.java:574)
10-05 12:21:07.072: E/AndroidRuntime(14176):    at com.actionbarsherlock.internal.ActionBarSherlockCompat.setContentView(ActionBarSherlockCompat.java:861)
10-05 12:21:07.072: E/AndroidRuntime(14176):    at com.WazaBe.HoloEverywhere.sherlock.SPreferenceActivity.setContentView(SPreferenceActivity.java:248)
10-05 12:21:07.072: E/AndroidRuntime(14176):    at com.WazaBe.HoloEverywhere.preference.PreferenceActivity.onCreate(PreferenceActivity.java:584)
10-05 12:21:07.072: E/AndroidRuntime(14176):    at app.Appstervan.Mail.PrefsGeneralActivity.onCreate(PrefsGeneralActivity.java:47)
10-05 12:21:07.072: E/AndroidRuntime(14176):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1072)
10-05 12:21:07.072: E/AndroidRuntime(14176):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1836)
10-05 12:21:07.072: E/AndroidRuntime(14176):    ... 11 more

I have not made any updates to the XML.  Should I?  Or is there anything else I should try?  I am currently using the Dev version which fixes another problem I had.

Thanks!

**Comment by bondjpf** [comment]
Your preferences xml file shold start like this:

<?xml version="1.0" encoding="utf-8"?>
< PreferenceScreen 
      xmlns:holo="http://schemas.android.com/apk/res-auto">

I don't think this would be enough to get it going but it's a start. Other's more experienced than I can say more...

**Comment by ghost** [comment]
That is what I have...here is a snippet of what I have:
<?xml version="1.0" encoding="utf-8"?>
<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android" >

```
<PreferenceCategory
    android:key="settings"
    android:title="Settings" >
    <EditTextPreference
        android:defaultValue="25"
        android:dialogMessage="Number to fetch."
        android:dialogTitle="Number to Fetch"
        android:key="emailsToFetch"
        android:maxLength="2"
        android:numeric="integer"
        android:singleLine="true"
        android:summary="Number to Fetch"
        android:title="Number to Fetch" />

    <CheckBoxPreference
        android:defaultValue="true"
        android:key="showDate"
        android:title="Show Date" />

    <Preference
        android:key="Data"
        android:summary="Enter Data"
        android:title="Email Data" />
</PreferenceCategory>
<PreferenceCategory
    android:key="other_settings"
    android:title="Other Settings" >
    <CheckBoxPreference
        android:defaultValue="true"
        android:key="enableStuff"
        android:title="Stuff" />

    <RingtonePreference
        android:dependency="enableStuff"
        android:key="stuffSound"
        android:ringtoneType="notification"
        android:showDefault="true"
        android:showSilent="true"
        android:summary="Select  Sound"
        android:title="Sound" />

    <app.Appstervan.TimePreference
        android:name="Start time"
        android:dependency="notiStuff"
        android:dialogLayout="@layout/time_preference"
        android:key="notiStartTime"
        android:summary=""
        android:title="Start notification time" />
</PreferenceCategory>
```

</PreferenceScreen>

**Comment by Prototik** [comment]
See demo, bro:)
You should use holo: prefix instead android:

**Comment by ghost** [comment]
Thanks for the tip.  I did look at the demo, but obviously not very well.  Next time I'll search!  Have a great weekend...
