### ISSUE TITLE
AlertDialog.setAdapter not working on 2.3.3-3.0

### ISSUE THREAD

**Issue by ru-nekit-android** [Prototik/HoloEverywhere#125]
I use AlertDialog.setAdapter with custom list item resource
AlertDialog.Builder builder = new AlertDialog.Builder(getSherlockActivity());
        builder.setTitle("Upload a photo");
        ArrayAdapter<String> adapter = new ArrayAdapter<String>(getSherlockActivity(), R.layout.alert_dialog_list_item); //R.layout.alert_dialog_list_item - custom list item resource
        adapter.add("1");
        adapter.add("2");
        adapter.add("3");
        builder.setAdapter(adapter, new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int which) {

```
        }
    });
    builder.show();
```

Source of custom list item resource (like android.R.layout.simple_list_item1)
<?xml version="1.0" encoding="utf-8"?>
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@android:id/text1"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:textAppearance="?android:attr/textAppearanceListItemSmall"
    android:gravity="center_vertical"
    android:paddingLeft="?android:attr/listPreferredItemPaddingLeft"
    android:paddingRight="?android:attr/listPreferredItemPaddingRight"
    android:minHeight="?android:attr/listPreferredItemHeightSmall"
/>

I get error on 2.3.3 -3.0 on 4.0 - all fine. With  android.R.layout.simple_list_item1 all work fine
10-06 16:28:52.809: E/AndroidRuntime(336): FATAL EXCEPTION: main
10-06 16:28:52.809: E/AndroidRuntime(336): android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.view.LayoutInflater.createView(LayoutInflater.java:518)
10-06 16:28:52.809: E/AndroidRuntime(336):  at com.WazaBe.HoloEverywhere.LayoutInflater.onCreateView(LayoutInflater.java:140)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.view.LayoutInflater.inflate(LayoutInflater.java:386)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:332)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.widget.ArrayAdapter.getView(ArrayAdapter.java:323)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.widget.AbsListView.obtainView(AbsListView.java:1430)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.widget.ListView.measureHeightOfChildren(ListView.java:1216)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.widget.ListView.onMeasure(ListView.java:1127)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.view.View.measure(View.java:8313)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
10-06 16:28:52.809: E/AndroidRuntime(336):  at com.WazaBe.HoloEverywhere.widget.LinearLayout.measureChildWithMargins(LinearLayout.java:233)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1017)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.widget.LinearLayout.measureVertical(LinearLayout.java:386)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.widget.LinearLayout.onMeasure(LinearLayout.java:309)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.view.View.measure(View.java:8313)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
10-06 16:28:52.809: E/AndroidRuntime(336):  at com.WazaBe.HoloEverywhere.widget.LinearLayout.measureChildWithMargins(LinearLayout.java:233)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1017)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.widget.LinearLayout.measureVertical(LinearLayout.java:386)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.widget.LinearLayout.onMeasure(LinearLayout.java:309)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.view.View.measure(View.java:8313)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.view.View.measure(View.java:8313)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.view.View.measure(View.java:8313)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.view.ViewRoot.performTraversals(ViewRoot.java:839)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.view.ViewRoot.handleMessage(ViewRoot.java:1859)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.os.Handler.dispatchMessage(Handler.java:99)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.os.Looper.loop(Looper.java:123)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.app.ActivityThread.main(ActivityThread.java:3683)
10-06 16:28:52.809: E/AndroidRuntime(336):  at java.lang.reflect.Method.invokeNative(Native Method)
10-06 16:28:52.809: E/AndroidRuntime(336):  at java.lang.reflect.Method.invoke(Method.java:507)
10-06 16:28:52.809: E/AndroidRuntime(336):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
10-06 16:28:52.809: E/AndroidRuntime(336):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
10-06 16:28:52.809: E/AndroidRuntime(336):  at dalvik.system.NativeStart.main(Native Method)
10-06 16:28:52.809: E/AndroidRuntime(336): Caused by: java.lang.reflect.InvocationTargetException
10-06 16:28:52.809: E/AndroidRuntime(336):  at java.lang.reflect.Constructor.constructNative(Native Method)
10-06 16:28:52.809: E/AndroidRuntime(336):  at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.view.LayoutInflater.createView(LayoutInflater.java:505)
10-06 16:28:52.809: E/AndroidRuntime(336):  ... 38 more
10-06 16:28:52.809: E/AndroidRuntime(336): Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x2
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.view.View.<init>(View.java:1957)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.widget.TextView.<init>(TextView.java:344)
10-06 16:28:52.809: E/AndroidRuntime(336):  at android.widget.TextView.<init>(TextView.java:337)
10-06 16:28:52.809: E/AndroidRuntime(336):  at com.WazaBe.HoloEverywhere.widget.TextView.<init>(TextView.java:24)
10-06 16:28:52.809: E/AndroidRuntime(336):  ... 41 more

**Comment by Prototik** [comment]
Of course, listPrefferedItemPaddingLeft and other attrs avaiable since 3.0. Use it without android package prefix.
