### ISSUE TITLE
MultiSelectListPreference - cannot set preferences

### ISSUE THREAD

**Issue by indieboyalex** [Prototik/HoloEverywhere#130]
This is basically https://github.com/ChristopheVersieux/HoloEverywhere/issues/128 which has been closed even though the issue has not be resolved, and nor has it been confirmed or rejected as a bug.

Using a com.WazaBe.HoloEverywhere.preference.MultiSelectListPreference in an SPreferenceActivity I find that I cannot uncheck tick boxes, and when I check unticked boxes the preference is not saved.

Here is a sample of my prefs.xml file:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:holo="http://schemas.android.com/apk/res-auto" >

    <PreferenceCategory
        holo:key="pref_category_ui"
        holo:title="@string/ui" >
        <ListPreference
            holo:defaultValue="red"
            holo:entries="@array/theme_names"
            holo:entryValues="@array/theme_keys"
            holo:key="pref_ui_theme"
            holo:persistent="true"
            holo:summary="Change colour scheme of app."
            holo:title="@string/app_theme" />

        <MultiSelectListPreference
            holo:defaultValue="@array/list_keys"
            holo:dialogTitle="Select Lists to Display"
            holo:entries="@array/list_names"
            holo:entryValues="@array/list_keys"
            holo:key="pref_ui_tabs"
            holo:persistent="true"
            holo:summary="Specify which lists to show on home screen."
            holo:title="Lists to Display" />
    </PreferenceCategory> 
```

I've added a debug logcat line to com.WazaBe.HoloEverywhere.preference.MultiSelectListPreference (around Line 135):

``` java
        boolean[] checkedItems = getSelectedItems();
        builder.setMultiChoiceItems(mEntries, checkedItems,
                new DialogInterface.OnMultiChoiceClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which,
                            boolean isChecked) {
                        Log.v("MultiSelectListPreference [HoloEverywhere]", "onClick: " + isChecked);
                        if (isChecked) {
                            mPreferenceChanged |= mNewValues
                                    .add(mEntryValues[which].toString());
                        } else {
                            mPreferenceChanged |= mNewValues
                                    .remove(mEntryValues[which].toString());
                        }
                    }
                });
        mNewValues.clear();
        mNewValues.addAll(mValues);
    }

```

And when I try to select/unselect anything you would expect the logcat statement to be displayed - it isn't - so one must assume the onClick method is not being called.  Now this was all working about ten days ago, and following a recent pull from the dev branch it isn't - so one can also assume that something has changed within HoloEverywhere which has broken this functionality.

**Comment by Prototik** [comment]
Okay, accepted.
You may print content of /data/data/package/shared_prefs/package***.xml?

**Comment by indieboyalex** [comment]
``` xml
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
<string name="genre">[&quot;3&quot;,&quot;2&quot;,&quot;10&quot;,&quot;1&quot;,&quot;7&quot;,&quot;6&quot;,&quot;5&quot;,&quot;4&quot;,&quot;9&quot;,&quot;8&quot;,&quot;11&quot;,&quot;12&quot;]</string>
<string name="pref_ui_theme">red</string>
<boolean name="notif_active" value="true" />
<string name="language">[&quot;eng&quot;]</string>
<string name="pref_ui_tabs">[&quot;history&quot;,&quot;draft&quot;,&quot;new&quot;,&quot;classic&quot;,&quot;popular&quot;]</string>
<boolean name="adult" value="true" />
</map>
```

I'm going to presume that the event isn't working it's way down (or up, if you prefer) from the checkbox item to the preference itself.

**Comment by Prototik** [comment]
In 1.2.3 all work?

**Comment by indieboyalex** [comment]
How would I go about checking that??  It's certainly not working on the latest version on the dev branch.

**Comment by Prototik** [comment]
M, 1.2.4, sorry.
git reset --hard HEAD^
And downgrade abs to 4.1

**Comment by indieboyalex** [comment]
_Phew_ - That took a bit of code modification 

However I can confirm that it DOES work with 1.2.4 - though other aspects of my project do break as I was using the SeekBar component elsewhere(!).  But hopefully this will help locate the issue.
