### ISSUE TITLE
Holo Everywhere with ABS 4.2

### ISSUE THREAD

**Issue by rfmussa** [Prototik/HoloEverywhere#131]
Hello this is what i am getting in projects after upgrading to the newest HoloEverywhere and ActionBarSherlock   

 (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '._')
    (skipping file '.DS_Store' due to ANDROID_AAPT_IGNORE pattern '._')
C:\workspace\holoeverywhere\ChristopheVersieux-HoloEverywhere-d3e779b\library\res\layout\time_picker_holo.xml:17: error: No resource identifier found for attribute 'importantForAccessibility' in package 'android'

**Comment by Prototik** [comment]
Which version of sdk you use? 14+?

**Comment by ChristopheVersieux** [comment]
I think level 16 is necessary:

http://developer.android.com/reference/android/view/View.html#setImportantForAccessibility(int)

**Comment by rfmussa** [comment]
Yes, I am using target level 16

**Comment by rfmussa** [comment]
Solved it, just did a full clean and re-added the libraries.

**Comment by blundell** [comment]
Strange because I just hit that issue. This library isn't eclipse friendly

**Comment by mdumrauf** [comment]
I don't think is a matter of the library but ADT itself. It sucks sometimes.

**Comment by gsingh93** [comment]
I get this error after add HoloEverywhere as a library to this project: https://github.com/bauerca/drag-sort-listview

I had to change the manifest to update the target API and I changed some of the classes to HoloEverywhere classes, but I then I get the error that the OP has.

**Comment by songzhiyong** [comment]
yes,at least level 16
