### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DineshAnandan** [Prototik/HoloEverywhere#132]
When I import the library project it shows too many error.

**Comment by ChristopheVersieux** [comment]
With such a describtion, it won't be easy to help :-p

Have you followed all the steps described here: https://github.com/ChristopheVersieux/HoloEverywhere/blob/master/README.md

and are you using API level 14+ (16 seems even better)?

**Comment by DineshAnandan** [comment]
don't know why this is happen but after restart my eclipse it's work fine thank you :)
