### ISSUE TITLE
HoloEverywhere errors when checking out

### ISSUE THREAD

**Issue by SebaSOFT** [Prototik/HoloEverywhere#133]
Hi all

I'm checking out HoloEverywhere and got this when initializing submodules:

> $ git submodule update --init
> Submodule 'contrib/ActionBarSherlock' (git://github.com/ChristopheVersieux/ActionBarSherlock.git) registered for path 'contrib/ActionBarSherlock'
> Cloning into 'contrib/ActionBarSherlock'...
> remote: Counting objects: 16743, done.
> remote: Compressing objects: 100% (4485/4485), done.
> remote: Total 16743 (delta 9350), reused 16399 (delta 9117)
> Receiving objects: 100% (16743/16743), 9.92 MiB | 793 KiB/s, done.
> Resolving deltas: 100% (9350/9350), done.
> fatal: reference is not a tree: 90939dc3925ffaaa0de269bbbe1b35e274968ea1
> Unable to checkout '90939dc3925ffaaa0de269bbbe1b35e274968ea1' in submodule path 'contrib/ActionBarSherlock'

So...

**Comment by Prototik** [comment]
Use standart ABS from Jake repo.

To Christophe: delete abs fork, not need more.
