### ISSUE TITLE
HoloEverywhere is at inconsistent state

### ISSUE THREAD

**Issue by SebaSOFT** [Prototik/HoloEverywhere#134]
I know that ActionBarSherlock (4.2.0) has been updated and that HoloEverywhere is using classes no longer existing in the current Google Support library r10 (i.e.: Watson)

**Comment by aiwilliams** [comment]
I don't know that it's related, but I cannot `git submodule update --init` without receiving the message `fatal: remote error: Repository not found.  Unable to fetch in submodule path 'contrib/ActionBarSherlock'`

**Comment by SebaSOFT** [comment]
It is not directly related but since today ActionBarSherlock has to be checked out from the original repo

**Comment by aiwilliams** [comment]
Okay, I changed the .gitmodules file and sync'd the url, it's happy enough. Any need to submit a pull request, I wonder? Surely this will be fixed Real Soon Now?

**Comment by stleusc** [comment]
even with ASB loaded it does NOT compile!
all styles related errors like:
error: Error: No resource found that matches the given name: attr 'listPreferredItemPaddingLeft'.

**Comment by aiwilliams** [comment]
I had a different missing attr, but no problems after using Android 4.1, support-v4:r7, and abs 4.2.0. If you're using maven, it could be good to clean before compile.

**Comment by stleusc** [comment]
a clean + restart helped

**Comment by SebaSOFT** [comment]
It really need to work with support(r10) IMHO
