### ISSUE TITLE
_SharedPreferencesImpl_JSON.java 226

### ISSUE THREAD

**Issue by byedown** [Prototik/HoloEverywhere#137]
Error: IOException 

if (tempFile.exists()) {
     if (!tempFile.isDirectory()) {
        if (!tempFile.delete() && !tempFile.mkdirs()) {
            throw new CouldNotCreateStorage(tempFile,
            "Сann't create a storage for the preferences.");
        }
    }
} else {
    tempFile.mkdirs();
}
Android: 4.1
Device: I9250

**Comment by Prototik** [comment]
You may temporary change SharedPreferencs impl on xml:

```
    Settings.setPreferenceMode(PreferenceMode.XML);
```
