### ISSUE TITLE
Error while trying to use SPreferenceActivity

### ISSUE THREAD

**Issue by nicous** [Prototik/HoloEverywhere#138]
I'm getting the following error:

10-12 12:51:23.269: E/AndroidRuntime(1863): Caused by: java.lang.ClassCastException: android.widget.ListView
10-12 12:51:23.269: E/AndroidRuntime(1863):     at com.WazaBe.HoloEverywhere.app.ListActivity.onContentChanged(ListActivity.java:62)
10-12 12:51:23.269: E/AndroidRuntime(1863):     at com.WazaBe.HoloEverywhere.preference.PreferenceActivity.onContentChanged(PreferenceActivity.java:573)
10-12 12:51:23.269: E/AndroidRuntime(1863):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.setContentView(ActionBarSherlockCompat.java:876)
10-12 12:51:23.269: E/AndroidRuntime(1863):     at com.actionbarsherlock.ActionBarSherlock.setContentView(ActionBarSherlock.java:671)
10-12 12:51:23.269: E/AndroidRuntime(1863):     at com.WazaBe.HoloEverywhere.sherlock.SPreferenceActivity.setContentView(SPreferenceActivity.java:249)
10-12 12:51:23.269: E/AndroidRuntime(1863):     at com.WazaBe.HoloEverywhere.preference.PreferenceActivity.onCreate(PreferenceActivity.java:583)
10-12 12:51:23.269: E/AndroidRuntime(1863):     at com.mercadolibre.activities.settings.SettingsActivity.onCreate(SettingsActivity.java:48)
10-12 12:51:23.269: E/AndroidRuntime(1863):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1069)
10-12 12:51:23.269: E/AndroidRuntime(1863):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2751)

This is just in the onCreate method when I do super.onCreate(savedInstanceState);

@Override
    protected void onCreate(Bundle savedInstanceState) {
        <b>super.onCreate(savedInstanceState);</b>
        addPreferencesFromResource(R.xml.settings);
}

**Comment by Prototik** [comment]
You apply Holo.Theme* on activity?

**Comment by nicous** [comment]
Thx for your answer.
You mean like this setTheme(com.WazaBe.HoloEverywhere.R.style.Holo_Theme_Sherlock_Light_DarkActionBar); before the super.onCreate?
If you do, it didn't work.

**Comment by Prototik** [comment]
So, print you settings.xml and full activity code.

**Comment by nicous** [comment]
Ok here it goes. The activity is a test one because I'm porting from SherlockPreferenceActivity.

``` java
public class SettingsActivityHolo extends com.WazaBe.HoloEverywhere.sherlock.SPreferenceActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        addPreferencesFromResource(R.xml.settings);
    }   
}
```

``` xml
<?xml version="1.0" encoding="utf-8"?>
<PreferenceScreen xmlns:holo="http://schemas.android.com/apk/res-auto" >
    <Preference
        holo:key="about"
        holo:title="@string/about_short_title" />

    <PreferenceCategory holo:title="@string/settings_category_accounts" >
        <Preference
            holo:key="ml_account"
            holo:summary="@string/settings_ml_account_summary"
            holo:title="@string/settings_ml_account_title" />
        <Preference
            holo:key="facebook_account"
            holo:title="@string/settings_facebook_account_title" />
        <Preference
            holo:key="twitter_account"
            holo:title="@string/settings_twitter_account_title" />
    </PreferenceCategory>
    <PreferenceCategory holo:title="@string/settings_cattegory_region" >
        <ListPreference
            holo:entries="@array/settings_site_list_entries"
            holo:entryValues="@array/settings_site_list_entries_values"
            holo:key="site_id"
            holo:summary="@string/settings_site_list_summary"
            holo:title="@string/settings_site_list_title" />
    </PreferenceCategory>
    <PreferenceCategory holo:title="@string/settings_notifications_category" >
        <Preference
            holo:key="notifications"
            holo:summary="@string/settings_notifications_content_summary"
            holo:title="@string/settings_notifications_content_title" />
    </PreferenceCategory>
    <PreferenceCategory holo:title="@string/settings_cattegory_personalization" >
        <CheckBoxPreference
            holo:defaultValue="true"
            holo:key="questions_signature"
            holo:summaryOff="@string/settings_questions_signature_summary_off"
            holo:summaryOn="@string/settings_questions_signature_summary_on"
            holo:title="@string/settings_questions_signature_title" />

        <Preference
            holo:key="clear_recent_searches"
            holo:summary="@string/about_clear_recent_searches_summary"
            holo:title="@string/about_clear_recent_searches_title" />
    </PreferenceCategory>

</PreferenceScreen>
```

**Comment by Prototik** [comment]
Mmm, i don't know, your SPreferenceActivity not use HoloEverywhere.LayoutInflater.

**Comment by stleusc** [comment]
I get the same exception in my app. But not consistently.....
I can build it, upload it and run it and it crashes..... then I just run again and it works!
It seems to depend on if com.WazaBe.HoloEverywhere.app.ListActivity.onContentChanged(ListActivity.java:62) gets called or not and that might depend on some previous state maybe.

**Comment by Prototik** [comment]
@stleusc If app crashed and user click "close" button, application process will be killed. Activity can not save state.

**Comment by stleusc** [comment]
I think I don't get the answer...
After a clean install it does NOT work..... THAT is the problem, regardless if it then works later.
Maybe my first comment was confusing.

**Comment by nicous** [comment]
I know I'm missing something. In the demo app onContentChanged get called and it works flawlessly.
All I did was:
- import the library and everything
- set the holo theme in the android manifest for the application (as shown in the description of this project).
- Then I couldn't replace our SherlockFragmentActivity because there's no holo equivalent so I leave it.
- And then change the SherlockPreferenceActivity to SPreference and its xml.

**Comment by Prototik** [comment]
SherlockFragmentActivity - SActivity.

**Comment by jaibatrik** [comment]
I too had this issue. I solved it by replacing **ListView** with **com.WazaBe.HoloEverywhere.widget.ListView** in the following files - 
- /HoloEverywhereLib/res/layout/preference_list_content_single.xml
- /HoloEverywhereLib/res/layout/preference_list_content.xml
- /HoloEverywhereLib/res/layout/preference_list_fragment.xml

**Comment by nicous** [comment]
jaibatrik thank you! that worked!

**Comment by Prototik** [comment]
![Screenshot](http://ubuntuone.com/2PLoF1VsUTrhVd4mnWjOBq)

```
package com.WazaBe.HoloDemo;

import android.os.Bundle;
import android.util.Log;

import com.WazaBe.HoloEverywhere.app.Activity.Holo;
import com.WazaBe.HoloEverywhere.preference.SwitchPreference;
import com.WazaBe.HoloEverywhere.sherlock.SPreferenceActivity;

@Holo(forceThemeApply = true)
public class SPrefActivity extends SPreferenceActivity {
    @SuppressWarnings("deprecation")
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        addPreferencesFromResource(R.xml.preferences);
        Log.v("TAG", ((SwitchPreference) findPreference("switch")).getKey());
    }
}

```

```
    V/TAG     (  274): switch
```
