### ISSUE TITLE
Remove unused ic_launcher.png files and strings

### ISSUE THREAD

**Issue by yukuku** [Prototik/HoloEverywhere#14]
Thanks for the library!

I noticed that there are ic_launcher.png files in drawable directories. This may seem safe, but actually will be packaged with the app and possibly causing the app to use the wrong icon. For example, an app defines only xhdpi icon for launcher icon, when it runs on hdpi device, it will use the icon from HoloEverywhere lib instead of scaling down the xhdpi icon. Hence it should be removed.

Also for app_name, hello, and (seemingly) spinner_prompt strings.

Also planets array. This may cause unwanted consequences to the app.

Thanks for the library, again!

**Comment by ChristopheVersieux** [comment]
Thank a lot for the great feedback, I will try to fix all that asap.
