### ISSUE TITLE
anywhere and everywhere: java.lang.ClassCastException

### ISSUE THREAD

**Issue by stleusc** [Prototik/HoloEverywhere#141]
here the story:
I was using HE with ABS since quite some time. No I upgraded to the latest version.
Suddenly there is a HE version of all widgets. Of course my code does not use them.
I constantly get 
com.WazaBe.HoloEverywhere.widget.EditText cannot be cast to android.widget.EditText
or similar all over the place. Sure I can patch one place, then I find another.
Any documentation on how to migrate?

Thanks!

**Comment by Prototik** [comment]
So, manuals: soon :)

**Comment by stleusc** [comment]
What can I say..... MAN YOU'RE FREAKING AWESOME AND FAST!

Thanks for the quick responses.... Can't wait for the manual now ;-)
