### ISSUE TITLE
java.lang.ClassCastException: com.WazaBe.HoloEverywhere.widget.Spinner

### ISSUE THREAD

**Issue by stleusc** [Prototik/HoloEverywhere#142]
Using Spinner in xml and casting it to android.widget.Spinner causes java.lang.ClassCastException: com.WazaBe.HoloEverywhere.widget.Spinner because HE Spinner is not based on Android Spinner.
Is this intended? Most of the HE widgets CAN be cast to the android version....

It's confusing when it works and when NOT....

**Comment by Prototik** [comment]
This is normal. Yes, some widgets do not extend the standard Android widgets. And not to tear himself the second question, all widgets should be casted to the same HoloEverywhere.widgets package.
