### ISSUE TITLE
Dialog crashes with ClassCastException

### ISSUE THREAD

**Issue by Michael-Zinn** [Prototik/HoloEverywhere#144]
When trying to create a dialog I get this error:

10-15 11:23:41.608: E/AndroidRuntime(225): java.lang.ClassCastException: android.widget.LinearLayout
10-15 11:23:41.608: E/AndroidRuntime(225):  at com.WazaBe.HoloEverywhere.internal.AlertController.setupView(AlertController.java:720)
10-15 11:23:41.608: E/AndroidRuntime(225):  at com.WazaBe.HoloEverywhere.internal.AlertController.installContent(AlertController.java:449)
10-15 11:23:41.608: E/AndroidRuntime(225):  at com.WazaBe.HoloEverywhere.app.AlertDialog.onCreate(AlertDialog.java:352)
10-15 11:23:41.608: E/AndroidRuntime(225):  at android.app.Dialog.dispatchOnCreate(Dialog.java:308)
10-15 11:23:41.608: E/AndroidRuntime(225):  at android.app.Dialog.show(Dialog.java:225)

I create the dialog like this, which works with standard dialogs:

``` Java
            AlertDialog.Builder builder = new AlertDialog.Builder(context);

            builder.setTitle(R.string.dialog_confirmReservation_title);
            builder.setMessage(context.getResources()
                    .getQuantityString(R.plurals.dialog_confirmReservation_message, numberOfLoansLeft, numberOfLoansLeft));

            builder.setNegativeButton(R.string.dialog_Cancel, new DialogInterface.OnClickListener() {
                @Override
                public void onClick(DialogInterface dialog, int which) {
                    dialog.dismiss();
                }
            });
[...]
```

Is this a bug? Why does it work with standard dialogs but not with HoloEverywhere dialogs? What's the right way to get a HoloEverywhere dialog?

**Comment by Prototik** [comment]
context - instance of HoloEverywhere.(S)Activity?

**Comment by Michael-Zinn** [comment]
No, it's a SherlockFragmentActivity. I tried to replace it with HoloEverywhere's Activity, but that one lacks the "getSupportActionBar()" method. What's the right class to use here?

Where's the documentation for setting up HoloEverywhere? I'm currently using it by simply guessing.

**Comment by Michael-Zinn** [comment]
Got it working using com.WazaBe.HoloEverywhere.sherlock.SActivity

I guess this resolves this issue, but I don't know what I'm doing here. Can you point me to a tutorial when closing this issue?

**Comment by Prototik** [comment]
That must be extend SActivity indicated even in README, other tutorials in the process.
