### ISSUE TITLE
How set theme?

### ISSUE THREAD

**Issue by Matungos** [Prototik/HoloEverywhere#146]
This is not a issue but I didn't know where to ask...

How is the right way to set a theme on every Activity?

I'm using this way:

public class MyActivity extends SActivity {

```
    @Override
    public void onCreate(Bundle savedInstanceState) {
    Utils u = new Utils(this);

            ThemeManager.restartWithTheme(this, u.getTheme());
            ...
    }
```

My class Utils reads the theme previusly selected by the user.

**Comment by Prototik** [comment]
?
[README](https://github.com/ChristopheVersieux/HoloEverywhere/blob/master/README.md)

```
<application
  android:theme="@style/Holo.Theme.Sherlock"
...
```

**Comment by Matungos** [comment]
Yes, but android:theme="@style/Holo.Theme.Sherlock" isn't it a "hardcoded" Dark theme? Am I right?

The way I want it is  programmatically/dynamically because it may variate by users.

**Comment by Prototik** [comment]
See demo. setForceThemeApply in Activity, ThemeManager.modifyDefaultTheme, ThemeManager.modify for all themes used in ThemeManager. And sure restartWith(Dark/Light/LightWithDarkActionBar)Theme. But it's restart, don't call it in onCreate.

**Comment by Prototik** [comment]
And Application.getConfig().setAlwaysUseParentTheme/setUseThemeManager

**Comment by bondjpf** [comment]
I'm  a bit lost on how to use it right now.
I used to do this way to get the current user selected theme:

OnCreate
.....
setForceThemeApply(true);
Settings.setUseThemeManager(true);
SP =Home.this.getSharedPreferences(SHARED_PREFS_NAME, 0);
this.SP.registerOnSharedPreferenceChangeListener(this);
if (SP.getString("theme_list_preference", "AppThemeLight").equals("AppThemeLight")){
            ThemeManager.restartWithTheme(this, ThemeManager.LIGHT);
    }
.......
So how do I do it now? 
Thanks.

**Comment by Prototik** [comment]
Let's start by defining: you need to set a theme on Activity or on all application?
If first: is not satisfied setTheme?
If second: then yes, you should use ThemeManager. But does not enable the everything, in the hope that everything will work out.

`Application.getConfig().setUseThemeManager(true).setAlwaysUseParentTheme(true);` - as static block in your application class.

`ThemeManager.setDefaultTheme(ThemeManager.DARK)` Or LIGHT, LIGHT_WITH_DARK_ACTION_BAR. There also.
`ThemeManager.modify(ThemeManager.FULLSCREEN)` - if you want full screen theme.
`ThemeManager.modify(ThemeManager.NO_ACTION_BAR)` - and if you want theme without action bar.

On launcher activity you should set @Holo annotation with attr forceThemeApply = true, or call setForceThemeApply(true) before call super.onCreate.

For restart activity with new theme use ThemeManager.restartWith***Theme.

**Comment by nicomott** [comment]
Just to be clear, can we define a theme that inherits from Holo.Theme.Sherlock, and then we use it in the manifest ? I tried but it doesn't seem to work : 

in Themes.xml:
`<style name="Theme.custom" parent="Holo.Theme.Sherlock.Light.DarkActionBar">`

In AndroidManifest : 
`<application android:theme="@style/Theme.custom" >`

In my application class :

`````` Application.getConfig().setUseThemeManager(true).setAlwaysUseParentTheme(true);```

If I don't set  : 
```ThemeManager.setDefaultTheme(ThemeManager.LIGHT_WITH_DARK_ACTION_BAR);``` it doesn't seem to work. My dialogs don't use Holo theme on Gingerbread etc
``````

**Comment by Prototik** [comment]
With custom themes you should allow them to use. `ThemeManager.setOnlyBaseThemes(false)` before setting any themes.

**Comment by bondjpf** [comment]
I have a better understanding now. 
I was doing some tests and seems that in 1.3.2 SPreferenceActivity is not working properly as it doesn't seem to save the selected value from ListPreference so I can then change the theme. In 1.3.0 it's working ok.

**Comment by Prototik** [comment]
Application sample with using custom themes: [download](http://ubuntuone.com/3xNlkx4ozSHnVOSOkIlJUZ)

**Comment by Prototik** [comment]
About ListPreference: use getSupportSharedPreferences (or getDefaultPreferences), will be reverted to getSharedPreferences in next release.

**Comment by bondjpf** [comment]
Thanks. You link above is not working.

**Comment by Prototik** [comment]
Yes? i'm sorry: [download](http://ubuntuone.com/1WD9b60uH6z5CD9yfLZtvz)

**Comment by 4nd3250n** [comment]
I too face the same problem. There is no clear documentation. Application launch on eclipse takes about 5 minutes so blind guessing is an awful waste of time.

It would be most welcomed to know how one sets and changes the theme for the application in runtime.

As far as I could gather is:
To change a theme of an activity use restartWithTheme (Activity, int);
But how does one change a theme application wide? All I have tried with ThemeManager produces an error.
What does the ThemeManager.setDefaultMethod() do?
What does the annotation @Holo(forceThemeApply = true) do? Black box guessing tells me nothing, but I am sure it must do something in the background.

Would it be possible to write at least some mini minimal documentation?

What I am doing is which bring me partial result is:
In every activity in onCreate() event I check what is the theme stored in the preferences. And then I do simple checks:
if (stringInPreferences.equals("Dark") setTheme(R.style.ThemeHoloDark);
if((stringInPreferences.equals("Light") setTheme(R.style.ThemeHoloDark);
Themes in that case are descendants from Holo.Theme.Dark.

How does one remove title bar which is visible above Action bar. I thought ThemeManager.modifyTheme(ThemeManager.FULLSCREEN) woudl do. But that does nothing. How does one use that correctly.

This is a lot of questions, but it is really frustrating to keep guessing blindly.
