### ISSUE TITLE
Can't start the HoloDemo

### ISSUE THREAD

**Issue by strangeoptics** [Prototik/HoloEverywhere#15]
Hi,

I would like to start the HoloDemo but I get an Error Type 3 that means:

ActivityManager: Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.WazaBe.HoloDemo/.HoloDemoActivity }
ActivityManager: Error type 3
ActivityManager: Error: Activity class {com.WazaBe.HoloDemo/com.WazaBe.HoloDemo.HoloDemoActivity} does not exist.

I am not an Android genius, do you know whats wrong.
I just imported your projects into my workspace.

Thanks

**Comment by ChristopheVersieux** [comment]
The app should be installed on your phone and an icon appear on the
launcher, no?
It just not launch automatically because I had to find a trick to launch a
different activity depending on the SDK version..

On Fri, May 11, 2012 at 5:47 PM, strangeoptics <
reply@reply.github.com

**Comment by strangeoptics** [comment]
No, for now I work just with the emulator and there is no icon.

But the error message says that the app wants to start with the HoloDemoActivity but it cant find it.

If you can help me you get 2 beer if you are around frankfurt.

**Comment by strangeoptics** [comment]
I started my own Project with your great library and it works just fine. Something is wrong with the demo sources.

**Comment by khalifavi** [comment]
Well, this issue should be closed then, the demo is already installed, this is just because of the eclipse not smart enough to pick activity based on resources variable.
I got the same case, and found the application icon on the launcher, just look carefully.

**Comment by ChristopheVersieux** [comment]
Yeah, sometimes Eclipse does not launch automatically the correct Activity based on boolean resource.
As +khalifavi commented, the icon is in the launcher and the project just works.
