### ISSUE TITLE
VolumePreference and holo:defaultValue attribute

### ISSUE THREAD

**Issue by ForestTree** [Prototik/HoloEverywhere#151]
Hello,
from 1.3.2 is  holo:defaultValue attribute mandatory for VolumePreference, otherwise:

<code>10-18 21:07:41.057: E/AndroidRuntime(11312): Caused by: java.lang.NumberFormatException: Invalid int: "null"
10-18 21:07:41.057: E/AndroidRuntime(11312):    at java.lang.Integer.invalidInt(Integer.java:138)
10-18 21:07:41.057: E/AndroidRuntime(11312):    at java.lang.Integer.parseInt(Integer.java:355)
10-18 21:07:41.057: E/AndroidRuntime(11312):    at java.lang.Integer.parseInt(Integer.java:332)
10-18 21:07:41.057: E/AndroidRuntime(11312):    at com.WazaBe.HoloEverywhere.preference.SeekBarDialogPreference.onGetDefaultValue(SeekBarDialogPreference.java:119)</code>

I'm not sure if and how is this default value used in VolumePreference, because this is hidden system preference.

Thanks you

**Comment by Prototik** [comment]
It's bug in SeekBarDialogPreference, fixed in dev version, i think :)
