### ISSUE TITLE
Error on try opening AlertDialog in android 4.1

### ISSUE THREAD

**Issue by ru-nekit-android** [Prototik/HoloEverywhere#153]
10-19 12:16:24.791: E/AndroidRuntime(1260): android.view.InflateException: Binary XML file line #2: Error inflating class com.WazaBe.HoloEverywhere.AlertController$RecycleListView
10-19 12:16:24.791: E/AndroidRuntime(1260):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:698)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at com.WazaBe.HoloEverywhere.internal.AlertController$AlertParams.createListView(AlertController.java:141)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at com.WazaBe.HoloEverywhere.internal.AlertController$AlertParams.apply(AlertController.java:127)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at com.WazaBe.HoloEverywhere.app.AlertDialog$Builder.create(AlertDialog.java:38)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at com.WazaBe.HoloEverywhere.app.AlertDialog$Builder.show(AlertDialog.java:293)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at ru.nekit.helpoidapp.PresentationListFragment.showCreatePresentationDialog(PresentationListFragment.java:186)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at ru.nekit.helpoidapp.PresentationListFragment.access$0(PresentationListFragment.java:168)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at ru.nekit.helpoidapp.PresentationListFragment$1.onClick(PresentationListFragment.java:77)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at android.view.View.performClick(View.java:4084)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at android.view.View$PerformClick.run(View.java:16966)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at android.os.Handler.handleCallback(Handler.java:615)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at android.os.Handler.dispatchMessage(Handler.java:92)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at android.os.Looper.loop(Looper.java:137)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at android.app.ActivityThread.main(ActivityThread.java:4745)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at java.lang.reflect.Method.invokeNative(Native Method)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at java.lang.reflect.Method.invoke(Method.java:511)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at dalvik.system.NativeStart.main(Native Method)
10-19 12:16:24.791: E/AndroidRuntime(1260): Caused by: java.lang.ClassNotFoundException: com.WazaBe.HoloEverywhere.AlertController$RecycleListView
10-19 12:16:24.791: E/AndroidRuntime(1260):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at android.view.LayoutInflater.createView(LayoutInflater.java:552)
10-19 12:16:24.791: E/AndroidRuntime(1260):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)

**Comment by Prototik** [comment]
Как-бэ обновись до 1.3.2, крешится не из-за 4.1, а из-за косячной разметки для больших экранов.

**Comment by ru-nekit-android** [comment]
Да точно! из-за больших экранов
