### ISSUE TITLE
maven unable to deploy demo to Emulator

### ISSUE THREAD

**Issue by agarwlGaurav** [Prototik/HoloEverywhere#155]
I am trying to deploy the demo from command line using the command 

mvn android:deploy and the message from maven is Successfully Installed, but when I try to look for the demo in the Emulator it is absent.

Why maven is unable to deploy the Demo to the Emulator?

**Comment by Prototik** [comment]
Try to add sign phase to pom.xml in demo.
http://code.google.com/p/maven-android-plugin/wiki/SigningAPKWithMavenJarsigner
