### ISSUE TITLE
Install HoloEverywhere to local Maven Repo till it is updated to Central

### ISSUE THREAD

**Issue by agarwlGaurav** [Prototik/HoloEverywhere#160]
I was looking for some help on how to install HoloEverywhere to local Maven Repo till it is updated to the central.

**Comment by agarwlGaurav** [comment]
I have asked a question on SO also. http://stackoverflow.com/questions/13035955/install-a-android-library-into-local-maven-repo/13037328#comment17700871_13037328

**Comment by ChristopheVersieux** [comment]
I am currently struggling with Java/Maven errors and cannot update to maven.

**Comment by agarwlGaurav** [comment]
Can we install it to local repos on our machines in the mean time?

**Comment by Prototik** [comment]
mvn install?

**Comment by agarwlGaurav** [comment]
Thanks I am closing the issue. For more details people can also visit  http://stackoverflow.com/questions/13035955/install-a-android-library-into-local-maven-repo/13037328#comment17700871_13037328
