### ISSUE TITLE
Changing SherlockFragment to SFragment leads to error with onCreateView

### ISSUE THREAD

**Issue by gosr** [Prototik/HoloEverywhere#167]
First of all, I hope this is the right place to ask questions (am relatively new to github).

My app is based on ActionBarSherlock, and from the guide on the front page I can see that I need to extend my activities etc. to S***Activity.

What I did was:
Change SherlockFragmentActivity to SActivity (why is there no SFragmentActivity?)
Change SherlockFragment to SFragment.

Then Eclipse is giving me this error (in my fragment) regarding onCreateView:
"Cannot override the final method from Fragment"
Nothing changes if I remove the override annotation.

My onCreateView is just as standard:
@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) { ... }

How can I proceed?

Thanks.

**Comment by Prototik** [comment]
Ctrl + Space - popup helper. Replace android.view.LayoutInflater on com.WazaBe.HoloEverywhere.LayoutInflater.

**Comment by gosr** [comment]
Thanks!
