### ISSUE TITLE
Extending SPreference Activity - Error Inflating Class

### ISSUE THREAD

**Issue by taraloca** [Prototik/HoloEverywhere#168]
I am trying to use your library, but keep coming up with this error....it points back to the preference_holo:

10-26 14:20:49.251: E/AndroidRuntime(5375): android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
10-26 14:20:49.251: E/AndroidRuntime(5375):     at android.view.LayoutInflater.createView(LayoutInflater.java:613)
10-26 14:20:49.251: E/AndroidRuntime(5375):     at com.WazaBe.HoloEverywhere.LayoutInflater.onCreateView(LayoutInflater.java:197)
10-26 14:20:49.251: E/AndroidRuntime(5375):     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
10-26 14:20:49.251: E/AndroidRuntime(5375):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
10-26 14:20:49.251: E/AndroidRuntime(5375):     at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
10-26 14:20:49.251: E/AndroidRuntime(5375):     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
10-26 14:20:49.251: E/AndroidRuntime(5375):     at com.WazaBe.HoloEverywhere.preference.Preference.onCreateView(Preference.java:516)
10-26 14:20:49.251: E/AndroidRuntime(5375):     at com.WazaBe.HoloEverywhere.preference.Preference.getView(Preference.java:405)
10-26 14:20:49.251: E/AndroidRuntime(5375):     at com.WazaBe.HoloEverywhere.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:158)
10-26 14:20:49.251: E/AndroidRuntime(5375):     at android.widget.AbsListView.obtainView(AbsListView.java:2267) 
...

Here is  a snippet of my settings.xml where I declare holo:

<?xml version="1.0" encoding="utf-8"?>
<PreferenceScreen xmlns:holo="http://schemas.android.com/apk/res-auto" >

```
<ListPreference
    holo:defaultValue="default_metric"
    holo:dialogTitle="units"
    holo:entries="@array/pref_temp_units"
    holo:entryValues="@array/pref_temp_units_values"
    holo:key="pref_temp_units"
    holo:title="xbasic" />

<Preference
    holo:key="advanced_pref"
    holo:title="advanced" >

</Preference>
<Preference
    holo:key="my_accuweather_pref"
    holo:title="My AccuWeather" >
</Preference>
<PreferenceScreen
    holo:key="notification_pref"
    holo:title="notifications" >
    <ListPreference
        holo:defaultValue="2"
        holo:dialogTitle="Notifications"
        holo:entries="@array/pref_temp_notifications"
        holo:entryValues="@array/pref_temp_notifications_values"
        holo:key="pref_temp_notifications"
        holo:title="Notifications" />
    <ListPreference
        holo:defaultValue="15"
        holo:dialogTitle="Interval"
        holo:entries="@array/pref_notification_interval"
        holo:entryValues="@array/pref_notification_interval_values"
        holo:key="pref_notification_interval"
        holo:title="Interval" />
    <ListPreference
        holo:defaultValue="1"
        holo:dialogTitle="open_at_launch"
        holo:entries="@array/pref_open_at_launch"
        holo:entryValues="@array/pref_open_at_launch_values"
        holo:key="pref_open_at_launch"
        holo:title="open_at_launch" />
    <ListPreference
        holo:defaultValue="1"
        holo:dialogTitle="enable_push"
        holo:entries="@array/pref_push_notification"
        holo:entryValues="@array/pref_push_notification_values"
        holo:key="pref_push_notification"
        holo:title="enable_push" />
</PreferenceScreen>
```

...

**Comment by Prototik** [comment]
Your SPreferenceActivity don't use holo theme (in manifest or setTheme before super.onCreate).

**Comment by taraloca** [comment]
I am using ActionBarSherlock in my application and when I declare the style in my manifest, I get this error:

10-29 08:35:04.423: E/AndroidRuntime(2424): FATAL EXCEPTION: main
10-29 08:35:04.423: E/AndroidRuntime(2424): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.accuweather.android/com.accuweather.android.preferences.SettingsActivity}: java.lang.IllegalStateException: You must use Theme.Sherlock, Theme.Sherlock.Light, Theme.Sherlock.Light.DarkActionBar, or a derivative.
10-29 08:35:04.423: E/AndroidRuntime(2424):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
10-29 08:35:04.423: E/AndroidRuntime(2424):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
10-29 08:35:04.423: E/AndroidRuntime(2424):     at android.app.ActivityThread.access$600(ActivityThread.java:130)
10-29 08:35:04.423: E/AndroidRuntime(2424):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
10-29 08:35:04.423: E/AndroidRuntime(2424):     at android.os.Handler.dispatchMessage(Handler.java:99)
10-29 08:35:04.423: E/AndroidRuntime(2424):     at android.os.Looper.loop(Looper.java:137)
10-29 08:35:04.423: E/AndroidRuntime(2424):     at android.app.ActivityThread.main(ActivityThread.java:4745)
10-29 08:35:04.423: E/AndroidRuntime(2424):     at java.lang.reflect.Method.invokeNative(Native Method)
10-29 08:35:04.423: E/AndroidRuntime(2424):     at java.lang.reflect.Method.invoke(Method.java:511)
10-29 08:35:04.423: E/AndroidRuntime(2424):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
10-29 08:35:04.423: E/AndroidRuntime(2424):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
10-29 08:35:04.423: E/AndroidRuntime(2424):     at dalvik.system.NativeStart.main(Native Method)
10-29 08:35:04.423: E/AndroidRuntime(2424): Caused by: java.lang.IllegalStateException: You must use Theme.Sherlock, Theme.Sherlock.Light, Theme.Sherlock.Light.DarkActionBar, or a derivative.
10-29 08:35:04.423: E/AndroidRuntime(2424):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.generateLayout(ActionBarSherlockCompat.java:1007)
10-29 08:35:04.423: E/AndroidRuntime(2424):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.installDecor(ActionBarSherlockCompat.java:919)
10-29 08:35:04.423: E/AndroidRuntime(2424):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.setContentView(ActionBarSherlockCompat.java:872)
10-29 08:35:04.423: E/AndroidRuntime(2424):     at com.actionbarsherlock.ActionBarSherlock.setContentView(ActionBarSherlock.java:666)
10-29 08:35:04.423: E/AndroidRuntime(2424):     at com.WazaBe.HoloEverywhere.sherlock.SPreferenceActivity.setContentView(SPreferenceActivity.java:249)
10-29 08:35:04.423: E/AndroidRuntime(2424):     at com.WazaBe.HoloEverywhere.preference.PreferenceActivity.onCreate(PreferenceActivity.java:573)
10-29 08:35:04.423: E/AndroidRuntime(2424):     at com.accuweather.android.preferences.SettingsActivity.onCreate(SettingsActivity.java:14)
10-29 08:35:04.423: E/AndroidRuntime(2424):     at android.app.Activity.performCreate(Activity.java:5008)
10-29 08:35:04.423: E/AndroidRuntime(2424):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
10-29 08:35:04.423: E/AndroidRuntime(2424):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
10-29 08:35:04.423: E/AndroidRuntime(2424):     ... 11 more

**Comment by Prototik** [comment]
You must use Holo.Theme.Sherlock\* theme.

**Comment by taraloca** [comment]
I do...here is my manifest entry:

<activity
            android:name=".preferences.SettingsActivity"
            android:label="@string/app_name"
            android:theme="@style/Holo.Theme.Sherlock"  />

**Comment by taraloca** [comment]
I still get the same error....I have changed it to this due to utilizing the DarkActionBar theme also:

<activity
            android:name=".preferences.SettingsActivity"
            android:label="@string/app_name"
            android:theme="@style/Holo.Theme.Sherlock.Light.DarkActionBar"  />

**Comment by 4nd3250n** [comment]
This is a common. What is the cause?
