### ISSUE TITLE
AutoCompleteTextView in ActionView not showing proper font color

### ISSUE THREAD

**Issue by jaibatrik** [Prototik/HoloEverywhere#169]
I have an `ActionView` for which layout contains an `AutoCompleteTextView`. I'm extending `SListActivity` and applying the theme `Holo_Theme_Sherlock_Light_DarkActionBar`.

When I expand the `ActionView` it shows a black `EditText`. However when I type in it, the writing also appears in black and are not visible. This problem occurs in my API 10 phone. In API 15, the writing appears in white.

Following are the code - 

menu.xml

``` xml
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android" >
    <item
        android:id="@+id/menu_new_task"
        android:actionLayout="@layout/actionbar_new"
        android:icon="@drawable/ic_action_new"
        android:showAsAction="always|collapseActionView"
        android:title="@string/new_task"/>
</menu>
```

actionbar_new.xml

``` xml
<?xml version="1.0" encoding="utf-8"?>
<AutoCompleteTextView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/actionbar_new"
    android:layout_width="fill_parent"
    android:layout_height="wrap_content"
    android:hint="@string/add_task_here"
    android:inputType="textCapSentences|textShortMessage"
    android:dropDownWidth="match_parent"
    android:completionThreshold="1"
    android:maxLines="1" />
```

Screenshot
![Screenshot](https://dl.dropbox.com/s/o0n0mpyod9b5bvt/device-2012-10-27-234014.png?dl=1)

**Comment by damson** [comment]
Hi,

I have the same issue using an EditText. I tried to fix it with the attribute textColor="@color/white" and it works except in the case where auto-completion makes a proposition. In this case the text becomes black again.

**Comment by Prototik** [comment]
Since 1.4.1 available Activity.getSupportActionBarContext/getSupportActionBarInflater. Use it for right theme in actionbar widgets.
