### ISSUE TITLE
Button styling in Dialogs

### ISSUE THREAD

**Issue by strangeoptics** [Prototik/HoloEverywhere#17]
Hi Christophe,

I am trying to make my own custom dialog that extends the dialog but I have problems with the buttons.

When I use your layout alert_dialog_holo.xml and inflate it, the 3 buttons looks just fine.

But whenn I create the buttons programatically and add them to the layout they are not styled with the holo theme anymore.

Do you know what happened?

**Comment by SRSMartin** [comment]
I assume the intention was to extend DialogHolo when creating a custom Dialog. But this did not work for me yet either.

**Comment by wonderb0lt** [comment]
Is there any ugly quick fix for this or pointers on what to do?

**Comment by SRSMartin** [comment]
I did not find one yet. Just extending DialogHolo did not work for me. I guess, we have to leave them pre Holo for now.

**Comment by wonderb0lt** [comment]
That's what we're doing in our project too at the moment, although this solution feels rather inconsistent with an otherwise Holo'd up application...

**Comment by Prototik** [comment]
1a73ab0297138c0a701b390376c896cf26ec913b
