### ISSUE TITLE
No ActionBarSherlok source in contrib folder

### ISSUE THREAD

**Issue by Antarix** [Prototik/HoloEverywhere#173]
there is no source in contrib folder

**Comment by Prototik** [comment]
git submodule update --init

**Comment by Antarix** [comment]
i am using GUI method. can you explain me how to do this.

Thanks in advance

**Comment by Prototik** [comment]
I have no idea, only the console, only hardcore :)
Just clone ABS repo to contrib/ActionBarSherlock
