### ISSUE TITLE
Slider knob draws bar too far to the left

### ISSUE THREAD

**Issue by Michael-Zinn** [Prototik/HoloEverywhere#176]
While you move the knob in a slider it has a piece of filled out slider attached to it that goes out to the left. When you move the knob to the left side of the progress bar this slider graphic gets drawn outside of the actual slider which looks like the slider grows to the left side.

Picture of what the problem is:
![screen](https://dl.dropbox.com/u/54355119/PIC000015.jpg)

**Comment by Prototik** [comment]
I am sorry for necrophilia, but this bug is somehow fixed itself :)
