### ISSUE TITLE
Make activities look like Dialogs

### ISSUE THREAD

**Issue by crushergad** [Prototik/HoloEverywhere#177]
In android's documentation says: 

 If you want a custom dialog, you can instead display an Activity as a dialog instead of using the Dialog APIs. Simply create an activity and set its theme to Theme.Holo.Dialog in the <activity> manifest element:

<activity android:theme="@android:style/Theme.Holo.Dialog" >

That's it. The activity now displays in a dialog window instead of fullscreen.

It would be great if we could achieve this with HoloEverywhere, it is posible?

Thnk You!

**Comment by Prototik** [comment]
Use @style/Holo.Theme.Dialog

**Comment by crushergad** [comment]
It doesn't seem to work :/

android:theme="@style/Holo.Theme.Dialog">
"error: Error: No resource found that matches the given name (at 'theme' with value '@style/Holo.Theme.Dialog')."

I'm using the master version on eclipse so it should be updated.

I really appreciate the help! This is an university project and I'm a little bit lost!

**Comment by Prototik** [comment]
[styles.xml, line 355](https://github.com/ChristopheVersieux/HoloEverywhere/blob/master/library/res/values/styles.xml#L355)
