### ISSUE TITLE
Are popup menus supported?

### ISSUE THREAD

**Issue by PureSpider** [Prototik/HoloEverywhere#179]
I am trying to get popup menus to work with android 2.2+, are they somehow supported by HE?
See http://developer.android.com/guide/topics/ui/menus.html#PopupMenu for reference.

**Comment by Prototik** [comment]
Test support appeared in dev branch.

**Comment by PureSpider** [comment]
How to use it?

**Comment by Prototik** [comment]
[See demo](https://github.com/ChristopheVersieux/HoloEverywhere/blob/dev/demo/src/org/holoeverywhere/demo/fragments/MainFragment.java#L106)

**Comment by PureSpider** [comment]
Is `prepareMenu(menu.getMenu());` a method you would also use on native 4.x code or is it specific to HE?

**Comment by Prototik** [comment]
prepareMenu applies only to the demo, it just sets the checkbox on the menu item.

**Comment by PureSpider** [comment]
Ah, just seen that, so the code I'd use to emulate the example on the android developer page would be

``` java
    public void showPopupMenu(View v) {
        PopupMenu menu = new PopupMenu(getActivity(), v);
        menu.inflate(R.menu.menu);
        menu.show();
    }
```

Right? :)

**Comment by Prototik** [comment]
Yes.

**Comment by PureSpider** [comment]
And I assume that also works just as fine on 4.x then? :)

**Comment by Prototik** [comment]
Are there any problems? No? And why it should non-work?

**Comment by PureSpider** [comment]
Just asking :)
Will try it later, thanks for your hard work so far!

**Comment by PureSpider** [comment]
Hmmm it's not building for me: http://nopaste.info/d5c9d78e8a.html

**Comment by Prototik** [comment]
Package changed from com.WazaBe.HoloEverywhere to org.holoeverywhere. And SActivity not exists more.

**Comment by PureSpider** [comment]
I am not even trying to build my OWN project, I just tried to build the HE library project.
What do I need to do to make it work again?

**Comment by Prototik** [comment]
Once again: NetBeans tries to compile classes from com.WazaBe.HoloEverywhere, and they're there! But in dev branch all classes moved in the package org.holoeverywhere. As you switch a branch? `git checkout dev` or otherwise?

**Comment by PureSpider** [comment]
I have replaced all my sources with the sources from the dev branch, yes!

The manifest file looks like this:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="org.holoeverywhere"
    android:versionCode="22"
    android:versionName="1.3.4" >
    <uses-sdk
        android:minSdkVersion="7"
        android:targetSdkVersion="16" />
</manifest>
```

Which is definitely the one from the dev branch, so I have no idea what I am doing wrong?

I will check out the files once again and try to compile again.

**Comment by Prototik** [comment]
Now carefully remove the mess that you've do, and download the source code again.

**Comment by PureSpider** [comment]
Yeah you were right, quite a mess of old and new source files mixed together, the library is compiling fine now! :)
You mentioned SActivity doesn't exist anymore, what do I need to use instead?

At the moment I am using `com.WazaBe.HoloEverywhere.sherlock.SActivity` and `com.WazaBe.HoloEverywhere.sherlock.SListActivity`, guess I need to change that to `org.holoeverywhere.app.Activity` and `org.holoeverywhere.app.ListActivity`, right?

**Comment by Prototik** [comment]
Yes.

**Comment by PureSpider** [comment]
Okay thanks, everything is working now :)
Will test the popup menu tomorrow and report back if it works!

**Comment by PureSpider** [comment]
Popup menus are working like a charm man, thanks! :)

**Comment by Prototik** [comment]
Nothing is true. With OpenSource power - everything is permitted. ;)
