### ISSUE TITLE
Dialog Title unreadable on small displays & landscape mode

### ISSUE THREAD

**Issue by jonasbark** [Prototik/HoloEverywhere#18]
See: http://img137.imageshack.us/img137/7171/device20120523204111.png

Steps to reproduce:
- use e.g. Theme.HoloEverywhereLight on your Activity
- open AlertDialog or ListPreference with more than 4 items
- Title text is white on white background

Only on devices in landscape mode with small display (QVGA)

**Comment by Prototik** [comment]
1a73ab0297138c0a701b390376c896cf26ec913b
