### ISSUE TITLE
Missing the ToggleButton and RadioButton widgets

### ISSUE THREAD

**Issue by bkhall** [Prototik/HoloEverywhere#180]
First, great work!

Just wanted to point out that the released version (and the dev version) are missing the ToggleButton and RadioButton widgets.

**Comment by Prototik** [comment]
What is that to you?
![Screen 1](http://i.imgur.com/5mUEE.png)
![Screen 2](http://i.imgur.com/YF6bi.png)

**Comment by bkhall** [comment]
Hi Sergey,

Yes I see them, but they are not in your package. They are the native classes. If that is what we are supposed to use – fine, but it’s not consistent with the rest of your widget implementations, which all extend the native classes.

Also, in the dev package you pushed this morning, don’t forget to update the README when you merge with Master, now that your package name has changed and the Activities no longer have the “S”

Regards,
Baron

**Comment by Prototik** [comment]
> Also, in the dev package you pushed this morning, don’t forget to update the README when you merge with Master, now that your package name has changed and the Activities no longer have the “S”

Not quite clear why this is.
Yes, for the next release, I will try to do help more informatianoy. And help take care of the update to the new version. I do not have to comment on any function that has just appeared in the dev branch.
