### ISSUE TITLE
DatePickerDialog always calls OnDateSetListener.onDateSet()

### ISSUE THREAD

**Issue by 4nd3250n** [Prototik/HoloEverywhere#181]
Problem:
DatePickerDialog is initialized with a given date. User selects another date and then presses cancel button. The DatePickerDialog.OnDateSetListener.onDateSet() method is called. I think it shoold not be called as there is no other way to know that change date was cancelled. On confirmation it is called twice, on cancel just once.
First time it is called within DatePickerDialog.onClick() method where it is checked if button was BUTTON_POSITIVE. This is ok.
If one look at DatePickerDialog.onStop() we see that tryNotifyDateSet() is called in every case. This is not ok.

**Comment by bkhall** [comment]
The complete problem and recommended workaround is documented here:

http://stackoverflow.com/questions/11444238/jelly-bean-datepickerdialog-is-there-a-way-to-cancel/11493752#11493752

I would not recommend folding this into HoloEverywhere. Instead, developers should implement the workaround in their own projects - but that's just my recommendation.
