### ISSUE TITLE
Inconsistent DialogFragment Presentation

### ISSUE THREAD

**Issue by bkhall** [Prototik/HoloEverywhere#182]
When using a HoloEverywhere DialogFragment built through onCreateView(), the resulting dialog does not pick up the Holo theme correctly on platforms older than ICS. HoneyComb is missing the titlebar separator. Older platforms are missing the separator too and render in the platform default theme.

The only way I could get consistent Holo presentations on older platforms was to build the DialogFragment through onCreateDialog(), using the HoloeEverywhere AlertDialog.Builder() class. This is fine for simple dialogs. Highly customize dialog views (such as mine) need to be created through the onCreateView() method.

**Comment by Prototik** [comment]
![Screen](http://i.imgur.com/3j6Gw.png)
DialogFragment. What's wrong? Android 2.1.

**Comment by bkhall** [comment]
Hi Sergey,

They only way I can get this to work across all platforms is to build the dialog fragment through onCreateDialog(), returning an AlertDialog with its internal view inflated from my custom layout.

If I try to build the same dialog through onCreateView() and inflate the exact same layout file, I get what you see in the attachments:

ICS & JB are correct.
![Screen 1](http://i.imgur.com/CuSzR.png)

HC is partially correct.
![Screen 2](http://i.imgur.com/oe5rA.png)

GB, FY, and older are not correct.
![Screen 3](http://i.imgur.com/3TEZq.png)
![Screen 4](http://i.imgur.com/jss6t.png)

Like I said, I can make it work with onCreateDialog(), but this particular class is a super class for other views which are not dialogs and need to override onCreateView().

This is the only item in our app that is not picking up the theme correctly.

Any thoughts?

Baron
