### ISSUE TITLE
DialogFragment Missing TitleBar

### ISSUE THREAD

**Issue by bkhall** [Prototik/HoloEverywhere#184]
Relates to issue #182.

Commit 1321cd9 fixed most of the styling issues mentioned in 182. However, it introduced a new issue.

DialogFragments created through onCreateView() are missing the titlebar and the titlebar separator on platforms prior to ICS.

**Comment by Prototik** [comment]
Reopen,  last fix is very bad, need to rewrite.

**Comment by bkhall** [comment]
Hope you get it fixed so that your implementation works like the native impmentation through onCreateView().

For now, I've rewritten my class to build the dialog through onCreateDialog() to work around the issue and allow our app to be released.
