### ISSUE TITLE
ListView does not refreshes

### ISSUE THREAD

**Issue by kostik1337** [Prototik/HoloEverywhere#185]
ListView can't be refreshed dynamically: when I try to refresh it on spinner's onItemSelected event - it just doesn't refreshes

``` java
package com.campuz.choosingactivities;

import android.os.Bundle;
import android.view.View;
import com.WazaBe.HoloEverywhere.ArrayAdapter;
import com.WazaBe.HoloEverywhere.app.Activity;
import com.WazaBe.HoloEverywhere.widget.AdapterView;
import com.WazaBe.HoloEverywhere.widget.ListView;
import com.WazaBe.HoloEverywhere.widget.Spinner;
import com.campuz.R;

import java.util.ArrayList;

public class ExampleActivity extends Activity {
    ArrayList<String> spinnerItems = new ArrayList<String>();

    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_choose_event);

        spinnerItems.add("from 1 to 2");
        spinnerItems.add("from 3 to 4");

        final ListView eventList = (ListView) findViewById(R.id.list_view);

        ArrayAdapter<String> arrayAdapter = new ArrayAdapter<String>(this, R.layout.simple_spinner_item, spinnerItems);
        arrayAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);

        Spinner spinner = (Spinner) findViewById(R.id.spinner);
        spinner.setAdapter(arrayAdapter);
        spinner.setSelection(0);

        final ArrayAdapter<String> adapter = new ArrayAdapter<String>(this, android.R.layout.simple_list_item_1, new ArrayList<String>());
        eventList.setAdapter(adapter);

        spinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                if(position==0){
                    adapter.clear();
                    adapter.addAll("item 1", "item 2");
                } if(position==1){
                    adapter.clear();
                    adapter.addAll("item 3", "item 4");
                }
                adapter.notifyDataSetChanged();
                eventList.invalidate();
            }

            @Override
            public void onNothingSelected(AdapterView<?> arg0) {
            }
        });
    }
}
```

**Comment by kostik1337** [comment]
Hey, does anyone knows how to fix this?

**Comment by Prototik** [comment]
It's bug in system ListView when list data updates in background window.
When you click on Spinner - showing popup window with spinner items, activity window has flag focus = false.

Temp workaround:
Override method onWindowFocusChanged in Activity:

``` java
    @Override
    public void onWindowFocusChanged(boolean hasFocus) {
        super.onWindowFocusChanged(hasFocus);
        if (hasFocus) {
            listView.onWindowFocusChanged(true);
            listView.invalidate();
            listView.invalidateViews();
        }
    }
```

**Comment by kostik1337** [comment]
Thanks, it's working.

**Comment by bdovaz** [comment]
I have a similar problem (in my case it's a FRAGMENT not an activity):
1. Click on a spinner item.
2. Change the data in the spinner listener.
3. Call notifyDataSetChanged;

The weird thing is that it doesn't update the view but if I start dragging it refreshes itself.

How can I fix all of this?

Thanks!!

P.D: In 4.3 I haven't any problem but in 4.0 or 4.1 yes.

**Comment by bdovaz** [comment]
Anything?

Thanks!

**Comment by ksennoun** [comment]
Hi prototik! I'm facing same issue as N3uRo here. Can you help with that?

**Comment by bdovaz** [comment]
My "workaround" was to change the Spinner to a custom dialog, it's not the same but it works on all versions.

**Comment by ksennoun** [comment]
Thanks. But I can't figure out why would changing from spinner to dialog fix the issue... Do you mean it is the itemchangelistener from spinner that provides sort of  "a wrong context"?

**Comment by bdovaz** [comment]
Not fix but a workaround... It's a similiar approach:

http://developer.android.com/guide/topics/ui/dialogs.html

You can implement single choice Dialogs, it's not the same but very similar to a Spinner.

**Comment by 0iron0** [comment]
I met a same issue. When i select spinner view and change the data source of spinner on the action bar, then, list view on the fragment will be blank. If I touch the screen, get view will be triggered.

And I tried build-in spinner, it is no this issue.

Same as http://stackoverflow.com/questions/21282964/notifiydatasetchanged-makes-listview-disappear-until-touch/22411606#22411606

**Comment by smith2310** [comment]
For anyone who may run into this issue, the trick is to post the action in the queue otherwise because the listView doesn't have the focus it does nothing.

```
    getListView().post(new Runnable() {
        @Override
        public void run() {
            mAdapter.notifyDataSetChanged();
        }
    });
```
