### ISSUE TITLE
EditText does not trigger Clipboard-services

### ISSUE THREAD

**Issue by TheNephilim88** [Prototik/HoloEverywhere#186]
Its not possible to copy or paste something into EditText-widgets.

**Comment by TheNephilim88** [comment]
Does anyone have a solution/workaround for this?

**Comment by Prototik** [comment]
No, I don't  have workaround for this.

**Comment by vinc3m1** [comment]
This seems to only affect pre-honeycomb devices. Anyone have any updates?

**Comment by vinc3m1** [comment]
I think I found the issue:

the method at line 256 of [_HoloActivity](https://github.com/ChristopheVersieux/HoloEverywhere/blob/master/library/src/android/support/v4/app/_HoloActivity.java)

``` java
@Override
    public void onCreateContextMenu(ContextMenu menu, View view,
            ContextMenuInfo menuInfo) {
        if (menu instanceof ContextMenuWrapper) {
            super.onCreateContextMenu(((ContextMenuWrapper) menu).unwrap(),
                    view, menuInfo);
        }
    }
```

in this case, menu is actually a `ContextMenuBuilder`, so the `if (menu instanceof ContextMenuWrapper)` statement fails and `super.onCreateContextMenu()` is never called. Unfortunately I can't figure out how to convert something from `ContextMenuBuilder` into `android.view.ContextMenu`.

**Comment by vinc3m1** [comment]
As a temporary workaround, setting: `Application.config().setDisableContextMenu(true);` in your application forces HoloEverywhere to use system context menus, so on ICS devices, you get the default context menus with rounded corners but this gets EditText context menus working. Don't forget to call the super `super.onCreateContextMenu(menu, v, menuInfo);` in your onCreateContextMenu.

You can see the code that affects this in: [`showContextMenuForChild` in ContextMenuDecorView](https://github.com/ChristopheVersieux/HoloEverywhere/blob/master/library/src/com/actionbarsherlock/internal/view/menu/ContextMenuDecorView.java#L102) is the offending function that returns a `ContextMenuBuilder`

**Comment by minioreo** [comment]
any update?

**Comment by Prototik** [comment]
@minioreo 

> As a temporary workaround, setting: `Application.config().setDisableContextMenu(true);`

I'm working on it.
