### ISSUE TITLE
How to change theme at runtime

### ISSUE THREAD

**Issue by 4nd3250n** [Prototik/HoloEverywhere#189]
Goal:
Have a user choose a theme form predefined list and then change a theme application wide to the chosen theme. How does one accomplish that with Holoeverywhere? There is absolutely no documentation so I am posting this as a question here.

I tried to do it the following way:
1. Define a variation on Holo Dark theme with some drawable for action bar menu and few custom text styles.

``` xml
<style name="ThemeHoloDark" parent="@style/Holo.Theme.Fullscreen">
    <item name="ic_action_about">@drawable/ic_action_about_holo_dark</item>
    <item name="text_color_data">#ffffffff</item>       
</style> 
<style name="ThemeHoloLight" parent="@style/Holo.Theme.Light.Fullscreen">
    <item name="ic_action_about">@drawable/ic_action_about_holo_light</item>
    <item name="text_color_data">#ffffffff</item>       
</style> 
```
1. I have implemented selection of theme via Preferences, yet this could also be achieved in some other way as long as a desired theme is persisted somewhere.
2. In every activity's onCreate() method there is a block of code:

``` java
SharedPreferences sharedPreferences = PreferenceManager.getDefaultSharedPreferences(activity);
String themeValue = sharedPreferences.getString("KEY_THEME", "THEME_HOLO_DARK");
if (themeValue.equals("THEME_HOLO_DARK")) activity.setTheme(R.style.ThemeHoloDark);
if (themeValue.equals("THEME_HOLO_LIGHT")) activity.setTheme(R.style.ThemeHoloLight);
```

I looked at the ThemeManager class but as there is no documentation there is not much one can do with it. By peeking in a source code I gathered that it is only intended to manage 3 in built themes. Am I wrong on this point? In that case what is the correct usage of ThemeManager? Is it possible to provide at least some minimum of documentation?
In sample source code I also noticed @Holo annotation. What is the purpose of this annotation, what is the usage?Again.. no documentation.
Blindly guessing by black box trying takes awful lot of time when one consideres that eclipse need about 5 minutes to launch an application. Emulator is completely unusable.

How to remove title bar?

Is there a more elegant way to change theme at runtime?

**Comment by 4nd3250n** [comment]
Bumping this one up as we still do not have an answer.

**Comment by edubsi** [comment]
Your Code looks fine to me. What I am doing is:

```
preferences = PreferenceManager.getDefaultSharedPreferences(this);
int themeId = preferences.getInt(SHARED_PREFERENCES_THEME, R.style.Holo_Theme);
setTheme(themeId);
super.onCreate(savedInstanceState);
```

It is important that you set your Theme before you set your Content View && call the onCreate (That's what I figured out right now)
You mean the ActionBar with TitleBar?
Here is a Question on StackOverflow: http://stackoverflow.com/questions/8456835/how-to-disable-action-bar-permanently
Basically it is:
- getActionBar.hide()  OR getSupportActionBar.hide()
- set the Theme to "Theme.Holo.Light.NoActionBar" e.g.

Good Luck hope it was helpful.

**Comment by 4nd3250n** [comment]
What i figured via black box testing, AS THERE IS NO DOCUMENTATION, which is a real issue is:
You cannot change a theme on an application level. You have to do it individually in for each activity.
Another complicatin is that you cannot use SharedPreferences as there is no way to init them to some default value.
So you have to find a way to persist and init your settings.
And in some cases you must be carefull which context are you using. Application context does not necesarilly carry all the information an activity context does.

**Comment by Prototik** [comment]
ThemeManager now has a docs and you can see using custom themes in demo.
