### ISSUE TITLE
error in _HoloActivity

### ISSUE THREAD

**Issue by ru-nekit-android** [Prototik/HoloEverywhere#191]
Master branch:
public abstract class Activity extends _HoloActivity ->
_HoloActivity code:
@Override
    public void supportInvalidateOptionsMenu() {
            invalidateOptionsMenu();
    }
but  invalidateOptionsMenu added in API level 11.

**Comment by Prototik** [comment]
[_HoloActivity.java line 360](https://github.com/ChristopheVersieux/HoloEverywhere/blob/dev/library/src/android/support/v4/app/_HoloActivity.java#L360)
