### ISSUE TITLE
Demo screen cannot be scrolled to the bottom in the emulator 2.1

### ISSUE THREAD

**Issue by httpdispatch** [Prototik/HoloEverywhere#194]
Demo screen and left pane menu cannot be scrolled to the bottom in some cases in the emulator 2.1
Holo branch: dev
![](http://dl.dropbox.com/u/37011471/Openphoto/device-2012-11-12-100759.png)

**Comment by Prototik** [comment]
Yea, it's 2.1 bug with fullscreen mode. Long press on home button fix it. Fullscreen flag will be cleared in 1.4 release.
Долбанный 2.1, сто лет его не видеть бы :D
