### ISSUE TITLE
AlertDialog.Builder.setTitle is ignored if it is used in the DialogFragment

### ISSUE THREAD

**Issue by httpdispatch** [Prototik/HoloEverywhere#197]
Instead of defined title i see text "Title"

**Comment by bkhall** [comment]
It works when you do it like this:

public class AboutDialogFragment extends DialogFragment {

```
@Override
public AlertDialog onCreateDialog(Bundle savedInstanceState) {
    super.onCreateDialog(savedInstanceState);
    View view = LayoutInflater.from(getActivity()).inflate(R.layout.about,
            null);

    return new AlertDialog.Builder(getActivity())
            .setTitle(R.string.settings_about)
            .setView(view)
            .setPositiveButton(android.R.string.ok, null).create();
}
```

}

EDIT: I checked my repo and I am still using commit 1321cd9. I have not tested the commit that closed issue #184, which changed the DialogFragment class.

**Comment by bkhall** [comment]
I updated to commit 499e8578d6 on dev and the method described above still works.

**Comment by httpdispatch** [comment]
@bkhall I don't use setView method in AlertDialog.Builder. I'm using setItems. Maybe when setItems is used something different happen inside holoeverywhere

**Comment by bkhall** [comment]
@httpdispatch Using setView was not the relevant piece of my post.

The point was that setTitle works when done as shown. I offered it as a way to solve the problem you described about setTitle not working.

**Comment by httpdispatch** [comment]
``` java
        @Override
        public Dialog onCreateDialog(Bundle savedInstanceState) {
            final CharSequence[] items = {
                    "one",
                    "two"
            };

            AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
            builder.setTitle(R.string.my_title);
            builder.setItems(items, new DialogInterface.OnClickListener() {
                @Override
                public void onClick(DialogInterface dialog, int item) {
                 // DO NOTHING
                }
            });
            return builder.create();
        }
```

**Comment by httpdispatch** [comment]
@bkhall can you please check the above code?

**Comment by bkhall** [comment]
@httpdispatch You are missing a call to super.onCreateDialog(saveInstanceState);

Also, what is the actual string value of R.string.my_title;

**Comment by httpdispatch** [comment]
@bkhall use any string from you resources

**Comment by httpdispatch** [comment]
@bkhall also i'm not sure i should to call super onCreateDialog which creates another unused dialog

**Comment by Prototik** [comment]
``` java
public class AlertDialogFragment extends DialogFragment {
    @Override
    public Dialog onCreateDialog(Bundle savedInstanceState) {
        final CharSequence[] items = {
                "One",
                "Two",
                "Three"
        };
        AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
        builder.setTitle(R.string.about);
        builder.setItems(items, new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int item) {
                // DO NOTHING
            }
        });
        return builder.create();
    }
}
```

![Screen](http://i.imgur.com/ez7u0.png)

**Comment by httpdispatch** [comment]
I have to sorry about that. The issue cause was that the strings.xml had 2 occurrence of my title. Second was wrong.

**Comment by bkhall** [comment]
@Prototik the text size of the items in the list is not correct, though.
