### ISSUE TITLE
Parent menu can be duplicated if setHasOptionsMenu(true) is used inside Fragment

### ISSUE THREAD

**Issue by httpdispatch** [Prototik/HoloEverywhere#198]
I'm trying to use standalone menus in fragment. Technique is described here http://startandroid.ru/uroki/vse-uroki-spiskom/182-urok-112-android-3-actionbar-dinamicheskoe-razmeschenie-elementov.html
The thing is that parent menu become duplicated once i attach the fragment with custom menu. It looks like this
![](http://dl.dropbox.com/u/37011471/Openphoto/device-2012-11-12-111955.png)
As you can see refresh and preferences menu items appear twice. Also second refresh appearance is much smaller

**Comment by Prototik** [comment]
OptionsMenu don't replaced by fragment, it's added to general menu, inflated into activity or other fragments.

**Comment by httpdispatch** [comment]
I understand this. But in the fragment menu i have only one menu item. But i see that parent menu items processed twice and have duplicates

**Comment by httpdispatch** [comment]
@Prototik can you please reopen this?

**Comment by Prototik** [comment]
Code. Or test it with only ActionBarSherlock.

**Comment by httpdispatch** [comment]
I've tested with ABS only and it works correct. Here is the project link
http://dl.dropbox.com/u/37011471/Openphoto/P1121_DynamicActionBar_ABS_Only.zip

Then i've added Holoeverywhere support and all become to work as reported in the issue. Parent menu items get duplicated
Here the link is to the project which demonstrates the issue
http://dl.dropbox.com/u/37011471/Openphoto/P1121_DynamicActionBar_Holoeverywher.zip

**Comment by Prototik** [comment]
Remove calling super.onCreateOptionsMenu in fragments. And in activity.

**Comment by httpdispatch** [comment]
But why it works properly in ABS and in the standard android actionbar?
