### ISSUE TITLE
Holo.Theme.Dialog.Light strange border around the dialog and view doesn't fit the dialog window

### ISSUE THREAD

**Issue by httpdispatch** [Prototik/HoloEverywhere#199]
Please see the shot. I've got this unexpected behaviour after the upgrading to the HE 1.4 dev. You can see border around the custom dialog. Also the bottom textview is truncated
![](http://dl.dropbox.com/u/37011471/Openphoto/device-2012-11-12-113005.png)

**Comment by Prototik** [comment]
Dialog or AlertDialog?

**Comment by httpdispatch** [comment]
DialogFragment with the view inflated from xml in the onCreateView method

**Comment by Prototik** [comment]
I'm don't can repeat this bug, code please.

**Comment by httpdispatch** [comment]
In the styles i have defined custom style inherited from Holo.Theme.Dialog.Light

``` xml
<style name="Theme.OpenPhoto.Dialog.Light" parent="Holo.Theme.Dialog.Light">
```

In the DialogFragment.onCreate i have code like this

``` java
setStyle(STYLE_NORMAL, R.style.Theme_OpenPhoto_Dialog_Light);
```

**Comment by Prototik** [comment]
... parent="Holo.Theme.Dialog.Alert.Light">
