### ISSUE TITLE
ListPreference failing on some platforms

### ISSUE THREAD

**Issue by bkhall** [Prototik/HoloEverywhere#203]
ListPreference seems to be failing on tablets with Android 4.0.3 and lower.

Stack trace says the "text" object is null in line 204 of ArrayAdapter.

The issue was that the passed view from the if block at line 184 was a CheckedTextView and the mFieldId was NOT zero.

So the if block at line 190 was entering the ELSE case - resulting in a null object.

I solved the isssue by modifying line 190 as follows:

if (mFieldId == 0 || view instanceof TextView) {...

**Comment by Prototik** [comment]
Mmm, in ArrayAdapter uses android.widget.TextView - if view cannot be cast to it - view is generally something not textual.

**Comment by bkhall** [comment]
Yes, I know...that's why I check the type with a call to instanceof before casting.

The list preference uses simple_list_item_single_choice.xml for its layout which has a CheckedTextView as the root view. That could be why the view.findViewById() call returns null - there isn't a child view at all.

It is very strange. I was able to reproduce it on two devices though - one running 4.03 (Asus) and one running 3.1 (Motorola Xoom).

**Comment by Prototik** [comment]
List Preference use select dialog single choice layout.  You may show full stacktrace of crash?

**Comment by bkhall** [comment]
Yes, sorry, that is correct. However, the select_dialog_single_choice.xml file is a virtual copy of the simple_list_item_single_choice.xml.

They both have a CheckedTextView as the view root, therefore, my point is the same.

I'll submit the stacktrace when I get into the office. I'll have to pull out the change to get it to happen again.

**Comment by bkhall** [comment]
As requested:

This was on an emulator running 3.2

My original post describes why.

11-21 07:46:37.095: E/AndroidRuntime(405): FATAL EXCEPTION: main
11-21 07:46:37.095: E/AndroidRuntime(405): java.lang.NullPointerException
11-21 07:46:37.095: E/AndroidRuntime(405):  at org.holoeverywhere.ArrayAdapter.createViewFromResource(ArrayAdapter.java:204)
11-21 07:46:37.095: E/AndroidRuntime(405):  at org.holoeverywhere.ArrayAdapter.getView(ArrayAdapter.java:250)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.widget.AbsListView.obtainView(AbsListView.java:1970)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.widget.ListView.measureHeightOfChildren(ListView.java:1228)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.widget.ListView.onMeasure(ListView.java:1139)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.view.View.measure(View.java:10828)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4351)
11-21 07:46:37.095: E/AndroidRuntime(405):  at org.holoeverywhere.widget.LinearLayout.measureChildWithMargins(LinearLayout.java:233)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1284)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.widget.LinearLayout.measureVertical(LinearLayout.java:613)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.widget.LinearLayout.onMeasure(LinearLayout.java:519)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.view.View.measure(View.java:10828)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4351)
11-21 07:46:37.095: E/AndroidRuntime(405):  at org.holoeverywhere.widget.LinearLayout.measureChildWithMargins(LinearLayout.java:233)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1284)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.widget.LinearLayout.measureVertical(LinearLayout.java:613)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.widget.LinearLayout.onMeasure(LinearLayout.java:519)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.view.View.measure(View.java:10828)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4351)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.widget.FrameLayout.onMeasure(FrameLayout.java:267)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.view.View.measure(View.java:10828)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4351)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.widget.FrameLayout.onMeasure(FrameLayout.java:267)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.view.View.measure(View.java:10828)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4351)
11-21 07:46:37.095: E/AndroidRuntime(405):  at org.holoeverywhere.widget.LinearLayout.measureChildWithMargins(LinearLayout.java:233)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1284)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.widget.LinearLayout.measureVertical(LinearLayout.java:613)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.widget.LinearLayout.onMeasure(LinearLayout.java:519)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.view.View.measure(View.java:10828)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4351)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.widget.FrameLayout.onMeasure(FrameLayout.java:267)
11-21 07:46:37.095: E/AndroidRuntime(405):  at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:1889)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.view.View.measure(View.java:10828)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.view.ViewRoot.performTraversals(ViewRoot.java:913)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.view.ViewRoot.handleMessage(ViewRoot.java:2040)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.os.Handler.dispatchMessage(Handler.java:99)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.os.Looper.loop(Looper.java:132)
11-21 07:46:37.095: E/AndroidRuntime(405):  at android.app.ActivityThread.main(ActivityThread.java:4123)
11-21 07:46:37.095: E/AndroidRuntime(405):  at java.lang.reflect.Method.invokeNative(Native Method)
11-21 07:46:37.095: E/AndroidRuntime(405):  at java.lang.reflect.Method.invoke(Method.java:491)
11-21 07:46:37.095: E/AndroidRuntime(405):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
11-21 07:46:37.095: E/AndroidRuntime(405):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
11-21 07:46:37.095: E/AndroidRuntime(405):  at dalvik.system.NativeStart.main(Native Method)

**Comment by bkhall** [comment]
More info:

Knowing that the ListPreference extends DialogPreference which extends Dialog. I've just done several tests with normal dialogs and alertdialogs, (not a preference) and this issue affects ANY dialog that uses a checkable list that goes through the ArrayAdapter.

I get the exact same stack trace - but only on platforms 3.0 to 4.03.
