### ISSUE TITLE
Need a SearchView

### ISSUE THREAD

**Issue by toadzky** [Prototik/HoloEverywhere#207]
I use the ActionBarSherlock SearchView, but the internal class extends the Android EditText. It would be nice to have all my widgets using HoloEverywhere.

**Comment by Prototik** [comment]
Internal? android.widget.SearchView?

``` java
public class SearchView extends LinearLayout implements CollapsibleActionView {
...
```

**Comment by toadzky** [comment]
The ABS SearchView has a custom EditText view inside it, which extends the native EditText view. I have to set properties on the EditText, so in just a couple places in my code, I have to import both the Holoeverywhere EditText and the native EditText.  I think it would be awesome if HoloEverywhere had a SearchView
