### ISSUE TITLE
ListView filled with ArrayAdapter not workin on Android > 4.0

### ISSUE THREAD

**Issue by a0g83agbc84** [Prototik/HoloEverywhere#208]
I'm trying to fill a ListView using an ArrayAdapter:

---

final ArrayAdapter<String> adapter = new ArrayAdapter<String>(this, R.layout.simple_list_item_1, tricks);
## lv.setAdapter(adapter); // THIS is the problematic thing that causes FC

"R.layout.simple_list_item_1" is the one in the res/layout folder of the HoloEverywhere library.

This is how I've declared the class on the manifest.xml

<activity
        android:name=".TricksList"
        android:theme="@style/Holo.Theme.Light.NoActionBar"
        android:screenOrientation="portrait" />

In devices and emulators with android < 4.0, it works great, but older Android versions show FC. Here's the stackstrace:

11-28 19:04:54.343: E/AndroidRuntime(32446): FATAL EXCEPTION: main
11-28 19:04:54.343: E/AndroidRuntime(32446): android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.LayoutInflater.createView(LayoutInflater.java:606)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at org.holoeverywhere.LayoutInflater.tryCreateView(LayoutInflater.java:347)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:299)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:653)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:678)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:278)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:263)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at org.holoeverywhere.ArrayAdapter.createViewFromResource(ArrayAdapter.java:185)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at org.holoeverywhere.ArrayAdapter.getView(ArrayAdapter.java:250)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.widget.AbsListView.obtainView(AbsListView.java:2476)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.widget.ListView.makeAndAddView(ListView.java:1772)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.widget.ListView.fillDown(ListView.java:672)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.widget.ListView.fillFromTop(ListView.java:732)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.widget.ListView.layoutChildren(ListView.java:1625)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.widget.AbsListView.onLayout(AbsListView.java:2306)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.View.layout(View.java:11369)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.ViewGroup.layout(ViewGroup.java:4224)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1658)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1647)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1431)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.View.layout(View.java:11369)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.ViewGroup.layout(ViewGroup.java:4224)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:980)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.View.layout(View.java:11369)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.ViewGroup.layout(ViewGroup.java:4224)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.View.layout(View.java:11369)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.ViewGroup.layout(ViewGroup.java:4224)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.View.layout(View.java:11369)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.ViewGroup.layout(ViewGroup.java:4224)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1658)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1516)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1429)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.View.layout(View.java:11369)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.ViewGroup.layout(ViewGroup.java:4224)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.View.layout(View.java:11369)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.ViewGroup.layout(ViewGroup.java:4224)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1510)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2469)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.os.Handler.dispatchMessage(Handler.java:99)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.os.Looper.loop(Looper.java:137)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.app.ActivityThread.main(ActivityThread.java:4516)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at java.lang.reflect.Method.invokeNative(Native Method)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at java.lang.reflect.Method.invoke(Method.java:511)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at dalvik.system.NativeStart.main(Native Method)
11-28 19:04:54.343: E/AndroidRuntime(32446): Caused by: java.lang.reflect.InvocationTargetException
11-28 19:04:54.343: E/AndroidRuntime(32446):    at java.lang.reflect.Constructor.constructNative(Native Method)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.LayoutInflater.createView(LayoutInflater.java:586)
11-28 19:04:54.343: E/AndroidRuntime(32446):    ... 50 more
11-28 19:04:54.343: E/AndroidRuntime(32446): Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x2
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.view.View.<init>(View.java:2804)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at android.widget.TextView.<init>(TextView.java:467)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at org.holoeverywhere.widget.TextView.<init>(TextView.java:26)
11-28 19:04:54.343: E/AndroidRuntime(32446):    at org.holoeverywhere.widget.TextView.<init>(TextView.java:22)
11-28 19:04:54.343: E/AndroidRuntime(32446):    ... 53 more

I've been reading this other issue: https://github.com/ChristopheVersieux/HoloEverywhere/issues/81

But that guy solved it removeing the layout-v14 from his project whereas I dont have this folder due to a higher version.

I've been testing other themes and the only working is this: android:theme="@style/Holo.Theme.Dialog.Light"

But I do not want a Dialog theme...

I've also tested the original Android layout: android.R.layout.simple_list_item_1, but this layout si awfull...

Which can be the problem? Thank you in advance!

**Comment by bkhall** [comment]
Awesome! Just ran into this yesterday. Nice to see it already fixed.
