### ISSUE TITLE
Work around Typeface.createFromAsset memory leak

### ISSUE THREAD

**Issue by tverona** [Prototik/HoloEverywhere#21]
Hi,

I ran into an Android memory leak issue & I thought you may want to consider working around this in HoloEverywhere. Here are the details:

I noticed that my app's memory consumption kept increasing as I navigated through the UI. I ran "adb shell dumpsys meminfo" and found that the Roboto type face assets seemed to get leaked each time we load the asset:

 Asset Allocations
    zip:/data/app/com.pansieve.telemetry-2.apk:/resources.arsc: 132K
    zip:/data/app/com.pansieve.telemetry-2.apk:/assets/Roboto-Regular.ttf: 155K
    zip:/data/app/com.pansieve.telemetry-2.apk:/assets/Roboto-Bold.ttf: 160K
    zip:/data/app/com.pansieve.telemetry-2.apk:/assets/Roboto-Regular.ttf: 155K
    zip:/data/app/com.pansieve.telemetry-2.apk:/assets/Roboto-Bold.ttf: 160K
    zip:/data/app/com.pansieve.telemetry-2.apk:/assets/Roboto-Regular.ttf: 155K
    zip:/data/app/com.pansieve.telemetry-2.apk:/assets/Roboto-Regular.ttf: 155K
    zip:/data/app/com.pansieve.telemetry-2.apk:/assets/Roboto-Regular.ttf: 155K
    ....

This seems to be an Android issue (at least for my device). I've implemented the following fix http://code.google.com/p/android/issues/detail?id=9904#c7 in my clone of HoloEverywhere. I'm not sure if this is a common issue, but may be something you'd want to work around. Let me know if you'd like me to push the changes to you.

Regards,
Tomer

**Comment by Prototik** [comment]
The fonts were moved to the raw resources 1a73ab0297138c0a701b390376c896cf26ec913b, others removed
