### ISSUE TITLE
TextView should be clickable by default

### ISSUE THREAD

**Issue by toadzky** [Prototik/HoloEverywhere#211]
I use basic TextViews all over as list items and buttons (usually with a compound drawable) and before I switched to HoloEverywhere 1.4 they worked just fine. Now they aren't clickable. 

I solved it by adding the "android:clickable" item to the style for "Holo.TextView".

EDIT: Not sure how to fix this one not that I've worked with it some more. I use TextView's a clickable items, and I never had to set the clickable attribute before. However, if you force all TextViews to be clickable, then TextView rows in your ListViews don't call the onListItemClick method for ListActivities or ListFragments. It may be that you should be making a TextView clickable if the onClick attribute is defined.

**Comment by Prototik** [comment]
No,  by default it's not clickable. If you call setOnClickListener  - then clickable flag will be setted.
