### ISSUE TITLE
findPreference in PreferenceActivity always returns null

### ISSUE THREAD

**Issue by gsingh93** [Prototik/HoloEverywhere#212]
Here is my preference:

```
<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android" >

<EditTextPreference
    android:capitalize="words"
    android:defaultValue="@string/pref_default_username"
    android:inputType="textCapWords"
    android:key="usernamePref"
    android:maxLines="1"
    android:selectAllOnFocus="true"
    android:singleLine="true"
    android:title="@string/pref_title_username" />

</PreferenceScreen>
```

And here is my PreferenceActivity:

```
import android.os.Bundle;
import android.preference.PreferenceActivity;

public class SettingsActivity extends PreferenceActivity {

@SuppressWarnings("deprecation")
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    addPreferencesFromResource(R.xml.pref_general);
    if (findPreference("usernamePref") == null) {
        throw new RuntimeException("preference is null");
    }
}

}
```

If I change the import to:

```
import org.holoeverywhere.preference.PreferenceActivity;
```

findPreference will always return null.

**Comment by 4nd3250n** [comment]
In the mean time you can check one thing:
Change the "schema declaration" to:
xmlns:holo="http://schemas.android.com/apk/res-auto"
Change all attribute name prefixes from android to holo.
For detail see:
https://github.com/ChristopheVersieux/HoloEverywhere/blob/master/demo/res/xml/preferences.xml

Report the result.

**Comment by Prototik** [comment]
Yea, use next layout:

``` xml
<PreferenceScreen xmlns:holo="http://schemas.android.com/apk/res-auto" 
   xmlns:android="http://schemas.android.com/apk/res/android" >

<EditTextPreference
    android:capitalize="words"
    holo:defaultValue="@string/pref_default_username"
    android:inputType="textCapWords"
    holo:key="usernamePref"
    android:maxLines="1"
    android:selectAllOnFocus="true"
    android:singleLine="true"
    holo:title="@string/pref_title_username" />

</PreferenceScreen>

```

**Comment by gsingh93** [comment]
Thanks, the layout Prototik provided works. There should be some documentation somewhere (outside the demos) that specifies when using the holo namespace should be used instead of the android namespace.

**Comment by jromero** [comment]
I agree with gsingh93. This is very important and easily overlooked.

**Comment by paulpv** [comment]
This most definitely should go in to a README.md file at:
https://github.com/wtcdev/HoloEverywhere/tree/master/addons/preferences

That and/or a fat comment in the demo preferences.xml explaining the "holo" namespace:
https://github.com/wtcdev/HoloEverywhere/blob/master/demo/res/xml/preferences.xml

Perhaps also a comment in:
https://github.com/wtcdev/HoloEverywhere/blob/master/demo/src/org/holoeverywhere/demo/fragments/SettingsFragment.java

I feel lucky to say that I only spent a few hours trying to figure out why my org.holoeverywhere.preference.PreferenceFragment subclass findPreference(...) method was always returning null.
