### ISSUE TITLE
Bug: PreferenceManager setDefaultValues() method not working

### ISSUE THREAD

**Issue by 4nd3250n** [Prototik/HoloEverywhere#213]
This bug is a deal breaker.

**Comment by 4nd3250n** [comment]
Any news about the issue? This one is urgent as it breaks the application behavior..

**Comment by Prototik** [comment]
Fixed via 15432a98

**Comment by 4nd3250n** [comment]
How does one apply the fix?

**Comment by Prototik** [comment]
@4nd3250n switch to dev branch
