### ISSUE TITLE
Could not find class: fragment

### ISSUE THREAD

**Issue by jblernout** [Prototik/HoloEverywhere#215]
This happens from time to time on android 2.3, I don't know exactly how to reproduce it !

E/AndroidRuntime(25147): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jbl.android.spotimote/com.blablabla}: android.view.InflateException: Binary XML file line #15: Error inflating class fragment
E/AndroidRuntime(25147):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1647)
E/AndroidRuntime(25147):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
E/AndroidRuntime(25147):        at android.app.ActivityThread.access$1500(ActivityThread.java:117)
E/AndroidRuntime(25147):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
E/AndroidRuntime(25147):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(25147):        at android.os.Looper.loop(Looper.java:130)
E/AndroidRuntime(25147):        at android.app.ActivityThread.main(ActivityThread.java:3683)
E/AndroidRuntime(25147):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(25147):        at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime(25147):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
E/AndroidRuntime(25147):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime(25147):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(25147): Caused by: android.view.InflateException: Binary XML file line #15: Error inflating class fragment
E/AndroidRuntime(25147):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:581)
E/AndroidRuntime(25147):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
E/AndroidRuntime(25147):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:626)
E/AndroidRuntime(25147):        at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
E/AndroidRuntime(25147):        at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:278)
E/AndroidRuntime(25147):        at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
E/AndroidRuntime(25147):        at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:263)
E/AndroidRuntime(25147):        at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:258)
E/AndroidRuntime(25147):        at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:253)
E/AndroidRuntime(25147):        at org.holoeverywhere.app.Activity.setContentView(Activity.java:241)
E/AndroidRuntime(25147):        at com.blablabla.onCreate(ActivityState.java:58)
E/AndroidRuntime(25147):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
E/AndroidRuntime(25147):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1611)
E/AndroidRuntime(25147):        ... 11 more
E/AndroidRuntime(25147): Caused by: java.lang.ClassNotFoundException: Could not find class: fragment
E/AndroidRuntime(25147):        at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:318)
E/AndroidRuntime(25147):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
E/AndroidRuntime(25147):        ... 23 more

 Caused by: java.lang.ClassNotFoundException: Could not find class: fragment
        at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:318)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)

I'm using the latest version of the android support library v4.

**Comment by 4nd3250n** [comment]
What build targer are you using? It might be you are compiling against newer API. When you run on the older device the class that was there at compile time might now exist.
Also... a good practice is to run clean after modifying xml files.

**Comment by jblernout** [comment]
I don't think it's an API version problem. I target API 16.

The app runs ok, everything works fine. To reproduce the problem, I switch to another app to put mine in the background, and from time to time, when I get back to my app it crashes with the error mentioned above.

I haven't changed the XML, I only switched from android.support.v4.app.Fragment to org.holoeverywhere.app.Fragment

**Comment by 4nd3250n** [comment]
What other imports are you using? code snippet?

**Comment by jblernout** [comment]
Just to add more info, the problem seems to only appear if I don't use the phone for a while and then return to my app.

The XML code is pretty basic: 

<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent" >

```
<LinearLayout
    xmlns:ads="http://schemas.android.com/apk/lib/com.google.ads"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:background="#ff000000"
    android:orientation="vertical" >

    <fragment
        android:id="@+id/stateFragment"
        android:name="com.jbl.android.spotimote.StateMgr.StateFragment"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:layout_weight="1" >

     <!-- Preview: layout=@layout/state_fragment -->
    </fragment>

    <com.google.ads.AdView
        android:id="@+id/adView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:layout_weight="0"
        ads:adSize="BANNER"
        ads:adUnitId=""
        ads:loadAdOnCreate="true" />

</LinearLayout>
```

</FrameLayout>

I don't do much in the activity either:

public void onCreate(Bundle savedInstanceState)
{
        super.onCreate(savedInstanceState);

```
    setContentView(R.layout.state);

    setTitle(R.string.app_name);
```

}

This is what I import in the Fragment class:

import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;

import android.content.DialogInterface;
import android.content.Intent;
import android.gesture.Gesture;
import android.gesture.GestureOverlayView;
import android.gesture.GestureOverlayView.OnGesturePerformedListener;
import android.gesture.Prediction;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.net.Uri;
import android.os.Bundle;
import android.text.SpannableString;
import android.text.style.UnderlineSpan;
import android.view.HapticFeedbackConstants;
import android.view.MotionEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.View.OnLongClickListener;
import android.view.View.OnTouchListener;
import android.view.ViewGroup;
import android.view.animation.Animation;
import android.view.animation.AnimationUtils;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.ImageView.ScaleType;

import org.holoeverywhere.LayoutInflater;
import org.holoeverywhere.app.Activity;
import org.holoeverywhere.app.AlertDialog;
import org.holoeverywhere.app.Fragment;
import org.holoeverywhere.widget.SeekBar;
import org.holoeverywhere.widget.TextView;

and this is what I import in the activity using the Fragment:
import java.util.ArrayList;
import java.util.Comparator;

import android.content.DialogInterface;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.PixelFormat;
import android.net.Uri;
import android.os.Bundle;
import android.text.Html;
import android.util.Log;
import android.view.KeyEvent;
import android.view.View;
import android.view.Window;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.TableRow;

import com.actionbarsherlock.view.Menu;
import com.actionbarsherlock.view.MenuItem;
import com.darvds.ribbonmenu.RibbonMenuView;
import com.google.android.gcm.GCMRegistrar;
import org.holoeverywhere.LayoutInflater;
import org.holoeverywhere.app.Activity;
import org.holoeverywhere.app.AlertDialog;
import org.holoeverywhere.preference.PreferenceManager;
import org.holoeverywhere.preference.SharedPreferences;
import org.holoeverywhere.widget.ListView;
import org.holoeverywhere.widget.TextView;
import org.holoeverywhere.widget.Toast;

**Comment by 4nd3250n** [comment]
Well... it just might be that in your xml file you are refering to class fragment (lowercase letter f). I think it should be Fragment, which is a correct class name.

``` xml
<Fragment
        android:id="@+id/stateFragment"
        android:name="com.jbl.android.spotimote.StateMgr.StateFragment"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:layout_weight="1" >

     <!-- Preview: layout=@layout/state_fragment -->
</Fragment>
```

**Comment by jblernout** [comment]
I don't think so: http://developer.android.com/guide/components/fragments.html

**Comment by wasky** [comment]
I'm having such errors when RuntimeException is thrown in my fragment in onCreateView() method. For some reason original exception is not thrown and doesn't appear in LogCat when using HoloEverywhere fragment. The solution I'm using is:

<pre>
    protected View onCreateView(LayoutInflater inflater, ViewGroup container,
            Bundle savedInstanceState) {
        try {
            // Here's an original code from onCreateView()
        } catch (RuntimeException e) {
            // Workaround to see Exception stack trace in LogCat.
            Log.e(TAG, "Error in onCreateView()", e);
            Toast.makeText(getActivity(),
                    e.getClass().getSimpleName() + " occured. Check LogCat output for details",
                    Toast.LENGTH_LONG).show();
            return new View(getActivity());
        }
    }
</pre>

EDIT: Please note that in my solution you will not be able to obtain the proper exception from Google Play crash logs.

**Comment by ghost** [comment]
My main list activity has problems finding the "fragment" class. I tried the solutions that were posted here but they didn't work. https://github.com/ChristopheVersieux/HoloEverywhere/issues/127

Anyone have anymore thoughts on this issue?

**Comment by Prototik** [comment]
Closed #215 via 6ef2f13cb

**Comment by ismoli** [comment]
Hi, I think there is still this issue if I try inflate custom DialogFragment with another fragment in it's layout (google map fragment):
This is layout for LocationFragment that extends DialogFragment (fragment_location.xml):

``` xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent" >

    <AutoCompleteTextView
        android:id="@+id/locSearchTextView1"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentTop="true"
        android:hint="Search for location"
        android:singleLine="true"
        android:imeOptions="actionSearch">

        <requestFocus />
    </AutoCompleteTextView>
<!-- REMOVING FRAGMENT BELOW MAKES ALL WORK OK -->
    <fragment 
    xmlns:tools="http://schemas.android.com/tools"
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/mapview"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentLeft="true"
        android:layout_below="@+id/locSearchTextView1"
        class="com.google.android.gms.maps.SupportMapFragment"
         /> 
</RelativeLayout>
```

in LocationFragment class:

``` java
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {  
        View rootView = inflater.inflate(R.layout.fragment_location, container, false); // <---- HERE EXCEPTION
//etc....
```

Activity that opens dilaog:

``` java

        FragmentManager fm = getSupportFragmentManager();
        FragmentTransaction ft = fm.beginTransaction();
        LocationFragment locFragment = new LocationFragment();
        locFragment.show(fm, ft);

```

Using latest trunk.

**Comment by Prototik** [comment]
Where stack trace?

**Comment by ismoli** [comment]
Sorry forgot main thing :)

 FATAL EXCEPTION: main
 java.lang.RuntimeException: android.view.InflateException: Binary XML file line #17: Error inflating class fragment
    at com.dome.android.LocationFragment.onCreateView(LocationFragment.java:148)
    at android.support.v4.app._HoloFragment.onCreateView(_HoloFragment.java:168)
    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1460)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:911)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1444)
    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:429)
    at android.os.Handler.handleCallback(Handler.java:725)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5039)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
    at dalvik.system.NativeStart.main(Native Method)
 Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class fragment
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:698)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:243)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:228)
    at com.dome.android.LocationFragment.onCreateView(LocationFragment.java:123)
    ... 16 more
 Caused by: java.lang.ClassNotFoundException: Could not find class: fragment
    at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:287)
    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
    ... 22 more

**Comment by Prototik** [comment]
```
java.lang.RuntimeException: android.view.InflateException: Binary XML file line #17: Error inflating class fragment
at com.dome.android.LocationFragment.onCreateView(LocationFragment.java:148)
```

Support of nested fragments available only since 11 revision of support library. You are sure that you use latest version of this?

If true - try to add line 

``` java
inflater.setFactory(getSupportActivity());
```

before inflating of fragment view.

**Comment by ismoli** [comment]
Using android-support-v13.jar

This also did not helped :(

``` java
inflater.setFactory(getSupportActivity());
```

Tested on JB emulator and Nexus10

also, LogCat under "System.err" tag  shows slightly different stack trace:

 java.lang.ClassNotFoundException: Could not find class: fragment
    at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:287)
    at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:293)
    at org.holoeverywhere.LayoutInflater$HoloFactoryMerger.onCreateView(LayoutInflater.java:42)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:676)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:243)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:228)
    at com.dome.android.LocationFragment.onCreateView(LocationFragment.java:124)
    at android.support.v4.app._HoloFragment.onCreateView(_HoloFragment.java:168)
    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1460)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:911)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1444)
    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:429)
    at android.os.Handler.handleCallback(Handler.java:725)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5039)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
    at dalvik.system.NativeStart.main(Native Method)
