### ISSUE TITLE
Feature request: Implement View.setActivated() method

### ISSUE THREAD

**Issue by 4nd3250n** [Prototik/HoloEverywhere#217]
Method setActivated() is very useful to indicate which view was selected to preform action upon via Contextual action mode.

**Comment by Prototik** [comment]
It's impossible.

**Comment by 4nd3250n** [comment]
Too bad. This is a useful feature of android 4.0+.

**Comment by 4nd3250n** [comment]
What should one use then to indicate that a View was selected for Contextual Action Bar ?
