### ISSUE TITLE
Error installing HoloEverywhere with ActionbarSherlock in Intellij Idea

### ISSUE THREAD

**Issue by agarwlGaurav** [Prototik/HoloEverywhere#218]
Trying to install Holoeverywhere 1.4 with ActionbarSherlock 4.2 in IntelliJ Idea. Getting the following error

`Error:[Holoeverywhere_lib_1.4] oid code & other info\HoloEverywhere-master\HoloEverywhere-master\holoeverywhere_lib_1.4\res\values\styles.xml:1098: error: Error: No resource found that matches the given name: attr 'windowNoTitle'.`

The below is the theme declaration on AndroidManifest.xml

`<application android:label="@string/app_name">
        <activity android:name="ABSHoloChk"
                  android:label="@string/app_name"
                  android:theme="@style/Holo.Theme">`

**Comment by jomp16** [comment]
What version of the Android API are you using?

In outdated APIs, the HoloEverywhere and Actionbar Sherlock doesn't work, need a newest API, like API 17 (I'm using 17 right now)

Try to change the project API to 17, and add android:minSdkVersion="10" (or other) on AndroidManifest to add support to older API ;)

(Sorry for my english :P)

**Comment by agarwlGaurav** [comment]
I have found a way and it is working this way, I am really not sure if it the way it is supposed to work.

I right clicked on the project -> open module settings -> Modules -> (Select + sign on top) and import ActionbarSherlock lirary folder. Similarly I imported HoloEverywhere Library folder -> Select Holoeverywhere library folder and add ABS lirary folder as dependency to HoloEverywhere and finally add the Holoeverywhere as dependency to the project.

Can someone verify this is the right way of adding ABS and HoloEverywhere in a Android project in IntelliJ Idea

**Comment by jomp16** [comment]
I use this way: create a new project, and FILE -> IMPORT MODULE, select the "library" folder of Holoeverywhere, and I repeat this but now with Sherlock, and open project settings, add android-v4-support.jar to the 3 projects, add Sherlock to Holoeverywhere, and add the Sherlock and Holoeverywhere to the main project, now working :)

**Comment by agarwlGaurav** [comment]
Looks like our ways are mostly similar. I shall wait for one more day then I will close the issue.
Thanks @jomp16 .
