### ISSUE TITLE
HE 1.4 Master/Dev Branch: Android 2.1 incorrect dialogfragment appearance

### ISSUE THREAD

**Issue by httpdispatch** [Prototik/HoloEverywhere#219]
I'm using custom dialog layout with the theme "Holo.Theme.Dialog.Light". It is displayed wrong in the Android 2.1 emulator. View is not stretched properly to the whole dialog. The view has "match_parent" attribute in the layout.

Incorrect look
![](http://dl.dropbox.com/u/37011471/Openphoto/device-2012-12-06-092816.png)

Correct look on ICS device
![](http://dl.dropbox.com/u/37011471/Openphoto/device-2012-12-06-095249.png)

The issue is absent on HE 1.3. Also it was absent on some prior 1.4 release when i used Holo.Theme.Dialog.Alert.Light #199

**Comment by httpdispatch** [comment]
I've found that org.holoeverywhere.app.Dialog.checkWindowSizes method causing the problem. If i comment its content the dialog looks properly. I don't know what exactly causing problem there but i hope it will help you to find the real cause. However as you can see title doesn't appear on 2.1 and it appears on 4.0.3
![](http://dl.dropbox.com/u/37011471/Openphoto/device-2012-12-06-101537.png)

**Comment by Prototik** [comment]
DialogFragment.setDialogType with AlertDialog arg.

**Comment by httpdispatch** [comment]
What about invalid look as shown in the first shot when child view is not stretched properly?

**Comment by httpdispatch** [comment]
Will you fix org.holoeverywhere.app.Dialog.checkWindowSizes method?

**Comment by httpdispatch** [comment]
Thanks. setDialogType helped a lot but i had to change theme to Holo.Theme.Dialog.Alert.Light. Thanks again
