### ISSUE TITLE
SlidingActivity is not properly working with onConfigurationChanged

### ISSUE THREAD

**Issue by ghost** [Prototik/HoloEverywhere#220]
Changing screen orientation from landscape to portrait , getSlidingMenu().toggle() is not working.

This bug is also in DemoActivity. I've tested it with galaxy note 10.1(4.0.4) and galaxy s2(4.0.4)

There are no error messages or crashing... , Just  action bar home button is not responding...!

**Comment by Prototik** [comment]
Current impl of slidingmenu will be replaced by impl special writed for HE.
