### ISSUE TITLE
Changing the padding of a PreferenceActivity... can it be done?

### ISSUE THREAD

**Issue by tslocum** [Prototik/HoloEverywhere#221]
Is there a way to remove the padding so the settings fill the window on all sides?  Before using HoloEverywhere there was no gap on the left or right sides.

[Reference](http://imgur.com/9xuVl)

**Comment by Prototik** [comment]
Create dimens.xml in your project and add next lines:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
<dimen name="preference_item_padding_side">0dp</dimen>
<dimen name="preference_item_padding_inner">0dp</dimen>
</resources>
```

**Comment by tslocum** [comment]
Thanks!
