### ISSUE TITLE
ListView item background selector

### ISSUE THREAD

**Issue by 4nd3250n** [Prototik/HoloEverywhere#226]
What background is used for list view items?
I would like to use that same effect for LinearLayout outside listview. Yet, it is impossible to find out which background is used for listview items.

**Comment by Prototik** [comment]
@drawable/list_selector_holo_dark or @drawable/list_selector_holo_light, as attr reference - ?attr/listSelector.

**Comment by 4nd3250n** [comment]
In the meantime I have tested this a bit further and now it seams tha transitions do not work for LinearLayout background.
