### ISSUE TITLE
Selector for LinearLayout

### ISSUE THREAD

**Issue by 4nd3250n** [Prototik/HoloEverywhere#227]
Recently I posted a question:

What background is used for list view items?
I would like to use that same effect for LinearLayout outside listview. Yet, it is impossible to find out which background is used for listview items.

To this Prototik commented:

@drawable/list_selector_holo_dark or @drawable/list_selector_holo_light, as attr reference - ?attr/listSelector.

I found that myself. But because it did not work as it should I have posted previous question.
I want to use the same background selector as in list view. For ilustration in list view my items are LinearLayouts and the selector works as it should.

Yet if I want to use this same selector for stand alone LinearLayout somewhere in the activity:

``` xml
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:clickable="true"
        android:focusable="true"
        android:enabled="true"       
        android:background="?android:attr/listSelector" >
```

This does not work! There is no cute little transition.

**Comment by Prototik** [comment]
Oh. Try ?selectableItemBackground

**Comment by 4nd3250n** [comment]
No. It does not work either. No transition. Just color change.
If one looks:

``` xml
<item name="selectableItemBackground">@drawable/item_background_holo_light</item>
```

it uses the same drawable as android:attr/listSelector.

**Comment by Prototik** [comment]
Fade effect only on long click. try `android:longClickable="true"`

**Comment by 4nd3250n** [comment]
Not solved. Please reopen.

**Comment by Prototik** [comment]
Try to use @drawable/list_selector_background_transition_holo_dark

**Comment by 4nd3250n** [comment]
This issue is still not resolved !

Prototik suggested:

>    Try to use @drawable/list_selector_background_transition_holo_dark

This is not a solution. The background is blue, but IT DOES NOT CHANGE when setSelected() method is invocated.

I would like to add that after 9 month the matter is URGENT.
At least a definite answer if this is at least possible?
