### ISSUE TITLE
HoloEverywhere + ActionBarSherlock

### ISSUE THREAD

**Issue by cesards** [Prototik/HoloEverywhere#229]
As you say in the README documentation:

Import HoloEverywhere from library folder and ActionBarSherlock from contrib/ActionBarSherlock/library folder into Eclipse

and Extend the Activities from org.holoeverywhere.app.***Activity

but, what if we want to extend to SherlockActivity? Because if we extend from your library, we are not able to use all the SherlockActionBar methods.

Thanks.

**Comment by Prototik** [comment]
?
org.holoeverywhere.app.Activity has getSupportActionBar(), setSupportProgress**\* and other methods from ABS.

**Comment by cesards** [comment]
I don't know why.. but my methods:

getSupportActionBar().setHomeButtonEnabled(true);
getSupportActionBar().setDisplayShowTitleEnabled(false);
getSupportActionBar().setIcon(R.drawable.logo2012);

didn't work extending from FragmentActivity, maybe I was not importing the correct libraries...

**Comment by Prototik** [comment]
In HoloEverywhere don't exists FragmentActivity. org.holoeverywhere.app.Activity already has a fragment impl.
You extend activities from android.support.v4.app.FragmentActivity. Change to org.holoeverywhere.app.Activity.
