### ISSUE TITLE
java.lang.NullPointerException onCreate setDisplayHomeAsUpEnabled

### ISSUE THREAD

**Issue by bondjpf** [Prototik/HoloEverywhere#232]
I'm getting a NullPointerException when I set the Actionbar.

Here's my imports:

import org.holoeverywhere.app.Activity;
import com.actionbarsherlock.app.ActionBar;
import com.actionbarsherlock.app.ActionBar.Tab;

The error is here:

ActionBar bar = getSupportActionBar();
bar.setDisplayHomeAsUpEnabled(true);<--- ERROR
bar.setHomeButtonEnabled(true);
bar.setTitle(R.string.top_feeds);
// bar.setDisplayShowTitleEnabled(true);
bar.setNavigationMode(ActionBar.NAVIGATION_MODE_TABS);
mTabsAdapter = new TabsAdapter(this, mViewPager);
mTabsAdapter.addTab(bar.newTab().setText(R.string.top),TopFragment.class, null);
mTabsAdapter.addTab(bar.newTab().setText(R.string.new), NewFragment.class, null);
......................

I'm using tabs adapter like this:

public static class TabsAdapter extends FragmentStatePagerAdapter implements
            ActionBar.TabListener, ViewPager.OnPageChangeListener {
        private final Context mContext;
        private final ActionBar mActionBar;
        private final ViewPager mViewPager;
        private final ArrayList<TabInfo> mTabs = new ArrayList<TabInfo>();

```
    static final class TabInfo {
        private final Class<?> clss;
        private final Bundle args;

        TabInfo(Class<?> _class, Bundle _args) {
            clss = _class;
            args = _args;
        }
    }

    public TabsAdapter(Activity activity, ViewPager pager) {
        super(activity.getSupportFragmentManager());
        mContext = activity;
        mActionBar = activity.getSupportActionBar();
        mViewPager = pager;
        mViewPager.setAdapter(this);
        mViewPager.setOnPageChangeListener(this);

    }

    public void addTab(ActionBar.Tab tab, Class<?> clss, Bundle args) {
        TabInfo info = new TabInfo(clss, args);
        tab.setTag(info);
        tab.setTabListener(this);
        mTabs.add(info);
        mActionBar.addTab(tab);
        notifyDataSetChanged();
    }

    @Override
    public int getCount() {
        return mTabs.size();
    }

    @Override
    public Fragment getItem(int position) {
        TabInfo info = mTabs.get(position);
        return Fragment.instantiate(mContext, info.clss.getName(),
                info.args);
    }

    public void onPageScrolled(int position, float positionOffset,
            int positionOffsetPixels) {
    }

    public void onPageSelected(int position) {
        mActionBar.setSelectedNavigationItem(position);
    }

    public void onPageScrollStateChanged(int state) {
    }

    public void onTabSelected(Tab tab, FragmentTransaction ft) {
        Object tag = tab.getTag();
        for (int i = 0; i < mTabs.size(); i++) {
            if (mTabs.get(i) == tag) {
                mViewPager.setCurrentItem(i);
            }

        }
    }

    public void onTabUnselected(Tab tab, FragmentTransaction ft) {
    }

    public void onTabReselected(Tab tab, FragmentTransaction ft) {
    }
```

}

How can I solve this?
Thanks

**Comment by 4nd3250n** [comment]
Check with debugger what is the value of variable bar.
Stack trace would be helpfull also.
Check if you are using correct theme so that ActionBar is created in the first place.

**Comment by bondjpf** [comment]
If I remember correctly I got this error when I changed the theme in the app settings.

I had to comment out Settings.setUseThemeManager(true);

Now this is what I'm using to set the themes:

setForceThemeApply(true);
//Settings.setUseThemeManager(true);
SP = Home.this.getSharedPreferences(SHARED_PREFS_NAME, 0);
this.SP.registerOnSharedPreferenceChangeListener(this);
if (SP.getString("theme_list_preference", "AppThemeLight").equals(
                "AppThemeLight")) {
        ThemeManager.restartWithTheme(this, ThemeManager.LIGHT);

```
    } else if (SP.getString("theme_list_preference",
            "AppThemeLightDarkActionBar").equals(
            "AppThemeLightDarkActionBar")) {

        ThemeManager.restartWithTheme(this, ThemeManager.MIXED);

    } else if (SP.getString("theme_list_preference", "AppThemeDark")
            .equals("AppThemeDark")) {

        ThemeManager.restartWithTheme(this, ThemeManager.DARK);
```

}

Is this a correct way to do it?
I was doing this way while using V.1.3 I got this error after upgrading to V1.4
Thanks

**Comment by 4nd3250n** [comment]
Go through with debugger and see if any theme gets set. I am guessing here but it is a strong guess there is something wrong with your theme.
As far as ThemeManager goes... I do not use it. I have my own pattern. But it would be nice to know more about ThemeManager (wink wink).

**Comment by bondjpf** [comment]
Ok. just found the error.
Thanks for pointing me in the right direction :)
In Application.java I was using R.style.Holo_Theme_Dialog for the dark theme like this:

public class Application extends org.holoeverywhere.app.Application {
    static {
        ThemeManager.setDefaultTheme(ThemeManager.LIGHT);

```
    ThemeManager.map(ThemeManager.DARK, R.style.Holo_Theme_Dialog);
    ThemeManager.map(ThemeManager.LIGHT, R.style.Holo_Theme_Light);
    ThemeManager.map(ThemeManager.MIXED,
            R.style.Holo_Theme_Light_DarkActionBar);

}
```

}

Changed to ThemeManager.map(ThemeManager.DARK, R.style.Holo_Theme;   and now the app starts
BTW there's no R.style.Holo_Theme_Dark ?

**Comment by Prototik** [comment]
> BTW there's no R.style.Holo_Theme_Dark ?

No need to multiply entities.
Simply Holo.Theme.
