### ISSUE TITLE
Update support library

### ISSUE THREAD

**Issue by Prototik** [Prototik/HoloEverywhere#233]
Hi.
HoloEverywhere now build with Maven.
And for some unknown reason Google is not the upload latest version of support library into maven central.
And HoloEverywhere build's with version r7, although the latest r11. ([maven search](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22support-v4%22)).
I suggest temporarily create a support-library in holoeverywhere group (ex. org.holoeverywhere:support-library).
Where will this lead: other libraries may sometimes conflict at build time, it will have to patch up the pom.xml (only for applications, not library).

What everyone thinks about this?

Of course, the build in the IDE is not concerned.

**Comment by mdumrauf** [comment]
How about using https://github.com/mosabua/maven-android-sdk-deployer to deploy locally last support version? This way we would not need to add a new project.

```
<dependency>
  <groupId>android.support</groupId>
  <artifactId>compatibility-v13</artifactId>
  <version>11</version>
</dependency>
```

**Comment by Prototik** [comment]
Yea, but it locally.

I want to create an artifact org.holoeverywhere:support-v4 instead of com.google.android:support-v4, but first will be conflict with second, and for other librares, which uses com.google.android:support-v4 want to add the exclusion to the definition of dependence in pom.xml
