### ISSUE TITLE
ListPreference + Honeycomb = Crash

### ISSUE THREAD

**Issue by otro678** [Prototik/HoloEverywhere#234]
App is crashing when I'm trying to open ListPreferences activity on Honeycomb emulator.
I've tried it in my own app and in your demo app.

Here are last messages in logcat.
11-14 04:05:10.119: E/AndroidRuntime(1028): FATAL EXCEPTION: main
11-14 04:05:10.119: E/AndroidRuntime(1028): java.lang.NullPointerException
11-14 04:05:10.119: E/AndroidRuntime(1028):     at org.holoeverywhere.ArrayAdapter.createViewFromResource(ArrayAdapter.java:204)
11-14 04:05:10.119: E/AndroidRuntime(1028):     at org.holoeverywhere.ArrayAdapter.getView(ArrayAdapter.java:250)

**Comment by Prototik** [comment]
Bug of 1.4, already fixed in dev branch.
