### ISSUE TITLE
Custom dialog view with Spinner. Spinner item size problem.

### ISSUE THREAD

**Issue by otro678** [Prototik/HoloEverywhere#235]
I have dialog with custom view. Here is it's layout:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:padding="10dp" >

    <Spinner
        android:id="@+id/dialogSaveAsFileTypeSpinner"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:entries="@array/save_types_names" />

    <EditText
        android:id="@+id/dialogSaveAsFileNameEditText"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="5dp"
        android:hint="@string/dialog_save_as_hint" />
</LinearLayout>
```

The issue is spinner's items are not having proper size to fit in popup.

Here is screenshot of common Holo from Jelly Bean:
https://f.cloud.github.com/assets/625515/24574/24b272a8-4ab2-11e2-8617-497344f90a79.png

And here are screenshots with HoloEverywhere:
In portait mode I can't even scroll list.
https://f.cloud.github.com/assets/625515/24575/24c25ad8-4ab2-11e2-9ba1-2d6f5f5efb50.png
In portrait mode I can scroll, but list doesn't scroll to it's end.
https://f.cloud.github.com/assets/625515/24573/24982ba0-4ab2-11e2-8a2e-841520c1b578.png

**Comment by Prototik** [comment]
Как вариант: включить режим диалога для спиннера. А вообще: бага в PopupWindow на 2.3, бум фиксить.

**Comment by otro678** [comment]
Проблема в том, что 

``` xml
android:spinnerMode="dialog"
```

не работает. Независимо от параметра в xml работает dropdown, проверил на 4.2, 4.1 и 2.3.

**Comment by Prototik** [comment]
Хей, юзай holo неймспейс:

``` xml
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:holo="http://schemas.android.com/apk/res-auto" ... >
  <Spinner holo:spinnerMode="dialog" ... />

```

**Comment by otro678** [comment]
Oh. My bad. :)

**Comment by Prototik** [comment]
Well, it's android limits and i don't can find workaround for issue, close.
