### ISSUE TITLE
Unable to Build

### ISSUE THREAD

**Issue by ghost** [Prototik/HoloEverywhere#236]
I am trying to build the HoloEverywhere library for API 17.  Android 4.2.  I imported the HoloEverywhere library and the ActionBarSherlock libraries into my Eclipse projects.  ABS builds fine.  But HE does not.  I tried reverting HE to use API 16 for Android 4.1.2, but I still received the same errors.

The errors are that certain HE classes are unable to resolve R.  Such as ThemeManager.java which can't resolve R.style.Holo_Theme_NoActionBar_Fullscreen.

How can I fix?

Thanks...

**Comment by Prototik** [comment]
Are you try build in Eclipse? Try make project - Clean, in gen folder should be R

**Comment by ghost** [comment]
Yes, I'm using Eclipse.  And I've cleaned multiple times.  Without success.  I turned off auto-build.  And then cleaned and built.  I've left auto-build on.  Then cleaned.

Same list of errors each time.

I also tried to delete the Gen folder and have it rebuild.  Same errors.

Peter Van Dyk
Appstervan Software

pvd@Appstervan.commailto:pvd@Appstervan.com
260-494-1760 (Work)
260-494-5661 (Cell)

http://www.Appstervan.com
Follow us: @Appstervanhttp://twitter.com/@Appstervan

**Comment by ghost** [comment]
This has been resolved.  I started from scratch in a new workspace in Eclipse and the problem has been solved.  It is building now.

Thanks and sorry to bother…

Peter Van Dyk
Appstervan Software

pvd@Appstervan.commailto:pvd@Appstervan.com
260-494-1760 (Work)
260-494-5661 (Cell)

http://www.Appstervan.com
Follow us: @Appstervanhttp://twitter.com/@Appstervan
