### ISSUE TITLE
Preference setChecked(true) is erased when added to a PreferenceScreen

### ISSUE THREAD

**Issue by mattprecious** [Prototik/HoloEverywhere#238]
``` java
PreferenceScreen preferenceScreen = getPreferenceManager().createPreferenceScreen(getActivity());
CheckBoxPreference preference = new CheckBoxPreference(getActivity());

preference.setChecked(true);
Log.d(TAG, "pre: " + preference.isChecked());
preferenceScreen.addPreference(preference);
Log.d(TAG, "post: " + preference.isChecked());
```

This will print:

```
pre: true
post: false
```

This works properly when using the native Preference classes, but not when using HE. For the time being, I've changed my code to use `setDefaultValue(true)` which works.

**Comment by mattprecious** [comment]
For what it's worth, the value is changed in `PreferenceGroup.addPreference()` when it executes

```
preference.onAttachedToHierarchy(getPreferenceManager());
```

where it eventually calls through to `Preference.dispatchSetInitialValue()`.

Everything I traced through from there is identical to AOSP and seems to be coded to do the right thing. The only thing I can think of that might be different is that maybe in AOSP, `mDefaultValue` is null, but in HE it's `Boolean.FALSE`. I don't really have the ability to test that theory.

Anyway, looking back on this two months later, using `setDefaultValue(true)` is probably the correct way for me to handle this, so this fix is definitely super low priority. However, since the result does differ from AOSP, it may be something to consider digging into deeper eventually.

**Comment by Prototik** [comment]
Preference, TwoStatePreference and CheckBoxPreference fully copy functional of AOSP.
