### ISSUE TITLE
Missing dialog theme Holo.Theme.Light.DarkActionBar on 4.2 Jelly Bean

### ISSUE THREAD

**Issue by uraid** [Prototik/HoloEverywhere#243]
Hello, 
When using the light theme with dark action bar, an inverted dialog works great on non Hollo devices. 
But,  when I try it on my 4.2.1 device,  it is not inverted and seems messed up. 
Please fix this issue. 
Thanks in advance for your hard work! 
Yair

**Comment by Prototik** [comment]
Fixed.
