### ISSUE TITLE
Messed up dark dialog when forcing invert with Hollo. Theme. Light. Dark action bar on 4.2.1

### ISSUE THREAD

**Issue by uraid** [Prototik/HoloEverywhere#244]
Hello, 
When using the light theme with dark action bar, an inverted dialog works great on non Hollo devices. 
But,  when I try it on my 4.2.1 device,  it is not inverted and seems messed up. 
Please fix this issue. 
Thanks in advance for your hard work! 
Yair

**Comment by Prototik** [comment]
Duplicate #243

**Comment by uraid** [comment]
My bad :(
Double post.
