### ISSUE TITLE
Missing style for Holo Widget.TabWidget

### ISSUE THREAD

**Issue by AlexBonel** [Prototik/HoloEverywhere#247]
Wanted to apply a Holo Widget.TabWidget style to created layout for FragmentTabHost's TabWidget, but didn't find it in the set of styles.

**Comment by jonasfa** [comment]
@ChristopheVersieux is there any limitation on <= Gingerbread's TabWidget that prevents reproducing Holo's tabWidgetStyle?

**Comment by jonasfa** [comment]
I've just tried.
It's not possible because an important TabHost attr (android:tabLayout) is private.

**Comment by AlexBonel** [comment]
@Prototik Tell me please, if TabWidget is deprecated for you, how can I make tabs for my FragmentTabHost with another color? They are depend on ActionBar Tab style.
