### ISSUE TITLE
TimePicker Appearance

### ISSUE THREAD

**Issue by snorkel123** [Prototik/HoloEverywhere#255]
This dialogs' appearance differs from one of ICS :
- no arrows under and above numbers 
- no animation applied on scrolling (after scrolling numbers under and above two blue lines should dissapear but they don't)

More here : http://stackoverflow.com/questions/14144716/android-holoeverywhere-timepicker-dialog-appearance
Regards,

**Comment by snorkel123** [comment]
Sorry for duplicate.

Why not use https://github.com/SimonVT/android-timepicker ? It is exactly like in ICS

**Comment by Prototik** [comment]
NumberPicker ported from jelly bean, not ics. It's native look.
