### ISSUE TITLE
Missing files, Importing Problems

### ISSUE THREAD

**Issue by shadoWalker89** [Prototik/HoloEverywhere#257]
Hi,
First of all the "contrib\ActionBarSherlock" folder is empty even if u did put the actionBarSherlock lib in there there is still these problems.

When importing project from existing code i get this

![1](https://f.cloud.github.com/assets/1449151/39044/2b1c869c-5511-11e2-9e81-e5d38690d013.PNG)

Then when i right click the library project --> java build path, it says that test folder is missing

![2](https://f.cloud.github.com/assets/1449151/39046/5d5b55fc-5511-11e2-8081-baaced2659e2.PNG)

Finally i get this in the java console.

![3](https://f.cloud.github.com/assets/1449151/39049/6c7bbb94-5511-11e2-835d-56cca1e6dd49.PNG)

**Comment by mephju** [comment]
Same errors here. I am not able to work with HoloEverywhere.

**Comment by Prototik** [comment]
First: install m2e and m2e-android.
Second: fixed in latest commit.
Third: Go to android and select any target (min 14)
