### ISSUE TITLE
HE v1.4.1 - SharedPreferences.OnSharedPreferenceChangeListener not called when a preference is set to its existing value

### ISSUE THREAD

**Issue by ghost** [Prototik/HoloEverywhere#259]
I was using HoloEverywhere v1.3.\* and updated to v1.4.1 yesterday.

After a bit of testing, it seems that, in v1.4.1, the OnSharedPreferenceChangeListener is not called when a preference is set to its existing value.

This was not the case in v1.3.\* and the listener was called even if the preference was set to the same value.

For instance, when a CheckBoxPreference (which is 'true') is set to 'true' again.

I hope this gets fixed soon. I'll really appreciate that.

Thanks!  

Rishit

**Comment by Prototik** [comment]
But it OnSharedPreference_Change_Listener, if you don't modify value - why need call the listener?

Sorry for the late reply.

**Comment by ghost** [comment]
Hi Sergey.

No problem, thanks for your reply, better late than never! :)

From the <a href="http://developer.android.com/reference/android/content/SharedPreferences.OnSharedPreferenceChangeListener.html">Android Documentation:</a>

```
onSharedPreferenceChanged
Called when a shared preference is changed, added, or removed.
This may be called even if a preference is set to its existing value.
```

As mentioned above, <b>onSharedPreferenceChanged may be called even if a preference is set to its existing value.</b> 

I need to call the listener in order to dynamically set the summaryOn (summary of the preference when it is checked) of a CheckBoxPreference while it is already checked.

Also, the summaryOn has to be set when something happens in another class. Therefore, first I need to commit the SharedPreferences value to true for the CheckBoxPreference in that class and then need the  OnSharedPreferenceChangeListener to be called so that the summaryOn can be set.

Thanks for your time, Sergey!

Rishit

**Comment by Prototik** [comment]
Hm. Yea, you right. But which implementation you use? XML or JSON?

**Comment by ghost** [comment]
I use XML.

**Comment by Prototik** [comment]
But xml impl only wrap a native impl and don't modify logic of listeners.

**Comment by ghost** [comment]
Hmm, I don't know, it used to work in v1.3.\* but when I updated to v1.4.1, it stopped working.

**Comment by Prototik** [comment]
In 1.3 by default was be JSON impl. Change to it and report.

**Comment by ghost** [comment]
I'm sorry but what do you exactly mean by JSON or XML implementation? And how do I change to it?

**Comment by Prototik** [comment]
See demo for need release: in your application object in static block code:
Application.config().setPreferenceImpl(PreferenceImpl.JSON) for 1.4.0-1.4.2.

**Comment by ghost** [comment]
Okay, I am not familiar with this, but I'll try and then get back to you.
