### ISSUE TITLE
HoloAlertDialogBuilder setItems

### ISSUE THREAD

**Issue by rodrigost23** [Prototik/HoloEverywhere#26]
I want to use `HoloAlertDialogBuilder` to create a dialog window with a list like this:

<pre>HoloAlertDialogBuilder adb = new HoloAlertDialogBuilder(this);
        adb.setTitle(dialogTitle);
        adb.setItems(R.array.subject_list_actions, null);
        adb.show();</pre>

Using `setItems` I get a list - but the text is black, almost unreadable, and the dividers between the items look ugly.

I noticed `HoloAlertDialogBuilder` does not override the `setItems` method. But I'm not able to do it myself. :(

Originally I tried to use a ContextMenu for my `ListView`, but it was too ugly, so I made it create an AlertDialog; but it looks weird too...

**Comment by rockschtar** [comment]
Same here :/

**Comment by rockschtar** [comment]
Ok, I have a workarround:

Instead of using ".setItems" use a simple ListView with a ArrayAdapter:

```
HoloAlertDialogBuilder dialogBuilder = new HoloAlertDialogBuilder(this);

    ListView modeList = new ListView(getActivity());
    String[] stringArray = new String[] { "Bright Mode", "Normal Mode" };
    ArrayAdapter<String> modeAdapter = new ArrayAdapter<String>(this, android.R.layout.simple_list_item_1, android.R.id.text1, stringArray);
    modeList.setAdapter(modeAdapter);

    dialogBuilder.setView(modeList);
    dialogBuilder.setTitle("Sometitle");
    dialogBuilder.create();
    dialogBuilder.show();
```

**Comment by rodrigost23** [comment]
Thanks, I'm going to try that.

**Comment by martinlong1978** [comment]
I'm also seeing this issue. The workaround creates a lot of work for me... going to see if I can fix this.

**Comment by Prototik** [comment]
Test support of setItems: 3d20ab16f555740be3a30990bcf9b474fd96cba1
