### ISSUE TITLE
Import into Eclipse  not possible

### ISSUE THREAD

**Issue by mephju** [Prototik/HoloEverywhere#260]
Hey guys,

the current state of the project is not usable...at least not for me.

I did this as written in the readme file:

git clone git://github.com/ChristopheVersieux/HoloEverywhere.git HoloEverywhere
cd HoloEverywhere
git checkout holoeverywhere-1.4.1
git submodule update --init --recursive

Then I imported the library into my workspace and Eclipse started complaining about duplicate entry src for project 'library'.

**Comment by mephju** [comment]
I forgot to mention I am using Eclipse Juno.

I've just tried the whole thing with the previous Eclipse release(indigo?)...and it doesn't complain at all !?

**Comment by Prototik** [comment]
Since 1.4.1 HoloEverywhere support only maven-android type for the projects (required m2e and m2e-android).
You can remove .classpath files from project and add projects into eclipse from file - new - android project from exists code.
