### ISSUE TITLE
ClassCastException on ListFragment.setFastScrollEnabled()

### ISSUE THREAD

**Issue by ChrisDavis8** [Prototik/HoloEverywhere#261]
when you set FastSCrollEnabled(true) FastScroller.getSectionsFromIndexer() does some casting to BaseAdapter which it cant do with the ListAdapterWrapper

01-04 18:33:33.335: E/AndroidRuntime(14126): Caused by: java.lang.ClassCastException: org.holoeverywhere.widget.ListView$ListAdapterWrapper cannot be cast to android.widget.BaseAdapter
01-04 18:33:33.335: E/AndroidRuntime(14126):    at android.widget.FastScroller.getSectionsFromIndexer(FastScroller.java:511)
01-04 18:33:33.335: E/AndroidRuntime(14126):    at android.widget.FastScroller.init(FastScroller.java:271)
01-04 18:33:33.335: E/AndroidRuntime(14126):    at android.widget.FastScroller.<init>(FastScroller.java:155)
01-04 18:33:33.335: E/AndroidRuntime(14126):    at android.widget.AbsListView.setFastScrollEnabled(AbsListView.java:1208)

**Comment by tverona** [comment]
Hitting this issue as well. Holoeverywhere's ListView implements setAdapter (which wraps it) but does not implement corresponding getAdapter (which should unwrap it...)

**Comment by Prototik** [comment]
Adapter view use getadapter for some needs. If getadapter will be unwrap adapter - then fact of wrap of adapter meanless. 

About issue: fastscroll fixed.

**Comment by tverona** [comment]
Regarding getAdapter - got it, thanks!

**Comment by SutharBhargav** [comment]
how to solve it ... which property need to set..
