### ISSUE TITLE
RingtonePreference

### ISSUE THREAD

**Issue by BraisGabin** [Prototik/HoloEverywhere#263]
This issue is related with the closed issue #256. It appers in the commit 13b0d5eddd3ed54647ffef4b4d4cf74e2d0b6c43.

Now the ringtones are checked in pairs. If you click in one ringtone the fifth below it is going to check. And if you click te fifth the first is going to check. Sometimes the distance between pairs is 1 (all ok), 2, 3...

This issue is reproducible in the HoleEverywhere demo and in the #256 example.

Tested in an Gallaxy Ace - API 10.

I tried to debug the problem to give more details but I could not.

**Comment by Prototik** [comment]
Fixed via da13ec5d
