### ISSUE TITLE
The method onViewStateRestored(Bundle) is undefined for the type ListFragment

### ISSUE THREAD

**Issue by ghost** [Prototik/HoloEverywhere#264]
I'm trying to configure the holoeverywhere library for my app, but for some reason, there is no onViewStateRestored method from the override/implement methods and if I put my old code in there, it says that the method is undefined for the type ListFragment. It worked before, but after adding in holoeverywhere, it doesn't exist anymore.

Any help is much appreciated, Thanks!

**Comment by Prototik** [comment]
Update support library to r11. By default HoloEverywhere using r7, where onViewStateRestored not exists.
