### ISSUE TITLE
ClassCastException at requestWindowFeature(Window.FEATURE_INDETERMINATE_PROGRESS)

### ISSUE THREAD

**Issue by gosr** [Prototik/HoloEverywhere#265]
I have a PreferenceActivity.
In onCreate:

```
@Override
public void onCreate(Bundle savedInstanceState) {
    requestWindowFeature(Window.FEATURE_INDETERMINATE_PROGRESS); // to show the progress at the top
    super.onCreate(savedInstanceState);
    addPreferencesFromResource(R.xml.preferences);
    ...
}
```

I get this error:
http://pastebin.com/AtwMQfKM

The exception occurs at line 120 in SettingsActivity, which is the line with requestWindowFeature above.

The code worked on a previous version of HoloEverywhere (back when it had another package name), but now, after updating, it doesn't work.

**Comment by Prototik** [comment]
You use android.view.Window instead actionbarsherlock Window. And he.progressbar already extend native pb in latest version.

**Comment by gosr** [comment]
It doesn't matter if I use android.view.Window or com.actionbarsherlock.view.Window. Same error.
What do you mean with your last sentence?

**Comment by Prototik** [comment]
This class cast exception already fixed in last version, but not in 1.4.1. Please wait 1.4.2 release.

**Comment by gosr** [comment]
Just updated to 1.4.2, error is now gone.
However, the progressbar is not shown in the Action Bar.

Even if I set `setSupportProgressBarIndeterminateVisibility(true);` in the onCreate method, nothing is shown.
Has this feature been removed from HE or?

I've also tried setting these, without changes:

```
setSupportProgressBarIndeterminate(true);
setSupportProgressBarVisibility(true);
```

**Comment by Prototik** [comment]
![he-abs-progress-test](https://f.cloud.github.com/assets/1416030/77690/a78bd1b6-6154-11e2-868b-a79a094aa714.png)

Full code of activity:

``` java
package org.heabsprogresstest;

import org.holoeverywhere.app.Activity;

import android.os.Bundle;
import android.view.View;

import com.actionbarsherlock.view.Window;

public class MainActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        requestWindowFeature(Window.FEATURE_INDETERMINATE_PROGRESS);
        setContentView(new View(this)); // dummy view
        setSupportProgressBarIndeterminate(true);
        setSupportProgressBarIndeterminateVisibility(true);
    }
}
```

**Comment by gosr** [comment]
Please try with a PreferenceActivity and see if you can see the progressbar at the top.

This is my code, and nothing is shown:

```
import org.holoeverywhere.preference.PreferenceActivity;

import android.os.Bundle;

import com.actionbarsherlock.view.Window;

public class MainActivity extends PreferenceActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        requestWindowFeature(Window.FEATURE_INDETERMINATE_PROGRESS);
        super.onCreate(savedInstanceState);
        addPreferencesFromResource(R.xml.preferences);

        setSupportProgressBarIndeterminate(true);
        setSupportProgressBarIndeterminateVisibility(true);
    }
}
```

It seems like it's working for a normal Activity, but not when you're making the layout from XML (PreferenceActivity).

**Comment by Prototik** [comment]
You should call requestWindowFeature after super.onCreate.
Only after super.onCreate will be attach sherlock addon to activity, which will be handle requestWindowFeature.

**Comment by gosr** [comment]
It's a bit difficult to do that, because Android won't allow it:

```
01-25 12:50:35.295: E/AndroidRuntime(30818): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.test2/com.example.test2.MainActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
```

Again, I think it's something that happens only when using a PreferenceActivity.

**Comment by Prototik** [comment]
Hm, yea, in onCreate PreferenceActivity set a content view.

Attach addon manually:

```
public class MainActivity extends PreferenceActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        requireSherlock()
        requestWindowFeature(Window.FEATURE_INDETERMINATE_PROGRESS);
        super.onCreate(savedInstanceState);
        addPreferencesFromResource(R.xml.preferences);

        setSupportProgressBarIndeterminate(true);
        setSupportProgressBarIndeterminateVisibility(true);
    }
}

```

**Comment by gosr** [comment]
That works, thank you!
