### ISSUE TITLE
1.4.2 compilation issues

### ISSUE THREAD

**Issue by httpdispatch** [Prototik/HoloEverywhere#266]
Can't compile latest master head

Description Resource    Path    Location    Type
mScrollY cannot be resolved to a variable   ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 257    Java Problem
drawOverscrollHeader cannot be resolved to a variable   ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 259    Java Problem
overscrollHeader cannot be resolved to a variable   ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 262    Java Problem
drawOverscrollFooter cannot be resolved to a variable   ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 279    Java Problem
mBottom cannot be resolved to a variable    ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 294    Java Problem
mScrollY cannot be resolved to a variable   ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 294    Java Problem
drawOverscrollFooter cannot be resolved to a variable   ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 295    Java Problem
overscrollFooter cannot be resolved to a variable   ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 299    Java Problem
mScrollY cannot be resolved to a variable   ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 304    Java Problem
drawOverscrollHeader cannot be resolved to a variable   ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 306    Java Problem
overscrollHeader cannot be resolved to a variable   ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 309    Java Problem
drawOverscrollHeader cannot be resolved to a variable   ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 312    Java Problem
drawOverscrollFooter cannot be resolved to a variable   ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 342    Java Problem
mBottom cannot be resolved to a variable    ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 343    Java Problem
overscrollFooter cannot be resolved to a variable   ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 346    Java Problem
mListPadding cannot be resolved to a variable   ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 249    Java Problem
mIsCacheColorOpaque cannot be resolved to a variable    ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 239    Java Problem
mTop cannot be resolved to a variable   ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 252    Java Problem
mBottom cannot be resolved to a variable    ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 252    Java Problem
mStackFromBottom cannot be resolved to a variable   ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 253    Java Problem
mScrollY cannot be resolved to a variable   ListView.java   /HoloEverywhere/src/org/holoeverywhere/widget   line 252    Java Problem

**Comment by httpdispatch** [comment]
Also can you please provide some instructions on how to build project properly

**Comment by Prototik** [comment]
Да знаю я.
Вот сижу я тут полупьяный, грустный-грустный: долбанная флешка скопировала лишь частично копию репы с ноута, где было почти все готово к релизу, заново переписываю...

А билд для эклипса никак не изменился: если только для связки клипсы и мавена.

**Comment by httpdispatch** [comment]
@Prototik в том то и дело что установлен плагин m2e, но матерится, что не может найти holoeverywhere build artifact.

**Comment by httpdispatch** [comment]
@Prototik какой стабильный коммит посоветуете в таком случае?

**Comment by Prototik** [comment]
А m2e-android стоит? Импортируй еще проекты builder и translator, это вспомогательные проекты, которые генерируют ресурсы для aapt.
git checkout holoeverywhere-1.4.1, не?

**Comment by httpdispatch** [comment]
@Prototik спасибо за помощь, попробую
