### ISSUE TITLE
OnOptionsSelectedMenu is called twice for each menu item

### ISSUE THREAD

**Issue by ghost** [Prototik/HoloEverywhere#267]
It looked like each Activity is re-opened when the Back Button is pressed.  However, it turns out that the ACtivity is actually opened twice due to a double call to OnOptionsSelectedMenu each time a menu item is pressed.

This does not happen on older versions of Android.  But on newer versions ICS and up, the Preference Screen or Activity is opened twice from OnOptionsSelectedMenu.  I can debug it and show the double entry into OnOptionsSelectedMenu.  Happens both in Master and in 1.4.1.

**Comment by Prototik** [comment]
Sorry for the late reply.

I'm test latest dev and onOptionsItemSelected called only once. You sure that you return true when process onOptionsItemSelected? Show code.
