### ISSUE TITLE
ListView.setOnItemClickListener() does not work with OnItemClickListener

### ISSUE THREAD

**Issue by tverona** [Prototik/HoloEverywhere#269]
ListView.setOnItemClickListener() does not work with holo.everywhere.widget.AdapterView.OnItemClickListener - there is a type mismatch. Looks like I need to use android.widget.AdapterView.OnItemClickListener instead. Is this expected? This is a bit confusing since other widgets expect holo everywher's OnItemClickListener definition.

**Comment by Prototik** [comment]
Yes, it's excepted. ListView yet extend native widget.

**Comment by tverona** [comment]
Ok, thanks!
