### ISSUE TITLE
ListView.getAdapter - how to get underyling adapter instance?

### ISSUE THREAD

**Issue by tverona** [Prototik/HoloEverywhere#270]
listView.setAdapter(new MyAdapter());
...
listView.getAdapter() <-- returns wrapped instance.

How do I get back my instance? The Android doc says:
"Returns the adapter currently in use in this ListView. The returned adapter might not be the same adapter passed to setAdapter(ListAdapter) but might be a WrapperListAdapter."

So, with Android's ListView, I can use WrappedListAdapter.getWrappedAdapter(). But Holoeverywhere has it's own wrapper called ListAdapterWrapper. So, can you also expose this on ListAdapterWrapper? Or, better yet, use Android's WrappedListAdapter instead?

**Comment by Prototik** [comment]
ListView.getAdapterSource()
