### ISSUE TITLE
Button text style?

### ISSUE THREAD

**Issue by PureSpider** [Prototik/HoloEverywhere#274]
I have a TextView that I want to look like the text on my `Button`s and `ImageButton`s with `style="?borderlessButtonStyle"`
How would I go on doing this so I can be sure the text style will be as expected on every device regardless of Android version?

Thanks in advance!

**Comment by Prototik** [comment]
Yes. It's all?

**Comment by PureSpider** [comment]
Is there a style that I can apply to my TextView so it looks like the default text on a HoloEverywhere ImageButton?

**Comment by Prototik** [comment]
`?android:buttonStyle`

**Comment by PureSpider** [comment]
Is that only for the text appearance or will my whole TextView look like a Button then (with background, etc)?

**Comment by Prototik** [comment]
Different between TextView and Button only in style attribute. TextView - android.R.attr.textViewStyle, Button - android.R.attr.buttonStyle. Any TextView-based widget which will be apply style buttonStyle without other adjustments - look like button pixel-to-pixel.

**Comment by PureSpider** [comment]
And what do I need to apply when I just want the text appearance of a button and NOT the rest like background and so on?

I am using a LinearLayout with `style="?borderlessButtonStyle"` and inside that LinearLayout is one ImageView and one TextView.
I already got the ImageView right but can't find the attribute I need to apply to the TextView so it looks like the text on a button?

**Comment by PureSpider** [comment]
Or can I just use `?android:buttonStyle` together with an explicitely set transparent background?

**Comment by Prototik** [comment]
``` xml
<TextView
  ...
  style="?android:buttonStyle"
  android:background="@drawable/transparent" />
```

**Comment by PureSpider** [comment]
Thanks a lot :+1:
