### ISSUE TITLE
Holoeverywhere ExpandableListView does not extends android ExapandableListView

### ISSUE THREAD

**Issue by r-gurzkowski** [Prototik/HoloEverywhere#275]
Holoeverywhere migration from 1.3 to 1.4 causes class cast exception due to ExpandableListView. Should be added to migration guide (https://github.com/ChristopheVersieux/HoloEverywhere/wiki/Migration-on-1.4) or inheritance tree should be adjusted for existing projects.

**Comment by Prototik** [comment]
ExpandableListView was be added in 1.4.2. I don't want to notify about every sneeze at .widget package. Crash - found the cause (wrong class) - changed - works.
