### ISSUE TITLE
Dialogbox not visible

### ISSUE THREAD

**Issue by agarwlGaurav** [Prototik/HoloEverywhere#276]
I am trying to show a Dialogfragment. The text in the box is visible but the the boundary is not.
I have described the full issue on the below link.

http://stackoverflow.com/questions/14347519/dialogbox-not-visible-in-holoeverywhere

**Comment by Prototik** [comment]
Maybe you should be use DialogFragment.show(FragmentManager) instead of custom work with fm? You add fragment view in container, it's mean less.

**Comment by agarwlGaurav** [comment]
Thanks Sergey and your work is very good.
