### ISSUE TITLE
Setting Switch textOn/textOff from xml doesn't work

### ISSUE THREAD

**Issue by brmcmaho** [Prototik/HoloEverywhere#277]
<org.holoeverywhere.widget.Switch
        android:id="@+id/my_switch"
        android:textOn="Foo"
        android:textOff="Bar" />

Setting custom slider text for a switch via attributes in xml (as in the above example) fails to change the default test. Calling setOnText()/setOffText() on the switch in code does work.

**Comment by Prototik** [comment]
Use HE package:

``` xml
<org.holoeverywhere.widget.Switch
  xmlns:holo="http://schemas.android.com/apk/res-auto"
  android:id="@+id/my_switch"
  holo:textOn="Foo"
  holo:textOff="Bar" />
```

By the way, why the full name with package? `<Switch />` doesn't work?
