### ISSUE TITLE
Cannot set selected state of list item

### ISSUE THREAD

**Issue by aliHafizji** [Prototik/HoloEverywhere#278]
I've trying to set the selected/activated state of my list items to an orange color. Since this color should be on all listviews in the app I decided to extend the style.

Here is the style:

<style name="cheddar_ListView" parent="@style/Holo.ListView.Light">
        <item name="android:listSelector">@drawable/selectable_background_cheddar</item>
</style>

and the selector is:

<selector xmlns:android="http://schemas.android.com/apk/res/android" android:exitFadeDuration="@android:integer/config_mediumAnimTime">

```
<item android:drawable="@color/transparent" android:state_window_focused="false"/>

<item android:drawable="@drawable/pressed_background_cheddar" android:state_focused="true" android:state_pressed="true"/>
<item android:drawable="@drawable/pressed_background_cheddar" android:state_focused="false" android:state_pressed="true"/>

<item android:drawable="@drawable/pressed_background_cheddar" android:state_activated="true"/>

<item android:drawable="@drawable/list_focused_cheddar" android:state_focused="true"/>
```

</selector>

Everything seems to work fine but when I long press the state changes to the Holo blue. Has anyone faced this issue? Am I doing something wrong?

**Comment by Prototik** [comment]
listChoiceBackgroundIndicatorSingle/listChoiceBackgroundIndicatorMultiplue

**Comment by aliHafizji** [comment]
@Prototik Can you please elaborate I tried searching for the properties you mentioned but couldn't find anything.

**Comment by Prototik** [comment]
Oops, `android:listChoiceBackgroundIndicator`, i'm sorry :)

**Comment by aliHafizji** [comment]
@Prototik  Here is the new style

![Screen Shot 2013-01-16 at 1 02 54 PM](https://f.cloud.github.com/assets/283681/70553/f907f6f2-5fae-11e2-82a0-c8fd3c176d87.png)

When I long press it still moves to the default blue color

**Comment by Prototik** [comment]
Try to set two attributes: android:listChoiceBackgroundIndicator and android:listSelector with equals values (your selector).

**Comment by aliHafizji** [comment]
@Prototik Nope still not working

![Screen Shot 2013-01-16 at 1 25 59 PM](https://f.cloud.github.com/assets/283681/70579/38c72e90-5fb2-11e2-8a08-48de0ee45a80.png)

**Comment by Prototik** [comment]
Duplicate attrs in theme.

**Comment by aliHafizji** [comment]
@Prototik is that a bug?

**Comment by aliHafizji** [comment]
@Prototik I tried setting these at the theme level and still no luck!

**Comment by Prototik** [comment]
Gm, I don't know) I will answer tomorrow.

**Comment by tmurakami** [comment]
I also faced a similar problem using multi choice mode.
To avoid this problem, I added the **modalBackgroundWrapper** to my theme.

res/values/styles.xml

``` xml
<style name="MyTheme" parent="Holo.Theme.Light.DarkActionBar">
  <item name="modalBackgroundWrapper">@drawable/my_activatable_background</item>
</style>
```

res/drawable/my_activatable_background.xml

``` xml
<selector xmlns:android="http://schemas.android.com/apk/res/android">
  <item android:drawable="@drawable/my_pressed_background" android:state_pressed="true"/>
  <item android:drawable="@drawable/my_focused_background" android:state_focused="true"/>
  <item android:drawable="@drawable/my_focused_background" android:state_selected="true"/>
  <item android:drawable="@drawable/my_activated_background" android:state_activated="true"/>
  <item android:drawable="@drawable/my_activated_background" android:state_checked="true"/>
  <item android:drawable="@color/transparent"/>
</selector>
```

**Comment by ghost** [comment]
@tmurakami where do you specify in your list that you are using the modalBackgroundWrapper?

**Comment by tmurakami** [comment]
@RemieM The **modalBackgroundWrapper** is used in **org.holoeverywhere.widget.ModalBackgroundWrapper** that is a wrapper for list item.
https://github.com/ChristopheVersieux/HoloEverywhere/blob/master/library/src/org/holoeverywhere/widget/ModalBackgroundWrapper.java#L29
https://github.com/ChristopheVersieux/HoloEverywhere/blob/master/library/src/org/holoeverywhere/widget/ListView.java#L531
