### ISSUE TITLE
Demo Activity following maven instructions (compile and run) does not work - No Android SDK path could be found.

### ISSUE THREAD

**Issue by ghost** [Prototik/HoloEverywhere#279]
Hello!

All of my projects have had no errors when adding to eclipse. I followed the instructions on the maven page of this HE's wiki. However, when I try to compile and run the DemoActivity, I get many errors. The first, when I create the "HoloEverywhere Build" and click apply and run, I get this:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building HoloEverywhere Library 1.4.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ library ---
[INFO] Deleting C:\Users\Akhil\HoloEverywhere\library\target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ library ---
[INFO] 
[INFO] --- builder:1.4.2:build (default) @ library ---
[INFO] 
[INFO] Compile styles.json => C:\Users\Akhil\HoloEverywhere\library\res\values\styles.xml
[INFO] 
[INFO] Compile styles-v14.json => C:\Users\Akhil\HoloEverywhere\library\res\values-v14\styles.xml
[INFO] 
[INFO] 
[INFO] --- translator:1.4.2:build (default) @ library ---
[ERROR] Android SDK path not valid: null
[INFO] 
[INFO] --- android-maven-plugin:3.5.0:generate-sources (default-generate-sources) @ library ---
[DEBUG] Expanding: C:\Users\Akhil.m2\repository\com\actionbarsherlock\actionbarsherlock\4.2.0\actionbarsherlock-4.2.0.apklib into C:\Users\Akhil\HoloEverywhere\library\target\unpack\apklibs\com.actionbarsherlock_actionbarsherlock_apklib_4.2.0
[DEBUG] expand complete
[INFO] ANDROID-904-002: Found aidl files: Count = 0
[INFO] ANDROID-904-002: Found aidl files: Count = 0
[INFO] ANDROID-904-002: Found aidl files: Count = 0
[INFO] Manifest merging disabled. Using project manifest only
[ERROR] Error when generating sources.
org.apache.maven.plugin.MojoExecutionException: No Android SDK path could be found. You may configure it in the plugin configuration section in the pom file using <sdk><path>...</path></sdk> or <properties><android.sdk.path>...</android.sdk.path></properties> or on command-line using -Dandroid.sdk.path=... or by setting environment variable ANDROID_HOME
    at com.jayway.maven.plugins.android.AbstractAndroidMojo.getAndroidHomeOrThrow(AbstractAndroidMojo.java:1077)
    at com.jayway.maven.plugins.android.AbstractAndroidMojo.getAndroidSdk(AbstractAndroidMojo.java:1030)
    at com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.generateR(GenerateSourcesMojo.java:455)
    at com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.execute(GenerateSourcesMojo.java:193)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.139s
[INFO] Finished at: Fri Jan 18 14:55:51 EST 2013
[INFO] Final Memory: 8M/21M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.5.0:generate-sources (default-generate-sources) on project library: No Android SDK path could be found. You may configure it in the plugin configuration section in the pom file using <sdk><path>...</path></sdk> or <properties><android.sdk.path>...</android.sdk.path></properties> or on command-line using -Dandroid.sdk.path=... or by setting environment variable ANDROID_HOME -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

And afterwards, when I try to create the HoloEverywhere Demo Run, I simply get this.

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building HoloEverywhere Demo 1.4.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- android-maven-plugin:3.5.0:deploy (default-cli) @ demo ---
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Skipping HoloEverywhere Demo
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.713s
[INFO] Finished at: Fri Jan 18 14:57:21 EST 2013
[INFO] Final Memory: 7M/18M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.5.0:deploy (default-cli) on project demo: No Android SDK path could be found. You may configure it in the plugin configuration section in the pom file using <sdk><path>...</path></sdk> or <properties><android.sdk.path>...</android.sdk.path></properties> or on command-line using -Dandroid.sdk.path=... or by setting environment variable ANDROID_HOME -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Any help as to why it says that the Android SDK path could not be found?
Thanks

**Comment by Prototik** [comment]
Execute the step "Rebuild library with Maven" include keystore specify.

**Comment by ghost** [comment]
Can't I just use the existing keystore and skip to step 2 with the xml editing?

**Comment by Prototik** [comment]
You can use exists keystore, but you cannot skip 2 step.

**Comment by ghost** [comment]
1) Can I use the debug keystore

2) Can I put something like this as the path to my keystore?
C:\Users<myName>.android\debug.keystore

**Comment by Prototik** [comment]
1) Any keystore.  
2) Yea, right, full path with C:/...

**Comment by ghost** [comment]
Where do I do this step?

cd HoloEverywhere
mvn clean install

**Comment by Prototik** [comment]
Just run build via Eclipse.

**Comment by ghost** [comment]
I received this. Better than last time I suppose.

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building HoloEverywhere Library 1.4.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ library ---
[INFO] Deleting C:\Users\Akhil\HoloEverywhere\library\target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ library ---
[INFO] 
[INFO] --- builder:1.4.2:build (default) @ library ---
[INFO] 
[INFO] Compile styles.json => C:\Users\Akhil\HoloEverywhere\library\res\values\styles.xml
[INFO] 
[INFO] Compile styles-v14.json => C:\Users\Akhil\HoloEverywhere\library\res\values-v14\styles.xml
[INFO] 
[INFO] 
[INFO] --- translator:1.4.2:build (default) @ library ---
[ERROR] Platform path for version 16 not found: C:\Users\Akhil\Downloads\Development\adt-bundle-windows-x86\adt-bundle-windows-x86\sdk\platforms\android-16
[INFO] 
[INFO] --- android-maven-plugin:3.5.0:generate-sources (default-generate-sources) @ library ---
[DEBUG] Expanding: C:\Users\Akhil.m2\repository\com\actionbarsherlock\actionbarsherlock\4.2.0\actionbarsherlock-4.2.0.apklib into C:\Users\Akhil\HoloEverywhere\library\target\unpack\apklibs\com.actionbarsherlock_actionbarsherlock_apklib_4.2.0
[DEBUG] expand complete
[INFO] ANDROID-904-002: Found aidl files: Count = 0
[INFO] ANDROID-904-002: Found aidl files: Count = 0
[INFO] ANDROID-904-002: Found aidl files: Count = 0
[INFO] Manifest merging disabled. Using project manifest only
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.006s
[INFO] Finished at: Fri Jan 18 22:21:11 EST 2013
[INFO] Final Memory: 9M/21M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.5.0:generate-sources (default-generate-sources) on project library: Execution default-generate-sources of goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.5.0:generate-sources failed: Invalid SDK: Platform/API level 16 not available. This command should give you all you need:
[ERROR] C:\Users\Akhil\Downloads\Development\adt-bundle-windows-x86\adt-bundle-windows-x86\sdk\tools\android update sdk --no-ui --obsolete --force
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

However, does my settings.xml have something wrong?

```
    <settings>
    <profiles>
      <profile>
        <activation>
          <activeByDefault>true</activeByDefault>
        </activation>
        <properties>
          <holo.sign.keystore>/C:\Users\Akhil\.android\debug.keystore</holo.sign.keystore>
          <holo.sign.alias>androiddebugkey</holo.sign.alias>
          <holo.sign.storepass>android</holo.sign.storepass>
          <holo.sign.keypass>android</holo.sign.keypass>
          <android.sdk.path>/C:\Users\Akhil\Downloads\Development\adt-bundle-windows-x86\adt-bundle-windows-x86\sdk</android.sdk.path>
        </properties>
      </profile>
    </profiles>
    </settings>
```

**Comment by Prototik** [comment]
All correct, but install API 16 platform.

**Comment by ghost** [comment]
It says that I'm using jdk instead of jre. I don't get how though. I even went and set the path to use jdk in the "Installed JRE's" when I got this error and it still gets it.

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.816s
[INFO] Finished at: Sat Jan 19 08:12:15 EST 2013
[INFO] Final Memory: 10M/35M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project library: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by ghost** [comment]
nevermind I fixed the build by adding the JRE inside the run configurations window. However, I get the following error when building the demo activity.

[INFO] ------------------------------------------------------------------------
[INFO] Building HoloEverywhere Demo 1.4.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- android-maven-plugin:3.5.0:deploy (default-cli) @ demo ---
[INFO] C:\Users\Akhil\Downloads\Development\adt-bundle-windows-x86\adt-bundle-windows-x86\sdk\platform-tools\aapt.exe [dump, xmltree, C:\Users\Akhil\HoloEverywhere\demo\target\demo-1.4.2.apk, AndroidManifest.xml]
[INFO] W/asset   ( 2152): Asset path C:\Users\Akhil\HoloEverywhere\demo\target\demo-1.4.2.apk is neither a directory nor file (type=1).
[INFO] ERROR: dump failed because assets could not be loaded
[ERROR] W/asset   ( 2152): Asset path C:\Users\Akhil\HoloEverywhere\demo\target\demo-1.4.2.apk is neither a directory nor file (type=1).ERROR: dump failed because assets could not be loaded
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Skipping HoloEverywhere Demo
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.610s
[INFO] Finished at: Sat Jan 19 18:28:38 EST 2013
[INFO] Final Memory: 7M/18M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.5.0:deploy (default-cli) on project demo: Error while trying to figure out package name from inside apk file C:\Users\Akhil\HoloEverywhere\demo\target\demo-1.4.2.apk -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by Prototik** [comment]
Check on javac in PATH. Run `HoloEverywhere Build` again.
Further discussion is meaningless - it does not refer to HoloEverywhere. Try StackOverflow or other QA resource.
