### ISSUE TITLE
Spinner popup

### ISSUE THREAD

**Issue by pavel-shatskikh** [Prototik/HoloEverywhere#280]
Hi,
On devices with low screen resolution (like a htc wildfire) and when software keyboard is showing, spinner popup window overlaps because it is not enough space. It seems to me that helps if always show spinner popup from bottom screen on such devices. 
Is there any API to provide this?

**Comment by llerik** [comment]
I found a bug in the spinner, recorded it on video: http://www.youtube.com/watch?v=FlytsjvwdJ0

**Comment by Prototik** [comment]
ListPopupWindow expect that window can be overlay the keyboard, but on 2.3 and less it's not work.
![device-2013-02-10-182534](https://f.cloud.github.com/assets/1416030/143121/e2bfdc76-736c-11e2-9f4d-37ae2a4b9725.png)

**Comment by Prototik** [comment]
Oops, I accidentally fix this bug, now to push a commit.
