### ISSUE TITLE
StrictMode during layout inflating / font loading

### ISSUE THREAD

**Issue by kkocel** [Prototik/HoloEverywhere#281]
When I use TextView I get StrictMode policy violation.

01-21 15:58:56.579: D/StrictMode(572): StrictMode policy violation; ~duration=20563 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=23 violation=2
01-21 15:58:56.579: D/StrictMode(572):  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:745)
01-21 15:58:56.579: D/StrictMode(572):  at dalvik.system.BlockGuard$WrappedFileSystem.open(BlockGuard.java:228)
01-21 15:58:56.579: D/StrictMode(572):  at java.io.FileOutputStream.<init>(FileOutputStream.java:94)
01-21 15:58:56.579: D/StrictMode(572):  at java.io.FileOutputStream.<init>(FileOutputStream.java:66)
01-21 15:58:56.579: D/StrictMode(572):  at org.holoeverywhere.FontLoader.loadTypeface(FontLoader.java:192)
01-21 15:58:56.579: D/StrictMode(572):  at org.holoeverywhere.FontLoader.applyDefaultStyles(FontLoader.java:162)
01-21 15:58:56.579: D/StrictMode(572):  at org.holoeverywhere.FontLoader.applyDefaultStyles(FontLoader.java:171)
01-21 15:58:56.579: D/StrictMode(572):  at org.holoeverywhere.FontLoader.applyDefaultStyles(FontLoader.java:171)
01-21 15:58:56.579: D/StrictMode(572):  at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:289)
01-21 15:58:56.579: D/StrictMode(572):  at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
01-21 15:58:56.579: D/StrictMode(572):  at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:272)
01-21 15:58:56.579: D/StrictMode(572):  at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:267)
01-21 15:58:56.579: D/StrictMode(572):  at my.app.MyFragment.onCreateView(MyFragment.java:32)
01-21 15:58:56.579: D/StrictMode(572):  at android.support.v4.app._HoloFragment.onCreateView(_HoloFragment.java:174)
01-21 15:58:56.579: D/StrictMode(572):  at android.support.v4.app.Fragment.performCreateView(Fragment.java:1460)
01-21 15:58:56.579: D/StrictMode(572):  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:911)
01-21 15:58:56.579: D/StrictMode(572):  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
01-21 15:58:56.579: D/StrictMode(572):  at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
01-21 15:58:56.579: D/StrictMode(572):  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1444)
01-21 15:58:56.579: D/StrictMode(572):  at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
01-21 15:58:56.579: D/StrictMode(572):  at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1129)
01-21 15:58:56.579: D/StrictMode(572):  at android.app.Activity.performStart(Activity.java:3791)
01-21 15:58:56.579: D/StrictMode(572):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1624)
01-21 15:58:56.579: D/StrictMode(572):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1667)
01-21 15:58:56.579: D/StrictMode(572):  at android.app.ActivityThread.access$1500(ActivityThread.java:117)
01-21 15:58:56.579: D/StrictMode(572):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:935)
01-21 15:58:56.579: D/StrictMode(572):  at android.os.Handler.dispatchMessage(Handler.java:99)
01-21 15:58:56.579: D/StrictMode(572):  at android.os.Looper.loop(Looper.java:123)
01-21 15:58:56.579: D/StrictMode(572):  at android.app.ActivityThread.main(ActivityThread.java:3687)
01-21 15:58:56.579: D/StrictMode(572):  at java.lang.reflect.Method.invokeNative(Native Method)
01-21 15:58:56.579: D/StrictMode(572):  at java.lang.reflect.Method.invoke(Method.java:507)
01-21 15:58:56.579: D/StrictMode(572):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
01-21 15:58:56.579: D/StrictMode(572):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
01-21 15:58:56.579: D/StrictMode(572):  at dalvik.system.NativeStart.main(Native Method)

**Comment by Prototik** [comment]
20563 ms. 20 seconds. Are you serious? 

Did you wait 20 seconds before starting the demo? Not even 20, 40, because there are use two sets of fonts. And it's executed in the ui thread.

**Comment by kkocel** [comment]
Usually it is 2 x 2 secs. But still it is quite a long time...

**Comment by damiafuentes** [comment]
Did you find a solution?
