### ISSUE TITLE
List scroll

### ISSUE THREAD

**Issue by juscyllan** [Prototik/HoloEverywhere#282]
Since I moved to version 1.4.1 of HoloEverywhere i'm having troubles with the scroll of my ListFragments in Android 10.

When the user scrolls and the scrollbar reached the bottom of the view, I don't know why the scrollbar goes up.

I noted that this doesn't happens in version 1.4.0 or if I'm using android 16

**Comment by dbacinski** [comment]
Are you using android:overScrollMode="never"? There is a bug in scroller implementation in Gingerbread:

http://code.google.com/p/android/issues/detail?id=15860

**Comment by juscyllan** [comment]
I'm not using it, but somewhere in the code you set the overScrollMode of the ListView to "never" programmatically. Check ListView constructor, line 211.

Now I changed the overscroll mode after the ListView was created and the scroll worked normal.

**Comment by BraisGabin** [comment]
This problem appears when you use AlertDialog.Builder.setAdapter() too.

**Comment by httpdispatch** [comment]
Experienced same problem with ListView after moving to latest master commit and adding Slider

**Comment by Prototik** [comment]
@httpdispatch 869e78d8618ea625c9d27eb807684bc4165041b8

**Comment by httpdispatch** [comment]
@Prototik thanks a lot. You are awesome. Seems that commit fixed an issue

**Comment by Prototik** [comment]
overScrollMode now untouched by library.
