### ISSUE TITLE
SetContentView in Activity causes InflateException in layout with merge tag

### ISSUE THREAD

**Issue by kkocel** [Prototik/HoloEverywhere#283]
I have very simple Activity layout with one element (TextView) and merge tag.

When I call setContentView I get:

```
InflateException: <merge /> can be used only with a valid ViewGroup root and attachToRoot=true
```

This exeception does not occur in pure Android or Sherlock library.

Related issue can be found here: http://stackoverflow.com/questions/14526325/set-content-view-in-activity-with-merge-tag-as-root

**Comment by Prototik** [comment]
Confirmed.

**Comment by Prototik** [comment]
Test now with fix above.

**Comment by kkocel** [comment]
It works, but I noticed that gravity in LinearLayout stopped working. I don't know if it's the case of the patch or some previous commits.

**Comment by Prototik** [comment]
LinearLayout - child of merge tag?

**Comment by kkocel** [comment]
No, if You have LinearLayout instead of merge and eg. a TextView inside

**Comment by Prototik** [comment]
You can show full layout and the difference between the expected (pure Android) and the current behavior?

**Comment by kkocel** [comment]
I have following layout: https://gist.github.com/3caf5e71fde7c7c69622

In version 1.4.2 gravity in root linear layout worked nice, but in 52dd374 gravity does not work (it moves the whole content to top).

Here you can see current and expected behaviour:
http://imgur.com/a/28s7x
