### ISSUE TITLE
Compilation Error on IAddOn

### ISSUE THREAD

**Issue by william-ferguson-au** [Prototik/HoloEverywhere#285]
I'm building using JDK6. source and target are both set to 1.6

[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ Lexathon ---
[INFO] Compiling 300 source files to C:\Source\lexathon\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] \Source\lexathon\target\unpack\apklibs\org.holoeverywhere_library_apklib_1.4.2\src\org\holoeverywhere\addons\IAddon.java:[14,21] type parameters of <T>T cannot be determined; no unique maximal instance exists for type variable T with upper bounds A,java.lang.Object
[ERROR] \Source\lexathon\target\unpack\apklibs\org.holoeverywhere_library_apklib_1.4.2\src\org\holoeverywhere\addons\IAddon.java:[39,21] type parameters of <T>T cannot be determined; no unique maximal instance exists for type variable T with upper bounds F,java.lang.Object
[INFO] 2 errors

**Comment by Prototik** [comment]
Update JDK. I'm use javac 1.7.0_09, but should be work on latest OpenJDK 6.

**Comment by william-ferguson-au** [comment]
Same failure on JDK7

**Comment by Prototik** [comment]
Am I compile on the mythical JDK?

```
[prok@prok-pc ~]$ pacman -Qi jdk7-openjdk 
Name           : jdk7-openjdk
Version        : 7.u9_2.3.4-1
```

**Comment by william-ferguson-au** [comment]
Am I?

C:\Source\lexathon>javac -version
javac 1.7.0

**Comment by william-ferguson-au** [comment]
This SO suggests that perhaps you are suggesting too of generics.
http://stackoverflow.com/questions/5666027/why-does-the-compiler-state-no-unique-maximal-instance-exists

**Comment by Prototik** [comment]
It is better to show the `java -version`.

It's bug in Oracle/Sun JDK.

**Comment by william-ferguson-au** [comment]
C:\Source\lexathon>java -version
java version "1.7.0"
Java(TM) SE Runtime Environment (build 1.7.0-b147)
Java HotSpot(TM) 64-Bit Server VM (build 21.0-b17, mixed mode)

Have you got a reference for the bug in the Oracle SDK?

**Comment by william-ferguson-au** [comment]
OK, I can confirm that this does indeed compile OK with JDK7. IntelliJ was masking where it was pulling the JDK from. Still not convinced it is a bug within the Oracle JDK, but definitely a difference in implementation between it and OpenJDK.

I'm planning on using HoloEverywhere as well as ActionBarSherlock (which I already use). Does HE contain all the functionality of ABS or do I need to include a dependency to ABS separately?

**Comment by Prototik** [comment]
HE has a ABS dependency. Fully compatibly.

**Comment by william-ferguson-au** [comment]
Awesome, thanks.

**Comment by william-ferguson-au** [comment]
Sergey I realise that this error probably occurs because the JDK6 compiler does not do a good job determining the return type inference is this case, but there is a simple change that can be made to the IAddon class that will allow compilation of HE by a client using JDK6.

I have submitted a pull request #295 with the changes.
Please consider.

**Comment by dlnsk** [comment]
I using OpenJDK 1.6:
java version "1.6.0_26"
Java(TM) SE Runtime Environment (build 1.6.0_26-b03)
Java HotSpot(TM) 64-Bit Server VM (build 20.1-b02, mixed mode)

Have 3 errors:
/HoloEverywhere/library/src/org/holoeverywhere/addon/IAddon.java
    Error:Error:line (58)java: type parameters of <V>V cannot be determined; no unique maximal instance exists for type variable V with upper bounds Z,org.holoeverywhere.addon.IAddonBase<T>
    Error:Error:line (62)java: type parameters of <V>V cannot be determined; no unique maximal instance exists for type variable V with upper bounds Z,org.holoeverywhere.addon.IAddonBase<T>
/HoloEverywhere/library/src/org/holoeverywhere/addon/IAddonBasicAttacher.java
    Error:Error:line (49)java: type parameters of <Z>Z cannot be determined; no unique maximal instance exists for type variable Z with upper bounds T,org.holoeverywhere.addon.IAddonBase<V>

**Comment by Prototik** [comment]
JRE 6 end of life date - February 2013. Maybe do you want use jre 5.0?
Man, just install jdk7.
