### ISSUE TITLE
Wrong list color when using setItems + setNegativeButton

### ISSUE THREAD

**Issue by RomanTruba** [Prototik/HoloEverywhere#286]
This bug is appear on android 2.1, emulator.

![screenshot1](https://f.cloud.github.com/assets/1570382/102789/45304436-693b-11e2-898d-a7f467612bd8.jpg)

App theme is set to @style/Holo.Theme.Light
My code is

``` java
new AlertDialog.Builder(getActivity())
.setItems(new String[]{getString(R.string.edit), getString(R.string.remove)}, new DialogInterface.OnClickListener() { ... })
.setNegativeButton(R.string.cancel, new DialogInterface.OnClickListener() {...})
.show();
```

**Comment by Prototik** [comment]
Эх, Dreddik-Dreddik. Нельзя так со мной :D

Confirmed.

**Comment by RomanTruba** [comment]
:)

**Comment by Prototik** [comment]
I'm try to reproduce this bug, but i don't can. See source in new branch [bugs](https://github.com/ChristopheVersieux/HoloEverywhere/blob/bugs/Bug286/src/org/holoeverywhere/bug/i286/MainActivity.java)

Issue rejected.

I'm sorry, i reproduce bug with light theme.

**Comment by Prototik** [comment]
![Screenshot](https://f.cloud.github.com/assets/1416030/106503/eec9929e-69fa-11e2-8e09-01dfc6332531.png)

**Comment by RomanTruba** [comment]
If I could, I would increase your habra-carma twice
