### ISSUE TITLE
Remap in layout inflater causes animator to stop

### ISSUE THREAD

**Issue by kkocel** [Prototik/HoloEverywhere#289]
remap(FrameLayout.class);

in commit 
https://github.com/ChristopheVersieux/HoloEverywhere/commit/4e2922386975aae75e497f3a4ea763c89d7b567d

causes UI to frezee.

**Comment by uKL** [comment]
Hi, 

I'm emailing you an example where this bug occurs. It occurs for example when you implement a drawer(sliding menu). I'm implementing my own drawer, however this example uses SlidingMenu.

It looks like it freeze drawing process, but motion events are processed properly.

Moreover, the issue appears only on pre-Honeycomb devices (emulator as well).

**Comment by Prototik** [comment]
Refers #273.

**Comment by Prototik** [comment]
@uKL you have more useful implementation of sliding drawer? I could use it if it will be good.

**Comment by uKL** [comment]
I'm sorry but for now I'm unable to go public with my implementation. 

However what I'm doing is injecting a view between **DecorView** and it's child. Probably **SlidingMenu** does the same and it causes problems on pre-HC devices. Without HoloEverywhere all looks fine. Particularly without using **Nineoldandroid proxyAnimator** (look at yout FrameLayout). In the mentioned commit you have started remaping **FrameLayouts**

**Comment by uKL** [comment]
BTW. To reproduce, just rotate the screen and try touching the button.

**Comment by uKL** [comment]
Thanks, it should work now. I will check and update here. When can we expect next stable release containing this fix?

**Comment by kkocel** [comment]
@Prototik I've seen that You removed NineOldAndroids support but in fact You're using internal package which usage is discouraged. See https://github.com/JakeWharton/NineOldAndroids/issues/33

**Comment by Prototik** [comment]
@kkocel Mmm... internal package? org.holoeverywhere.internal? Even if it is, then what? The fact that there is should not be used directly by developers.
@uKL I do not know, but pretty soon. I'm busy right now, but @ChristopheVersieux  promised to return soon,

**Comment by kkocel** [comment]
@Prototik I think that bug (animation stop) occurred because You  were using internal nineOldAndroids instead of separate library. Maybe If you would use the full library it would work....

**Comment by Prototik** [comment]
@kkocel Yea, maybe, but i don't see reason for any usage NOA or embedded copy from ABS package in any class of HoloEverywhere. Code was there by my mistake, I admit.
