### ISSUE TITLE
GooglePlayServicesUtil.getErrorDialog != HoloEverywhere Dialog

### ISSUE THREAD

**Issue by tverona** [Prototik/HoloEverywhere#291]
HoloEverywhere DialogFragment.onCreateDialog cannot return GooglePlayServicesUtil.getErrorDialog(), since of course it is a different type. What's the best way to handle this? Thanks.

**Comment by Prototik** [comment]
We will not add support for third-party or system dialogs, it's just not possible. You can get a View of the dialog and create HoloEverywhere.Dialog with the desired view.

**Comment by httpdispatch** [comment]
@Prototik can you please tell more how to get view of the GooglePlayServices dialog without showing it?

**Comment by Prototik** [comment]
`GooglePlayServicesUtil.getErrorDialog().getView()` ?

**Comment by httpdispatch** [comment]
It looks like there is no such method
![image](https://f.cloud.github.com/assets/2315223/494565/f0c7cb32-bb9f-11e2-95f2-7e25890c7e43.png)
However seems that app doesn't crash when i call `errorDialog.show()`

**Comment by Prototik** [comment]
`GooglePlayServicesUtil.getErrorDialog().getWindow().getDecorView().findViewById(android.R.id.content)`

**Comment by httpdispatch** [comment]
Result is not good in this case

``` java
                Dialog errorDialog = GooglePlayServicesUtil.getErrorDialog(availabilityResult,
                        getActivity(),
                        requestCode);
                org.holoeverywhere.app.Dialog dialog = new org.holoeverywhere.app.Dialog(
                        getActivity());
                dialog.setContentView(errorDialog.getWindow().getDecorView()
                        .findViewById(android.R.id.content));
                dialog.show();
```

Seeing this
![image](https://f.cloud.github.com/assets/2315223/494659/d97289f0-bba3-11e2-9f54-620341609bab.png)

instead of this
![image](https://f.cloud.github.com/assets/2315223/494670/3ad5f600-bba4-11e2-9936-22aabfdac31b.png)
