### ISSUE TITLE
PreferenceFramework not found

### ISSUE THREAD

**Issue by a0g83agbc84** [Prototik/HoloEverywhere#296]
Today I've updated HoloEverywhere and ActionBarSherlock to the last version and SharedPreferences isn't working properly.

Here's the log:

02-06 12:52:06.559: E/AndroidRuntime(2423): FATAL EXCEPTION: main
02-06 12:52:06.559: E/AndroidRuntime(2423): java.lang.UnsatisfiedLinkError: HoloEverywhere: PreferenceFramework not found
02-06 12:52:06.559: E/AndroidRuntime(2423):     at org.holoeverywhere.preference.PreferenceManagerHelper.checkImpl(PreferenceManagerHelper.java:35)
02-06 12:52:06.559: E/AndroidRuntime(2423):     at org.holoeverywhere.preference.PreferenceManagerHelper.wrap(PreferenceManagerHelper.java:51)
02-06 12:52:06.559: E/AndroidRuntime(2423):     at org.holoeverywhere.preference.PreferenceManagerHelper.wrap(PreferenceManagerHelper.java:57)
02-06 12:52:06.559: E/AndroidRuntime(2423):     at android.support.v4.app._HoloActivity.getSharedPreferences(_HoloActivity.java:263)
02-06 12:52:06.559: E/AndroidRuntime(2423):     at android.support.v4.app._HoloActivity.getSharedPreferences(_HoloActivity.java:1)
02-06 12:52:06.559: E/AndroidRuntime(2423):     at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:348)
02-06 12:52:06.559: E/AndroidRuntime(2423):     at carl.fri.fer.ks.Main.onStart(Main.java:76)
02-06 12:52:06.559: E/AndroidRuntime(2423):     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1129)
02-06 12:52:06.559: E/AndroidRuntime(2423):     at android.app.Activity.performStart(Activity.java:3791)
02-06 12:52:06.559: E/AndroidRuntime(2423):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1620)
02-06 12:52:06.559: E/AndroidRuntime(2423):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
02-06 12:52:06.559: E/AndroidRuntime(2423):     at android.app.ActivityThread.access$1500(ActivityThread.java:117)
02-06 12:52:06.559: E/AndroidRuntime(2423):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
02-06 12:52:06.559: E/AndroidRuntime(2423):     at android.os.Handler.dispatchMessage(Handler.java:99)
02-06 12:52:06.559: E/AndroidRuntime(2423):     at android.os.Looper.loop(Looper.java:130)
02-06 12:52:06.559: E/AndroidRuntime(2423):     at android.app.ActivityThread.main(ActivityThread.java:3683)
02-06 12:52:06.559: E/AndroidRuntime(2423):     at java.lang.reflect.Method.invokeNative(Native Method)
02-06 12:52:06.559: E/AndroidRuntime(2423):     at java.lang.reflect.Method.invoke(Method.java:507)
02-06 12:52:06.559: E/AndroidRuntime(2423):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
02-06 12:52:06.559: E/AndroidRuntime(2423):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
02-06 12:52:06.559: E/AndroidRuntime(2423):     at dalvik.system.NativeStart.main(Native Method)

I've tried the following:

SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(this);
SharedPreferences prefs = getDefaultSharedPreferences();

But none of them is working.

**Comment by Prototik** [comment]
Attach PreferenceFramework from addons folder.

**Comment by a0g83agbc84** [comment]
You are very fast! Thank you! But... why the preferences has been extracted?

**Comment by Prototik** [comment]
For religious and political reasons. Well why? I wanted to do this :P

Just do not all need PreferenceFramework, well, I did split from the core of library.

**Comment by a0g83agbc84** [comment]
Hahah! Ok, it makes sense. Thank you for the hard work!

**Comment by Prototik** [comment]
A button "Thank you" is placed on the main page and named "Donate" :P Joke.

**Comment by a0g83agbc84** [comment]
A donation will be sent as soon as I register a PayPal account. NOT a joke. :)

**Comment by prograde** [comment]
How do I do this? I imported the Addon Preferences project in my Eclipse workspace, and made a reference to it from my own project. Is this the correct way? Is there anything more I have to do? I Still get the same error " java.lang.UnsatisfiedLinkError: HoloEverywhere: PreferenceFramework not found" when running the project.

**Comment by Prototik** [comment]
@prograde Like you attach main library - android/library menu.

**Comment by TheLushpen** [comment]
Привет, такая же проблема. Однако проект  Addon Preferences приааттачен. Дебаг версия работает отлично. Когда собираю Signed версию для маркета, падает при запуске.

**Comment by Prototik** [comment]
@TheLushpen ProGuard включен?

**Comment by TheLushpen** [comment]
Да, я решил уже проблему, спасибо!
