### ISSUE TITLE
Preference items are ignoring my theme

### ISSUE THREAD

**Issue by mattprecious** [Prototik/HoloEverywhere#299]
Updated to `1.4.3-SNAPSHOT` and now all of my Preference items (`CheckBoxPreference`, `ListPreference`, etc.) are all using `Holo` when my app is using `Holo.Light.DarkActionBar`.

The preference headers are correct, it's just the preference items that are broken. I'll start investigating, but maybe you'll be quicker to find it than me.

**Comment by mattprecious** [comment]
So I discovered that you've added new `Holo.PreferenceTheme` themes, however, switching to `Holo.PreferenceTheme.Light` still has the text colours for preference items as Holo. Still investigating.

**Comment by mattprecious** [comment]
So, just an update on what's come up in my testing...
- The `PreferenceActivity` is fine, the Action Bar and my background are all `Holo.Light.DarkActionBar`
- The `preference-headers` are all fine
- All of my `Preferences` are Holo Dark
- All of the `PreferenceDialogs` are Holo Dark
- The `PreferenceCheckBox` items are ignoring my custom orange checkbox images

This is the case for both my phone and my tablet. It sounds like it might be a problem with the `PreferenceFragment`? I honestly have no clue.

**Comment by Prototik** [comment]
![device-2013-02-11-153443](https://f.cloud.github.com/assets/1416030/144457/0fe7f524-741e-11e2-8ea5-cd0767b8e756.png)

Thanks for bug report!

**Comment by Prototik** [comment]
About this:

> The PreferenceCheckBox items are ignoring my custom orange checkbox images

You should create custom theme extends from Holo.PreferenceTheme and Holo.PreferenceTheme.Light and remap Preference themes on yours:

``` xml
<style name="CustomPreferenceTheme" parent="Holo.PreferenceTheme">
  <item name="checkBoxPreferenceStyle">@style/CustomPreferenceCheckBox</item>
</style>
<style name="CustomPreferenceTheme.Light" parent="Holo.PreferenceTheme.Light">
  <item name="checkBoxPreferenceStyle">@style/CustomPreferenceCheckBox</item>
</style>
```

In static code block of your `Application` class:

``` java
PreferenceInit.map(R.style.CustomPreferenceTheme, R.style.CustomPreferenceTheme_Light);
```

**Comment by mattprecious** [comment]
Doesn't seem to be working for me. Any suggestions?

![nope](https://f.cloud.github.com/assets/333672/145171/f66e8b26-7454-11e2-8dfe-9c8cda2de410.png)

**Comment by Prototik** [comment]
Show code.

**Comment by mattprecious** [comment]
I've emailed you a test project that I just wrote, and a screenshot of how it looks on my device.

**Comment by Prototik** [comment]
You are specify theme in manifest. When theme manager resolve activity theme and try to determine color scheme (dark/light/mixed), it's cannot resolve it. And it apply default PreferenceTheme - Dark.
Use ThemeManager: 

You can apply theme before onCreate:

``` java
setTheme(ThemeManager.MIXED);
super.onCreate(savedInstanceState);
```

Or define default application theme in Application class:

``` java
public class MyApplication extends org.holoeverywhere.app.Application {
  static {
    ThemeManager.setDefaultTheme(ThemeManager.MIXED);
  }
}
```

Screenshots:
![holoeverywhere_bug299_dark](https://f.cloud.github.com/assets/1416030/147815/05d718ac-74d8-11e2-946b-6b1be7e6d38d.png)
![holoeverywhere_bug299_light](https://f.cloud.github.com/assets/1416030/147816/05d96c4c-74d8-11e2-98c0-bbedb5223e92.png)
![holoeverywhere_bug299_mixed](https://f.cloud.github.com/assets/1416030/147817/06172dca-74d8-11e2-936f-8da81ccc6448.png)

**Comment by Prototik** [comment]
Now you can specify theme in manifest - theme manager also checking theme attribute for determine color scheme.

**Comment by mattprecious** [comment]
Lots of possibilities! :)

This works!:

``` java
public class MyApplication extends org.holoeverywhere.app.Application {
  static {
    ThemeManager.setDefaultTheme(ThemeManager.MIXED);
  }
}
```

This doesn't:

``` java
setTheme(ThemeManager.MIXED);
super.onCreate(savedInstanceState);
```

I'd prefer to use XML to do this, though, so I tried your new Manifest changes, but I'm not sure how to use them.

This doesn't work:

``` xml
<application
        android:name="org.holoeverywhere.app.Application"
        android:allowBackup="true"
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/Holo.Theme.Light.DarkActionBar">
```

Neither does this:

``` xml
<application
        android:name="org.holoeverywhere.app.Application"
        android:allowBackup="true"
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/Holo.Theme.Light.DarkActionBar"
        holo:holoTheme="mixed" >
```

Or this:

``` xml
<activity
            android:name="com.example.preferencetest.SettingsActivity"
            android:label="@string/app_name"
            android:theme="@style/Holo.Theme.Light.DarkActionBar"
            holo:holoTheme="mixed" >
```

What am I doing wrong? Thanks for working through this with me.

**Comment by Prototik** [comment]
[Bug project](https://github.com/ChristopheVersieux/HoloEverywhere/blob/bugs/Bug299/AndroidManifest.xml)

**Comment by MartinRajniak** [comment]
Is there a temporary solution for this? 
The best I get is action bar theming, but otherwise everything stays in dark theme for the preferences when using headers.

**Comment by Prototik** [comment]
@demartino88 With latest version from master you can specify any theme from manifest or code, even without ThemeManager. You are all good checked?

**Comment by mattprecious** [comment]
Wooooooo!!!!!! It's working again!

My custom styling isn't working, though :( Test project here: https://github.com/mattprecious/Bug299

Could you possibly make that work via the Manifest again? Or is that too much work? It was working perfectly on 1.4.2 before you pulled Preferences out into an add-on.

Thanks!

**Comment by MartinRajniak** [comment]
The latest commit fixed my issue. 

It would be nice though to specify the theme only in xml.

Thank you for help.

**Comment by mattprecious** [comment]
@demartino88 If you don't have any custom drawables for check boxes or the like, the latest update honours your android:theme attribute in your manifest file. See the demo project Sergey posted earlier.

**Comment by Prototik** [comment]
@mattprecious PreferenceTheme should be extends Holo.PreferenceTheme.

**Comment by Prototik** [comment]
Okay, I'm make resolving preference theme also by activity theme attribute, but only tomorrow and only if my girlfriend allow me to run ide :P

**Comment by mattprecious** [comment]
Haha, spend time with your girlfriend, Sergey! This doesn't need to be done tomorrow.

**Comment by eiuol07** [comment]
Hi theres a weird shadow above the context menu when I am using ThemeManager.Light theme.. Is this fixed?

Thanks..
