### ISSUE TITLE
Doesn't work holo:id atribute

### ISSUE THREAD

**Issue by TheLushpen** [Prototik/HoloEverywhere#303]
Doesnt work with:
<Preference
holo:selectable="false"
holo:id="@+id/query"
holo:title="@string/query_settings" />

But work without atribute holo:id.

logcat:
02-12 13:23:03.201: E/AndroidRuntime(1753): android.view.InflateException: Binary XML file line #5: Error inflating class org.holoeverywhere.widget.Preference
02-12 13:23:03.201: E/AndroidRuntime(1753):     at org.holoeverywhere.internal.GenericInflater.createItemFromTag(GenericInflater.java:117)
02-12 13:23:03.201: E/AndroidRuntime(1753):     at org.holoeverywhere.internal.GenericInflater.rInflate(GenericInflater.java:223)

**Comment by Prototik** [comment]
PreferenceFramework?
You application should be extends org.holoeverywhere.app.Application and it's should be specified in AndroidManifest.xml in `<application>` tag with `android:name` attr. Or disable `Named preferences` property in org.holoeverywhere.HoloEverywhere class.

**Comment by TheLushpen** [comment]
it helps, thank you for this and for all your work.
