### ISSUE TITLE
Incorrect fragment size

### ISSUE THREAD

**Issue by Codewaves** [Prototik/HoloEverywhere#306]
When I add fragment programmatically, I'm getting wrong fragment size. Parent activity have single RelativeLayout with both match_parent width and height.

<pre>
RelativeLayout 
   android:id="@+id/container" 
   android:layout_width="match_parent" android:layout_height="match_parent" 
/RelativeLayout
</pre>

Fragment layout has top LinearLayout with same "match_parent" width and height.

<pre>
LinearLayout 
   android:layout_width="match_parent" android:layout_height="match_parent" 
/LinearLayout 
</pre>

When I add the fragment using following code:

<pre>
FragmentManager     fragmentManager = getSupportFragmentManager();
FragmentTransaction fragmentTransaction = fragmentManager.beginTransaction();
fragmentTransaction.add(R.id.container, new TestFragment());
fragmentTransaction.commit();
</pre>

fragment view creation code:

<pre>
...
View fragment = inflater.inflate(R.layout.fragment, container, false);
...
</pre>

fragment is not full screen. It seems when fragment is wrapped into com.actionbarsherlock.internal.view.menu.ContextMenuDecorView it looses layout params, and size is calculated incorrectly.

If I add fragment directly into activity layout xml all works ok.

**Comment by Prototik** [comment]
Please test fix above.

**Comment by Prototik** [comment]
Fully fixed via e41bb86c
