### ISSUE TITLE
Increase performance

### ISSUE THREAD

**Issue by DragonWork** [Prototik/HoloEverywhere#307]
HoloEverywhere, especially PreferenceFragment, is on older devices/Android versions (like 2.3.6 or older) very slow and lags often. It should be smoother. Could you fix this, please?

**Comment by pavel-shatskikh** [comment]
Also I have noticed that PreferenceActivity spends a lot of external memory on devices with Android lower than 3.0. On image below you can see (red line) that memory consumption increased when PreferenceActivity opens (tested on Sony Ericsson Xperia Pro with Android 2.3.4):
![Screenshot from 2013-02-18 16:56:10](https://f.cloud.github.com/assets/2558313/167230/98ec011a-79ca-11e2-9110-bb1f2a4078cd.png)

**Comment by Prototik** [comment]
If I'm going to do something in this direction - that is not exactly to the 1.5 release and a special profit will not be there. Do you really want that?

**Comment by DragonWork** [comment]
Sorry, but I didn't really understand that. You think, you're able to fix this but you won't, because it would cause some problems in the newer Android versions?

**Comment by Prototik** [comment]
No, I meant that I could not improve the performance of even 20% without complete redesign of the architecture PreferenceFramework.

**Comment by DragonWork** [comment]
Oh.. that's a real shame.. :( I thought that the lagging is caused by wrong loading of the Preference images. The images (checkboxes, buttons etc.) should be loaded into RAM for smoother scrolling experience. For example by help of LruCache.

**Comment by Prototik** [comment]
For Preference classes which located in org.holoeverywhere.preference already enabled reusage of views in lists. Even if it doesn't help...

**Comment by Prototik** [comment]
This issue will be closed while I don't want make it.
