### ISSUE TITLE
Crouton library with Holoeverywhere doesn't show Crouton messages right

### ISSUE THREAD

**Issue by MartinRajniak** [Prototik/HoloEverywhere#309]
Hi,
I know you don't promise to support every library out there, but I was wondering if you couldn't help me with this. 

Crouton message when using Holoeverywhere is taking whole screen instead of its actual height.

Maybe it is a reference thing, because action bar was taking whole screen also before I changed all imports to Holoeverywhere.

**Comment by MartinRajniak** [comment]
The problem is when using

void org.holoeverywhere.app.Activity.addContentView(View view, LayoutParams params)

Params and view is set well with right values

**Comment by MartinRajniak** [comment]
I have created a show case project

https://github.com/demartino88/CroutonTestProject

**Comment by cesards** [comment]
Same problem here. Were talking about it with @keyboardsurfer here:

https://github.com/keyboardsurfer/Crouton/issues/79

**Comment by Prototik** [comment]
Yea-yea, it's bug of HE. Please wait - I don't have a free time now for fix it.

**Comment by MartinRajniak** [comment]
Can you please lead us to the workaround maybe, I have a presentation of the app, early next week. I will think of something else if not, though. Thx

**Comment by Prototik** [comment]
You owe me :D
![crouton-bug-screenshot](https://f.cloud.github.com/assets/1416030/175775/5b2f8f42-7b58-11e2-9946-bd34c8e40121.png)

**Comment by MartinRajniak** [comment]
You are the best
