### ISSUE TITLE
Feature Request: Borderless Buttons

### ISSUE THREAD

**Issue by navarr** [Prototik/HoloEverywhere#31]
Re: 
- http://stackoverflow.com/questions/8855791/how-to-create-standard-borderless-buttons-like-in-the-design-guidline-mentioned
- http://stackoverflow.com/a/9022642/43790

**Comment by ChristopheVersieux** [comment]
Thank a lot for this link.

I discovered it a few weeks ago.

I just need time to work on the project this weekend
On Jun 21, 2012 11:31 PM, "Navarr Barnier" <
reply@reply.github.com>
wrote:

**Comment by Prototik** [comment]
f77568910d379545b1d17cfebda6bff62145ef31
