### ISSUE TITLE
resbuilder

### ISSUE THREAD

**Issue by andrasfindt** [Prototik/HoloEverywhere#311]
Hi there, 

We were trying to use this for a project recently and couldn't get it to rebuild. We were using IntelliJ and couldn't figure it out for a while. Turns out the resbuilder needs to be compiled against Java 1.6, while the rest of the project compiles against android sdk. I'm sure there is something about that written somewhere in the world, but in case anyone needs to know this, here is where you will find out.

**Comment by Prototik** [comment]
Resbuilder generate styles and translations for library and demo. Uses android sdk.

Officially supported IDE - Eclipse. I'm don't want to support other IDE, really. You can try StackOverflow or other QA resource, and if you want - can supplement pages in Wiki.
