### ISSUE TITLE
Error using addHeaderView on ListFragment

### ISSUE THREAD

**Issue by giwrgos88** [Prototik/HoloEverywhere#314]
Hello I'm trying to use addHeaderView to add a header on a list view but i'm getting erros. how i can solve it?

02-20 23:50:26.288: I/Waiter(10306): Home Page is called
02-20 23:50:26.319: I/Waiter_Home_Screen(10306): Waiter home screen called
02-20 23:50:26.374: D/dalvikvm(10306): GC_FOR_ALLOC freed 180K, 3% free 9208K/9428K, paused 21ms, total 23ms
02-20 23:50:26.374: D/AndroidRuntime(10306): Shutting down VM
02-20 23:50:26.374: W/dalvikvm(10306): threadid=1: thread exiting with uncaught exception (group=0x4153c930)
02-20 23:50:26.390: E/AndroidRuntime(10306): FATAL EXCEPTION: main
02-20 23:50:26.390: E/AndroidRuntime(10306): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dmu.waiter.home/com.dmu.waiter.home.Waiter}: java.lang.NullPointerException
02-20 23:50:26.390: E/AndroidRuntime(10306):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
02-20 23:50:26.390: E/AndroidRuntime(10306):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
02-20 23:50:26.390: E/AndroidRuntime(10306):    at android.app.ActivityThread.access$600(ActivityThread.java:141)
02-20 23:50:26.390: E/AndroidRuntime(10306):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
02-20 23:50:26.390: E/AndroidRuntime(10306):    at android.os.Handler.dispatchMessage(Handler.java:99)
02-20 23:50:26.390: E/AndroidRuntime(10306):    at android.os.Looper.loop(Looper.java:137)
02-20 23:50:26.390: E/AndroidRuntime(10306):    at android.app.ActivityThread.main(ActivityThread.java:5041)
02-20 23:50:26.390: E/AndroidRuntime(10306):    at java.lang.reflect.Method.invokeNative(Native Method)
02-20 23:50:26.390: E/AndroidRuntime(10306):    at java.lang.reflect.Method.invoke(Method.java:511)
02-20 23:50:26.390: E/AndroidRuntime(10306):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
02-20 23:50:26.390: E/AndroidRuntime(10306):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
02-20 23:50:26.390: E/AndroidRuntime(10306):    at dalvik.system.NativeStart.main(Native Method)
02-20 23:50:26.390: E/AndroidRuntime(10306): Caused by: java.lang.NullPointerException
02-20 23:50:26.390: E/AndroidRuntime(10306):    at com.dmu.waiter.home.Waiter_Home_Screen.onCreateView(Waiter_Home_Screen.java:73)
02-20 23:50:26.390: E/AndroidRuntime(10306):    at android.support.v4.app._HoloFragment.onCreateView(_HoloFragment.java:174)
02-20 23:50:26.390: E/AndroidRuntime(10306):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:870)
02-20 23:50:26.390: E/AndroidRuntime(10306):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1080)
02-20 23:50:26.390: E/AndroidRuntime(10306):    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:622)
02-20 23:50:26.390: E/AndroidRuntime(10306):    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1416)
02-20 23:50:26.390: E/AndroidRuntime(10306):    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:505)
02-20 23:50:26.390: E/AndroidRuntime(10306):    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1164)
02-20 23:50:26.390: E/AndroidRuntime(10306):    at android.app.Activity.performStart(Activity.java:5114)
02-20 23:50:26.390: E/AndroidRuntime(10306):    at android.app.A

**Comment by Prototik** [comment]
NPE on

> com.dmu.waiter.home.Waiter_Home_Screen.onCreateView(Waiter_Home_Screen.java:73)

Are you try retrive ListView in onCreateView? No, just call getListView().addHeaderView(*) before setListAdapter() or call getListView().setForceHeaderListAdapter(true) and you can add/delete any header/footer views in any time.
