### ISSUE TITLE
EditText in list header view looses focus after items are reloaded

### ISSUE THREAD

**Issue by MartinRajniak** [Prototik/HoloEverywhere#315]
Hi,
I have a filter like EditText in header of a list view. Items in the list view are reloaded when user writes into the EditText. 

The problem is that it was working before I implemented HoloEverywhere, but I am not sure if it is the cause. 

The current situation is that when user writes first letter edit text loses focus because items are reloaded. After that user can write, but no characters are written in edit text. When I try to reload the soft keyboard by hiding it and then clicking back on EditBox no keyboard shows up.

I was just wondering if you have any idea what it can be. Thx

**Comment by Prototik** [comment]
Create bug project in bugs branch.

**Comment by MartinRajniak** [comment]
Will do, but for now I did it in an alternative way, so it isn't a priority.

**Comment by croemmich** [comment]
Same issue. I got around it by using android.widget.ListView rather than the HE widget.

**Comment by Prototik** [comment]
It's not HoloEverywhere bug. See [1](http://stackoverflow.com/questions/10109072/android-listview-edittext-focus-issues) [2](http://stackoverflow.com/questions/11414170/edittext-focus-in-a-listview) [3](http://stackoverflow.com/questions/9527067/android-edittext-in-listview-loses-focus-on-calling-notifydatachanged) [4](http://stackoverflow.com/questions/2679948/focusable-edittext-inside-listview)

**Comment by MartinRajniak** [comment]
I wouldn't put it here, if I haven't tried it without HE before. But there may be some issues with the core list view also.
I am not using it anymore, so it is better as a closed issue. 

Thanks for you time.

**Comment by Prototik** [comment]
``` java
getListView().setDescendantFocusability(ListView.FOCUS_AFTER_DESCENDANTS);
```

This bug fixed by this line. But still it is not a HE bug.

**Comment by MartinRajniak** [comment]
Alright, I ll try that, next time I come around the bug.

Thanks again.

**Comment by velsans** [comment]
Same Issue, having answer?
