### ISSUE TITLE
NoSuchMethodError when calling RadioGroup#hasOnClickListeners

### ISSUE THREAD

**Issue by neoh-zz** [Prototik/HoloEverywhere#316]
on Android 2.2 device (API 8)

My simplified fragment code:

``` java
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
    Bundle savedInstanceState) {
        RadioGroup radioGroup = (RadioGroup) fragmentview.findViewById(R.id.radioGroup);
        if(radioGroup.hasOnClickListeners()) {
            // do stuff
        }
    }
```

StackTrace:

<pre><code>02-21 23:01:04.320: E/AndroidRuntime(3753): FATAL EXCEPTION: main
02-21 23:01:04.320: E/AndroidRuntime(3753): java.lang.NoSuchMethodError: android.widget.RadioGroup.hasOnClickListeners
02-21 23:01:04.320: E/AndroidRuntime(3753):     at android.support.v4.app.Fragment.performCreateView(Fragment.java:1460)
02-21 23:01:04.320: E/AndroidRuntime(3753):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:911)
02-21 23:01:04.320: E/AndroidRuntime(3753):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
02-21 23:01:04.320: E/AndroidRuntime(3753):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1070)
02-21 23:01:04.320: E/AndroidRuntime(3753):     at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1861)
02-21 23:01:04.320: E/AndroidRuntime(3753):     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
</code></pre>

**Comment by Prototik** [comment]
Like #317, we are cannot override any method for all View hierarchy, use api compatible code.
