### ISSUE TITLE
NoSuchMethodError when calling Button#setBackground

### ISSUE THREAD

**Issue by neoh-zz** [Prototik/HoloEverywhere#317]
on Android 2.2 device (API 8)

My simplified fragment code:

``` java
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
    Bundle savedInstanceState) {

        Button button = (Button) fragmentview.findViewById(R.id.button);

        ansBttn.setOnClickListener(new View.OnClickListener() {             
            @Override
            public void onClick(View v) {
                ansBttn.setBackground(null);
            }
        });
    }
```

StackTrace:

<pre><code>
02-21 23:21:03.165: E/AndroidRuntime(3952): FATAL EXCEPTION: main
02-21 23:21:03.165: E/AndroidRuntime(3952): java.lang.NoSuchMethodError: android.widget.Button.setBackground
02-21 23:21:03.165: E/AndroidRuntime(3952):     at android.view.View.performClick(View.java:2408)
02-21 23:21:03.165: E/AndroidRuntime(3952):     at android.view.View$PerformClick.run(View.java:8817)
02-21 23:21:03.165: E/AndroidRuntime(3952):     at android.os.Handler.handleCallback(Handler.java:587)
02-21 23:21:03.165: E/AndroidRuntime(3952):     at android.os.Handler.dispatchMessage(Handler.java:92)
02-21 23:21:03.165: E/AndroidRuntime(3952):     at android.os.Looper.loop(Looper.java:143)
02-21 23:21:03.165: E/AndroidRuntime(3952):     at android.app.ActivityThread.main(ActivityThread.java:4914)
</code></pre>

**Comment by Prototik** [comment]
View#setBackground was be created only in 16 api. Use setBackgroundDrawable instead.
