### ISSUE TITLE
Programatically adding CheckBoxPreferences has no check boxes

### ISSUE THREAD

**Issue by mattprecious** [Prototik/HoloEverywhere#319]
Here's another issue I noticed recently. I don't have time to look into it this week, but I can try to figure it out next week if you're too busy.

https://github.com/mattprecious/PreferenceBug

Creating a PreferenceScreen manually and adding in a bunch of CheckBoxPreferences via the Activity results in a bunch of Preferences with no check boxes. I tried to make the demo project as simple as possible.

**Comment by Prototik** [comment]
In the morning I said that you must use Preference.context(Context) to get the styled context.
I take it back ;)

I created a bug project that creates two nodes: from xml and in code. Both are displayed correctly.

As a bonus: change the checkbox button to orange, images grabbed from http://android-holo-colors.com.
![bug319-screenshot](https://f.cloud.github.com/assets/1416030/191108/dc5f5df4-7f27-11e2-9b1b-807990ccf233.png)
By the way, a rather interesting situation: more styles is not necessary for drawables from android-holo-colors.com. It's use standard names of files and if you place this images into your res folder - it's override default blue drawables from HoloEverywhere library.

**Comment by mattprecious** [comment]
Woo! Works great! #299 is working great as well through XML.

I couldn't figure out how to use the images without setting them in the styles, but that's alright, it's no big deal.
