### ISSUE TITLE
Progress bar not spinning on Android 2.3

### ISSUE THREAD

**Issue by jblernout** [Prototik/HoloEverywhere#32]
When using the light theme on the holo demo, the progress bars are not spinning but they do with the dark theme.

The horizontal indeterminate progress bar works with both themes.

**Comment by christophedupont** [comment]
Hello, I've take a look on this bug, but I don't found any solution.

Have you found something or a temporary workaround ?

Thanks.

**Comment by jblernout** [comment]
I use the ABS one : 

<ProgressBar
            android:id="@+id/progress"
            android:indeterminate="true"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginRight="16dip"
            android:indeterminateDrawable="@drawable/abs__progress_medium_holo"
            android:indeterminateOnly="true"
            android:layout_gravity="center_vertical"
            style="Widget.Sherlock.ProgressBar"
            />

**Comment by christophedupont** [comment]
Ho ! Fine! I haven't thought to solve it like that.

Thanks for this very responsive answer !

**Comment by jblernout** [comment]
You're welcome

**Comment by Prototik** [comment]
c3305f1d1da2e8ecffe60337e4495113566163f5
