### ISSUE TITLE
Cannot import HoloEverywhere to Eclipse

### ISSUE THREAD

**Issue by ghost** [Prototik/HoloEverywhere#320]
First of all, I apologize if this question has been asked before. I usually don't ask questions on GitHub or Stackoverflow unless I have absolutely no clue on how to solve an issue.

The issue is:
When I try to import the library folder from HoloEverywhere zip file, I get the following error:
Build path contains duplicate entry: 'src' in project 'library'

I have tried to modifying the .classpath file or deleting it, but when I do so, I get the following error when importing:
Project has no project.properties file! Edit the project properties to set one.
AndroidManifest.xml file missing!

How can this fixed?

Thanks in advance.

**Comment by Prototik** [comment]
![he-maven](https://f.cloud.github.com/assets/1416030/195700/35b62d18-7ffc-11e2-8d4f-25856dfba54e.png)
[Wiki](https://github.com/ChristopheVersieux/HoloEverywhere/wiki/Maven)

**Comment by ghost** [comment]
I don't understand why these instructions are radically different from the ones here: https://github.com/ChristopheVersieux/HoloEverywhere

Is there any easier way to import HoloEverywhere like you are able to import ActionBarSherlock?
