### ISSUE TITLE
Switch size calculate wrongly

### ISSUE THREAD

**Issue by billynyh** [Prototik/HoloEverywhere#322]
https://github.com/ChristopheVersieux/HoloEverywhere/blob/master/library/src/org/holoeverywhere/widget/Switch.java
in the onMeasure method (line 313 - 357), widthSize and heightSize are calculated but not used, always gives me a fix height no matter my text height

**Comment by Prototik** [comment]
Officially backport from 4.1 jellybean: [link](http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/4.1.1_r1/android/widget/Switch.java#Switch.onMeasure%28int%2Cint%29). You can fix it and send pull request.
