### ISSUE TITLE
DialogFragment.getDialog().setCanceledOnTouchOutside(false) doesn't prevent dialog from being canceled by clicking outside of the dialog

### ISSUE THREAD

**Issue by MartinRajniak** [Prototik/HoloEverywhere#323]
DialogFragment.getDialog().setCanceledOnTouchOutside(false) doesn't prevent dialog from being canceled by clicking outside of the dialog.

I have tested it on fresh projects, one with HoloEverywhere and one without it. It doesn't work just on HoloEverywhere project.

The behaviour is also tested when using AlertDialog.Builder.create().setCanceledOnTouchOutside(false) when building custom dialog.

I would be very grateful if you could look at it. Thanks

**Comment by Prototik** [comment]
Use [DialogFragment#setCancelable(boolean)](https://github.com/ChristopheVersieux/HoloEverywhere/blob/master/library/src/org/holoeverywhere/app/DialogFragment.java#L284)

**Comment by MartinRajniak** [comment]
Thanks, this works. Is there a reason setCanceledOnTouchOutside(false) doesn't work?

**Comment by Prototik** [comment]
setCanceledOnTouchOutside work, but you set it's value before DialogFragment, which call setCancelable(true) that call setCanceledOnTouchOutside(true) also.

**Comment by MartinRajniak** [comment]
I see now, thanks again
