### ISSUE TITLE
Roboguice addon?

### ISSUE THREAD

**Issue by croemmich** [Prototik/HoloEverywhere#324]
I see there is a RoboGuice addon. I've been trying to get it to work, but can't seem to figure out how. Does it work, or is it a WIP?

First I tried to set config.requireRoboguice=true in onCreateConfig, which resulted in the mEventManager in the RoboGuice addon to not be initiated.

Then I tried in onInit, with the same problem.

Finally I called requireAddon before the super.onCreate call in my activity, which did result in the mEventManager being initialized, but then I got the error: InitActivity does not appear to be a RoboGuice context (instanceof RoboContext)

Thanks!

**Comment by Prototik** [comment]
Support roboguice still not complete, although most things should be working already. Please test holoeverywhere + roboguice to anything more than a demo project higher.

Do not forget to add next line to your activity class, bug in roboguice.

```
@Inject ContentViewListener ignored;
```

**Comment by croemmich** [comment]
Thanks, I'll look in to it. I'm in a time crunch for the project, so I just pulled RoboGuice for now.. I'll probably throw it back in soonish.

**Comment by Prototik** [comment]
Now fragments extend activity config, like attaching roboguice. And if you attach fragment to activity which has roboguice addon - fragment also will be have roboguice addon. Just for reference :)

**Comment by croemmich** [comment]
Awesome!

**Comment by benoitdion** [comment]
Is roboguice support in a maven snapshot somewhere?

Also, I currently have roboguice working without 

```
@Inject ContentViewListener ignored
```

Is it required because of the way holoeverywhere uses roboguice?
