### ISSUE TITLE
How remove Action Bar from sliding menu.

### ISSUE THREAD

**Issue by TheLushpen** [Prototik/HoloEverywhere#328]
Hi. How i can remove Action Bar from sliding menu on Large devices, like on normal, in demo project?

**Comment by Prototik** [comment]
You want slide only content or make menu static on large screen?

If first:
Latest master version:

``` java
AddonSlidingMenuA addon = addon(AddonSlidingMenu.class);
addon.setSlidingActionBarEnabled(false);
```

Stable version (1.4.2):

``` java
AddonSlidingMenuA addon = requireAddon(AddonSlidingMenu.class).activity(this);
addon.setSlidingActionBarEnabled(false);
```

If second: you can see example of demo project and in [SlidingMenu](https://github.com/jfeinstein10/SlidingMenu) repo by @jfeinstein10.  
Two layouts: in layout/ and layout-w***dp/. First contains only frame for content, second splited by two frames: for menu and for content. Of course quite a bit of code in activity :)

**Comment by TheLushpen** [comment]
I want to create custom action bar in static slidding menu.

**Comment by Prototik** [comment]
Just apply .NoActionBar theme to activity. For example Holo.Theme.Light.NoActionBar. Or use thememanager.

**Comment by TheLushpen** [comment]
No, i want to put custom action bar in sliding menu (in left part) and yours action bar in content (in right part), with non-sliding menu.

Вобщем думаю так будет проще общатся. Я хочу в левой зоне над sliding menu сделать свой action bar, а над контентом ваш. Меню статическое. На телефонах я так реализовал. В меню мой action bar. Но на планшетах не могу найти возможности сделать статическое меню с мои action barом.

**Comment by Prototik** [comment]
Можете сделать эскиз, я примерно понял, чего вы хотите, но в детали не въехал.

**Comment by TheLushpen** [comment]
Сейчас на телефоне выглядит так:
![Normal](https://f.cloud.github.com/assets/1141085/247577/d3afa474-8ae5-11e2-80f0-26fc10e1b48c.png)
Меню выдвигается.

Я хочу сделать вот так на планшете:
![Large](https://f.cloud.github.com/assets/1141085/247578/ea6e3d92-8ae5-11e2-932b-8b0994ff600d.png)
Меню статическое.

Тоесть одновременно на экране 2 ActionBarа

**Comment by TheLushpen** [comment]
Можно как то это реализовать?

**Comment by Prototik** [comment]
Два варианта:
- Пихать два ActionBarView из ABS, а дефолтовый скрыть.
- Модифицировать DecorView окна, взяв всю ветку с ActionBarView и запихать в свой layout, туда еще одну панель с еще одним ActionBarView и засунуть обратно в DecorView. Так делает SlidingMenu, можно в исходниках посмотреть.
