### ISSUE TITLE
Problems with CHOICE_MODE_MULTIPLE_MODAL in ListView

### ISSUE THREAD

**Issue by bwilburn** [Prototik/HoloEverywhere#333]
Hello. I am trying to implement CHOICE_MODE_MULTIPLE_MODAL in ListView. I realize that this feature is only available on API>=11, so I put a check in my initialization code that checks the installed API and does not use this unless the device is API>=11. This works fine for API <11, but when I try to use mulitchoice modal for API>=11 I get NullPointerException errors in my array adapter. I found similar issues with ActionBarSherlock at http://stackoverflow.com/questions/11001539/multichoicemodelistener-causing-issues-with-sherlocklistfragment and http://stackoverflow.com/questions/12123247/native-actionbar-to-actionbarsherlock-migration. Are there any workarounds for this? Am I doing something wrong or is this an issue with HE? It should just revert to the stock widgets if the API is large enough, right?

Thanks!

**Comment by Prototik** [comment]
HoloEverywhere backport CHOICE_MODE_MODAL to 2.1+. See [demo](https://github.com/ChristopheVersieux/HoloEverywhere/blob/master/demo/src/org/holoeverywhere/demo/fragments/lists/ListsChoiceModeModalFragment.java).

If you got a crash - show stacktrace of exception.
