### ISSUE TITLE
Non-Overflow menu doesn't open for devices with hardware menu key

### ISSUE THREAD

**Issue by jonasbark** [Prototik/HoloEverywhere#334]
I recently updated my outdated HoloEverywhere to the newest commit ("Fix #331").
This code would usually open the bottom menu on devices with hardware menu key, such as Motorola Milestone:

``` java
public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {

        menu.addSubMenu(0, 0, 0, "Hello").getItem().setIcon(android.R.drawable.ic_menu_info_details);

        return super.onCreateOptionsMenu(menu);
    }
} 
```

This does no longer work. No menu popping up from the bottom, no overflow menu present. I just made a simple test project using that code. Overflow menu is working fine for any other device.

**Comment by MartinRajniak** [comment]
This doesn't work for me also. Tested on Samsung Galaxy Note and Samsung Galaxy S3.

Also long menu click initiates Search in app on Samsung, that does not happen either. As if menu button click is not  propagated at all.

**Comment by MartinRajniak** [comment]
BTW, definetely caused by HE. 

Tried to revert few commits and it is working again. Also it is easily reproductible on HE Demo project.

**Comment by Samutz** [comment]
Same problem here on Motorola Droid 4 after updating to get fixes for a few other problems I was having.

**Comment by Samutz** [comment]
As a temporary fix, I've done this in my activity:

``` java
    @Override
    public boolean onKeyUp(int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_MENU) {
            openOptionsMenu();
        }
        return super.onKeyUp(keyCode, event);
    }
```

**Comment by MartinRajniak** [comment]
This error still occurs to me.

Tested on Galaxy S3. After pressing hardware menu button, application menu doesn't appear.

**Comment by Prototik** [comment]
![bug334](https://f.cloud.github.com/assets/1416030/247849/e38fe8ce-8af2-11e2-82f3-77de20564218.png)

**Comment by MartinRajniak** [comment]
Tried out now on a fresh project, still no luck. 

But the temporary fix proposed by Samutz no longer works after the update. Can it be phone specifc? what are you testing on?

**Comment by Prototik** [comment]
@demartino88 Show code.

**Comment by MartinRajniak** [comment]
``` java
import org.holoeverywhere.app.Activity;

import android.os.Bundle;

import com.actionbarsherlock.view.Menu;
import com.actionbarsherlock.view.MenuItem;

public class MainActivity extends Activity{

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getSupportMenuInflater().inflate(R.menu.main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch(item.getItemId()){
        case R.id.action_settings:
            return true;
        default:
            return super.onOptionsItemSelected(item);
        }
    }
}
```

**Comment by MartinRajniak** [comment]
Do you need anything else to check it?

**Comment by matux** [comment]
Idem here, does not work after update from 1.4.2 to 1.5.0. Tested on Galaxy Ace (2.3.6).

**Comment by eavsievich** [comment]
Проблема все еще есть на Desire (2.3.7). Сергей, можно попросить уделить этому багу больше внимания? :)

**Comment by Prototik** [comment]
Abstract 2.1 with hardware menu key:
![338-2 1](https://f.cloud.github.com/assets/1416030/295096/528ba992-944f-11e2-9440-07ce8d593c94.png)
Real 4.1 device by Sony with hardware key:
![338-4 1-with](https://f.cloud.github.com/assets/1416030/295097/63eef964-944f-11e2-92f8-142a682cb445.png)
Real 4.1 device by Google without hardware key:
![338-4 1-without](https://f.cloud.github.com/assets/1416030/295100/92ab9f6e-944f-11e2-9dee-faac493e754b.png)
Real 2.3 device by fucked vendor with hardware key:
INSTALL_FAILED_ACWF_INCOMPATIBLE, i don't know why. But menu should work.

**Comment by matux** [comment]
I can confirm this is now working on the same device I was testing on (Galaxy Ace (2.3.6)), using the same code as before with HoloEverywhere's latest master commit.

I really appreciate you looking into this so quickly, Prototik. Thanks!
