### ISSUE TITLE
RoboAsyncTask

### ISSUE THREAD

**Issue by benoitdion** [Prototik/HoloEverywhere#337]
Hi,

It looks like commit 985ea0ef4eb936b16e4512ce36e5d191472875a2 partially fixed #335. Injection works properly now but RoboAsyncTask is still broken. I was able to get it working using something like

```
public class RoboContextWrapper extends ContextWrapper implements RoboContext {
        protected HashMap<Key<?>, Object> scopedObjects = new HashMap<Key<?>, Object>();

    public RoboContextWrapper(Context base) {
        super(base);
    }

    @Override
    public Map<Key<?>, Object> getScopedObjectMap() {
        return scopedObjects;
    }
}
```

but it's not a pretty workaround..

Thanks for the quick turnaround on #335!

**Comment by Prototik** [comment]
Use org.holoeverywhere.roboguice.RoboAsyncTask.
