### ISSUE TITLE
Null pointer exception: View cannot be null in ContextMenuDecorView.attachView

### ISSUE THREAD

**Issue by MartinRajniak** [Prototik/HoloEverywhere#340]
After latest updates I get this error.

![null pointer exception](https://f.cloud.github.com/assets/1181874/231300/f4b8bcbc-86ff-11e2-8f7b-37ee726adca4.png)

**Comment by Prototik** [comment]
Your onCreateView return null.

**Comment by MartinRajniak** [comment]
It may be true, but it didn't do it before update. I will try to investigate which onCreateView is being called, but my guess for now is DialogFragment.

**Comment by MartinRajniak** [comment]
Thanks, it seems to work now
