### ISSUE TITLE
LGPLv3

### ISSUE THREAD

**Issue by tmurakami** [Prototik/HoloEverywhere#341]
The license of the HoloEverywhere was recently changed from the MIT license to the LGPLv3.

The Android SDK generates an apk file with a single "classes.dex" file.
This dex file contains all my classes and 3rd party libs codes, so it seems like static linking.

According to 4d0 of the LGPLv3, do I have to convey source code of my app that uses the HoloEverywhere?

**Comment by Prototik** [comment]
No, you only should open code of library if you modify it.

**Comment by dschuler** [comment]
Hi,

Would you mind adding this point to the license file for future reference? I'm concerned that without that clarification, the new LGPL v3 would not allow linking like stated above.
