### ISSUE TITLE
SlidingMenu open and rotation

### ISSUE THREAD

**Issue by pawelantczak** [Prototik/HoloEverywhere#345]
Hello.
I'm using SM in portrait mode, but in landscape i have static view (as it is in demo app on tablet).
My problem is, that when I leave SM open in portrait mode and rotate, on landscape dummy view is shown. I have to press back to see default layout.
How can I prevent this? (showing dummy after rotation).

**Comment by Prototik** [comment]
It's problems in implementation of SlidingMenu. In demo using next code for disable saving of opened state after change of theme:

``` java
    @Override
    protected void onPostCreate(Bundle savedInstanceState) {
        savedInstanceState = instanceState(savedInstanceState);
        if (mCreatedByThemeManager && savedInstanceState != null) {
            savedInstanceState.putBoolean("SlidingActivityHelper.open", false);
            savedInstanceState.putBoolean("SlidingActivityHelper.secondary", false);
        }
        super.onPostCreate(savedInstanceState);
    }
```

You can put any custom condition instead `mCreatedByThemeManager && savedInstanceState != null`, for example, check on landscape orientation.

Also it's 'dirty hack', you can create issue in [slidingmenu tracker](https://github.com/jfeinstein10/SlidingMenu/issues) or fix it manually.
