### ISSUE TITLE
NoSuchMethodException when calling onSaveInstance() on HE ListView on 2.3.6

### ISSUE THREAD

**Issue by MartinRajniak** [Prototik/HoloEverywhere#347]
Galaxy Note 2.3.6

![NoSuchMethod](https://f.cloud.github.com/assets/1181874/253560/a5a754f8-8bd7-11e2-97ab-49d413469ba8.png)

**Comment by Prototik** [comment]
Update to the latest master.

**Comment by MartinRajniak** [comment]
thx
