### ISSUE TITLE
Extend Dialog

### ISSUE THREAD

**Issue by bwilburn** [Prototik/HoloEverywhere#351]
Hello. Not sure if this is an issue, or if I'm just trying to do something I shouldn't, but anyway.. In my application before I started porting for compatibility with HE, I was extending the native Dialog class to make a custom popup dialog (everything working fine). When I tried to convert for HE, I get "DialogFragment don't have any reference to Context or FragmentManager" errors on the show() method. Is there any way in HE to extend the dialog class? I ported my popup to a DialogFragment with the AlertDialog style, but I am trying to get a transparent background, no title, and a specified dimension and features of AlertDialog seem to be getting in the way (ie, I cannot get a transparent background, and I cant get my layouts to match_parent since I am setting the params in the onStart method). Bug or am I doing something wrong? Any advice?

**Comment by Prototik** [comment]
You are don't should use DialogFragment#show() without reference on fragmentactivity or fragmentmanager. Try to call DialogFragment#show(Activity) or DialogFragment#show(FragmentManager)
