### ISSUE TITLE
Inflate Exception when creating ABS SearchView

### ISSUE THREAD

**Issue by MartinRajniak** [Prototik/HoloEverywhere#352]
![InflateException](https://f.cloud.github.com/assets/1181874/263017/fce7546c-8d57-11e2-9dd6-d890a0f8984c.png)

**Comment by Prototik** [comment]
Full stacktrace and inflate code/xml

**Comment by MartinRajniak** [comment]
This is an action bar inflate code:
        LayoutInflater inflater = (LayoutInflater) context
                .getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        inflater.inflate(R.layout.abs__search_view, this, true);

Full stack trace:
03-15 11:24:56.744: E/AndroidRuntime(21263): FATAL EXCEPTION: main
03-15 11:24:56.744: E/AndroidRuntime(21263): java.lang.RuntimeException: Unable to resume activity {XXX}: android.view.InflateException: Binary XML file line #29: Error inflating class TextView
03-15 11:24:56.744: E/AndroidRuntime(21263):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2616)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2644)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2130)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at android.app.ActivityThread.access$600(ActivityThread.java:140)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1227)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at android.os.Handler.dispatchMessage(Handler.java:99)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at android.os.Looper.loop(Looper.java:137)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at android.app.ActivityThread.main(ActivityThread.java:4898)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at java.lang.reflect.Method.invokeNative(Native Method)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at java.lang.reflect.Method.invoke(Method.java:511)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at dalvik.system.NativeStart.main(Native Method)
03-15 11:24:56.744: E/AndroidRuntime(21263): Caused by: android.view.InflateException: Binary XML file line #29: Error inflating class TextView
03-15 11:24:56.744: E/AndroidRuntime(21263):    at org.holoeverywhere.LayoutInflater.createViewFromTag(LayoutInflater.java:454)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:737)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:542)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:492)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at com.actionbarsherlock.widget.SearchView.<init>(SearchView.java:264)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at com.actionbarsherlock.widget.SearchView.<init>(SearchView.java:252)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at XXXActivity$1.<init>(XXXActivity.java:27)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at XXXActivity.setupSearchMenuItem(XXXActivity.java:27)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at XXXActivity.onCreateOptionsMenu(XXXActivity.java:163)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at android.support.v4.app.Watson.onCreatePanelMenu(Watson.java:45)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at com.actionbarsherlock.ActionBarSherlock.callbackCreateOptionsMenu(ActionBarSherlock.java:559)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchCreateOptionsMenu(ActionBarSherlockNative.java:60)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at org.holoeverywhere.addon.AddonSherlock$AddonSherlockA.onCreatePanelMenu(AddonSherlock.java:78)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at org.holoeverywhere.app.Activity$10.action(Activity.java:258)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at org.holoeverywhere.app.Activity$10.action(Activity.java:1)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at org.holoeverywhere.addon.IAddonAttacher$AddonCallback.performAction(IAddonAttacher.java:24)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at org.holoeverywhere.addon.IAddonBasicAttacher.performAddonAction(IAddonBasicAttacher.java:76)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at org.holoeverywhere.app.Activity.performAddonAction(Activity.java:523)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at org.holoeverywhere.app.Activity.onCreatePanelMenu(Activity.java:255)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:445)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at com.android.internal.policy.impl.PhoneWindow.invalidatePanelMenu(PhoneWindow.java:819)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchInvalidateOptionsMenu(ActionBarSherlockNative.java:49)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at org.holoeverywhere.addon.AddonSherlock$AddonSherlockA.invalidateOptionsMenu(AddonSherlock.java:64)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at org.holoeverywhere.app.Activity$30.action(Activity.java:635)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at org.holoeverywhere.app.Activity$30.action(Activity.java:1)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at org.holoeverywhere.addon.IAddonAttacher$AddonCallback.performAction(IAddonAttacher.java:24)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at org.holoeverywhere.addon.IAddonBasicAttacher.performAddonAction(IAddonBasicAttacher.java:76)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at org.holoeverywhere.app.Activity.performAddonAction(Activity.java:523)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at org.holoeverywhere.app.Activity.supportInvalidateOptionsMenu(Activity.java:632)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at android.support.v4.app.Fragment.setHasOptionsMenu(Fragment.java:763)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at XXXFragment.onCreate(ProjectsFragment.java:153)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at android.support.v4.app.Fragment.performCreate(Fragment.java:1437)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:877)
03-15 11:24:56.744: E/AndroidRuntime(21263):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.jav

**Comment by Prototik** [comment]
Are you use Holo.Theme.Light.DarkActionBar?

Try to use themed context from HoloEverywhere:

``` java
import org.holoeverywhere.LayoutInflater;

LayoutInflater inflater = LayoutInflater.from(getSupportActionBarContext());
inflater.inflate(R.layout.abs__search_view, this, true);
```

Also getSupportMenuInflater() overrided by HoloEverywhere and should normally inflate search view via xml. But i'm not test it.

**Comment by MartinRajniak** [comment]
1. Yes I use Holo.Theme.Light.DarkActionBar
2. The SearchView is ActionBarSherlock library class, I cannot change it to include HoloEverywhere inflater.
3. It was working, just recent changes caused it to stop working (maybe that can help you :))

**Comment by MartinRajniak** [comment]
Sorry, but this hasn't changed anything. 

Even when using getSupportActionBarContext, I get the same error (cannot inflate TextView).

It seems when I debug, that the method doesn't get even after the first null condition, so it doesn't return ContextThemeWrapperPlus

**Comment by MartinRajniak** [comment]
Alright, so the condition on which you decide whether to return ContextThemeWrapperPlus seems to be wrong, because if I run it with Holo.Theme.Light.DarkActionBar theme, it picks the first option, not the ContextThemeWrapperPlus option.

That is why it is still failing, please fix for future references.

**Comment by Prototik** [comment]
![device-2013-03-16-172408](https://f.cloud.github.com/assets/1416030/266673/7b90c4ee-8e23-11e2-9ede-45ea77ea24ec.png)

**Comment by MartinRajniak** [comment]
I will try to implement it your way, like in the bug project. Sorry for constantly bugging you.
Thank you very much.
