### ISSUE TITLE
In Holo.Theme.Light.DarkActionBar in contextual action mode the popup background is black

### ISSUE THREAD

**Issue by MartinRajniak** [Prototik/HoloEverywhere#354]
When displaying additional items in action bar, the popover window with the items used to be white for this theme style. Now it is black. I wouldn't mind but the text is also black, so I cannot see anything.

I have tried using "android:popupBackground" attribute on both the application style and on actionbar style with no success.

I would be grateful if you could help me out with this one.

**Comment by Prototik** [comment]
I'm sorry, commit above about #352, not 354.

**Comment by Prototik** [comment]
Create bug project in `bugs` branch.

**Comment by Prototik** [comment]
Damn, github simply mocking of me.

**Comment by Prototik** [comment]
See JakeWharton/ActionBarSherlock#268, it's not HoloEverywhere bug, i cannot fix it.

**Comment by MartinRajniak** [comment]
The thing is that it was working somewhere back, before too many commits :) 

Another thing is that I get an impression that bug in ABS is more related to spinners and custom dropdown items.
That is working perfectly for me. I got problem only with "Action overflow" button.
