### ISSUE TITLE
NPE at onCreateOptionsMenu() with overflow

### ISSUE THREAD

**Issue by AlexBonel** [Prototik/HoloEverywhere#358]
Updated the library to the 19th march commit "Release:prepare release holoeverywhere-1.5.0" and when press a menu hardware button got NullPointerException:

03-21 17:27:41.018: E/AndroidRuntime(7491): java.lang.NullPointerException
03-21 17:27:41.018: E/AndroidRuntime(7491):     at com.android.internal.view.menu.IconMenuView.addItemView(IconMenuView.java:292)
03-21 17:27:41.018: E/AndroidRuntime(7491):     at com.android.internal.view.menu.IconMenuView.updateChildren(IconMenuView.java:364)
03-21 17:27:41.018: E/AndroidRuntime(7491):     at com.android.internal.view.menu.IconMenuView.initialize(IconMenuView.java:346)
03-21 17:27:41.018: E/AndroidRuntime(7491):     at com.android.internal.view.menu.MenuBuilder$MenuType.getMenuView(MenuBuilder.java:208)
03-21 17:27:41.018: E/AndroidRuntime(7491):     at com.android.internal.view.menu.MenuBuilder.getMenuView(MenuBuilder.java:353)
03-21 17:27:41.018: E/AndroidRuntime(7491):     at com.android.internal.policy.impl.PhoneWindow.initializePanelContent(PhoneWindow.java:944)
03-21 17:27:41.018: E/AndroidRuntime(7491):     at com.android.internal.policy.impl.PhoneWindow.openPanel(PhoneWindow.java:482)
03-21 17:27:41.018: E/AndroidRuntime(7491):     at com.android.internal.policy.impl.PhoneWindow.onKeyUpPanel(PhoneWindow.java:703)
03-21 17:27:41.018: E/AndroidRuntime(7491):     at com.android.internal.policy.impl.PhoneWindow.onKeyUp(PhoneWindow.java:1475)
03-21 17:27:41.018: E/AndroidRuntime(7491):     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1845)
03-21 17:27:41.018: E/AndroidRuntime(7491):     at android.view.ViewRoot.deliverKeyEventToViewHierarchy(ViewRoot.java:2758)
03-21 17:27:41.018: E/AndroidRuntime(7491):     at android.view.ViewRoot.handleFinishedEvent(ViewRoot.java:2730)
03-21 17:27:41.018: E/AndroidRuntime(7491):     at android.view.ViewRoot.handleMessage(ViewRoot.java:1999)
03-21 17:27:41.018: E/AndroidRuntime(7491):     at android.os.Handler.dispatchMessage(Handler.java:99)
03-21 17:27:41.018: E/AndroidRuntime(7491):     at android.os.Looper.loop(Looper.java:150)
03-21 17:27:41.018: E/AndroidRuntime(7491):     at android.app.ActivityThread.main(ActivityThread.java:4385)
03-21 17:27:41.018: E/AndroidRuntime(7491):     at java.lang.reflect.Method.invokeNative(Native Method)
03-21 17:27:41.018: E/AndroidRuntime(7491):     at java.lang.reflect.Method.invoke(Method.java:507)
03-21 17:27:41.018: E/AndroidRuntime(7491):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
03-21 17:27:41.018: E/AndroidRuntime(7491):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
03-21 17:27:41.018: E/AndroidRuntime(7491):     at dalvik.system.NativeStart.main(Native Method)

Tried your demo and making disableMusic item showAsAction="never" - the same effect.

Model: HTC Desire S (Android 2.3.5)

**Comment by ccoffey** [comment]
This issue is also effect me.

**Comment by Prototik** [comment]
Hi. I fix it and make small improve: panel of menu in holo style:
![device-2013-03-24-130653](https://f.cloud.github.com/assets/1416030/295022/b4993d38-9441-11e2-8163-15a2c31fea47.png)

**Comment by AlexBonel** [comment]
Oh, great!!! Now I can't get split actionbar with this kind of menu on 2.3 and also it has another text color which is close to menu's background but not light grey as on your screenshot.

**Comment by iglaweb** [comment]
Is it a normal view of Options Menu?
![device-2013-03-28-201814](https://f.cloud.github.com/assets/3032604/314167/a7410028-97c3-11e2-9120-da5da90d90d4.png)
 Why not so? 
http://developer.android.com/guide/topics/ui/menus.html#options-menu
![options_menu](https://f.cloud.github.com/assets/3032604/314163/9e49bd52-97c3-11e2-8262-c2b0aafe170f.png)
