### ISSUE TITLE
HoloEverywhereLight theme with ActionBar Sherlock crashing on Gingerbread

### ISSUE THREAD

**Issue by julianonunes** [Prototik/HoloEverywhere#36]
I've created a SherlockActivity that uses HoloEverywhereLight theme and it is working only on ICS devices.

I'm getting these error messages on Gingerbread:

07-05 10:03:03.375: D/AndroidRuntime(410): Shutting down VM
07-05 10:03:03.375: W/dalvikvm(410): threadid=1: thread exiting with uncaught exception (group=0x40015560)
07-05 10:03:03.385: E/AndroidRuntime(410): FATAL EXCEPTION: main
07-05 10:03:03.385: E/AndroidRuntime(410): java.lang.RuntimeException: Unable to start activity ComponentInfo{br.com.remote/br.com.remote.MainActivity}: java.lang.IllegalStateException: You must use Theme.Sherlock, Theme.Sherlock.Light, Theme.Sherlock.Light.DarkActionBar, or a derivative.
07-05 10:03:03.385: E/AndroidRuntime(410):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1647)
07-05 10:03:03.385: E/AndroidRuntime(410):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
07-05 10:03:03.385: E/AndroidRuntime(410):  at android.app.ActivityThread.access$1500(ActivityThread.java:117)
07-05 10:03:03.385: E/AndroidRuntime(410):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
07-05 10:03:03.385: E/AndroidRuntime(410):  at android.os.Handler.dispatchMessage(Handler.java:99)
07-05 10:03:03.385: E/AndroidRuntime(410):  at android.os.Looper.loop(Looper.java:130)
07-05 10:03:03.385: E/AndroidRuntime(410):  at android.app.ActivityThread.main(ActivityThread.java:3683)
07-05 10:03:03.385: E/AndroidRuntime(410):  at java.lang.reflect.Method.invokeNative(Native Method)
07-05 10:03:03.385: E/AndroidRuntime(410):  at java.lang.reflect.Method.invoke(Method.java:507)
07-05 10:03:03.385: E/AndroidRuntime(410):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
07-05 10:03:03.385: E/AndroidRuntime(410):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
07-05 10:03:03.385: E/AndroidRuntime(410):  at dalvik.system.NativeStart.main(Native Method)
07-05 10:03:03.385: E/AndroidRuntime(410): Caused by: java.lang.IllegalStateException: You must use Theme.Sherlock, Theme.Sherlock.Light, Theme.Sherlock.Light.DarkActionBar, or a derivative.
07-05 10:03:03.385: E/AndroidRuntime(410):  at com.actionbarsherlock.internal.ActionBarSherlockCompat.generateLayout(ActionBarSherlockCompat.java:1007)
07-05 10:03:03.385: E/AndroidRuntime(410):  at com.actionbarsherlock.internal.ActionBarSherlockCompat.installDecor(ActionBarSherlockCompat.java:919)
07-05 10:03:03.385: E/AndroidRuntime(410):  at com.actionbarsherlock.internal.ActionBarSherlockCompat.setContentView(ActionBarSherlockCompat.java:853)
07-05 10:03:03.385: E/AndroidRuntime(410):  at com.actionbarsherlock.app.SherlockActivity.setContentView(SherlockActivity.java:218)
07-05 10:03:03.385: E/AndroidRuntime(410):  at br.com.remote.MainActivity.onCreate(MainActivity.java:12)
07-05 10:03:03.385: E/AndroidRuntime(410):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
07-05 10:03:03.385: E/AndroidRuntime(410):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1611)
07-05 10:03:03.385: E/AndroidRuntime(410):  ... 11 more

**Comment by nonproto** [comment]
I believe you need to use  android:theme="@style/Theme.HoloEverywhereLight.Sherlock
since you are using ABS
