### ISSUE TITLE
_HoloFragment won't compile due to missing mChildFragmentManager instance

### ISSUE THREAD

**Issue by OS-Chris** [Prototik/HoloEverywhere#360]
See subject. Also compile errors with _HoloFragmentInflater.java

**Comment by OS-Chris** [comment]
It is due to the support library in ActionBarSherlock (which all the other projects link to) which is missing some things from support-library/android-support-v4-r12.jar.

Maybe have a mention in the "How to use" section to swap the ActionBarSherlock lib to the r12 version.
Also maybe a quick mention on how to use the addons (i.e. SlidingMenu & Preferences).

Anyway, thanks for sharing your work. Awesome library !!

**Comment by Prototik** [comment]
Yeah, i add this info.
(although you could do it yourself)
