### ISSUE TITLE
Custom checkable items in ListView

### ISSUE THREAD

**Issue by mvsmal** [Prototik/HoloEverywhere#361]
After upgrading to 1.5.0 custom Checkable items became not working. 
I have my custom RelativeLayout which extends from RelativeLayout and implements Checkable interface. On version 1.4.2 everything worked OK, but after upgrading not.
While in debug mode any breakpoints in methods setChecked() or toggle() from Checkable interface in my class don't fire. Seems like they don't receive checking event.
Please help.

**Comment by Prototik** [comment]
![device-2013-03-24-152608](https://f.cloud.github.com/assets/1416030/295122/a551a6ae-9454-11e2-9039-58de9e13a9e1.png)
