### ISSUE TITLE
License (LGPLv3)

### ISSUE THREAD

**Issue by gosr** [Prototik/HoloEverywhere#362]
1) I am using the HE library in my Android app. Can I distribute my app (closed apk form, not source code) if I include the LGPLv3 license text in a "license part" of the app? I have not modified anything in the library.

2) For HE v1.4.1, the license is not LGPLv3 but MIT. If I use v1.4.1, I should include the MIT license instead, correct?

**Comment by HenriqueRocha** [comment]
For both licenses, you only need to say that you're using them and include the license.
For LGPL you need to give your changes back in case you change the library.

**Comment by gosr** [comment]
Great. Was my question 2 correct?

**Comment by Prototik** [comment]
@eightx2 Yea, correct.
