### ISSUE TITLE
android support/ABS version

### ISSUE THREAD

**Issue by benoitdion** [Prototik/HoloEverywhere#363]
commit 4b2f98d61ffa4f855598ad6c00fec5544c54519a message mentions that HoloEverywhere is in an inconsistent state. 

Opening this issue to keep track of this.

How does it affect maven users?

**Comment by Prototik** [comment]
Created _dummy_ artifact org.holoeverywhere:support-library which install com.google.android:support-v4:r12 into local repository into `install` phase. Just try to rebuild library.
