### ISSUE TITLE
windowMinWidthMajor/windowMinWidthMinor issues

### ISSUE THREAD

**Issue by JstnPwll** [Prototik/HoloEverywhere#364]
On my Android 4+ device, activities themed as dialogs do not display properly. The window width is narrower than the content, and it causes the right edge of the content to be cut off. I found that if I comment out android:windowMinWidthMajor and android:windowMinWidthMinor from styles.xml, the content is not cut off (because the dialog stretches to fill the screen).

Changing the window width should recalculate the width of the window's contents.

Wrong:
![device-2013-03-25-155616](https://f.cloud.github.com/assets/3968718/300291/6d255682-9593-11e2-92ff-793a67dd743e.png)

Right:
![device-2013-03-25-155751](https://f.cloud.github.com/assets/3968718/300293/6d312bba-9593-11e2-83d6-afc38cb14c5c.png)

Wrong:
![device-2013-03-25-155531](https://f.cloud.github.com/assets/3968718/300294/6d5fc95c-9593-11e2-984c-ace41d79a38e.png)

Right:
![device-2013-03-25-155726](https://f.cloud.github.com/assets/3968718/300292/6d28b28c-9593-11e2-8d0c-17f4e803a796.png)

**Comment by Prototik** [comment]
![device-2013-03-30-155358](https://f.cloud.github.com/assets/1416030/320045/d5ed0536-9910-11e2-929e-939e67c8f753.png)
![device-2013-03-30-160117](https://f.cloud.github.com/assets/1416030/320046/d6044584-9910-11e2-97d8-f2114076c89e.png)
![device-2013-03-30-160156](https://f.cloud.github.com/assets/1416030/320047/d61b64b2-9910-11e2-8917-bfce9ab525c6.png)
![device-2013-03-30-160323](https://f.cloud.github.com/assets/1416030/320048/d6314e4e-9910-11e2-9b17-ec491c924151.png)

Works perfectly with the latest master.
