### ISSUE TITLE
Custom Theme

### ISSUE THREAD

**Issue by rfmussa** [Prototik/HoloEverywhere#365]
Hello how can I use this library with a custom theme(extending Holo.Theme.Light)?
Thank you

**Comment by HenriqueRocha** [comment]
You should extend Holo.Theme (dark), Holo.Theme.Light or Holo.Theme.Light.DarkActionBar.

**Comment by rfmussa** [comment]
yes,  i am extending Holo.Theme.Light and setting the theme betfore setContentView of the Activity iscalled. i get an error when showing the customized actionbar for that theme ( getSupportActionBar.show() )

**Comment by HenriqueRocha** [comment]
It would help to know which error. Do you have the ActionBarSherlock dependency added to your project?

**Comment by rfmussa** [comment]
yes, I call getSupportActionBar on ics and all works fine. on 2.3 i get this error

```
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
    at dalvik.system.NativeStart.main(Native Method)
    Caused by: java.lang.NullPointerException
    at com.mezzo..MyActivity.onCreate(MyActivity.java:41)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1615)
    ... 11 more
```

when i cal getSupportActionBar.show();

**Comment by HenriqueRocha** [comment]
You should check with the sample project what you have wrong in your code.
In ICS it works fine because ABS bypasses the calls since ICS already has the ActionBar.

**Comment by rfmussa** [comment]
The only thing I did different was create an ActionBar style using the android UI assets site and then set it to extend Holo.Theme.Light. is this the correct approach?

**Comment by HenriqueRocha** [comment]
I think it should work. Add android:theme="@style/YourTheme" to your activity in the Manifest.

**Comment by Prototik** [comment]
Setting theme after super.onCreate _definitely_ bad idea. ThemeManager cannot check it, Or rather, it _can_, but not do it now.

You are try to get action bar before setting content - try to call getSupportActionBar() only after setting content.

**Comment by rfmussa** [comment]
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
       setTheme(R.style.Theme_Pocket);
      /getWindow().requestFeature(Window.FEATURE_ACTION_BAR_OVERLAY);
        setContentView(R.layout.mainanim);
        getSupportActionBar().hide();
}

here is the oncreate and the "main" declarationof the style

```
<style name="Theme.Pocket_ariely_light" parent="@style/Holo.Theme.Light">
    <item name="actionBarItemBackground">@drawable/selectable_background_pocket_ariely_light</item>
    <item name="popupMenuStyle">@style/PopupMenu.Pocket_ariely_light</item>
    <item name="dropDownListViewStyle">@style/DropDownListView.Pocket_ariely_light</item>
    <item name="actionBarTabStyle">@style/ActionBarTabStyle.Pocket_ariely_light</item>
    <item name="actionDropDownStyle">@style/DropDownNav.Pocket_ariely_light</item>
    <item name="actionBarStyle">@style/ActionBar.Solid.Pocket_ariely_light</item>
    <item name="actionModeBackground">@drawable/cab_background_top_pocket_ariely_light</item>
    <item name="actionModeSplitBackground">@drawable/cab_background_bottom_pocket_ariely_light</item>
    <item name="actionModeCloseButtonStyle">@style/ActionButton.CloseMode.Pocket_ariely_light</item>

    i still get a nullpointer exception when I call getSupportActivity (be it in a fragment or in an activity)
```

**Comment by Prototik** [comment]
Without custom theme get support action bar works normally?
