### ISSUE TITLE
Custom font when extending from Activity

### ISSUE THREAD

**Issue by PShchahelski** [Prototik/HoloEverywhere#366]
Hello.

First of all thank you very much for such a great work. It saves me a lot of time to port different ui widgets to old android versions.

But while implementing logic I faced a problem. I have a custom TextView that does only one thing - gets from attributes the value which represents the name of the custom font and set it to the TextView. Unfortunately when my Activity class extends from Activity in holo package nothing works. I found out that in holo LayoutInflater you do "FontLoader.applyDefaultStyles(result);" that replaces everything I set to the TextView. I experienced that problem on old versions. Maybe you can give me a piece of advice how to avoid it and at the same time extends from holo Activity?

Thanks a lot in advance.

**Comment by Prototik** [comment]
In custom TextView you can override setTypeface:

```
public class MyTextView extends TextView {
 / Constructors /
  @Override
  public void setTypeface(Typeface typeface) {

  }
}
```

In constructor obtain your Typeface instance and set it with super.setTypeface(typeface).

But i'm recommend just create custom HoloFont object and apply it on view with built-in tools, like FontLoader and LayoutInflater.
