### ISSUE TITLE
Allow use of fragments in the slider

### ISSUE THREAD

**Issue by croemmich** [Prototik/HoloEverywhere#367]
With SlidingMenu, it was possible to set the behind view to a placeholder and then attach a fragment to it. However, with the new slider, it is not possible because the view is never actually added to the content view, thus it is not found by the fragment manager. Any ideas/workarounds?

**Comment by Prototik** [comment]
AddonSlider override findViewById and pass it to content view. Compatibility with old code is saved. It's all just working in the demo. Also after onPostCreate _any_ attached view to left/right/content to sliding menu will be into decorview of window.

**Comment by Prototik** [comment]
Oops, yea, left/right view doesn't pass, sorry. One minute...

**Comment by croemmich** [comment]
Haha.. your awesome! Thanks for the quick reply and the other fixes you have done for me.

**Comment by croemmich** [comment]
It's not quite working. Your changes work, but it's impossible to get to them. See my comment on findViewById in the commit da03848b29dcc2b9ec2e40a01ee17a0296662776.
