### ISSUE TITLE
Sliding menu not working after you select nested item

### ISSUE THREAD

**Issue by httpdispatch** [Prototik/HoloEverywhere#370]
Noticed this issue in the demo. 
System ICS 4.0.3
Open sliding menu in the demo
Choose others
Select something from the right screen, for example "Lists"
After that menu become not working

**Comment by Prototik** [comment]
SlidingMenu or Slider?
I cannot reproduce this bug. Try latest snapshot: [link](https://docs.google.com/file/d/0BxcxDFWRyauQakU3T3JHckhRQlk/edit?usp=sharing)

**Comment by httpdispatch** [comment]
I think it is slider. I've tried latest master commit. Is your snapshot more fresh?

**Comment by Prototik** [comment]
It's build of 39c539e540

**Comment by httpdispatch** [comment]
let me try it then

**Comment by httpdispatch** [comment]
your snapshot is working fine. I've used this one https://github.com/ChristopheVersieux/HoloEverywhere/commit/7cdd262e08bb6177014e779d7fbe65e3274cc27f and it had an issue

**Comment by httpdispatch** [comment]
thank you
