### ISSUE TITLE
Nested PreferenceScreen and Holo.Theme.Light.DarkActionBar

### ISSUE THREAD

**Issue by BraisGabin** [Prototik/HoloEverywhere#372]
In the example project if you choose the theme Holo.Theme.Light.DarkActionBar (Mixed) and you go to _Settings > Unsupported preferences_ the ActionBar color changes to gray. Is the nested PreferenceScreen unsupported too?

I'm using the last version of the library (1.5.0) and a Nexus 7 with Android v4.2.2

**Comment by Prototik** [comment]
Nested pref screen supported, of course. I'll fix it tomorrow.
