### ISSUE TITLE
Finishing an activity don't work

### ISSUE THREAD

**Issue by Leandros** [Prototik/HoloEverywhere#374]
If I try to finish an activity (by calling `finish()` or pressin the back button) the activity isn't finished but restarted. Trying to finish it works the second time like it should, it finish the activity.

Edit: Happens only on my Nexus 4 with Android 4.2.2, it works fine on Android 2.2.

**Comment by Prototik** [comment]
That you have two activities in back stack. Are you call ThemeManager.restart\* or any other method, which _can_ recreate activity?

**Comment by Leandros** [comment]
I just call finish on the activity

**Comment by Prototik** [comment]
Accepted.

**Comment by Prototik** [comment]
Fixed...

At least now i don't can reproduce this bug.

**Comment by Prototik** [comment]
Not HoloEverywhere bug.

**Comment by sohayb** [comment]
I'm having the same problem, when I start an activity from a fragment, when I press back (supposed to be calling the finish() statement) the activity restarts, then when I press back again, it goes back to the previous layout. when I start this same activity from an activity, everything works just fine. 
This problem also happens only on Android with API > 11, works perfectly on my Galaxy Gio with API 10

Edit: it was solved by using android:launchMode="singleTask"  in activity definition in the manifest file

**Comment by sohayb** [comment]
This is not working when the activity is called by startActivityForResult :( now i'm stuck with the activity restarting 
how can I fix that?
