### ISSUE TITLE
syntax error 

### ISSUE THREAD

**Issue by crossle** [Prototik/HoloEverywhere#376]
[/HoloEverywhere Addon Slider/src/org/holoeverywhere/slider/SliderView.java](https://github.com/Prototik/HoloEverywhere/blob/master/addons/slider/src/org/holoeverywhere/slider/SliderView.java#L193)

line 193, use , instead of ;

**Comment by Prototik** [comment]
Om, No. It's absolutely right java code.

**Comment by crossle** [comment]
OK
