### ISSUE TITLE
Dialogs in Preferences have a black line above

### ISSUE THREAD

**Issue by BraisGabin** [Prototik/HoloEverywhere#380]
With the Light or Mixed theme: Open a list preference (or some other dialog preference) in the demo app. You will can see a black line with gradient above the Dialog.

HoloEverywhere 1.5.0
Nexus 7
Android 4.2.2

**Comment by Prototik** [comment]
Screenshot?

**Comment by BraisGabin** [comment]
![device-2013-04-01-214751](https://f.cloud.github.com/assets/721244/325270/37412664-9b05-11e2-8c7e-a0384e08307c.png)

I can test it in more devices tomorrow (Nexus 4 & Galaxy Nexus) if it helps

**Comment by Prototik** [comment]
Yea, more screenshots with device/os description, please.

**Comment by BraisGabin** [comment]
I compile the library, addons and demo with de APK 17, but I think this isn't related. I don't have other APK installed.

**Nexus 4
Android 4.2.2**
![device-2013-04-02-175346](https://f.cloud.github.com/assets/721244/329185/f4266796-9bad-11e2-8f9e-677e74bb971c.png)

**Samsung Galaxy Tab 2 7.0' (GT-P3110)
Android 4.1.1**
![device-2013-04-02-175515](https://f.cloud.github.com/assets/721244/329204/352ec0a8-9bae-11e2-8f49-61a0511b62fc.png)

**Asus Transformer TF101
Android 4.0.3**
![device-2013-04-02-180515](https://f.cloud.github.com/assets/721244/329302/572e546a-9baf-11e2-8854-33b4119a0a22.png)

**Galaxy Nexus
Android 4.2.2**
![device-2013-04-02-181229](https://f.cloud.github.com/assets/721244/329333/2ef9c71c-9bb0-11e2-92bf-12360dfe7089.png)

**Samsung Galaxy Ace 2 (GT-I8160)
Android 2.3.6**
Works properly

**Comment by Prototik** [comment]
Thanks, bug accepted.

**Comment by ViliusKraujutis** [comment]
looks like problem with nine-patch.

## 

Vilius Kraujutishttp://dl.dropbox.com/u/3180822/public_static_final_File/Vilius_Kraujutis.vcf
 | Android Developerhttps://plus.google.com/u/0/102636224116943763820/posts
 | viliusk@gmail.com | +370 611 21436
