### ISSUE TITLE
ClassNotFound exception in Demo

### ISSUE THREAD

**Issue by Gordi90** [Prototik/HoloEverywhere#381]
I use the HEW library in a project, so it basically works. I needed example for PreferenceActivity, so I decided to download the Demo. I've set up the libs (HEW + ABS/up-to-date supportlib + Preference plugin + Slider plugin). 

Demo builds, and closes with FC: ClassNotFoundException: DemoApplicaton. If I comment the application part in manifest, I get the same exception for DemoActivity.

**Comment by Prototik** [comment]
You have a incorrect build. Decompile classes.dex with dex2jar tool and try to find class org.holoeverywhere.demo.DemoApplication

**Comment by Gordi90** [comment]
I'm on it, just a moment, but shouldn't that be fixed with project/clean?
Sorry if the issue #382 has the same problem.

**Comment by Gordi90** [comment]
You were right, thx for help and for your work.

**Comment by Prototik** [comment]
Not HE related, try stackoverflow or other qa resource.
