### ISSUE TITLE
Searchview white background and white text

### ISSUE THREAD

**Issue by bdovaz** [Prototik/HoloEverywhere#383]
I use ActionBarSherlock with HoloEverywhere and I set the theme to "@style/Holo.Theme.Light".

In 4.2.2 I have no problems but in 2.2 and 2.3.3 I see it like this:

It's a bug?
![Sin t tulo](https://f.cloud.github.com/assets/950602/329361/a8be56e4-9bb0-11e2-9eff-98a3427270fc.png)

**Comment by Prototik** [comment]
Would not be SearchView inside ActionBar and be Holo styled?
![Screenshot](https://f.cloud.github.com/assets/1416030/320062/a0499b68-9912-11e2-9ab5-9320a4c22d61.png)

**Comment by bdovaz** [comment]
How do you do that? I don't understand, this is my code.

In 2.2 and 2.3.3 I can't see it like you do in your screenshot.

![test](https://f.cloud.github.com/assets/950602/334535/9d9542b2-9c75-11e2-8cc2-f27f4ad5707b.png)

![4](https://f.cloud.github.com/assets/950602/334553/08152044-9c76-11e2-9a63-b2b8191d58bd.png)

**Comment by Prototik** [comment]
It is screenshot of bug application #359.

**Comment by bdovaz** [comment]
I see the problem.

Because I use "ActionbarSherlock" I'm forced to use it like this:

@Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
        case R.id.dictionary_menu_item00:
            onSearchRequested();
            return true;
        default:
            return super.onOptionsItemSelected(item);
        }
    }

I have to call "onSearchRequested()" so the suggestion system work. When I call that, it changes the Theme from  Holo to the native style.

It seems a bug.

EDIT: If it helps, tomorrow I can record a short video with that behaviour.

**Comment by bdovaz** [comment]
Here you have the video

http://vimeo.com/63337844

You can see the problem better.

**Comment by Prototik** [comment]
onSearchRequested(), startSearch(), triggerSearch() and other don't supported by HoloEverywhere or ActionBarSherlock. You should change a behavior for correct handling of search feature.

Remove _any_ handling of your search menu item on `onOptionsItemSelected`, override onKeyUp and make like this:

``` java
    private MenuItem mSearchMenuItem;

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getSupportMenuInflater().inflate(R.menu.myMenu, menu);
        mSearchMenuItem = menu.findItem(R.id.search);
        return true;
    }

    @Override
    public boolean onKeyUp(int keyCode, KeyEvent event) {
        switch (keyCode) {
            case KeyEvent.KEYCODE_SEARCH:
                return mSearchMenuItem != null ? mSearchMenuItem.expandActionView() : false;
            default:
                return super.onKeyUp(keyCode, event);
        }
    }
```

**Comment by bdovaz** [comment]
I have tried that but I have the same problem, it doesn't trigger the suggestions. If I don't call "onSearchRequested" I can't use suggestions.

Don't mark as closed because is not resolved, help please!!

**Comment by Prototik** [comment]
You should manually process suggestions with usage SearchView.setSuggestionsAdapter(CursorAdapter).
HoloEverywhere don't will be support standard search popup window.
