### ISSUE TITLE
ActivityInstrumentationTestCase2 for activity with slider addon hangs

### ISSUE THREAD

**Issue by httpdispatch** [Prototik/HoloEverywhere#384]
I'm trying to use ActivityInstrumentationTestCase2 with activity annotated with `@Addons(Activity.ADDON_SLIDER)`. But it hangs at startup (`getActivity()` method) just because of the annotation. Do you have any suggestions how to use ActivityInstrumentationTestCase2  with slider activity?

**Comment by httpdispatch** [comment]
Forgot to mention. Activity itself is running properly, but testing methods are not called until i finish activity manually by pressing back key

**Comment by Prototik** [comment]
Да хер его знает, если честно. Та же фигня была и со SlidingMenu, и вот мне так влом стало дебаггер включать на тестах...

**Comment by Prototik** [comment]
Слух, а эта хрень случайно не ждет установки content view? Что SlidingMenu, что Slider устанавливают контент в onPostCreate

**Comment by httpdispatch** [comment]
К сожалению не знаю, но думаю, что не ждет. Где-то на просторах интернета (http://stackoverflow.com/questions/7168527/activityinstrumentationtestcase2-issues-test-hangs-because-of-invalidate-cal) встречал, что если вызывается где-то invalidate при старте, то возможно зависание.

**Comment by httpdispatch** [comment]
Активити то запускается и работает. Но видно метод waitForIddleSync в ActivityInstrumentationTestCase2 ждет вечно, пока не закрыть приложение.

**Comment by Prototik** [comment]
Если это и связано с invalidate(), все равно с postInvalidate() работает все точно так-же.
Вызов postInvalidate() обязателен после первого вызова onLayout().
Я как-то не хочу уродовать код лишними проверками.

**Comment by httpdispatch** [comment]
Дело в том, что пока не известно, с чем это связано. Invalidate - это было только предположение
