### ISSUE TITLE
Applying own style based on HE @ PreferenceAddon

### ISSUE THREAD

**Issue by TheNephilim88** [Prototik/HoloEverywhere#388]
Hey,

I use HoloEverywhere as a base for my own style.
So I got everything styled as desired. My styles were even applied to PreferenceActivity when using an old version of HoloEverywhere (like https://github.com/Prototik/HoloEverywhere/tree/201530875f827e5dc1ffb48e76210877d1ed7270 where Preferences were not made as an addon yet).

Now, with Preferences as addon, the styles were not applied anymore - instead it is showing Checkboxes etc. from the base-theme of my own one.

Any suggestions to easily get Preferences styled again?

**Comment by BraisGabin** [comment]
Did you read [this wiki section](https://github.com/Prototik/HoloEverywhere/wiki/Addon:-Preference-Framework#im-put-custom-preference-styles-in-activity-theme-but-nothing-happened)?

**Comment by TheNephilim88** [comment]
Ooops, nope. Thanks a lot.
