### ISSUE TITLE
Activity with view pager causes NullPointerException

### ISSUE THREAD

**Issue by kkocel** [Prototik/HoloEverywhere#389]
I have an Activity with a Fragment that have a ViewPager. When I have some pages, swype them and go back from activity I get:

04-08 10:22:24.251: E/AndroidRuntime(4997): FATAL EXCEPTION: main
04-08 10:22:24.251: E/AndroidRuntime(4997): java.lang.RuntimeException: Unable to destroy activity {a.my.package/a.my.package.MyActivity}: java.lang.NullPointerException
04-08 10:22:24.251: E/AndroidRuntime(4997):     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3314)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3332)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at android.app.ActivityThread.access$1200(ActivityThread.java:140)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at android.os.Handler.dispatchMessage(Handler.java:99)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at android.os.Looper.loop(Looper.java:137)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at android.app.ActivityThread.main(ActivityThread.java:4898)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at java.lang.reflect.Method.invokeNative(Native Method)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at java.lang.reflect.Method.invoke(Method.java:511)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at dalvik.system.NativeStart.main(Native Method)
04-08 10:22:24.251: E/AndroidRuntime(4997): Caused by: java.lang.NullPointerException
04-08 10:22:24.251: E/AndroidRuntime(4997):     at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1175)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at android.support.v4.app._HoloFragment.onDestroyView(_HoloFragment.java:198)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at android.support.v4.app.Fragment.performDestroyView(Fragment.java:1665)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:980)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1070)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1898)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:324)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at android.support.v4.app._HoloActivity.onDestroy(_HoloActivity.java:395)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at org.holoeverywhere.app.Activity.onDestroy(Activity.java:275)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at android.app.Activity.performDestroy(Activity.java:5370)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1113)
04-08 10:22:24.251: E/AndroidRuntime(4997):     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3301)
04-08 10:22:24.251: E/AndroidRuntime(4997):     ... 11 more

**Comment by croemmich** [comment]
Try calling setDestoryChildFragments(false) in onCreate in all of the fragments in your ViewPager.

**Comment by Prototik** [comment]
Duplicate #357
