### ISSUE TITLE
notifyDataSetChanged causes java.lang.IllegalStateException: Fragment {} is not currently in the FragmentManager

### ISSUE THREAD

**Issue by kkocel** [Prototik/HoloEverywhere#390]
Calling notifyDataSetChanged causes IllegalStateException in PagerAdapter

04-08 11:13:28.057: E/AndroidRuntime(17953): java.lang.RuntimeException: Unable to destroy activity {a.my.package/a.my.package.detail.DetailActivity}: java.lang.IllegalStateException: Fragment DetailFragment{42cbaee0} is not currently in the FragmentManager
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3451)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3469)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.app.ActivityThread.access$1200(ActivityThread.java:141)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1287)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.os.Handler.dispatchMessage(Handler.java:99)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.os.Looper.loop(Looper.java:137)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.app.ActivityThread.main(ActivityThread.java:5041)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at java.lang.reflect.Method.invokeNative(Native Method)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at java.lang.reflect.Method.invoke(Method.java:511)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at dalvik.system.NativeStart.main(Native Method)
04-08 11:13:28.057: E/AndroidRuntime(17953): Caused by: java.lang.IllegalStateException: Fragment DetailFragment{42cbaee0} is not currently in the FragmentManager
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.support.v4.app.FragmentManagerImpl.saveFragmentInstanceState(FragmentManager.java:573)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.support.v4.app.FragmentStateMyPagerAdapter.destroyItem(FragmentStateMyPagerAdapter.java:136)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:835)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:2688)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.support.v4.view.MyPagerAdapter.notifyDataSetChanged(MyPagerAdapter.java:276)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at a.my.package.detail.gallery.MyPagerAdapter.clear(MyPagerAdapter.java:30)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at a.my.package.detail.DetailFragment.onDestroyView(DetailFragment.java:354)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.support.v4.app.Fragment.performDestroyView(Fragment.java:1665)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:980)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1070)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1898)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:324)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.support.v4.app._HoloActivity.onDestroy(_HoloActivity.java:395)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at org.holoeverywhere.app.Activity.onDestroy(Activity.java:275)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.app.Activity.performDestroy(Activity.java:5273)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1110)
04-08 11:13:28.057: E/AndroidRuntime(17953):    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3438)
04-08 11:13:28.057: E/AndroidRuntime(17953):    ... 11 more

**Comment by croemmich** [comment]
If you are using the child fragment manager, call setDestoryChildFragments(false) in onCreate on the parent fragment. This will avoid having the child fragments removed.

It's due to this: https://github.com/Prototik/HoloEverywhere/blob/master/library/src/android/support/v4/app/_HoloFragment.java#L185

I'm not actually sure why Sergey has it in there.

**Comment by croemmich** [comment]
Watch #391 for more info on the issue.
