### ISSUE TITLE
setDestoryChildFragments

### ISSUE THREAD

**Issue by croemmich** [Prototik/HoloEverywhere#391]
@Prototik What is the purpose of your onDestroyView method in HoloFragment?
https://github.com/Prototik/HoloEverywhere/blob/master/library/src/android/support/v4/app/_HoloFragment.java#L185

It seems to be causing a number of undesirable issues for people, as it breaks normal functionality of FragmentStatePagerAdapters.

**Comment by Prototik** [comment]
Yea, very funny situation: this code in onDestroyView should be provide compability with the Fragment(State)PagerAdater with the nested fragments. Rewrited for detaching (not removing) fragments from parent fragment only if child fragment was be inflated via xml.
