### ISSUE TITLE
windowContentOverlay visible on dialogs

### ISSUE THREAD

**Issue by r-gurzkowski** [Prototik/HoloEverywhere#393]
After 1.5.0 update all dialogs has a windowContentOverlay, from main application theme, on top of them. On previous version everything was ok. Probably it is a problem with dialog styles. Screen attached. 

![device-2013-04-08-131101](https://f.cloud.github.com/assets/3274891/351901/f2311d52-a056-11e2-979c-7a6d0b43cef5.png)

**Comment by BraisGabin** [comment]
Related with #380 but I don't sure if it's a duplicate.

**Comment by Prototik** [comment]
Yea, related with #380, but... Holo.Theme.Dialog have android:windowContentOverlay=@null...

**Comment by BraisGabin** [comment]
@Prototik, if it helps: I worked on my app yesterday and I still had the same black line in the preferences but I didn't have it in the demo app. I thought that it was a problem in my code but I don't investigate this issue yet. If I would have news I will comment again. I was using bd754f636b8fa9cedd65e104702c31713d4ffcba.

**Comment by Prototik** [comment]
Stop... I know cause. Fix will be tomorrow.
