### ISSUE TITLE
Build issues with support-v4 

### ISSUE THREAD

**Issue by sfkamath** [Prototik/HoloEverywhere#394]
I've tried a a few different ways to get the project to build. 

The first thing I had to do was to manually place the support-v4-r12 library in the local maven repository. Is this the recommended approach?

I also get the same issue as that outlined in issue #360. 

Also tried to add a scope of provided to the support-v4 dependency in the actionbarsherlock project. That seems to help
and I can get the project to build in eclipse with m2e (android). However this approach isn't documented anywhere and I ideally wouldn't want to have to modify a dependency.

Thanks in advance
Suneet

**Comment by Prototik** [comment]
Run `mvn clean` into support-library. This install artifact com.google.android:support-v4:r12 into local maven repository. By default this target runs when you are try to rebuild all repository.
m2e-android have a bug with overriding of dependencies, that you _should_ replace jar into abs/libs.

**Comment by sfkamath** [comment]
FYI, I had to update to android-support-v13 to get this to work correctly. It did work with v12 as well but had to update since I read somewhere that v13 includes v4 (which was referenced by another library). Not sure how that works !
