### ISSUE TITLE
Noob in License trouble.

### ISSUE THREAD

**Issue by bhaambhu** [Prototik/HoloEverywhere#399]
Sir/Bro, 
I am sort of totally confused bout the lgpl3 license and I read the license and it confused me even more. All I want to ask is-

1) If I use HoloEverywhere do I have to show my app's source code to the public.
2) Can I use HoloEverywhere in an app which is not free to download on the play store (That is in a paid app).
3) Or Should I simply mention "I used HoloEverywhere" in the about/info section and show This - "https://raw.github.com/Prototik/HoloEverywhere/master/LICENSE" with it.

Thank you. I hope this helps other noobs too  :smile_cat:

**Comment by Prototik** [comment]
1) No, only changes in library.
2) Any applications
3) You should provide full copy of license, not only link.

**Comment by bhaambhu** [comment]
Thanks for quick reply. Does line 3 mean all the text that shows up on opening 
"https://raw.github.com/Prototik/HoloEverywhere/master/LICENSE".
Along with "This app uses HoloEverywhere" :wink:

**Comment by Prototik** [comment]
Yea, also you can simply write "HoloEverywhere" and text of license below.

**Comment by bhaambhu** [comment]
Thanks Sir/Bro :smile_cat:
