### ISSUE TITLE
Is EditTextHolo deprecated?

### ISSUE THREAD

**Issue by bearburger** [Prototik/HoloEverywhere#40]
Hi Christophe

First of all I should thank you for your project. It's very helpful.

But now I have issue and not sure if I'm doing it right.

This is my layout code

``` xml
        <EditText
            android:inputType="text"
            android:layout_width="fill_parent" 
            android:layout_height="wrap_content"
            android:text="Booo"/>
        <com.WazaBe.HoloEverywhere.EditTextHolo
            android:inputType="text"
            android:layout_width="fill_parent" 
            android:layout_height="wrap_content"
            android:text="Booo Holo"/>
```

Result on my 2.3.4 looks like

![Holo](https://dl.dropbox.com/u/485932/holo.png)

So EditTextHolo doesn't work and native EditText stylized like it should.

Can you update example if it's right behaviour because I think it could confuse new users.

Best regards, Roman

**Comment by imminent** [comment]
I was just looking at this issue myself. Did you check the logs? I believe (at least in my case) that the `FontLoader` is throwing an error "Error: native typeface cannot be made" which I guess is quietly breaking the `EditText`. The styling of the `EditText` comes from the theme so, as long as your application/activity is from one of the HoloEverywhere themes the `EditText` will look right. The `EditTextHolo` and other "Holo" classes try to load the Roboto typeface in as the typeface.
