### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by whatis777** [Prototik/HoloEverywhere#400]
Please provide better (or any) documentation! Some use cases can only be realized by reverse-engeneering source code or demo source code. This costs a lot of time for a lot of people.

Also please provide documentation for your older released distributions, not only for the bleeding edge.

**Comment by tester5000** [comment]
+1 Please make normal documentation.

**Comment by MartinRajniak** [comment]
+1 would be very helpful

**Comment by stefan222** [comment]
+1 Please provide a useful documentation.

**Comment by MaxjTechno** [comment]
Yes, pls provide it. The library is wonderful, but with no docs it's very difficult to understand how you must do things right, when the bug is in the framework or is yours, what you can do and what you cannot do

**Comment by snorkel123** [comment]
+1 needed so much

**Comment by brmcmaho** [comment]
+1

**Comment by Prototik** [comment]
My fucked English is very bad, no?
Are you /really/ want to read my docs?

**Comment by soswow** [comment]
You can write it in Russian, and there will be for sure people who willing to translate it for u. 

I have no idea what should I do with this library. Should I build it with maven? How do I add it to my main project?
Building with maven gives "[ERROR] Failed to execute goal org.holoeverywhere:resbuilder:2.1.0:build (default) on project library: Error in FileProcesser: java.lang.NullPointerException -> [Help 1]
"
You made so good job making this library, do a bit more and describe how to use it. pls.

**Comment by Prototik** [comment]
HoloEverywhere use a maven, yea, but you can build your project with internal ide tools (adt, idea and other).
About error: re-run maven with -e key and show me full stacktrace.

**Comment by soswow** [comment]
For me - build is to get some kind of artifact. Like jar. With IDEA I can compile. 
I've made separate ticket for maven install issue.

**Comment by AceFrahm** [comment]
Please help,  I need a tutorial or documentation of SOME kind, any language will do.  I'm so close, I got the demo to run but I can't quite figure out how to make my own app use HoloEverywhere.  My app opens, but no widgets show up.  2013-08-26 current Andriod version is API 18, but I want to support Gingerbread API 10 at least.  Just getting the demo to work was a royal pain, I don't know how any dev newbies could get even that far.  The reason no one bought a Mac from 1980's to late 1990's is that Apple never helped anyone figure out how to write programs for it.  Windows PC's were cheaper, sure, but Microsoft deliberately showed programnerds how to code for it.   HoloEverywhere could die if we don't get any kind of knowledge at all.

**Comment by jstefanowski** [comment]
Hi,
Please add comments to methods and classes (at least for those which are not present in original Android API). There are a lot of places where I don't know how something works. For example: what does "addButtonBehaviour" in AlertDialog class, and what values can I add there? Or what does ChooserActivity?

**Comment by Prototik** [comment]
Basic JavaDoc placed [here](http://prototik.github.io/HoloEverywhere/docs/)
