### ISSUE TITLE
Use ndextending Fragment from HE

### ISSUE THREAD

**Issue by fredgrott** [Prototik/HoloEverywhere#404]
In certain ways we use Fragments Iat least have to extend the Fragment HE class

But in -HoloFragment(android.support.v4.app) onCreateView is marked with a final modifier preventing this..

My suggestion is if it does not harm anything to remove that modifier.

Testing it out on a demo app right now over the next few days, if it does not work will let you guys know but in theory it should work as if we do not extend the Fragment class from He we should get a runtime error in an app amyway

**Comment by Prototik** [comment]
No, this breaks view overriding and support of nested fragments. You can try - 99% of code in demo will be throw ClassCastException.
