### ISSUE TITLE
No PreferenceFragment in latest Stable

### ISSUE THREAD

**Issue by metinkale38** [Prototik/HoloEverywhere#405]
Hey,

in the latest stable (1.5.0) there is no PreferenceFragment, but in 1.4.2 there is. Could not find any alternative, the demo is also using PrefererenceFragment.

Hope it will fixed i go back to 1.4.2

**Comment by metinkale38** [comment]
ouh sorry, i looked into the commits for the preferences package and saw preferences are splitted into an addon (why?)

A documentation would be nice

**Comment by BraisGabin** [comment]
https://github.com/Prototik/HoloEverywhere/wiki/Addon:-Preference-Framework
