### ISSUE TITLE
OverFlow menu text color bug

### ISSUE THREAD

**Issue by crossle** [Prototik/HoloEverywhere#407]
used @style/Holo.Theme.Light.DarkActionBar, but overflow menu text color is black..not light

**Comment by MartinRajniak** [comment]
same is happening to me

**Comment by MartinRajniak** [comment]
I found a workaround on stackoverflow
http://stackoverflow.com/questions/3519277/how-to-change-the-text-color-of-menu-item-in-android 

look for the answer from Marcus Wolschon

I am still looking for unwanted consequences :)

**Comment by MartinRajniak** [comment]
Thank you it works perfect now

**Comment by crossle** [comment]
Thanks!
