### ISSUE TITLE
android:dropDownListViewStyle styling bug

### ISSUE THREAD

**Issue by TheNephilim88** [Prototik/HoloEverywhere#408]
Hi,

I am using HoloEverywhere as a base for my own theme.

To style the DropDown-Menu I use following code in my style-definitions:

<code>< item name="android:dropDownListViewStyle">@style/actionbar_own_DropDownListView</ item>
< item name="dropDownListViewStyle">@style/actionbar_own_DropDownListView</ item></code>

("@style/actionbar_own_DropDownListView" defines the listSelector)

This worked perfectly before I upgraded HoloEverywhere to current version (I do not exactly know from when my "old" HoloEverywhere checkout was, it had version 1.4.3-snapshot).

Now, on the current version, this is working perfectly on my Android 2.3.6-device. On my Nexus 4 with Android 4.2 the defined colors get mixed with the selection-color of the base theme.

I took a screenshot to show, what I mean:

![IMG_20130415_100633](https://f.cloud.github.com/assets/1174584/379574/c6d40fdc-a5a3-11e2-9b72-6cbf4968f6a0.JPG)

The selection of "Details anzeigen" is the mixed color of the intended color + holo-selection-color. It should have been the green, which I added to the bottom of the screenshot.

**Comment by Prototik** [comment]
Fixed via fa59aa35d0

**Comment by TheNephilim88** [comment]
This still seems not to be fixed with fa59aa3.

Same behaviour like before:
- Working an Galaxy S (Android 2.3.6).
- Not working on Nexus 4 (Android 4.2.2).

I pushed a little quick'n'dirty test-project to github:   https://github.com/reneph/heDropdownTest

**Comment by Prototik** [comment]
Now HoloEverywhere simply don't add any custom layout for selector. If you find different in native and backported behavior - tell me.

**Comment by TheNephilim88** [comment]
Found out, that this bug has been introduced with commit 2e17fae0d235c7811369b6c235f12f9d3e787f06 (Fix #358).

There you added
< item name="android:itemBackground">?selectableItemBackground< /item>
to styles-v14.

Overriding android:itemBackground in my theme with desired selector is working fine now...
