### ISSUE TITLE
DialogFragment show() deprecation

### ISSUE THREAD

**Issue by BraisGabin** [Prototik/HoloEverywhere#410]
Why is [`show(FragmentManager, String)`](https://github.com/Prototik/HoloEverywhere/blob/master/library/src/org/holoeverywhere/app/DialogFragment.java#L355) and [`show(FragmentTransaction, String)`](https://github.com/Prototik/HoloEverywhere/blob/master/library/src/org/holoeverywhere/app/DialogFragment.java#L364) are deprecated? In the [official API](http://developer.android.com/reference/android/app/DialogFragment.html#show%28android.app.FragmentTransaction,%20java.lang.String%29) they are not deprecated.

If it's an error it's easy to fix. If not I think is better add javadoc with an explanation or pointing another function to use instead.

**Comment by Prototik** [comment]
See #298
