### ISSUE TITLE
Can't style action dropdown menu selection background

### ISSUE THREAD

**Issue by httpdispatch** [Prototik/HoloEverywhere#412]
I am having troubles with styling dropdown menu selection background.
It works fine on android 2.3
![image](https://f.cloud.github.com/assets/2315223/395482/dd991b50-a7ff-11e2-9275-1792e15731f8.png)

But in android 4.0.3 the background is looking not properly because seems that some other background is drawing above it

The problem is in some Holo.Theme.Light parameter but i am not sure which one exactly. In Sherlock.Theme it works fine: i see only the selectable background specified in styles.xml. 
![image](https://f.cloud.github.com/assets/2315223/391214/f37f6048-a75d-11e2-9303-55f9436d45d0.png)

As you can see it is green, not yellow

**Comment by Prototik** [comment]
Какие атрибуты используются?

**Comment by httpdispatch** [comment]
Ну можно взять abs-styled демо и посмотреть, там их много. Если в демке поменять тему на Holo.Theme.Light и добавить меню с выпадающим списком то можно воспроизвести проблему

**Comment by httpdispatch** [comment]
я вот пытаюсь перебирать разные drawable параметры из Holo.Theme.Light, чтобы понять что же там рисуется поверх

**Comment by Prototik** [comment]
Там рисуется listSelector и listBackgroundChoiceIndicator.

**Comment by httpdispatch** [comment]
Holo.Theme.Light
![image](https://f.cloud.github.com/assets/2315223/395552/0bb8cf36-a804-11e2-8bbe-c46093f945e2.png)

Theme.Sherlock.Light
![image](https://f.cloud.github.com/assets/2315223/395559/451b57ee-a804-11e2-82a1-835298c5b7af.png)

**Comment by httpdispatch** [comment]
Спасибо, сейчас попробую

**Comment by httpdispatch** [comment]
Похоже что не они. После добавления в стиль

``` xml
<item name="android:listChoiceBackgroundIndicator">@android:color/transparent</item>
<item name="android:listSelector">@android:color/transparent</item>
```

ничего не меняется

**Comment by httpdispatch** [comment]
Похоже проблема вот в этом

``` xml
<item name="android:itemBackground">?selectableItemBackground</item>
```

**Comment by httpdispatch** [comment]
Фух, перепроверил на своем приложении. Таки да причиной оказалась эта строчка в стиле Holo.Theme.Light

**Comment by Prototik** [comment]
Это таки решение для обратной совместимости с 2.*.
Рекомендую просто переопределить selectableItemBackground, android:listSelector и android:listChoiceBackgroundIndicator на няшненький цвет.

**Comment by Prototik** [comment]
Кстати, я вообще /против/ создания кастомных стилей, когда это просто не нужно.
Просто добавляйте свои drawable с аналогичными именами в свой проект, они перезапишут стандартные из библиотеки. В итоге имеем минус в размере приложение и отсутсвие насилия над мозгом в результате вот такой бабуйни, которая описана в этом issue.

**Comment by httpdispatch** [comment]
Ну что ж, это мысль. Надо будет как-нибудь попробовать. Спасибо
