### ISSUE TITLE
DatePicker always uses month-day-year order

### ISSUE THREAD

**Issue by stefan222** [Prototik/HoloEverywhere#413]
The DatePicker always uses the month-day-year order to display a date. It should take care of the system preferences. E.g. for France and Germany the order is day-month-year. (Works fine with the original DatePicker from Android 4.x.)

**Comment by Prototik** [comment]
Library, OS version?
For Russia date sort order also dmy, this works:
![Screenshot from 2013-04-19 17:22:56](https://f.cloud.github.com/assets/1416030/401227/6ab40c2e-a8d3-11e2-9702-ed3423b1b218.png)

**Comment by stefan222** [comment]
Thank you for the quick reply!

I'm using a Galaxy Nexus, Android 4.2.2. The library is a snapshot from Jan. 14 2013. I tried the demo app from Google's Play Store too, see attached screenshot. The title of the dialog is correct, but inside the dialog the order is different.
![device-2013-04-19-121058](https://f.cloud.github.com/assets/2979398/401393/e3cab940-a8d9-11e2-87c5-247c328c1736.png)

**Comment by Prototik** [comment]
Try to update the library. I switch phone locale on "Deutsch (Deutschland)" (right, yea?) and all ok:
![413-1](https://f.cloud.github.com/assets/1416030/401534/238be140-a8de-11e2-97e3-817b22bcc378.png)
![413-2](https://f.cloud.github.com/assets/1416030/401536/2c1e2d40-a8de-11e2-92c3-98ff4b209666.png)

**Comment by stefan222** [comment]
Works! Thank you for your help!
