### ISSUE TITLE
in the tab and swipe activity if there are a lot of tabs, how to hide other tabs and show three tabs, and i could slide on the tabs to switch the tabs?

### ISSUE THREAD

**Issue by Boli-CS** [Prototik/HoloEverywhere#419]
in the tab and swipe activity if there are a lot of tabs, how to hide other tabs and show three tabs, and i could slide on the tabs to switch the tabs?

**Comment by BraisGabin** [comment]
I think you are looking for [ViewPagerIndicator](https://github.com/JakeWharton/Android-ViewPagerIndicator).

But this question should have been asked ​​on StackOverflow or similar pages.
