### ISSUE TITLE
Popup Context Menu colors are wrong, blue line is missing

### ISSUE THREAD

**Issue by stleusc** [Prototik/HoloEverywhere#42]
When using a context menu the blue line is missing and the text is black in dark gray!

**Comment by 2mas29** [comment]
I have the same problem, and can't seem to find a working solution. Please somebody, help fix this issue.

**Comment by newbyca** [comment]
+1

**Comment by newbyca** [comment]
@stleusc and @2mas29 ... for now, i added this to my app's theme (which inherits Theme.HoloEverywhereDark.Sherlock):

```
<item name="android:itemTextAppearance">?android:attr/textAppearanceLarge</item>
```

it doesn't fix the header view problem, but the item text will look better at least.

@ChristopheVersieux i checked the HoloEverywhere source to see if i could patch it, but wasn't sure how you're styling context menus. if you point me in the right direction, i'd be happy to make a pull request. 

also note, i'm actually using the ABS version of HoloEverywhere ... could the problem be coming from there?
