### ISSUE TITLE
How to use custom theme in older versions on android?

### ISSUE THREAD

**Issue by giwrgos88** [Prototik/HoloEverywhere#420]
Hello I'm using the HoloEveryWhere with the ActionBar in my project. I have used the "Android Action Bar Style Generator" to create a custom theme. The problem now is that when i run my application on any ICS and Jelly Bean app it shows correct the theme and when i load it in older versions like Honeycomb etc it shows the Holo design but the Holo.Light instead of my custom theme.

In the manifest i have this

```
<application
    android:icon="@drawable/ic_launcher"
    android:label="@string/app_name"
    android:theme="@style/Theme.MyTheme">
```

and here is the code of my theme

```
<style name="Theme.MyTheme" parent="Holo.Theme.Light">
    <item name="android:popupMenuStyle">@style/PopupMenu.MyTheme</item>
    <item name="android:dropDownListViewStyle">@style/DropDownListView.MyTheme</item>
    <item name="android:actionBarTabStyle">@style/ActionBarTabStyle.MyTheme</item>
    <item name="android:actionDropDownStyle">@style/DropDownNav.MyTheme</item>
    <item name="android:actionBarStyle">@style/ActionBar.Solid.MyTheme</item>
    <item name="android:actionModeBackground">@drawable/cab_background_top</item>
    <item name="android:actionModeSplitBackground">@drawable/cab_background_bottom</item>
    <item name="android:actionModeCloseButtonStyle">@style/ActionButton.CloseMode.MyTheme</item>
    <item name="android:windowBackground">@color/layout_background</item>
    <item name="android:itemTextAppearance">@style/myCustomMenuTextApearance</item>
</style>
```

How i can fix it?

**Comment by Prototik** [comment]
HoloEverywhere uses ActionBarSherlock for backporting a ActionBar on older systems. Just create styles for ABS.
![asd](https://f.cloud.github.com/assets/1416030/424305/93369922-ad84-11e2-8c90-932cfd60a5d8.png)
