### ISSUE TITLE
Use activity as dialog cuts off layout

### ISSUE THREAD

**Issue by isayamayomi** [Prototik/HoloEverywhere#424]
met the same issue as: http://stackoverflow.com/questions/15623965/activity-as-dialog-using-holoeverywhere-cuts-off-layout

Use holoeverywhe1.5，with org.holoeverywhere.app.Activity & Holo.Theme.Dialog

As Hierachy View shows, this problem is caused by org.holoeverywhere.internal.WindowDecorView, which has a larger width than content view, and the out of boundry part is cut. 

screenshot of  Hierachy View
![Screenshot 1](http://i250.photobucket.com/albums/gg266/alviney/1.jpg)
![Screenshot 2](http://i250.photobucket.com/albums/gg266/alviney/2.jpg)

**Comment by Prototik** [comment]
In the latest shapshot Activity with the theme Holo.Theme.Dialog cause crash application XD.

Yea, i know about bug.

**Comment by Prototik** [comment]
Fixed.
