### ISSUE TITLE
ClassCastException when opening context menu

### ISSUE THREAD

**Issue by httpdispatch** [Prototik/HoloEverywhere#428]
HE commit 8e242734e7776282e77856360f34ea948cabef77

The menu is created like this:

``` java
            MenuInflater inflater = getSupportActivity()
                   .getSupportMenuInflater();
            inflater.inflate(R.menu.share, menu);
            super.onCreateContextMenu(menu, v, menuInfo);
```

```
04-29 10:47:17.395: E/AndroidRuntime(9344): FATAL EXCEPTION: main
04-29 10:47:17.395: E/AndroidRuntime(9344): java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to org.holoeverywhere.widget.LinearLayout$LayoutParams
04-29 10:47:17.395: E/AndroidRuntime(9344):     at org.holoeverywhere.widget.LinearLayout.measureVertical(LinearLayout.java:965)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at org.holoeverywhere.widget.LinearLayout.onMeasure(LinearLayout.java:1168)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at android.view.View.measure(View.java:12727)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at android.view.View.measure(View.java:12727)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at android.view.View.measure(View.java:12727)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2092)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at android.view.View.measure(View.java:12727)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1043)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2446)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at android.os.Handler.dispatchMessage(Handler.java:99)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at android.os.Looper.loop(Looper.java:137)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at android.app.ActivityThread.main(ActivityThread.java:4424)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at java.lang.reflect.Method.invokeNative(Native Method)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at java.lang.reflect.Method.invoke(Method.java:511)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
04-29 10:47:17.395: E/AndroidRuntime(9344):     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by httpdispatch** [comment]
Демо тоже крэшится, когда пыдаешься вызвать Context Menu
![image](https://f.cloud.github.com/assets/2315223/437485/3dc93bd0-b0a3-11e2-9701-4f255c953b35.png)

**Comment by Prototik** [comment]
Пока на pre-HC не будет поддержки mixed темы и context/popup menu, окда? :)

**Comment by httpdispatch** [comment]
А есть варианты? Буду пока на старой версии тогда, т.к. приложение должно работать на Android 2.1 и выше

**Comment by Prototik** [comment]
Есть, но это сломает overflow options menu на ics+.

**Comment by httpdispatch** [comment]
С какого коммита, приблизительно, не будет работать context menu?

**Comment by Prototik** [comment]
Эм, коммит выше исправляет эту ситуацию, все работает. но на pre-hc с mixed темой будут неверные цвета - светлый текст на светлом фоне.

**Comment by httpdispatch** [comment]
Скажите, и как профиксить цвет текста контекстного меню, пусть даже сломав оверфлоу меню?

**Comment by httpdispatch** [comment]
@Prototik так не подскажете, как же профиксить это? У меня в приложении нет overflow menu, только drop down popup.

**Comment by Prototik** [comment]
Чувак, ну первое мае ведь, я был мягко говоря не в себе :D

Вообще, должен за это дело отвечать textAppereanceLargePopupMenu, но PopupMenu охренел малость, игнорирует его, разбираюсь...

**Comment by httpdispatch** [comment]
Похоже что на этой ревизии с контекстным меню проблем не было в части цвета текста https://github.com/Prototik/HoloEverywhere/tree/869e78d8618ea625c9d27eb807684bc4165041b8

**Comment by httpdispatch** [comment]
Нашлось решение http://stackoverflow.com/a/5538709/527759

``` xml
<style name="MenuTextAppearance" parent="Holo.TextAppearance.Widget.IconMenu.Item">
        <item name="android:textColor">@android:color/black</item>
</style>

<item name="android:itemTextAppearance">@style/MenuTextAppearance</item>
```

**Comment by httpdispatch** [comment]
Хм, но тогда ломается цвет текста в выпадающем меню на Android ICS

**Comment by Prototik** [comment]
Я же сказал, ломается overflow меню на post-HC.

**Comment by Prototik** [comment]
Хотя, должно все это исправлятся довольно легко, приду домой - сделаю.

**Comment by httpdispatch** [comment]
Ну чтоб не ломалось надо править стиль Holo.TextAppearance.Widget.IconMenu.Item, наверное, который используется только до v14. И до v14 цвет меню определяется как раз таки textAppereanceLargePopupMenu. А вот на ICS почему-то определяется комбинацией и android:itemTextAppearance "выигрывает"

**Comment by httpdispatch** [comment]
Похоже фиксить надо так: в теме Holo.Theme.Light.DarkActionBar

``` xml
<item name="android:panelColorForeground">@color/primary_text_holo_light</item>
```

**Comment by Prototik** [comment]
С ffd38fbe365e8b0c73191e278bef2d8c712e78bf лучше будет?

**Comment by httpdispatch** [comment]
Сейчас протестирую. С контекстным меню этот коммит тоже что-то делает?

**Comment by Prototik** [comment]
Не, чисто переносит panel\* атрибуты в глобальный пул, т.е. они применяются и на v7 и на v14 темы.

**Comment by httpdispatch** [comment]
А по контексному меню есть идеи? Почему-то в демо работает, а у меня в приложении рисует линию поверх.

**Comment by Prototik** [comment]
Код?

**Comment by httpdispatch** [comment]
Уже что только не пробовал, и чистую Holo.Theme.Light.DarkActionBar даже. Вроде код почти такой же как в демо, а результат - нет

shareButton создается в ListView адаптере

``` java
            final ImageView shareButton = (ImageView) convertView
                    .findViewById(R.id.share_button);
            shareButton.setOnClickListener(new OnClickListener()
            {
                @Override
                public void onClick(final View v)
                {
                    TrackerUtils.trackButtonClickEvent("share_button", HomeFragment.this);
                    activePhoto = photo;
                    showShareOptions(v);
                }

                public void showShareOptions(View v) {
                    registerForContextMenu(v);
                    v.showContextMenu();
                    unregisterForContextMenu(v);
                }
            });

    @Override
    public void onCreateContextMenu(ContextMenu menu, View v,
            ContextMenuInfo menuInfo)
    {
        if (v.getId() == R.id.share_button)
        {
            MenuInflater inflater = getSupportActivity()
                    .getSupportMenuInflater();
            inflater.inflate(R.menu.share, menu);
            super.onCreateContextMenu(menu, v, menuInfo);
        } else
        {
            super.onCreateContextMenu(menu, v, menuInfo);
        }
    }
```

share.xml

``` xml
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android" >

    <item
        android:id="@+id/menu_share_email"
        android:title="@string/menu_share_email"
        />
    <item
        android:id="@+id/menu_share_twitter"
        android:title="@string/menu_share_twitter"
        />
    <item
        android:id="@+id/menu_share_facebook"
        android:title="@string/menu_share_facebook"
        />

</menu>
```

**Comment by httpdispatch** [comment]
Это все проискодит в потомке org.holoverywhere.app.Fragment

**Comment by Prototik** [comment]
Точно последний снапшот используется?
Тема на Application применяется?

**Comment by httpdispatch** [comment]
Снапшот последний. На Android 2.x линии черной нету, есть только на 4.x
Тема на Application не применяется, только на Activity

**Comment by Prototik** [comment]
Этот проект в публичном доступе?

**Comment by httpdispatch** [comment]
Да http://github.com/photo/mobile-android

**Comment by httpdispatch** [comment]
только без Maven пока

**Comment by httpdispatch** [comment]
> С ffd38fb лучше будет?

Не будет.
![image](https://f.cloud.github.com/assets/2315223/458623/b2ae36e6-b3df-11e2-9842-87f75635fa7f.png)

**Comment by httpdispatch** [comment]
Но это я могу обойти как уже писал выше.

``` xml
<item name="android:panelColorForeground">@color/primary_text_holo_light</item>
```

**Comment by httpdispatch** [comment]
Вот с фиксом
![image](https://f.cloud.github.com/assets/2315223/458630/18d54036-b3e0-11e2-8786-6ea599ca8b19.png)

**Comment by Prototik** [comment]
``` xml
    <application
        ...
        android:theme="@style/Theme.Trovebox.Light" >
```

Эм?

**Comment by httpdispatch** [comment]
Извините меня, замотался с этими тестами совсем

**Comment by httpdispatch** [comment]
Так на application тему нельзя прикручивать?

**Comment by Prototik** [comment]
Вообще можно, но эту ситуацию обрабатывает немного кривоватый код в конструкторе Dialog'a.
Все должно работать, по идее...

**Comment by httpdispatch** [comment]
я сейчас попробую убрать оттуда, и применить к Активити

**Comment by httpdispatch** [comment]
Попробовал, изменений нет

**Comment by httpdispatch** [comment]
Цвет шрифта, наконец-то, правильный в последнем коммите

**Comment by Prototik** [comment]
```
    [javac] Compiling 170 source files to /home/sergey/git/mobile-android/app/bin/classes
    [javac] /home/sergey/git/mobile-android/app/src/com/trovebox/android/app/net/account/IAccountTroveboxApiFactory.java:19: error: cannot find symbol
    [javac]         return new AccountTroveboxApi(context);
    [javac]                    ^
    [javac]   symbol:   class AccountTroveboxApi
    [javac]   location: class IAccountTroveboxApiFactory
```

**Comment by httpdispatch** [comment]
В IAccountTroveboxApiFactory AccountTroveboxApi надо заменить на FakeAccountTroveboxApi. AccountTroveboxApi это приватный API

**Comment by httpdispatch** [comment]
Без этого API вход будет работать только через OAuth, т.е. нужно предварительно зарегистрироваться на trovebox.com

**Comment by Prototik** [comment]
Может есть какой-то тестовый аккаунт или типа того?

**Comment by httpdispatch** [comment]
Сейчас скину FakeAccountTroveboxApi с тестовым доступом

**Comment by httpdispatch** [comment]
https://dl.dropboxusercontent.com/u/37011471/Openphoto/FakeAccountTroveboxApi.java
Нажмите войти используя email, потом введите любые данные и нажмите вход

**Comment by httpdispatch** [comment]
А есть ли возможность сменить цвет фона в PopupMenu? Я вот уже подумываю, может ну его это контекстное меню.

**Comment by Prototik** [comment]
Есть, создаете свою тему, которая наследуется от Holo.Theme.Dialog, там делаем няшный диалог и в конструктор PopupMenu передает новый ContextThemeWrapper с этой темой.

**Comment by httpdispatch** [comment]
ContentThemeWrapper - не могу такой найти, да и параметра такого нет в PopupMenu

**Comment by httpdispatch** [comment]
Получилось по другому через аттрибут listPopupWindowStyle

**Comment by httpdispatch** [comment]
Получилось только на Android 4.x, на 2.3 все выглядит странно

**Comment by httpdispatch** [comment]
Вот что получается на 2.3
Цвет текста не белый, а черный. Но это еще полбеды
![image](https://f.cloud.github.com/assets/2315223/458866/5432b2ee-b3ef-11e2-90ab-351aa302a936.png)

Зажимаю мышку на верхнем пункте меню
![image](https://f.cloud.github.com/assets/2315223/458873/6a499994-b3ef-11e2-8d5d-c80d7bbcb504.png)

Начинаю вести курсор вниз и меню приобретает такой вид
![image](https://f.cloud.github.com/assets/2315223/458880/850aa8ea-b3ef-11e2-9677-a2ccc35d9ee3.png)

Это я получается выделил несколько пунктов?

**Comment by Prototik** [comment]
Вы там не шерлоковский ListPopupWindow стиль используете?

**Comment by httpdispatch** [comment]
Да, именно он. Он же используется как drowdown меню в ABS. Нужно менять на какой-то holo widget?

**Comment by Prototik** [comment]
Вы сами ответили на свой вопрос: в abs. PopupMenu использует бекпорт из org.holoeverywhere.

**Comment by httpdispatch** [comment]
Спасибо, с новой недели начну экспериментировать. Могу сказать, что drow-down в ABS работает без вышеперечисленных глюков на Android 2.3

**Comment by Prototik** [comment]
Вы применили стиль шерлока на he виджет. Я пишу стили только в одну сторону совместимости: когда he стиль применяется на виджет шерлока.

**Comment by httpdispatch** [comment]
Я попробовал изменить стиль на Holo.ListPopupWindow, но никаких изменений

**Comment by httpdispatch** [comment]
Нашел как поправить цвет текста, через dialogItemTextAppearance. Но с background пока не нашел решения

**Comment by httpdispatch** [comment]
Я вот подумал, может это в бэкграунде не хватает описания для каких-то состояний?

``` xml
<selector xmlns:android="http://schemas.android.com/apk/res/android" android:exitFadeDuration="@android:integer/config_mediumAnimTime">

    <item android:drawable="@drawable/list_focused_trovebox" android:state_focused="true" android:state_pressed="false"/>
    <item android:drawable="@drawable/pressed_background_trovebox" android:state_pressed="true"/>
    <item android:drawable="@android:color/transparent"/>

</selector>
```

**Comment by httpdispatch** [comment]
Нет, не похоже. Это больше похоже на наложение цветов холо поверх кастомного бекграунда

**Comment by httpdispatch** [comment]
@Prototik у Вас не найдется совета в какую сторону копать?

**Comment by httpdispatch** [comment]
@Prototik хотите, чтобы я приготовил демку, демонстрирующую проблему?

**Comment by httpdispatch** [comment]
Ура, нашел фикс пока пытался демку приготовить. Проблема была в кастомном dropDownListViewStyle почему-то. Унаследовал его от Holo.ListView.DropDown.Light (до этого было Widget.Sherlock.ListView.DropDown) и теперь все работает как полагается на Android 2.x
