### ISSUE TITLE
Context menu: dark line above the menu

### ISSUE THREAD

**Issue by httpdispatch** [Prototik/HoloEverywhere#429]
HE commit f55aaeb1d3208c8ebd8d05bf9dba7a58132123c3 (such as here context menu is still working)
It is same issue as this one https://github.com/Prototik/HoloEverywhere/issues/380 but for context menu

![image](https://f.cloud.github.com/assets/2315223/437595/f01d669a-b0a7-11e2-95ca-f601a5c05594.png)

**Comment by httpdispatch** [comment]
Кстати, линия у меня так и не исчезла, почему-то. ЧЯДНТ?
![image](https://f.cloud.github.com/assets/2315223/458189/dfc40ec0-b3cc-11e2-82c5-9bc79bc3af09.png)

**Comment by IronicallyJesus** [comment]
I am probably using ContextMenu wrong, but this problem still persists.
Works well on Gingerbread/Froyo but the bug occurs in Jelly Bean on my Galaxy Nexus (Pictured)
![screenshot_2013-07-13-15-25-11](https://f.cloud.github.com/assets/3488086/793273/0a86d3ec-ebf2-11e2-9e95-7dff3e8825f3.png)

**Comment by Prototik** [comment]
Provide a sample project in `bugs` branch. I can't repeat this bug.

**Comment by IronicallyJesus** [comment]
I'll try. I don't really know how to github

**Comment by Prototik** [comment]
@TheWizKid95 Well, [try.github.io](http://try.github.io/) is just for you...

**Comment by IronicallyJesus** [comment]
Sorry for the wait, but I just requested a commit. Hope I did well.

**Comment by Prototik** [comment]
Fixed.
