### ISSUE TITLE
AutoCompleteTextView style not covered

### ISSUE THREAD

**Issue by SRSMartin** [Prototik/HoloEverywhere#43]
Hello,
AutoCompleteTextViews do not seem to get styled.
Best regards,
Martin

EDIT, Solved:
This is the list where to find the Android style attribute names:
http://developer.android.com/reference/android/R.attr.html

Simply adding
        &#60;item name="android:autoCompleteTextViewStyle"&#62;@style/EditTextHoloDark&#60;/item&#62;
in
    &#60;style name="Theme.HoloEverywhereDark.Sherlock" parent="Theme.Sherlock"&#62;
or wherever it is needed should solve the issue till the next update.

**Comment by ironjan** [comment]
Adding simply this line throws a NullPointerException in android.widget.AbsListView.setSelector on Android 2.3

The minimal style I could create was:

``` xml
  <style name="AutoCompleteTextViewHoloLight" parent="android:style/Widget.AutoCompleteTextView">
        <item name="android:background">@drawable/edit_text_holo_light</item>
        <item name="android:textColor">#000000</item>
        <item name="android:dropDownSelector">@drawable/list_selector_holo_light</item>
    </style>

    <style name="AutoCompleteTextViewHoloDark" parent="android:style/Widget.AutoCompleteTextView">
        <item name="android:background">@drawable/edit_text_holo_dark</item>
        <item name="android:textColor">#ffffff</item>
        <item name="android:dropDownSelector">@drawable/list_selector_holo_dark</item>
    </style>
```

Adding 

``` xml
        <item name="android:autoCompleteTextViewStyle">@style/AutoCompleteTextViewHoloLight</item>
```

or 

``` xml
        <item name="android:autoCompleteTextViewStyle">@style/AutoCompleteTextViewHoloLight</item>
```

to the coresponding themes solved crashing and styling. I did not have the time to test this completely.

Edit: DropDown-Items are white text on white background (light theme) on Android 2.3.

**Comment by Prototik** [comment]
@ironjan AutoCompleteTextView already supported in dev version, in the future - version 1.2.2

**Comment by Prototik** [comment]
48d3fe01092a822feea3b997b83061b7284d8603
