### ISSUE TITLE
Put src to the top of Order and Export

### ISSUE THREAD

**Issue by httpdispatch** [Prototik/HoloEverywhere#437]
Would be good to place it to the top so HE source code can be opened from projects using HE library. Also would be good to have selected Android Dependencies like this
![image](https://f.cloud.github.com/assets/2315223/477321/0ae1d546-b7de-11e2-8483-e97635424e5c.png)

**Comment by Prototik** [comment]
Reasons?

**Comment by httpdispatch** [comment]
If to import HE library to project and want to debug through HE or open some HE source directly from your project (ctrl + click) it will not be availalbe (Source is not attached). But when i put src to the top of Order and Export i can browse HE source directly from my project
