### ISSUE TITLE
The IAddon class seems to be causing memory leaks

### ISSUE THREAD

**Issue by bastienbeurier** [Prototik/HoloEverywhere#438]
Hello, 

I just saw that doing a memory dump and analyzing with MAT. Here is the detailed issue: 

http://stackoverflow.com/questions/16429243/memory-leak-due-to-iaddon-class-in-holoeverywhere

If anybody has a clue about what am I doing wrong or what could solve the issue, I would very much appreciate it!

**Comment by BraisGabin** [comment]
Did you try the current master version? #436 fix it.

**Comment by httpdispatch** [comment]
@bastienbeurier we discussed it here #432. Does this help?

**Comment by bastienbeurier** [comment]
@httpdispatch This is exactly it! Thanks a lot!
