### ISSUE TITLE
Problem styling a Switch

### ISSUE THREAD

**Issue by dominicthomas** [Prototik/HoloEverywhere#439]
When using Holo Everywhere, setting the textOn, textOff, thumb and track on a Switch view in xml or in styles has no effect. Please help.

**Comment by Prototik** [comment]
[See](https://github.com/Prototik/HoloEverywhere/blob/master/library/res/values/styles.xml#L337)

You should use attrs without `android:` prefix, but with `holo:` in xml and with nothing in styles.

**Comment by dominicthomas** [comment]
Thanks. I solved it by using the full class name <org.holoeverywhere.widget.Switch and then declaring xmlns:app="http://schemas.android.com/apk/res/com.my.package.name" in my parent layout. So app:textOn, app:thumb etc now works. Thanks again.
