### ISSUE TITLE
Importing to IDE

### ISSUE THREAD

**Issue by dementhius** [Prototik/HoloEverywhere#441]
Hi all,

I´m installing HoloEverywhere reading the guide you do but I don´t know what do you mean in the path "Replace contrib/ActionBarSherlock/library/libs/android-support-v4.jar by support-library/android-support-v4-r12.jar". What should I change? 

Thx

**Comment by BraisGabin** [comment]
Remove `HoloEverywhere/contrib/ActionBarSherlock/actionbarsherlock/libs/android-support-v4.jar` and copy `HoloEverywhere/support-library/android-support-v4-r12.jar` to `HoloEverywhere/contrib/ActionBarSherlock/actionbarsherlock/libs/`. I'll update the wiki to clarify this point.
