### ISSUE TITLE
Android 2.3 Holo.Theme invalid text color when typing

### ISSUE THREAD

**Issue by httpdispatch** [Prototik/HoloEverywhere#443]
It is black, but should be white
Android 2.3
![image](https://f.cloud.github.com/assets/2315223/505966/10182320-bd3e-11e2-826a-55d4e8f303b5.png)
Android 4.x
![image](https://f.cloud.github.com/assets/2315223/505968/352714c8-bd3e-11e2-871e-23b257321ae6.png)

**Comment by Prototik** [comment]
Mmm...
![device-2013-05-15-171945](https://f.cloud.github.com/assets/1416030/506064/e9c17462-bd40-11e2-89a6-4f1b407be991.png)

**Comment by httpdispatch** [comment]
Может это на Android x86 только тогда

**Comment by httpdispatch** [comment]
у Вас андроид 2.1 или 2.3 эмулятор?

**Comment by Prototik** [comment]
2.1 arm, 2.3 x86 от интела

**Comment by Prototik** [comment]
Хм, на 2.3 повторил проблему

**Comment by httpdispatch** [comment]
значит надо поправить заголовок, что на android 2.3

**Comment by Prototik** [comment]
Так, да все, нашел проблему, потерялся один блок в билдере, ща поправлю.

**Comment by httpdispatch** [comment]
Спасибо, жду

**Comment by httpdispatch** [comment]
Спасибо
