### ISSUE TITLE
Import Lib with updated ADT

### ISSUE THREAD

**Issue by silversmurf** [Prototik/HoloEverywhere#450]
I have an Error after cloning from git and importing as Library.
A few moments before cloning I updated the libs on SDK-Manager and Eclipse-Addons.

![screener_holoeverywhere_fragmentactivity_error](https://f.cloud.github.com/assets/3669877/512419/32ee662c-be27-11e2-95ac-94959763812d.png)

Any help?

Thanks in advance...
Z. Trulec

**Comment by silversmurf** [comment]
I think this one is the core of the Problem, what should I do?
Any help is appreciated!

![screener_holoeverywhere_fragmentactivity_error1](https://f.cloud.github.com/assets/3669877/512491/d5e2a53a-be29-11e2-814f-37135b277370.jpg)

Thanks...

**Comment by BraisGabin** [comment]
Did you install the support package? https://github.com/Prototik/HoloEverywhere/wiki/Import-in-IDE#eclipse

**Comment by silversmurf** [comment]
Yes I have - I've tryed first with the r12 and now with r13. Still no changes...  :(

**Comment by silversmurf** [comment]
OH FU... NO!! I updated the plugins in SDK-Manager and thought it would be enough! But you have to open it twice to check if anything is updated and ready, depending on the previous updated versions...

sorry for that! It works now like a charme!

(by the way, thanks a lot for the great lib!!!)
