### ISSUE TITLE
Other memory leak related to IAddon class when using PagerAdapter

### ISSUE THREAD

**Issue by bastienbeurier** [Prototik/HoloEverywhere#451]
I remember the previous topic on the IAddon class memory leak: #432. The fix worked for me, now my activities are being correctly garbage collected.

But I just ran into another memory leak where ImageViews in my PagerAdapter are not being garbage collected. Using MAT, it looks like a reference is kept by the sAddonsMap variable in the IAddon class. Here is a screenshot:  

![screen](https://dl.dropboxusercontent.com/u/11061286/Screen%20Shot%202013-05-16%20at%205.36.24%20PM.png)

I might be doing something wrong. In particular, I noticed that the method onDestroyItem from the PagerAdapter is never being called.

Anybody has a clue?

Thanks!

**Comment by Prototik** [comment]
This bug still to be or it's your fail?

**Comment by bastienbeurier** [comment]
@Prototik I was on the wrong branch, sorry for that!
