### ISSUE TITLE
onRetainNonConfigurationInstance: overridden method is final

### ISSUE THREAD

**Issue by PureSpider** [Prototik/HoloEverywhere#452]
```
onRetainNonConfigurationInstance() in MyActivity cannot override onRetainNonConfigurationInstance() in FragmentActivity
overridden method is final
```

I am extending `org.holoeverywhere.app.ListActivity` in MyActivity.
Is there someting I need to change or is it a bug?

**Comment by PureSpider** [comment]
Okay, I can override `onRetainCustomNonConfigurationInstance()`.
But why do I have to do that?

**Comment by Prototik** [comment]
It's default behavior of FragmentActivity: [link](http://developer.android.com/reference/android/support/v4/app/FragmentActivity.html#onRetainNonConfigurationInstance%28%29)
