### ISSUE TITLE
Can't Import to Eclipse

### ISSUE THREAD

**Issue by sjvc** [Prototik/HoloEverywhere#453]
I think it can be an issue with my eclipse, or something I don't know, but I'm crazy with it...

I'm following these instructions: https://github.com/Prototik/HoloEverywhere/wiki/Import-in-IDE#eclipse. I go to "Import" then "Project form GIT", then I select "URI", and I paste "ssh://git@github.com/Prototik/HoloEverywhere.git" in URI field. But when I press "OK" I receive this error message: "Auth fail: Invalid password or missing SSH key". 

Can you help me please?

**Comment by luciferz2012** [comment]
@sjvc You can simply import this project from https uri: https://github.com/Prototik/HoloEverywhere.git. That works fine for me.

**Comment by Prototik** [comment]
Just i think that ssh setuped de-facto on all machines. Use URI `git://github.com/Prototik/HoloEverywhere.git`.

**Comment by sjvc** [comment]
Thanks for your help :)
