### ISSUE TITLE
AddonRoboguice of 1.5.1-SNAPSHOT issue

### ISSUE THREAD

**Issue by Rutton** [Prototik/HoloEverywhere#455]
Hello Prototik,

Thanks for the great work with HE.

I use the Roboguice addon of 1.5.1-SNAPSHOT from the sonatype snapshot repository. My Activities properly have the Roboguice annotation and the addon does get instantiated fine. Though I do get the error "xyzActivity does not appear to be a RoboGuice context (instanceof RoboContext)" during onCreate.

I quickly fixed that in the AddonRoboguice by wrapping a RoboguiceContextWrapper in the
`private static HoloInjector createInjector(final Context context) {`
method around the context like this:
`return new HoloInjector(new RoboguiceContextWrapper(context), Guice.createInjector(module));`

**Comment by Prototik** [comment]
Full stacktrace, please.

**Comment by Rutton** [comment]
Here it is:
D/AndroidRuntime(24904): Shutting down VM
W/dalvikvm(24904): threadid=1: thread exiting with uncaught exception (group=0x40b92930)
E/AndroidRuntime(24904): FATAL EXCEPTION: main
E/AndroidRuntime(24904): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wheelmap.android.develop/org.wheelmap.android.activity.StartupActivity}: java.lang.IllegalArgumentException: org.wheelmap.android.activity.StartupActivity@40e906d8 does not appear to be a RoboGuice context (instanceof RoboContext)
E/AndroidRuntime(24904):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2307)
E/AndroidRuntime(24904):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2357)
E/AndroidRuntime(24904):    at android.app.ActivityThread.access$600(ActivityThread.java:153)
E/AndroidRuntime(24904):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247)
E/AndroidRuntime(24904):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(24904):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(24904):    at android.app.ActivityThread.main(ActivityThread.java:5226)
E/AndroidRuntime(24904):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(24904):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(24904):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
E/AndroidRuntime(24904):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
E/AndroidRuntime(24904):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(24904): Caused by: java.lang.IllegalArgumentException: org.wheelmap.android.activity.StartupActivity@40e906d8 does not appear to be a RoboGuice context (instanceof RoboContext)
E/AndroidRuntime(24904):    at roboguice.inject.ContextScope.getScopedObjectMap(ContextScope.java:147)
E/AndroidRuntime(24904):    at roboguice.inject.ContextScope.enter(ContextScope.java:79)
E/AndroidRuntime(24904):    at roboguice.inject.ContextScopedRoboInjector.getInstance(ContextScopedRoboInjector.java:141)
E/AndroidRuntime(24904):    at org.holoeverywhere.addon.AddonRoboguice$AddonRoboguiceA.obtainInjector(AddonRoboguice.java:71)
E/AndroidRuntime(24904):    at org.holoeverywhere.addon.AddonRoboguice$AddonRoboguiceA.onPreCreate(AddonRoboguice.java:141)
E/AndroidRuntime(24904):    at org.holoeverywhere.app.Activity$5.justAction(Activity.java:231)
E/AndroidRuntime(24904):    at org.holoeverywhere.app.Activity$5.justAction(Activity.java:228)
E/AndroidRuntime(24904):    at org.holoeverywhere.addon.IAddonAttacher$AddonCallback.action(IAddonAttacher.java:11)
E/AndroidRuntime(24904):    at org.holoeverywhere.addon.IAddonAttacher$AddonCallback.performAction(IAddonAttacher.java:24)
E/AndroidRuntime(24904):    at org.holoeverywhere.addon.IAddonBasicAttacher.performAddonAction(IAddonBasicAttacher.java:118)
E/AndroidRuntime(24904):    at org.holoeverywhere.app.Activity.performAddonAction(Activity.java:507)
E/AndroidRuntime(24904):    at org.holoeverywhere.app.Activity.onCreate(Activity.java:228)
E/AndroidRuntime(24904):    at org.wheelmap.android.activity.StartupActivity.onCreate(StartupActivity.java:84)
E/AndroidRuntime(24904):    at android.app.Activity.performCreate(Activity.java:5104)
E/AndroidRuntime(24904):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
E/AndroidRuntime(24904):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
E/AndroidRuntime(24904):    ... 11 more
W/ActivityManager(  423):   Force finishing activity org.wheelmap.android.develop/org.wheelmap.android.activity.StartupActivity

**Comment by Prototik** [comment]
Fixed in `org.holoeverywhere:addon-roboguice:2.0`
