### ISSUE TITLE
Tab navigation in new HoloEverywhere not displays fragment after screen rotation

### ISSUE THREAD

**Issue by ljarka** [Prototik/HoloEverywhere#456]
http://stackoverflow.com/questions/16664764/tab-navigation-in-new-holoeverywhere-not-displays-fragment-after-screen-rotation

**Comment by Prototik** [comment]
Not HE bug.
Officially supported tab navigation - [TabSwipeActivity](https://github.com/Prototik/HoloEverywhere/blob/master/library/src/org/holoeverywhere/app/TabSwipeActivity.java)/[TabSwipeFragment](https://github.com/Prototik/HoloEverywhere/blob/master/library/src/org/holoeverywhere/app/TabSwipeFragment.java). If this bug still occur in this case - post it.  
[Usage example](https://github.com/Prototik/HoloEverywhere/blob/master/demo/src/org/holoeverywhere/demo/fragments/DemoTabsFragment.java)

**Comment by ljarka** [comment]
Apparently, it is not the fault of tabs. If I create simple activity like this:

``` java

        public class MainActivity extends Activity {

            @Override
            protected void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();
                transaction.add(android.R.id.content, new NewFragment(), "newTag");
                transaction.commit();

                getSupportActionBar().setHomeButtonEnabled(true);
            }

            @Override
            public boolean onOptionsItemSelected(MenuItem item) {
                FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();
                transaction.add(android.R.id.content, new NewFragment(), "newTag");
                transaction.commit();

                return true;
            }
        }
```

And fragment:

``` java
    public class NewFragment extends Fragment {
        @Override
        public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
            View view = new View(getActivity());
            view.setBackgroundColor(Color.BLACK);
            return view;
        }
    }
```

Fragment is not shown when I add it in onCreate method but when I do this in OnOptionsItemSelected then it is.

**Comment by Prototik** [comment]
I'm not recommend use fragments while content view not created.
As a id `android.R.id.content`.

Create a simple layout:

``` xml
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
  android:id="@+id/content"
  android:layout_width="match_parent"
  android:layout_height="match_parent" />
```

And in fragment manager use `R.id.content` instead of `android.R.id.content`.

**Comment by ljarka** [comment]
Thank you. This solved my problem ;)
