### ISSUE TITLE
Spinner.setDropDownWidth doesn't work on android 2.3.6

### ISSUE THREAD

**Issue by JPMagalhaes** [Prototik/HoloEverywhere#458]
I'm using a spinner as an ActionProvider and I'm setting drop-down width dynamically because the design has specified this width should be equal to the screen width.
It works well on 4.1.2 but not in 2.3.6.

**Comment by Prototik** [comment]
Spinner at top and left has default behavior. For third spinner was called setDropDownWidth with display width param.
Works fine on 2.1, 2.3, 4.2.
![screenshot from 2013-05-22 15 31 04](https://f.cloud.github.com/assets/1416030/546929/fffb388c-c2b1-11e2-9313-07aa814c3eda.png)
[Bug APK for testing](https://docs.google.com/file/d/0BxcxDFWRyauQMEp4cXFFb2xXeWc/edit?usp=sharing)

**Comment by JPMagalhaes** [comment]
Actually this problem happened when I tried to set a (valid) cursor to the SimpleCursorAdapter linked to my spinner. I'll try to reproduce it later on the code of Bug #458. And, as I said, the spinner was in the ActionBar, implemented as an ActionProvider.
I fixed it through a workaround implementing the newDropDownView function on my SimpleCursorAdapter, as follows:

``` java
@Override
public View newDropDownView(Context context, Cursor cursor, ViewGroup parent) {
    View ret = super.newDropDownView(context, cursor, parent);
    ret.setLayoutParams(new ListView.LayoutParams(screenWidth, LayoutParams.WRAP_CONTENT));
    return ret;
}
```
