### ISSUE TITLE
Missing ActionBar Title/Subtitle

### ISSUE THREAD

**Issue by kibish** [Prototik/HoloEverywhere#459]
after getSupportActionBar().setSubtitle("...

on Android 10 (2.3.4 Sony Ericsson LT18i)

![screenshot_2013-05-23_1057](https://f.cloud.github.com/assets/4507769/553524/a479a94e-c388-11e2-9d0f-741bc478b183.png)

**Comment by Prototik** [comment]
1.6.0 release
![device-2013-05-23-171947](https://f.cloud.github.com/assets/1416030/553577/261086d4-c38a-11e2-95d2-6c60db27aba4.png)

**Comment by MarinaEariel** [comment]
Hi! I'm getting this issue once again. I'm using the latest version available here on Github.
![screenshot_2013-12-12_1210](https://f.cloud.github.com/assets/2913224/1733894/760bc578-633e-11e3-90c9-4d574c1abefc.png)
