### ISSUE TITLE
Custom font

### ISSUE THREAD

**Issue by juliocbcotta** [Prototik/HoloEverywhere#460]
Hello there,
I would like to know if it's possible to load a custom font into HoloEveryWhere.
I mean, could it be a problem to add a method into FontLoader class to be called in the Application class to load a custom font configuration?
I know I can just change the file references in the FontLoader file, but if I do that I will have to do that after each library update.
Thanks.

**Comment by Prototik** [comment]
Place your font in res/raw folder.
Use method `HoloFont.makeFont(**)` for creating a new instance of font object.
Also you can provide four styles of fonts (regular, bold, italic, bolditalic) like this:

``` java
            ROBOTO = makeFont(
                    ROBOTO_REGULAR = makeFont(R.raw.roboto_regular),
                    ROBOTO_BOLD = makeFont(R.raw.roboto_bold),
                    ROBOTO_ITALIC = makeFont(R.raw.roboto_italic),
                    ROBOTO_BOLD_ITALIC = makeFont(R.raw.roboto_bolditalic)
                    );
```

And finally call `FontLoader.setDefaultFont(HoloFont)` and this font will be everywhere in application.
This code should be placed in static `Application` codeblock, of course.

**Comment by juliocbcotta** [comment]
Thanks a lot man!
I think many people would like to know this, how about an entry into the project wiki?

**Comment by Prototik** [comment]
Just do it, man. I have no time for it.
