### ISSUE TITLE
Some visual problems with Demo on HTC Desire (2.2.2)

### ISSUE THREAD

**Issue by soswow** [Prototik/HoloEverywhere#466]
**Inside "Settings" I see 2 problems**
1. Title is not shown fully (maybe it's a feature, I don't know)
2. List group titles don't have 2dp line under it (this line seems to be concentrated on the right)
Here is the screen:
![2013-05-26-17-49-30](https://f.cloud.github.com/assets/108065/565455/432840bc-c615-11e2-8a7a-61080f812170.png)

**Comment by Prototik** [comment]
Definitely problems with your build environment,
![device-2013-05-28-164647](https://f.cloud.github.com/assets/1416030/571312/59c9fcc0-c773-11e2-840a-4cd66a21a0d8.png)
Latest snapshot of demo you can find in [oss sonatype repository](https://oss.sonatype.org/content/repositories/snapshots/org/holoeverywhere/demo/1.6.1-SNAPSHOT/)
Now latest is [this](https://oss.sonatype.org/content/repositories/snapshots/org/holoeverywhere/demo/1.6.1-SNAPSHOT/demo-1.6.1-20130528.071110-10-aligned.apk) version.
