### ISSUE TITLE
Having some errors with android.support.v4.widget.DrawerLayout

### ISSUE THREAD

**Issue by giwrgos88** [Prototik/HoloEverywhere#468]
Hello I'm having a small issue with the android.support.v4.widget.DrawerLayout after i have imported the project in to the eclipse. 
![screen shot 2013-05-28 at 5 19 00 pm](https://f.cloud.github.com/assets/3164113/572736/98513f2a-c7a1-11e2-8792-adec3db0ea86.png)
 how i can fix it? thank you

**Comment by Prototik** [comment]
/Which/ problems are you have? In latest snapshot demo using DrawerLayout - second screenshot on mainpage.

**Comment by giwrgos88** [comment]
the one is this
Description Resource    Path    Location    Type
android.support.v4.widget.DrawerLayout cannot be resolved to a type DrawerLayout.java   /HoloEverywhere Library/src/org/holoeverywhere/widget   line 11 Java Problem

and the other one is 
Description Resource    Path    Location    Type
DrawerLayout cannot be resolved to a type   DrawerLayout.java   /HoloEverywhere Library/src/org/holoeverywhere/widget   line 36 Java Problem

**Comment by Prototik** [comment]
Update ABS/libs/android-support-v4.jar by HoloEverywhere/android-support-v4-r13.jar.
This step described in `import in ide` guide.
