### ISSUE TITLE
How do I use TabSwipeActivity?

### ISSUE THREAD

**Issue by tkiela** [Prototik/HoloEverywhere#469]
Hello guys,

I am just playing around with HoloEverywhere.
I found the "TabSwipeActivity". How do I use this?

I tried:

```
public class TabSwipe extends TabSwipeActivity {

@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.main);
}

@Override
protected void onHandleTabs() {
    // TODO Auto-generated method stub
    addTab("main", MainFragment.class, new Bundle());
    addTab("result", MainFragment.class, null);
    addTab("player", MainFragment.class, null);
}


}
```

But nothing happens.

**Comment by Prototik** [comment]
[TabSwipeFragment example](https://github.com/Prototik/HoloEverywhere/blob/master/demo/src/org/holoeverywhere/demo/fragments/TabsFragment.java)

You don't should call setContentView() in onCreate(). Keep only onHandleTabs():

``` java
public class TabSwipe extends TabSwipeActivity {
  @Override
  protected void onHandleTabs() {
    addTab("Main", MainFragment.class, new Bundle());
    addTab("Result", ResultFragment.class, null);
    addTab("Player", PlayerFragment.class, null);
  }
}

```

**Comment by tkiela** [comment]
Hmm, it does not work this way either. Below actionbar everything stays black.

**Comment by paulpv** [comment]
I used to be using TabSwipeActivity with a custom layout that defined a ViewPager with id tabSwipePager.
It has worked fine for weeks, but is now broken after pulling the latest master code: "findViewById" returns null for other Views defined in my simple custom layout.
How to get this working again?
Thanks!
