### ISSUE TITLE
Still wrong text color in AutoCompleteTextView suggestion dropdown

### ISSUE THREAD

**Issue by PureSpider** [Prototik/HoloEverywhere#471]
See #462

**Comment by Prototik** [comment]
![screenshot from 2013-05-29 19 38 01](https://f.cloud.github.com/assets/1416030/578375/7b11136e-c854-11e2-8687-5c7e01e854cf.png)
![screenshot from 2013-05-29 19 37 39](https://f.cloud.github.com/assets/1416030/578376/7b16d24a-c854-11e2-8a55-3ad77eb3a777.png)
![screenshot from 2013-05-29 19 38 17](https://f.cloud.github.com/assets/1416030/578377/7b355a12-c854-11e2-9bbe-ed0d66f7e37c.png)

AutoCompleteTextView with all 3 themes (Dark, Light, Mixed) in demo application.
Issue with /your/ code.

**Comment by PureSpider** [comment]
On which version of android are you trying this?
I can't see how this would be an issue with my code as I'm doing nothing to change text colors in any way.

**Comment by Prototik** [comment]
See windows title - 2.1, 2.3.3 and 4.2.

**Comment by PureSpider** [comment]
It indeed was a problem with my code - I was using `android.R.layout.simple_dropdown_item_1line` instead of `R.layout.simple_dropdown_item_1line`.
