### ISSUE TITLE
HoloEverywhere with Holo Colors Generator

### ISSUE THREAD

**Issue by wildsvinja** [Prototik/HoloEverywhere#472]
Hi guys! Great library)))

I just can't figure out one thing! Im implementing custom colors to HoloEverywhere using Holo Colors Generator, i follow the instructions they have on their web site:

"Is it possible to combine Holo Colors with HoloEverywhere ?
Holo Everywhere provide the full backport of Android 4.2 widgets to 2.x. You can use both Holo Everywhere and Holo Colors. Clone the Holo Everywhere github project. In the library module, remove the res/values-v14 folder. Override all pictures in drawable-mdpi, drawable-hdpi and drawable-xhdpi with the ones generated by Holo Colors. Build the library and use it as usual, you should have your colored widget. (Ex: Holo Everywhere Demo with red color)"

I replace all the images in in drawable-mdpi, drawable-hdpi and drawable-xhdpi. No folder  res/values-v14 to be found, so i don't delete it. clean and rebuild, no problems.

But the widgets color changes only in android 2.2 and 2.3. In Android 4.0 and up it uses the standard widget color??? any ideas? solutions?

thanks for the help!

**Comment by Prototik** [comment]
Yea, values-v14 renamed to values-v11 :)
Try it.

**Comment by wildsvinja** [comment]
it works perfectly XD Thanks!

**Comment by NirpE** [comment]
Hello, currently there is values-v11 and values-v14 folders, so what do you need to do to get this working?

**Comment by NirpE** [comment]
Removing values-v11 solved it mostly, only ActionBar behaves different with new and old device.
