### ISSUE TITLE
Slider addon

### ISSUE THREAD

**Issue by tkiela** [Prototik/HoloEverywhere#473]
Hey. 

Since there is no documentation for the Slider adden, I am asking for some Help. 
I want to add an radiogroup in the Slider. How do I approach this? Thanks you in advance.

**Comment by BraisGabin** [comment]
[Stackoverflow](http://stackoverflow.com/) is your friend.

**Comment by tkiela** [comment]
I will ask there, if there's no satisfying answer here. Thankks.

**Comment by Prototik** [comment]
Slider addon just provide simplified interface for DrawerLayout now. You can place anything in left/right/center panels.  
res/layout/content.xml

``` xml
<?xml version="1.0" encoding="utf-8"?>
<DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@id/slider" >
    <FrameLayout
        android:id="@id/contentView"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
    <LinearLayout
        android:id="@id/leftView"
        android:layout_width="200dp"
        android:layout_height="match_parent">
        <TextView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="center"
            android:text="TEXT" />
    </LinearLayout>
</DrawerLayout>
```

Activity class:

``` java
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        final AddonSliderA slider = addon(AddonSlider.class);
        slider.setDrawerLayout(R.layout.content);
    }
```

**Comment by tkiela** [comment]
Thanks till here. But using this, I will get:

05-30 13:29:10.436: E/AndroidRuntime(10206): Caused by: org.holoeverywhere.addon.IAddonAttacher$AttachException: Couldn't attach addon org.holoeverywhere.addon.AddonSlider after init of object de.svennergr.radiosongs.NewTabSwipe@42711350
05-30 13:29:10.436: E/AndroidRuntime(10206):    at org.holoeverywhere.addon.IAddonBasicAttacher.addon(IAddonBasicAttacher.java:47)
05-30 13:29:10.436: E/AndroidRuntime(10206):    at org.holoeverywhere.app.Activity.addon(Activity.java:89)
05-30 13:29:10.436: E/AndroidRuntime(10206):    at de.svennergr.radiosongs.NewTabSwipe.onCreate(NewTabSwipe.java:93)
05-30 13:29:10.436: E/AndroidRuntime(10206):    at android.app.Activity.performCreate(Activity.java:5104)
05-30 13:29:10.436: E/AndroidRuntime(10206):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
05-30 13:29:10.436: E/AndroidRuntime(10206):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
05-30 13:29:10.436: E/AndroidRuntime(10206):    ... 11 more

```
@Override
public void onCreate(Bundle savedInstanceState){
    super.onCreate(savedInstanceState);

    final AddonSliderA slider = addon(AddonSlider.class);
    slider.setDrawerLayout(R.layout.main);
...
```

**Comment by Prototik** [comment]
``` java
@Addons(Activity.ADDON_SLIDER)
public class NewTabSwipe extends Activity  {
...
```

**Comment by tkiela** [comment]
Thanks again.
I can't open it by swiping from the left any more. What do I have to change?

EDIT:
Okay, sorry. My fault. I used a wrong ID in the XML-Layout. 

Everything is fine.

**Comment by httpdispatch** [comment]
Раньше при выдвижении слайдера контент съезжал вправо, сейчас контент остается, а слайдер рисуется поверх с оверлеем. Есть ли возможность настроить это поведение и использовать такой же эффект как был в предыдущих версиях HE?

**Comment by Prototik** [comment]
А хз, читай доки по DrawerLayout.

**Comment by httpdispatch** [comment]
@Prototik покопал немного. Подобный эффект обеспечивает SlidingPaneLayout, но в AddonSlider захардкожено использовать DrawerLayout

**Comment by httpdispatch** [comment]
В Youtube и G+ приложениях используется такой эффект, как был в предыдущих версиях HE, а не DrawerLayout почему-то
