### ISSUE TITLE
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo issue

### ISSUE THREAD

**Issue by giwrgos88** [Prototik/HoloEverywhere#475]
I'm having this issue when I'm including the holoeverywhere in my project

05-30 14:11:47.076: E/AndroidRuntime(25721): FATAL EXCEPTION: main
05-30 14:11:47.076: E/AndroidRuntime(25721): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.mixfm.cyprus.radio/com.mixfm.cyprus.radio.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.mixfm.cyprus.radio.MainActivity" on path: /data/app/com.mixfm.cyprus.radio-1.apk
05-30 14:11:47.076: E/AndroidRuntime(25721):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2106)
05-30 14:11:47.076: E/AndroidRuntime(25721):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
05-30 14:11:47.076: E/AndroidRuntime(25721):    at android.app.ActivityThread.access$600(ActivityThread.java:141)
05-30 14:11:47.076: E/AndroidRuntime(25721):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
05-30 14:11:47.076: E/AndroidRuntime(25721):    at android.os.Handler.dispatchMessage(Handler.java:99)
05-30 14:11:47.076: E/AndroidRuntime(25721):    at android.os.Looper.loop(Looper.java:137)
05-30 14:11:47.076: E/AndroidRuntime(25721):    at android.app.ActivityThread.main(ActivityThread.java:5041)
05-30 14:11:47.076: E/AndroidRuntime(25721):    at java.lang.reflect.Method.invokeNative(Native Method)
05-30 14:11:47.076: E/AndroidRuntime(25721):    at java.lang.reflect.Method.invoke(Method.java:511)
05-30 14:11:47.076: E/AndroidRuntime(25721):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
05-30 14:11:47.076: E/AndroidRuntime(25721):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
05-30 14:11:47.076: E/AndroidRuntime(25721):    at dalvik.system.NativeStart.main(Native Method)
05-30 14:11:47.076: E/AndroidRuntime(25721): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mixfm.cyprus.radio.MainActivity" on path: /data/app/com.mixfm.cyprus.radio-1.apk
05-30 14:11:47.076: E/AndroidRuntime(25721):    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
05-30 14:11:47.076: E/AndroidRuntime(25721):    at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
05-30 14:11:47.076: E/AndroidRuntime(25721):    at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
05-30 14:11:47.076: E/AndroidRuntime(25721):    at android.app.Instrumentation.newActivity(Instrumentation.java:1054)
05-30 14:11:47.076: E/AndroidRuntime(25721):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2097)
05-30 14:11:47.076: E/AndroidRuntime(25721):    ... 11 more

for example if i will use the Activity on the holo
import org.holoeverywhere.app.Activity;

how i can fix it?

**Comment by Prototik** [comment]
Problems with your build environment. If you are use Eclipse + ADT make sure that `Android Private Libraries` is checked in classpath menu.

**Comment by giwrgos88** [comment]
ok thanks a lot

**Comment by nadavati** [comment]
Hello Prototik,

Still am getting problem, Please me.

**Comment by Prototik** [comment]
Please you, right.

Well, provide basic info about your environment.
