### ISSUE TITLE
Holoeverywhere is not work any more with Android Action Bar Style Generator? 

### ISSUE THREAD

**Issue by giwrgos88** [Prototik/HoloEverywhere#476]
Hello i tried to use Android Action Bar Style Generator for a custom theme and i found out that i'm having a problem when i'm trying to execute the application. the error is 

05-30 15:34:41.423: E/AndroidRuntime(299): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mixfm.cyprus.radio/com.mixfm.cyprus.radio.MainActivity}: android.support.v4.app._HoloActivity$HoloThemeException: You must apply Holo.Theme, Holo.Theme.Light or Holo.Theme.Light.DarkActionBar theme on the activity (MainActivity) for using HoloEverywhere

I'm using the Holoeverywhere together with the Sherlock ActionBar 4.3.1. I saw this http://android-holo-colors.com/
buts it's too complicated from the Android Action Bar Style Generator.
Any help? thank you

**Comment by Prototik** [comment]
Describe yours steps for integrating HE + Android Holo Colors.

**Comment by giwrgos88** [comment]
it doesn't have the ui that the Android Action Bar Style Generator has and you know what you color you are changing.

**Comment by giwrgos88** [comment]
here is my style

```
<style name="Theme.Mixfmradio" parent="Theme.Sherlock.Light">
    <item name="android:actionBarItemBackground">@drawable/selectable_background_mixfmradio</item>
    <item name="android:popupMenuStyle">@style/PopupMenu.Mixfmradio</item>
    <item name="android:dropDownListViewStyle">@style/DropDownListView.Mixfmradio</item>
    <item name="android:actionBarTabStyle">@style/ActionBarTabStyle.Mixfmradio</item>
    <item name="android:actionDropDownStyle">@style/DropDownNav.Mixfmradio</item>
    <item name="android:actionBarStyle">@style/ActionBar.Solid.Mixfmradio</item>
    <item name="android:actionModeBackground">@drawable/cab_background_top_mixfmradio</item>
    <item name="android:actionModeSplitBackground">@drawable/cab_background_bottom_mixfmradio</item>
    <item name="android:actionModeCloseButtonStyle">@style/ActionButton.CloseMode.Mixfmradio</item>


</style>
```

and in the manifest i have this
android:theme="@style/Theme.Mixfmradio"

**Comment by Prototik** [comment]
Change parent to Holo.Theme.Light.
