### ISSUE TITLE
Black Background and Black text on Options Menu on Ginger Bread and below with Light.DarkActionBar Theme

### ISSUE THREAD

**Issue by jcampbell05** [Prototik/HoloEverywhere#477]
I used a previous version of this Library and the option menu used to be white with dark text on Gingerbread with the Light.DarkActionBarTheme but recently its changed to black with dark text which makes it impossible to read.

**Comment by Prototik** [comment]
![screenshot from 2013-05-31 11 20 38](https://f.cloud.github.com/assets/1416030/588949/4a665974-c9a1-11e2-9cc8-1813b5542579.png)
Eclair, Gingerbread.

Ginger has an incorrect screen dpi, i know :D

**Comment by jcampbell05** [comment]
This was on a device, not the simulator.

I had to manually override the styles.

**Comment by Prototik** [comment]
@jcampbell05 if are you can provide screen from device with latest demo (download link on mainpage) with broken colors - bug of library. If not - your problems.

**Comment by jcampbell05** [comment]
Okay I'll give it a go.
