### ISSUE TITLE
Change Dialogue title blue line

### ISSUE THREAD

**Issue by bencallis** [Prototik/HoloEverywhere#478]
Is it possible to change the blue line under the title of an alert dialogue?

I have had a look through the XML and it appears to be set in the alert_dialog_holo.xml file. However, if I change it directly here to another colour it still appears blue.

I know it is non-trivial to change in Android 4.0 but would it be possible to add a method or provide a style to make it easily changeable?

**Comment by Prototik** [comment]
``` xml
<style name="MyTheme" parent="Holo.Theme">
  <item name="alertDialogTheme">@style/MyAlertDialogTheme</item>
</style>
<style name="MyAlertDialogTheme" parent="Holo.Theme.Dialog.Alert">
  <item name="alertDialogTitleDividerColor">@color/holo_green_light</item>
</style>
```

**Comment by bencallis** [comment]
Error: No resource found that matches the given name: attr 'alertDialogTitleDividerColor'.

```
<style name="Theme_LightDialog" parent="Holo.Theme.Dialog.Alert">
    <item name="alertDialogTitleDividerColor">@color/hukd_orange</item>
</style>
```

**Comment by Prototik** [comment]
Update library, i'm push commit with this feature 10 minutes ago.

**Comment by bencallis** [comment]
Ah OK. Thanks very much :)

**Comment by bencallis** [comment]
Should this also work for normal dialogues?

**Comment by Prototik** [comment]
No.

**Comment by bencallis** [comment]
Would it be possible to add this to a future update?

**Comment by Prototik** [comment]
Noooo.

**Comment by bencallis** [comment]
Why's that? That's a shame.

**Comment by Prototik** [comment]
Because I said so.  
For this it is necessary to alter the existing flawed implementation of Dialog.  
Two options:
- You do it yourself.
- You pay me for it, because I need to eat, rest, resources for developing. My girl too.

AlertDialog looks absolutely like Dialog, why not it?

**Comment by bencallis** [comment]
Which XML file is the dialogue blue bar defined in?

**Comment by Prototik** [comment]
Nowhere. HoloEverywhere now doesn't patch dialog layout.  
Funny, yea?

**Comment by bencallis** [comment]
Thanks for your help. I just created a custom XML. I didn't realise HoloEverywhere does not patch the default dialog layout.
