### ISSUE TITLE
android:fontFamily="sans-serif-light" not working anymore

### ISSUE THREAD

**Issue by lukrop** [Prototik/HoloEverywhere#480]
If i specify android:fontFamily="sans-serif-light" in a TextView in a layout .xml file it doesn't display the Roboto Light Font on Android 4.1+ anymore. This worked sometime ago, haven't updated in a while but now it doesn't work anymore.

Edit: Also specifing android:fontFamily="sans-serif-light" in the AppTheme gets overwritten somehow. You can see that the Roboto Light font is loaded in the application title (ActionBar, just for a half second) but as soon as the app is initialized it gets overwritten with standard Roboto.

**Comment by Prototik** [comment]
In 0a04b97 i'm fully rewrite a FontLoader.
Now you can use `android:fontFamily="roboto-light"` (or `sans-serif-light`, or even simply `light`, or `thin`, or ...) and all other roboto fonts even on 2.1+. But for it you should just place a ttf file in `project/res/raw` folder
In this comment i attach `HoloEverywhere Resource Palette` project, see `res/layout/activity_main.xml` and `res/raw` folder.
![device-2013-06-05-203304](https://f.cloud.github.com/assets/1416030/611702/912db1e2-cddc-11e2-9c0e-b2ebe3b2c50a.png)  
[Sources on GDrive](https://docs.google.com/file/d/0BxcxDFWRyauQQnhOR1p4cVdYSm8/edit?usp=sharing)  
[APK](https://docs.google.com/file/d/0BxcxDFWRyauQSEtRRzNlTjJwZmM/edit?usp=sharing)

**Comment by lukrop** [comment]
Hey man! First of all, you are doing a really, really great job on maintaining this library! Big kudos! :)

I don't want to be a PITA but it isn't really working for me with roboto-*. I even compiled your demo and launched it in  a 2.3.3 emulator and it doesn't work :(

I'm using gradle and the newest Android Studio. I know HoloEverywhere isn't supporting gradle as of yet until AS is stable. But since everything else is working perfectly I don't think it has something to do with my build environment.
![screenshot from 2013-06-05 21 32 01](https://f.cloud.github.com/assets/68344/614155/a009cc70-ce16-11e2-83e3-e24c4c6a3a66.png)

Edit: OK, just opened your parent.iml file from the git repo with android studio. Compiled it using maven from within the IDE since AS is essentially IntelliJ IDEA. But it looks like I can't seem to get the Font of the HoloEverywhere Demo About page to Roboto Light. I tried "sans-serif-light", "light", "roboto-light". And yes, I have roboto_light.ttf in res/raw.

So it isn't a problem with gradle after all it seems to me.

**Comment by waninkoko** [comment]
The new font loader isn't working for me too.

I'm using 'FontLoader.apply(view, FontLoader.ROBOTO_LIGHT)' to use Roboto Light font in a view (I have the TTF file in res/raw and with the old font loader works) and doesn't work... Even I think the text appears with Roboto Bold instead.

If I have some free time I'll try to help looking into this issue.

**Comment by Prototik** [comment]
Try the latest master with fix by @restorer (btw thanks).
![screenshot from 2013-06-08 14 44 17](https://f.cloud.github.com/assets/1416030/627190/2785f77c-d007-11e2-8bc0-751e7b547020.png)

**Comment by Prototik** [comment]
[Demo APK built by travis-ci](https://oss.sonatype.org/content/repositories/snapshots/org/holoeverywhere/demo/1.6.2-SNAPSHOT/demo-1.6.2-20130608.105037-5-aligned.apk)

**Comment by lukrop** [comment]
It works for me now too. But if I want to style the SliderMenu items using a custom textAppearance attribute applying fonts through xml doesn't work. Maybe related to this issue?

**Comment by Prototik** [comment]
@lukrop Test it please with the latest master version.
But modifying a origin layout has no effect. Text appearance for textview in layout present is two attrs:
textAppearanceSliderItem and textAppearanceSliderItemInverse. You can customize text appearance like this:

``` xml
<style name="CustomSliderTheme" parent="Holo.Internal.SliderTheme">
  <item name="textAppearanceSliderItem">@style/CustomTextAppearanceSliderItem</item>
  <item name="textAppearanceSliderItemInverse">@style/CustomTextAppearanceSliderItem.Inverse</item>
</style>
<style name="CustomSliderTheme.Light" parent="Holo.Internal.SliderTheme.Light">
  <item name="textAppearanceSliderItem">@style/CustomTextAppearanceSliderItem.Light</item>
  <item name="textAppearanceSliderItemInverse">@style/CustomTextAppearanceSliderItem.Inverse.Light</item>
</style>
```

Application static codeblock:

``` java
SliderMenu.map(R.style.CustomSliderTheme, R.style.CustomSliderTheme_Light);
```

**Comment by lukrop** [comment]
@Prototik Thanks! That worked! Just for the record, if you are creating SliderItem instances and set custom layouts etc. make sure you don't set the textAppearance programmatically on the object.

**Comment by ghost** [comment]
hi, if I just want this feature (the fonts), should I import all the library?
Also, what's the correct `gradle compile '...'` line for HoloEverywhere with ActionBarCompact support?
Thank you.

**Comment by Prototik** [comment]
@domenicop if you want the fonts - do it! But this library too big for using it as a font engine.
You can manually cut off FontLoader from library or find a more suitable solution for your targets.

And you cannot build HoloEverywhere with ABS via gradle, no one version of this library never support gradle+abs build variation. Only maven+abs and gradle+abc, choose one please.
