### ISSUE TITLE
Dialogs shown wrong, content part is missing

### ISSUE THREAD

**Issue by restorer** [Prototik/HoloEverywhere#484]
One of testers of my game has problems with dialogs. I told him to install holoeverywhere demo application (demo-1.6.1-aligned.apk) and take some screenshots.

Dialogs shown wrong - wrong width, height and buttons:

![holoeverywhere-demo-1](https://f.cloud.github.com/assets/85473/617738/d068b7e4-ce9f-11e2-9c93-48d4fc86b181.png)

Same for white theme:

![holoeverywhere-demo-2](https://f.cloud.github.com/assets/85473/617739/d866ec72-ce9f-11e2-9cd5-5bd4ba7f6a88.png)

In my game situation is even worse - content not shown at all (I use setView() with custom view):

![my-game-1](https://f.cloud.github.com/assets/85473/617740/de29cd00-ce9f-11e2-8333-f64cf745e425.png)

Wrong height if no content set:

![my-game-2](https://f.cloud.github.com/assets/85473/617742/e8bce1a8-ce9f-11e2-9667-b697deccfca3.png)

Content not shown at all:

![my-game-3](https://f.cloud.github.com/assets/85473/617743/ef385dd2-ce9f-11e2-970a-eb0ece759dcd.png)

He has Sony Xperia Arc with Android 2.3.3:

![xperia-arc-version](https://f.cloud.github.com/assets/85473/617746/f81d644c-ce9f-11e2-9596-06a6953437ba.png)

I can't reproduce this bug with my devices (Huawei U9508 with Android 4.0.4, Samsung Galaxy Tab 2 10.1 with Android 4.0.3 and even Samsung Galaxy Spica with android 2.2), not with devices of my friends (HTC Hero 2 with Android 2.X, and some chinese tablet also with android 2.X)

Any suggestions? I can add logging into my game and holoeverywhere library, and tester can send me logcat, but at the current moment I have no idea where to add logging.

**Comment by Prototik** [comment]
Well...
Fucked Sony.
No, i like Sony. Really.
But sometimes Sony make Android /very/ customized.

I have only Sony U20i with stock 2.1, CM6-7 (2.2-2.3) and CM10 (4.2) - i also cannot reproduce bug.
Tomorrow i make some debug apk, this tester should run it once. Maybe. Or not once.

**Comment by restorer** [comment]
Forgot to say: with very old version of holoeverywhere (with com.WazaBe package) dialogs shown correctly.

**Comment by maiys** [comment]
I've met this problem too, on my Sony X10i which runs Android 2.3.3, sony customized rom, could you tell me how to fix this problem? thanks a lot.

**Comment by zenyagami** [comment]
that's a shame, actually i tried on emulator, i test in a sony as well, this bug only affect sony devices with gb?there is any workaround? available?

**Comment by antonyt** [comment]
I have seen this problem on the Sony Xperia Acro (http://en.wikipedia.org/wiki/Sony_Ericsson_Xperia_acro) when running Android 2.3.x. I have not seen this problem on any 4.x Sony device.

The problem is caused by the HoloEverywhere LinearLayout. I am not sure exactly where, but in any case, disabling it causes the layout to render with proper dimensions. To disable the LinearLayout only, you can call LayoutInflater.register(...) with your own LinearLayout class (e.g. the default one), which will take priority. You also need to update all of the existing references to the HoloEverywhere LinearLayout to point to your new LinearLayout class (or the default parent class). I only do this for 2.x Sony devices.

Finding the root cause is obviously the best fix but I have not been able to spend enough time with the device either.

FYI: There is a (paid, in Japanese only) testing service called Remote Testkit (appkitbox.com/testkit) which has devices which exhibit this problem.

**Comment by tomekziel** [comment]
Is it possible to speed up bugfixing of this issue with a donation or sth?

**Comment by Prototik** [comment]
@tomekziel Only if donations will enough for Xperia device :) I have only one Sony device with 2.3.7/4.1 - and i cannot reproduce this bug on this versions.

**Comment by tomekziel** [comment]
Hi Sergey!

Would it be enough to provide you access to Testdriod Cloud with Xperia?
Not as convenient as real device, but still something:
http://testdroid.com/product/testdroid-cloud#0

Tomek

On 6 November 2013 16:48, Sergey Shatunov notifications@github.com wrote:

> @tomekziel https://github.com/tomekziel Only if donations will enough
> for Xperia device :) I have only one Sony device with 2.3.7/4.1 - and i
> cannot reproduce this bug on this versions.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Prototik/HoloEverywhere/issues/484#issuecomment-27884410
> .

## 

Tomek Z.
tomasz.zielinski@gmail.com

**Comment by Prototik** [comment]
Which your relations with testdroid?  Or you just provide link to me?)
Okay, i'll see this tommorow.

**Comment by tomekziel** [comment]
On 6 November 2013 17:06, Sergey Shatunov notifications@github.com wrote:

> Which your relations with testdroid? Or you just provide link to me?)
> Okay, i'll see this tommorow.
> 
> Please create account (and try the trial devices), send me username and I
> will provide you access to devices where problem can be spotted.

## 

Tomek Z.
tomasz.zielinski@gmail.com

**Comment by nicogiagnoni** [comment]
Same problem here (MercadoLibre App), we are on Holo 1.4.3, and it has memory leaks problems (IAddon class). I've migrated to 2.1 but here in LATAM Sony has a big share of Android Devices, so we cannot use that version because we use many DialogFragments.

**Comment by Prototik** [comment]
@tomekziel 
Testroid cannot provide me a full access to devices (with debug, adb, etc).
Only tests not enough for solving this issue.

**Comment by nicogiagnoni** [comment]
Can I help you with something (Logs, measured sizes dump, anything)? I've an Xperia Mini Pro in my possession and I can reproduce this bug easily.

Here in Argentina, and probably in the rest of LATAM, Xperia devices has enough share to make this bug important to avoid last versions of HE.

Regards,

**Comment by Prototik** [comment]
Well, you can connect to my vpn network (from phone) and allow remote access. Then i can try to fix it.

**Comment by nicogiagnoni** [comment]
Ok, I can do that, contact me if you want by my mail, to provide me your VPN info.

Remote access will provide you ADB integration?

**Comment by ghost** [comment]
http://stackoverflow.com/questions/20729326/holoeverywhere-dialog-wrong-layout-sony-xperia-neo-v-2-3-x I did some hack to use relative instead linear but I am not able to fix >measureVertical< in your linearlayout, but I am sure there is something wrong with counting height. On sony I gets only itle and the rest is gone. I would need much time to fix it but it's very heavy to understand it in few hours.. `I will give you 10E if you fix it xD - ok I'm kidding :)`

**Comment by ksennoun** [comment]
Anything new about this?

**Comment by hungnguyen-vn** [comment]
@Prototik anything new with this?

**Comment by lgawin** [comment]
@all_interested: there's a fix candidate for the issue available on my branch (#816). 

It solved most of the problems we had with our application running on some 2.3.x Android powered Sony Xperia device (I don't have device details atm), which was the most p.i.t.a. device in our project and the main source of bad reviews. Now it seems to work! HoloEverywhere demo application also seems to look and behave better.

But I'd still appreciate more evidences...please check your applications with that build if possible.

Thanks in advance!
