### ISSUE TITLE
AdapterView.OnItemClickListener

### ISSUE THREAD

**Issue by andrew-boyarshin** [Prototik/HoloEverywhere#486]
I use this code for setting ItemClickListener, but it doesn't want to work, it offers to cast HoloEverywhere AdapterView.OnItemClickListener to Android AdapterView.OnItemClickListener. I need it for working components of my app. Do I do something wrong?

``` Java
org.holoeverywhere.widget.ListView lv = (org.holoeverywhere.widget.ListView) getListView();
lv.setTextFilterEnabled(true);
org.holoeverywhere.widget.AdapterView.OnItemClickListener lis = new org.holoeverywhere.widget.AdapterView.OnItemClickListener() {
    public void onItemClick(org.holoeverywhere.widget.AdapterView<?> parent, View view, int position, long id) {
        //work!
    }
};
((org.holoeverywhere.widget.ListView)lv).setOnItemClickListener(lis);
```

**Comment by restorer** [comment]
HoloEverywhere's ListView extends android's ListView, you don't need cast listView to org.holoeverywhere.widget.ListView.

This works successfully in my application:

``` java
import android.widget.AdapterView;
import android.widget.ListView;

...

itemsList = (ListView)viewGroup.findViewById(R.id.items);

...

itemsList.setOnItemClickListener(new AdapterView.OnItemClickListener() {
    @Override
    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
        Store.CATEGORIES[storeCategory][position].run(profile, activity, storeCategory, position);
    }
});
```

**Comment by andrew-boyarshin** [comment]
But is HoloEverywhere's ListView adds more features? I use fast scrolling and something more. Will it be able in it?
P.S. I forgot, I use ListActivity.

**Comment by restorer** [comment]
It will be HoloEverywhere's ListView, and it is no problem if you use ListActivity.
Just try :)

**Comment by andrew-boyarshin** [comment]
Thanks, it works.
