### ISSUE TITLE
Unable to create SliderMenu with tabs

### ISSUE THREAD

**Issue by mehdifanai** [Prototik/HoloEverywhere#487]
First i want to thank you for your great effort in this project.
i am using holoeverywhere+ABS+ViewPager.i have a mainactivity with 3 actionbar tabs(fragments) in it and i need to implement  slider addon to my project which switches between mainactivity and a second activity. I tried to reverse engineer but i noticed that you are using a main activity with fragments in it(all slider items are fragments and not activities). I dont know how i can setup slidermenu in my main activity which already has fragments in it.

here is my activitie's onCreate():

```
    tabs = getResources().getStringArray(R.array.tabs);
    pager = ((CustomViewPager) findViewById(R.id.pager));
    pager.setOffscreenPageLimit(3);
    adapterViewPager = new AdapterViewPager(getSupportFragmentManager(),
            tabs);
    pager.setAdapter(adapterViewPager);
    pager.setOnPageChangeListener(this);
```

The link to my question in stackoverflow:
http://stackoverflow.com/questions/17014244/how-to-create-to-holoeverywhere-slidermenu-with-tabs
PS: can i use slidingmenu project with holoeverywhere? is yours better regarding compatibility with holoeverywhere?
Regards

**Comment by Prototik** [comment]
SliderMenu addon support only fragments.
But SliderMenu - only pre-built control view over Slider addon.
You can make /anything/ with /any/ view in /any/ hierarchy.
Just create your custom layout and place it in left (right) panel and provide control logic for it.
