### ISSUE TITLE
Menu Drawer

### ISSUE THREAD

**Issue by Zeliret** [Prototik/HoloEverywhere#490]
Я сделал все по гайду, дошел до момента, где нужно вызвать обработчик нажатия на home button:

``` java
 @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Pass the event to ActionBarDrawerToggle, if it returns
        // true, then it has handled the app icon touch event
        if (mDrawerToggle.onOptionsItemSelected(item)) {
          return true;
        }
        // Handle your other action bar items...

        return super.onOptionsItemSelected(item);
    }
```

И оказалось, что у меня доступен MenuItem из пакета Sherlock, тогда как метод объекта mDrawerToggle принимает родной MenuItem.

Поддержки нового виджета в шерлоке не нашел.
Есть вариант найти исходники этого меню и переопределить метод onOptionsItemSelected, чтобы научить его работать с MenuItem шерлоковским. 

Однако, может быть в HoloEverywhere уже планируется поддержка этого виджета? Есть какие-то новости? :)

**Comment by Prototik** [comment]
А можно еще много чего сделать, если честно. От выкидывания ABS до выкидывания андроида.
Если нужно только выезжание панельки по нажатию кнопки Home:

``` java
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                  addonSlider().toggle();
                break;
            default:
                return super.onOptionsItemSelected(item);
        }
        return true;
    }
```

Аль если не испльзуется slider аддон... Горько. Каждый день так странно горько.

``` java
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                if (mDrawerLayout.isDrawerVisible(Gravity.LEFT)) {
                    mDrawerLayout.closeDrawer(Gravity.LEFT);
                } else {
                    mDrawerLayout.openDrawer(Gravity.LEFT);
                }
                break;
            default:
                return super.onOptionsItemSelected(item);
        }
        return true;
    }
```

**Comment by Zeliret** [comment]
Благодарю. 
Думал воспользоваться слайдером, но не нашел документации, отложил, пока не будет время изучить по коду...
