### ISSUE TITLE
Roboguice addon

### ISSUE THREAD

**Issue by BraisGabin** [Prototik/HoloEverywhere#492]
HoloEverywhere with roboguice wanted to try but I just realized that it is not the addon. Have you dropped support?

**Comment by Prototik** [comment]
Maven:

``` xml
<dependency>
  <groupId>org.holoeverywhere</groupId>
  <artifactId>addon-roboguice</artifactId>
  <version>2.0</version>
  <type>apklib</type>
</dependency>
```

Eclipse: [repo](https://github.com/Prototik/HoloEverywhere-Addon-Roboguice)
