### ISSUE TITLE
Fragment instantiate deprecated

### ISSUE THREAD

**Issue by BraisGabin** [Prototik/HoloEverywhere#493]
Is there any reason why the calls [`Fragment.instantiate(Context, String)`](https://github.com/Prototik/HoloEverywhere/blob/master/library/src/org/holoeverywhere/app/Fragment.java#L40) and [`Fragment.instantiate(Context, String, Bundle)`](https://github.com/Prototik/HoloEverywhere/blob/master/library/src/org/holoeverywhere/app/Fragment.java#L46) are deprecated?

**Comment by Prototik** [comment]
Standart usecase of `Fragment.instantiate(Context, String)`:

``` java
Fragment f = Fragment.instantiate(context, MyFragment.class.getName());
```

Why not use just `Fragment.instantiate(MyFragment.class)`?

**Comment by BraisGabin** [comment]
I'm agree that is more easy. The problem is that I paste a StackOverflow's code and Eclipse warns me about a deprecation and the doc doesn't tell me an alternative.

I quickly found alternatives: `android.support.v4.app.Fragment.instantiate(Context, String)` or `org.holoeverywhere.app.Fragment.instantiate(Class<T>)` but I think that the changes at the API must be documented.

I would want to commit something like e5d19bb6e7a51b9be77ca14504752c398da1df5c to explain the reason of deprecation and give a alternative. This is the reason of the question.

**Comment by Prototik** [comment]
@BraisGabin okay.
