### ISSUE TITLE
ListView choiceMode 

### ISSUE THREAD

**Issue by Zeliret** [Prototik/HoloEverywhere#495]
Задал в xml атрибут android:choiceMode="singleChoice". 

Получил объект через findViewById. Приватное поле mChoiceMode равно нулю, а не тому значению, которое я установил в xml. Я что-то делаю не так или это баг?

**Comment by Prototik** [comment]
Кто-нибудь, подебажьте эту хрень, мне так влом...
Are you try to use latest version of master? @restorer provide fix for some things, was be merged into master 4-5 days ago.

**Comment by Prototik** [comment]
Все работает.
