### ISSUE TITLE
Bottom menu`s text color is black in Holo.Theme.Light.DarkActionBar

### ISSUE THREAD

**Issue by wildsvinja** [Prototik/HoloEverywhere#496]
Hi Sergey!

I`m using Holo.Theme.Light.DarkActionBar as my parent theme to my custom theme.
The OverFlow menu is working perfectly, dark background and white text. But on android 4.1 and 2.2 i get dark background and dark text than i use hardware menu button. i have spend two days trying to solve this problem but no luck. What i did is just changed the background to light and left the text dark but this is not a good solution. Any ideas how i can get white text?

thanks for your help!

**Comment by Prototik** [comment]
This bug happens on [latest demo](https://oss.sonatype.org/content/repositories/snapshots/org/holoeverywhere/demo/1.6.2-SNAPSHOT/demo-1.6.2-20130615.032157-11-aligned.apk)?

**Comment by wildsvinja** [comment]
If i set mixed theme to the demo all the menus have light background and black text, instead of dark background and white text.

**Comment by Prototik** [comment]
It's default behavior of Android.

**Comment by wildsvinja** [comment]
Ok thanks! but in that case how can i change the color on the text to white, I'm getting dark background but cant set the text color!

**Comment by Prototik** [comment]
> light background and black text

? How do you get dark background and dark color?

**Comment by wildsvinja** [comment]
in  themes.xml of HoloEverywhere Library you set this(look att the code below) values to the menu panel, and if use the default settings of Holo.Theme.Light.DarkActionBar i get dark menu colour with dark text, but clearly the text is set to white(Holo.TextAppearance)! I dont know what to do?



```
    <item name="android:panelBackground">@drawable/menu_hardkey_panel_holo_dark</item>
    <item name="android:panelColorBackground">#000000</item>
    <item name="android:panelColorForeground">@color/primary_text_holo_dark</item>
    <item name="android:panelFullBackground">@drawable/menu_background_fill_parent_width_holo_dark</item>
    <item name="android:panelTextAppearance">@style/Holo.TextAppearance</item>
    <!--End of block BackportBarDark-->
```

**Comment by Prototik** [comment]
This. Bug. Is. Happens. On. Latest. Demo?

**Comment by wildsvinja** [comment]
Not on the latest demo, but i have tried the latest library.
