### ISSUE TITLE
Switch onClick

### ISSUE THREAD

**Issue by superpopos** [Prototik/HoloEverywhere#498]
Hi

I've added a Switch button but the "onClick" function is not executed.
Is this a bug? Am I doing something wrong? This is my code:

``` xml
    <org.holoeverywhere.widget.Switch
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text=""
        app:textOn="@string/switch_on"
        app:textOff="@string/switch_off"
        android:onClick="toggleSwitch"
        style="@style/Holo.Switch" />
```

``` java
    public void toggleSwitch(View v) {
        Log.d("toggleSwitch", "toggleSwitch");
    }
```

Thanks!

**Comment by Prototik** [comment]
No, for switch you should use [setOnCheckedChangeListener](http://developer.android.com/reference/android/widget/CompoundButton.html#setOnCheckedChangeListener%28android.widget.CompoundButton.OnCheckedChangeListener%29)
