### ISSUE TITLE
RatingBar render glitches

### ISSUE THREAD

**Issue by BraisGabin** [Prototik/HoloEverywhere#501]
![device-2013-06-17-153141](https://f.cloud.github.com/assets/721244/662324/cf07e7c4-d752-11e2-8df7-b19f04358801.png)
![device-2013-06-17-153153](https://f.cloud.github.com/assets/721244/662326/cf35acb8-d752-11e2-892f-8472b2807dc4.png)
![device-2013-06-17-153201](https://f.cloud.github.com/assets/721244/662327/cf373f6a-d752-11e2-9cda-80aef71a13a2.png)
![device-2013-06-17-153221](https://f.cloud.github.com/assets/721244/662328/cf5fb2c4-d752-11e2-8f32-a3765b5086a0.png)

Demo 1.6.1, Nexus 4 (4.2.2)

**Comment by BraisGabin** [comment]
Never mind... This bug is native.

**Comment by Prototik** [comment]
But we are can fix it! :)

**Comment by Prototik** [comment]
Or we are can not fix it... Hardly.
