### ISSUE TITLE
Missing Fonts: roboto_light

### ISSUE THREAD

**Issue by AdamJB** [Prototik/HoloEverywhere#502]
Hi,

I tried running the Library, and found that roboto_light was missing from the Library. It's included in the demo, but it appears the library requires it.

The issue happens when I try using HoloEveryewhere's TextView and/or EditText.

In the HoloEverywhere Library, you'll notice most roboto_... in org.holoeverywhere.FontLoader are missing from the library res/raw folder, but are in the demo's res/raw folder.
- Adam

**Comment by HenriqueRocha** [comment]
The resources need to be in the main project. Not in the library project.

**Comment by Prototik** [comment]
New FontLoader yet not have stable codebase. After next release i'm provide detailed wiki pages about some parts of library, including FontLoader.

> you'll notice

Am I? Where?  
If I'm provide all roboto fonts in basic packaging of library then all projects increase size of apk ~1.5 MiB, even if you don't use this fonts. I don't want.
