### ISSUE TITLE
Create a 'gradle' branch

### ISSUE THREAD

**Issue by HenriqueRocha** [Prototik/HoloEverywhere#503]
Hi.
I've forked HE and added the necessary files to compile the demo project with Gradle.
Can you please upload a gradle branch so that I can do a pull request to that branch instead of master?
That way people can just use your gradle branch instead of using my repo.
Thanks.

**Comment by Prototik** [comment]
... Are you provide correctly gradle config for assembling in one command?
Without many actions for installing abs and some cool things...

**Comment by HenriqueRocha** [comment]
Yes, it assembles with one command if the developer has ActionBarSherlock inside his local Maven repository because it's needed by HE.
"gradle build" successfully builds the project and "gradle installDebug" builds and installs the apk of the demo project on the phone. You can try it with my repo.
I can also provide instructions in the wiki if you want.
As soon as ABS has an .aar in Maven Central the developer doesn't even need to have ABS in a local Maven repo.

**Comment by Prototik** [comment]
Commands for installing abs from `dev` into local maven repo?

**Comment by HenriqueRocha** [comment]
ABS has Gradle support in dev, so you just need to build ABS, move into the build/libs directory inside the actionbarsherlock directory and type this command:

`mvn install:install-file -Dfile=actionbarsherlock-4.3.2-SNAPSHOT.aar -DgroupId=com.actionbarsherlock -DartifactId=actionbarsherlock -Dversion=4.3.2 -Dpackaging=aar`

**Comment by Prototik** [comment]
Maybe are you provide support of [maven gradle plugin](http://www.gradle.org/docs/current/userguide/maven_plugin.html) for abs first?

btw thx for `gradle build`, i find solution two fucked days why `gradle assemble` not work :)

**Comment by HenriqueRocha** [comment]
When you create the gradle branch I'll do the pull request. I'll probably receive a notification when it's created.
Thanks. :)

**Comment by Prototik** [comment]
First: rebase your commits under `holoeverywhere-1.6.1` tag.
Second: make a pull request into master branch, after fix all bad places i'll merge it into need branch.
