### ISSUE TITLE
Wrong color icons in the contextual ActionBar

### ISSUE THREAD

**Issue by BraisGabin** [Prototik/HoloEverywhere#507]
Add this lines at the end of DemoActivity's onCreate

``` java
new AlertDialog.Builder(this).setView(new EditText(this)).show();
```

![device-2013-06-19-200811](https://f.cloud.github.com/assets/721244/676780/da17c4f2-d90c-11e2-8d85-8eb7f9060ed3.png)
![device-2013-06-19-200847](https://f.cloud.github.com/assets/721244/676781/da4de83e-d90c-11e2-9d93-00c029cfa0d8.png)

You can't see the icons because they are white. You only can see them when you click.

Happens with Holo Light and Mixed theme. With dark is all OK.

Another thing: I have not time to check now, but: The white contextual ActionBar is correct with mixed theme? I will check.

Version: 7832c19c30e8ecf1bccfc5f920f075152884a0bf Nexus 4 (4.2.2)

**Comment by BraisGabin** [comment]
F***! I wrote a comment yesterday but I think that I didn't click the "Comment" button...

The native behaviour is really strange and have bugs.

Two cases:
1. **Light theme**
   The icons must be dark. HE bug or ABS bug?
2. **Mixed theme**
   Native doesn't show them neither.
   ![device-2013-06-20-110011 copy](https://f.cloud.github.com/assets/721244/686284/71b0d7f2-da54-11e2-8d9b-2eac9b8c48ce.png)

The color of the context ActionBar I really don't know. In an Activity is dark but in an Dialog is light. I don't know if is the same bug or not...

I push a project to check this strange behaviour.

**Comment by Prototik** [comment]
![device-2013-07-05-133644](https://f.cloud.github.com/assets/1416030/752159/42e3ff12-e535-11e2-95a7-53d25e6b0b37.png)
Android 4.2.
For the mixed theme result is similar, because for edittext we're provide context with light theme, not dark or mixed.
