### ISSUE TITLE
SliderMenu and setRetainInstance

### ISSUE THREAD

**Issue by agrebnev** [Prototik/HoloEverywhere#508]
I would like to use the the method http://developer.android.com/reference/android/app/Fragment.html#setRetainInstance(boolean) and set true.

However according source code of  https://github.com/Prototik/HoloEverywhere/blob/master/addons/slider/src/org/holoeverywhere/slider/SliderMenu.java class and changePage(int position, SliderItem item) method it looks like that the new instance of Fragment is created every time when I use slider menu. In this case it is impossible to retain the fragment instance.

Probably it will be better to check the existence of fragment instance before creation of new one.

**Comment by Prototik** [comment]
Try fix from `fix-508` branch.

**Comment by agrebnev** [comment]
Now I have the following error 

E/AndroidRuntime( 2997): FATAL EXCEPTION: main
E/AndroidRuntime( 2997): java.lang.IllegalStateException: Fragment already active
E/AndroidRuntime( 2997):        at android.support.v4.app.Fragment.setInitialSavedState(Fragment.java:523)
E/AndroidRuntime( 2997):        at android.support.v4.app._HoloFragment.setInitialSavedState(_HoloFragment.java:276)
E/AndroidRuntime( 2997):        at org.holoeverywhere.slider.SliderMenu.changePage(SliderMenu.java:503)
E/AndroidRuntime( 2997):        at org.holoeverywhere.slider.SliderMenu.setCurrentPage(SliderMenu.java:623)
E/AndroidRuntime( 2997):        at org.holoeverywhere.slider.SliderMenu.access$3(SliderMenu.java:614)
E/AndroidRuntime( 2997):        at org.holoeverywhere.slider.SliderMenu$SliderMenuAdapter.onItemClick(SliderMenu.java:240)
E/AndroidRuntime( 2997):        at android.widget.AdapterView.performItemClick(AdapterView.java:298)
E/AndroidRuntime( 2997):        at android.widget.AbsListView.performItemClick(AbsListView.java:1086)
E/AndroidRuntime( 2997):        at org.holoeverywhere.widget.ListView.performItemClick(ListView.java:677)
E/AndroidRuntime( 2997):        at android.widget.AbsListView$PerformClick.run(AbsListView.java:2855)
E/AndroidRuntime( 2997):        at android.widget.AbsListView$1.run(AbsListView.java:3529)
E/AndroidRuntime( 2997):        at android.os.Handler.handleCallback(Handler.java:615)
E/AndroidRuntime( 2997):        at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 2997):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 2997):        at android.app.ActivityThread.main(ActivityThread.java:4745)
E/AndroidRuntime( 2997):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2997):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 2997):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime( 2997):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 2997):        at dalvik.system.NativeStart.main(Native Method)

It does not depend on the value of setRetainInstance.

**Comment by OS-Chris** [comment]
Didn't notice your comment before posting my issue. Sorry about that.

From the API docs: "This can only be used with fragments not in the back stack. If set, the fragment lifecycle will be slightly different when an activity is recreated". I might be mistaken but unless you have a basic app, this may not be the way to go.

IMO, find a tutorial on "onSaveInstanceState" and save your state manually for complete control. My app was saving & reloading perfectly before Fix #508 was uploaded (no big deal, I just reverted that commit).
