### ISSUE TITLE
Wrong fonts

### ISSUE THREAD

**Issue by TheNephilim88** [Prototik/HoloEverywhere#509]
After updating to the current HE-Version my defined bold-textstyles are getting ignored.

For example:

``` xml
<TextView
            android:id="@+id/textView1"
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:textAppearance="?android:attr/textAppearanceMedium"
            android:textColor="?attr/listheader_colorstates"
            android:textIsSelectable="false"
            android:textStyle="bold" />
```

Will be shown as italic text and not as bold.

Any suggestions?

**Comment by Prototik** [comment]
![screenshot from 2013-07-02 16 15 02](https://f.cloud.github.com/assets/1416030/735287/e3069a88-e2ef-11e2-8fb2-a6917499625c.png)

Yea, i have one suggestion: Check ALL... TWICE before reporting a issue.

**Comment by TheNephilim88** [comment]
Yeah yeah, but people are reporting their issues here not for fun or to annoy you...

But I found probably the problem:
I simply copied all fonts from the demo-projects raw-folder and noticed: if I put roboto_black.ttf AND roboto_blackitalic.ttf to the raw-folder, then the bold-style is screwed. By deleting one or both of them resolves the problem and the text is bold again...

**Comment by stefan222** [comment]
Had a very similar problem. Suddenly all texts (action bar, TextViews, EditTexts, Spinners, etc.) were italic. Removed "roboto_blackitalic.ttf", removed italic attributes from XML and used "setTypeface(null, Typeface.ITALIC)" in code instead. Works fine now, but I agree with reneph that something really weird happened here.
