### ISSUE TITLE
Problem loading Roboto fonts in Android 4.2.2

### ISSUE THREAD

**Issue by HenriqueRocha** [Prototik/HoloEverywhere#511]
There seems to be a problem in the font loading process because I've just created a Hello World project with two TextView, one without fontFamily and one with fontFamily="roboto-light" and it works fine in Android 2.2 emulator but it doesn't work on my Nexus 4 with Android 4.2.2.
I'm testing with the updated master branch.
Thanks.

![device-2013-06-23-003701](https://f.cloud.github.com/assets/140122/691488/60be0094-db8c-11e2-9125-3bbcc23c8e3e.png)

![device-2013-06-23-003732](https://f.cloud.github.com/assets/140122/691489/6c0e1010-db8c-11e2-9cb5-aa6c6d15dd8d.png)

**Comment by Imara** [comment]
Try using android:fontFamily="light" instead of fontFamily="roboto-light".
Solved the problem for me.

**Comment by HenriqueRocha** [comment]
Still doesn't work for me. It's very strange because it works in the demo.

**Comment by Prototik** [comment]
![screenshot from 2013-11-02 11 52 22](https://f.cloud.github.com/assets/1416030/1458454/4137f3c6-4372-11e3-9f0b-e2c38c7388ad.png)

_It's randomly fixed, but it's fixed._
