### ISSUE TITLE
SliderMenu causes crash on page change when initialState is not null

### ISSUE THREAD

**Issue by OS-Chris** [Prototik/HoloEverywhere#516]
Happens if your on 1 fragment, you switch to another (and the state of the 1st one is saved), then you return to the first fragment.

java.lang.IllegalStateException: Fragment already active
android.support.v4.app.Fragment.setInitialSavedState(Fragment.java:523)
android.support.v4.app._HoloFragment.setInitialSavedState(_HoloFragment.java:276)
org.holoeverywhere.slider.SliderMenu.changePage(SliderMenu.java:508)

Edit: solved by reverting to before commit 63aeb44bc43af6d1cbd7228d9974a548829e2e0d
Though I have to manual save UI state, my app works great (storing & reloading state) before that commit.

**Comment by agrebnev** [comment]
See also https://github.com/Prototik/HoloEverywhere/issues/508
