### ISSUE TITLE
java.lang.IllegalArgumentException: bitmap size exceeds 32bits

### ISSUE THREAD

**Issue by Tigre-K** [Prototik/HoloEverywhere#521]
in Activity:

``` java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_user);
        if (savedInstanceState == null) {
             switchPage(new FragmentList(), false);
        }
    }

public void switchPage(Fragment fragment, boolean add) {
        FragmentManager fm = getSupportFragmentManager();
        FragmentTransaction ft = fm.beginTransaction().setCustomAnimations(
                R.anim.page_in, R.anim.page_out, R.anim.page_pop_in,
                R.anim.page_pop_out);
        ft.replace(R.id.contentView, fragment);
        if (add) {
            ft.addToBackStack(null);
        } else {
            fm.popBackStack(null, FragmentManager.POP_BACK_STACK_INCLUSIVE);
        }
        ft.commit();
    }
```

R.layout.activity_user = FrameLayout

in FragmentList:
only ListView

if I fist show FragmentList - FatalError. If I first show another fragment, then FragmentList - its good.

06-28 10:49:36.522: E/AndroidRuntime(2675): java.lang.IllegalArgumentException: bitmap size exceeds 32bits
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.graphics.Bitmap.nativeCreate(Native Method)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.graphics.Bitmap.createBitmap(Bitmap.java:477)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.view.View.buildDrawingCache(View.java:6577)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.view.ViewGroup.onAnimationStart(ViewGroup.java:1259)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.view.ViewGroup.drawChild(ViewGroup.java:1505)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.view.View.draw(View.java:6883)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.widget.FrameLayout.draw(FrameLayout.java:357)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.view.View.draw(View.java:6883)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.view.View.draw(View.java:6883)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.widget.FrameLayout.draw(FrameLayout.java:357)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1862)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.view.ViewRoot.draw(ViewRoot.java:1522)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.view.ViewRoot.performTraversals(ViewRoot.java:1258)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.view.ViewRoot.handleMessage(ViewRoot.java:1859)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.os.Handler.dispatchMessage(Handler.java:99)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.os.Looper.loop(Looper.java:123)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at android.app.ActivityThread.main(ActivityThread.java:3683)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at java.lang.reflect.Method.invokeNative(Native Method)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at java.lang.reflect.Method.invoke(Method.java:507)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
06-28 10:49:36.522: E/AndroidRuntime(2675):     at dalvik.system.NativeStart.main(Native Method)

**Comment by TheNephilim88** [comment]
+1
Have some (only a few!) crash reports with pretty the same stacktrace, too. But cant reproduce...

**Comment by Tigre-K** [comment]
I try sent simple example with crash.

**Comment by sohayb** [comment]
I have the same problem when testing on Android 2.3.3!!

**Comment by tomekziel** [comment]
I had the same issue with animation which modified height of a view like this:

```
view.getLayoutParams().height = newHeight;
view.requestLayout();
```

As a workaround I disabled animation for 2.x devices.

**Comment by Prototik** [comment]
Argh. Hardware/software limitations. Like @tomekziel said, you can disable some animations or other hard things.
