### ISSUE TITLE
Widget Switch doesn't allow xml track

### ISSUE THREAD

**Issue by BraisGabin** [Prototik/HoloEverywhere#522]
If I set a xml drawable as Switch's track the widgets becomes "invisible".

``` xml
<org.holoeverywhere.widget.Switch
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    holo:track="@drawable/bg_switch_track" />
```

`bg_switch_track.xml:`

``` xml
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle" >

    <solid android:color="#ffffff" />

    <stroke
        android:width="1dp"
        android:color="#000000" />

</shape>
```

*_Edit: *_ The sames happens with a color `holo:track="@android:color/transparent"`

There isn't problem with a xml thum.

**Comment by Prototik** [comment]
Mmm.. this works with native switch?

**Comment by BraisGabin** [comment]
No, it doesn't. Close this if it is not easy to fix, use nine-patch is not a drama.

**Comment by Prototik** [comment]
Well, try to specify size by `<size>` node in shape

**Comment by BraisGabin** [comment]
Fixed! You're a genius ;)
