### ISSUE TITLE
DropDown menu background color issue

### ISSUE THREAD

**Issue by andresmafra** [Prototik/HoloEverywhere#523]
Hi everyone,

I´m using the HoloEveryWhere theming on my app, the theme choosed is "Holo.Theme.Light.DarkActionBar".

The problem is when I change between one activity to another, the color of the text of the menu item change his color to dark.

When my activity extends a class from _com.actionbarsherlock.app._ like _com.actionbarsherlock.app.SherlockFragmentActivity_ it is ok, but when I extends _org.holoeverywhere.app_ like _org.holoeverywhere.app.Activity_ it causes the issue.

Have you know what is this issue?

**Comment by Prototik** [comment]
More details. Is it options menu? Overflow menu? Library version, os version, device info?

**Comment by andresmafra** [comment]
Yes, it is options menu.

The library version is 1.5.1.
I´ve testing on Android  2.2 and 4.1. (Samsung Galaxy S and Motorola Razr D1).

If you need more details please tell me.

**Comment by Prototik** [comment]
Are you not want to try 1.6.0 version?

**Comment by andresmafra** [comment]
I'll try and retest the scenario..

**Comment by ludw** [comment]
We also have this issue, even with latest snapshot of holoeverywhere.

**Comment by andresmafra** [comment]
The problem was the class I was extending in my activities. When I extend SherlockFragmentActivity it is ok, but any other different, the problem happens. I managed extending only SherlockFragmentActivity.
