### ISSUE TITLE
findpreference returns null

### ISSUE THREAD

**Issue by mehdifanai** [Prototik/HoloEverywhere#525]
findpreference(R.id.myprefid) always returns null in my holoeverywhere preferenceActivity.I was unable to find an example for findpreference. Here is my preference xml:

```
  <?xml version="1.0" encoding="utf-8"?>
 <PreferenceScreen xmlns:holo="http://schemas.android.com/apk/res-auto"
 xmlns:android="http://schemas.android.com/apk/res/android" >

<EditTextPreference
    holo:id="@+id/examiner_preference"
    android:inputType="textCapWords|textPersonName"
    holo:dialogTitle="@string/examiner_dialogTitle"
    holo:key="examiner_preference"
    holo:summary="@string/examiner_summary"
    holo:title="@string/examiner_name" />
<EditTextPreference
    holo:id="@+id/email"
    android:inputType="textEmailAddress"
    holo:dialogTitle="@string/prefs__title"
    holo:key="acra.user.email"
    holo:summary="@string/pref_a_summary"
    holo:title="@string/pref_aemail" />

  </PreferenceScreen>
```

I did everything suggested in this issue: https://github.com/Prototik/HoloEverywhere/issues/212  but still no success.

Please either suggest a solution or reference an example app which uses holoeverywhere's findpreference(). (I couldn't find one in demo app)
  here is the link to my question on stackoverflow: http://stackoverflow.com/questions/17410913/how-to-findpreference-in-holoeverywhere

**Comment by Prototik** [comment]
You shouldn't use id and key together. Choose only one.
