### ISSUE TITLE
FontLoader Error on 2.2

### ISSUE THREAD

**Issue by dbacinski** [Prototik/HoloEverywhere#527]
Holo 1.6.1
Android 2.2.2 HTC Desire

07-02 11:43:21.515: E/FontLoader(12557): Error of loading font
07-02 11:43:21.515: E/FontLoader(12557): java.io.FileNotFoundException: /fonts/font_0x7f070003 (No such file or directory)
07-02 11:43:21.515: E/FontLoader(12557):    at org.apache.harmony.luni.platform.OSFileSystem.openImpl(Native Method)
07-02 11:43:21.515: E/FontLoader(12557):    at org.apache.harmony.luni.platform.OSFileSystem.open(OSFileSystem.java:152)
07-02 11:43:21.515: E/FontLoader(12557):    at java.io.FileOutputStream.<init>(FileOutputStream.java:97)
07-02 11:43:21.515: E/FontLoader(12557):    at java.io.FileOutputStream.<init>(FileOutputStream.java:69)
07-02 11:43:21.515: E/FontLoader(12557):    at org.holoeverywhere.FontLoader.readTypeface(FontLoader.java:267)
07-02 11:43:21.515: E/FontLoader(12557):    at org.holoeverywhere.FontLoader.readTypeface(FontLoader.java:275)
07-02 11:43:21.515: E/FontLoader(12557):    at org.holoeverywhere.FontLoader.loadTypeface(FontLoader.java:244)
07-02 11:43:21.515: E/FontLoader(12557):    at org.holoeverywhere.FontLoader$HoloFont.obtainTypeface(FontLoader.java:105)
07-02 11:43:21.515: E/FontLoader(12557):    at org.holoeverywhere.FontLoader.internalApply(FontLoader.java:219)
07-02 11:43:21.515: E/FontLoader(12557):    at org.holoeverywhere.FontLoader.internalApply(FontLoader.java:228)
07-02 11:43:21.515: E/FontLoader(12557):    at org.holoeverywhere.FontLoader.internalApply(FontLoader.java:228)
07-02 11:43:21.515: E/FontLoader(12557):    at org.holoeverywhere.FontLoader.internalApply(FontLoader.java:228)
07-02 11:43:21.515: E/FontLoader(12557):    at org.holoeverywhere.FontLoader.apply(FontLoader.java:166)
07-02 11:43:21.515: E/FontLoader(12557):    at org.holoeverywhere.FontLoader.apply(FontLoader.java:170)
07-02 11:43:21.515: E/FontLoader(12557):    at org.holoeverywhere.FontLoader.apply(FontLoader.java:157)
07-02 11:43:21.515: E/FontLoader(12557):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:553)
07-02 11:43:21.515: E/FontLoader(12557):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:482)
07-02 11:43:21.515: E/FontLoader(12557):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:477)
07-02 11:43:21.515: E/FontLoader(12557):    at xxx.CreatePinFragment.createView(CreatePinFragment.java:47)
07-02 11:43:21.515: E/FontLoader(12557):    at yyy.SherlockAbstractFragment.onCreateView(SherlockAbstractFragment.java:59)
07-02 11:43:21.515: E/FontLoader(12557):    at android.support.v4.app._HoloFragment.onCreateView(_HoloFragment.java:173)
07-02 11:43:21.515: E/FontLoader(12557):    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1460)
07-02 11:43:21.515: E/FontLoader(12557):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:911)
07-02 11:43:21.515: E/FontLoader(12557):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
07-02 11:43:21.515: E/FontLoader(12557):    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
07-02 11:43:21.515: E/FontLoader(12557):    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1444)
07-02 11:43:21.515: E/FontLoader(12557):    at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:445)
07-02 11:43:21.515: E/FontLoader(12557):    at org.holoeverywhere.app.Activity.onPostResume(Activity.java:372)
07-02 11:43:21.515: E/FontLoader(12557):    at android.app.Activity.performResume(Activity.java:3874)
07-02 11:43:21.515: E/FontLoader(12557):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3337)
07-02 11:43:21.515: E/FontLoader(12557):    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3362)
07-02 11:43:21.515: E/FontLoader(12557):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)
07-02 11:43:21.515: E/FontLoader(12557):    at android.app.ActivityThread.access$2300(ActivityThread.java:135)
07-02 11:43:21.515: E/FontLoader(12557):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
07-02 11:43:21.515: E/FontLoader(12557):    at android.os.Handler.dispatchMessage(Handler.java:99)
07-02 11:43:21.515: E/FontLoader(12557):    at android.os.Looper.loop(Looper.java:144)
07-02 11:43:21.515: E/FontLoader(12557):    at android.app.ActivityThread.main(ActivityThread.java:4937)
07-02 11:43:21.515: E/FontLoader(12557):    at java.lang.reflect.Method.invokeNative(Native Method)
07-02 11:43:21.515: E/FontLoader(12557):    at java.lang.reflect.Method.invoke(Method.java:521)
07-02 11:43:21.515: E/FontLoader(12557):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
07-02 11:43:21.515: E/FontLoader(12557):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-02 11:43:21.515: E/FontLoader(12557):    at dalvik.system.NativeStart.main(Native Method)

**Comment by Prototik** [comment]
Well, in 1.6.2-SNAPSHOT i'm fully rewrite a FontLoader. Are you try to use latest `master` version?

**Comment by dbacinski** [comment]
Works fine on 1.6.2-SNAPSHOT c5b5f318bcd4
