### ISSUE TITLE
Can't add ActionItems to ActionBar anymore

### ISSUE THREAD

**Issue by lukrop** [Prototik/HoloEverywhere#528]
I can't add ActionItems via XML menu file to the ActionBar anymore. In Fragments it's working but not in Activites anymore on pre ICS Devices.

The same code worked before but I don't remember the last commit where it worked. On Devices with native ActionBar everything is working as expected.

I have the feeling is has something to do with the getSupportMenuInflater(). Btw debugging the app and looking at the menu object it has both my items in it but not as actionItems but rather as standard items.

```
@Override
public boolean onCreateOptionsMenu(Menu menu) {
    super.onCreateOptionsMenu(menu);
    MenuInflater inflater = getSupportMenuInflater();
    inflater.inflate(R.menu.activity_new_ud, menu);
    return true;
}
```

imports are correct, using

```
import com.actionbarsherlock.view.Menu;
import com.actionbarsherlock.view.MenuInflater;
```

There is no error, the items just don't show up. And yes, they have the showAsAction attribute.

```
<item
            android:id="@+id/action_cancel"
            android:title="@string/cancel"
            android:showAsAction="always"
            android:icon="@drawable/ic_cancel" />
```

**Comment by BraisGabin** [comment]
With git bisect http://code-worrier.com/blog/git-bisect-basics/ you can find the commit. I think that @Prototik will appreciate it.

**Comment by Prototik** [comment]
I'm already :D Bugged commit: c76856abdc1d085ee6b21a370b317e369ec46d9b
