### ISSUE TITLE
Holoeverywhere Compile Release Error

### ISSUE THREAD

**Issue by MrEngineer13** [Prototik/HoloEverywhere#532]
I am using Actionbarsherlock and Holoeverywhere with my project in Android Studio. Whenever I try to compile I get the following error:

> Gradle: Execution failed for task ':libraries:holoeverywhere:compileRelease'.
> Compilation failed; see the compiler error output for details.

The full output is [here](http://pastebin.com/GQFWygdB).

My build.gradle in my Project directory:

```
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:0.4'
    }
}

apply plugin: 'android'

dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    //compile project(":libraries:actionbarsherlock")
    compile project(":libraries:holoeverywhere")

}

android {
    compileSdkVersion 17
    buildToolsVersion "17.0.0"

    defaultConfig {
        minSdkVersion 7
        targetSdkVersion 17
    }

}
```

My build.gradle in the Holoeverywhere directory:

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:0.4'
    }
}

apply plugin: 'android-library'

dependencies {
  file 'libs/android-support-v4-r13.1.jar'
  compile project(":libraries:actionbarsherlock")
}

android {
    compileSdkVersion 17
    buildToolsVersion "17.0.0"

  defaultConfig {
    minSdkVersion 17
    targetSdkVersion 17
  }

  sourceSets {
    main {
      manifest.srcFile 'AndroidManifest.xml'
      java.srcDirs = ['src']
      res.srcDirs = ['res']
    }
  }
}
```

My build.gradle in my Actionbarsherlock directory:

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:0.4'
    }
}
apply plugin: 'android-library'

dependencies {
   compile fileTree(dir: 'libs', include: '*.jar')
}

android {
    compileSdkVersion 17
    buildToolsVersion "17.0.0"

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            res.srcDirs = ['res']
        }
    }
}
```

My build.gradle in my project root:

```
task assemble{}
```

Settings.gradle in my project root:

```
include ':MyProject'
include ':libraries:holoeverywhere'
include ':libraries:actionbarsherlock'
```

Things I've tried:

-Updating the files in C:\Program Files (x86)\Android\android-studio\plugins\gradle with fresh downloaded ones but that did not help.

-Updating the files in C:\Users<User>.gradle\wrapper\dists\gradle-1.6-bin\72srdo3a5eb3bic159kar72vok

-Made sure there was a <application/> tag in the HE manifest

-Downloaded latest version of Android Studio, ABS and HE

-Uninstalled and reinstalled Android Studio

-Deleted all trace of ABS and HE in my project and added them again. ABS worked fine but once I added HE I started getting this error

-Reimported my project into Android Studio

I've been stuck on this the past couple of days so if anyone has any ideas I'd appreciate it. Thanks!

**Comment by ThatoMokhomong** [comment]
did you manage to resolve the problem? MrEnginee13

**Comment by MrEngineer13** [comment]
Yes I did thanks.

**Comment by ThatoMokhomong** [comment]
How did you manage to include the ActionBarSherlock, I am stuck here?please help

**Comment by MrEngineer13** [comment]
http://stackoverflow.com/questions/16718026/how-to-build-an-android-library-with-android-studio-and-gradle
