### ISSUE TITLE
DialogFragment doesn't show title by default

### ISSUE THREAD

**Issue by Ereza** [Prototik/HoloEverywhere#541]
Hi, I am subclassing DialogFragment and the dialog title is hidden on pre-ICS (ICS and above are OK). My workaround is to override onCreateDialog with the following:

```
    @Override
    public Dialog onCreateDialog(Bundle savedInstanceState) {
        setDialogType(DialogType.AlertDialog); //To workaround bug which shows no title
        return super.onCreateDialog(savedInstanceState);
    }
```

The title is correctly shown if I use the original classes, so I assume it's a bug in HoloEverywhere.

If I can provide any more info please let me know. Thanks!

**Comment by Prototik** [comment]
HE doesn't provide a dialog layout on pre-HC. Maybe in next release...

**Comment by Ereza** [comment]
Wow... I am amazed to read that statement. I thought it was a bug. Well then, thanks for the response, I'll stick to my workaround for now.
