### ISSUE TITLE
Programmatically adding Fragment in Activities onCreate: Content view from Fragment not showing

### ISSUE THREAD

**Issue by bfoese** [Prototik/HoloEverywhere#542]
When a Fragment is being added programmatically in the Activities onCreate() method, the content view from the Fragment won't show up. I set up two test projects to verify that this is a HoloEverywhere issue. The ActionbarSherlock project behaved properly and displayed the Button contained in the view of the Fragment whereas the HoloEverywhere project failed on that.

![android-fragments-he-vs-abs](https://f.cloud.github.com/assets/1623552/805840/520d4550-ee2e-11e2-9b46-198b7060f428.jpg)

Within the Activity the Fragment was added like this:

``` java
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    this.fm = getSupportFragmentManager();
    Fragment fragment = Fragment.instantiate(this, FrgmLogin.class.getName());
    FragmentTransaction ft = fm.beginTransaction();
    ft.add(android.R.id.content, fragment, "login");
    ft.commit();
}
```

The MenuItem showing in the screenshot is part of an options menu that was inflated by the Fragment. Also the subtitle in the ActionBar was set by the Fragment.

Debugging the state of the FragmentManager in the Activities onResume() revealed, that the Fragment is in fact attached to the Activity. Even the view of the Fragment is completely set up.

**Comment by Prototik** [comment]
Doesn't use `android.R.id.content` for something in HoloEverywhere.
Now library not fully implement a content view behavior, but...
First you should set any content view. You can even set null content view, but only once and only after super.onCreate and in onCreate method. And use `R.id.contentView` instead `android.R.id.content`
