### ISSUE TITLE
Layout issues on Sony Xperia U, Android 2.3.7

### ISSUE THREAD

**Issue by Ereza** [Prototik/HoloEverywhere#543]
Hi:

I am using HoloEverywhere in my app, and some users have problems with the layouts on Sony Xperia U. More precisely, a ListView is not shown, and even the application title in the action bar is blank!

This happens with HE 1.6.8, if I use a previous version (1.5.0), it works correctly.

I attach some images:

![screenshot_2013-07-17_0741](https://f.cloud.github.com/assets/285008/813849/18d935b4-ef0a-11e2-8821-266ff531dfd3.png)
(action bar text is not visible, and below "Pulsa una línea para ver su recorrido" there is a ListView with several items, which is also hidden somehow)

![screenshot_2013-07-17_0742](https://f.cloud.github.com/assets/285008/813857/4e0a8b8e-ef0a-11e2-8a9d-aa6bed97f4a4.png)
(map's InfoWindow is strangely expanded... maybe related to #484?)

**Comment by ViliusKraujutis** [comment]
You can try adding `android.widget.LinearLayout`instead of `LinearLayout` in your layouts, but this does not solve AlertDialog layout issues

See more here:
http://stackoverflow.com/questions/17852581/linearlayout-with-weight-x-does-not-work-properly-on-sony-ericsson-using-lib-ho/17854542#17854542

**Comment by nakardo** [comment]
Same issue here for `DialogFragment` and it seems to be happening on android ~2.2 versions. I've reports from Sony R800i, WT19a, MT27i, ST27a, SK17i, ST18i ... Any ideas?

**Comment by Prototik** [comment]
Sony sucks. After migrating on ABC this bug shouldn't be happens. But you can report to this issue again.
