### ISSUE TITLE
AlertDialog doesn't allow text input

### ISSUE THREAD

**Issue by croemmich** [Prototik/HoloEverywhere#544]
I have a ViewPager inside the custom view of an AlertDialog. Some of the view pager pages have EditTexts, however the soft keyboard does not work for them because of this:
https://github.com/Prototik/HoloEverywhere/blob/master/library/src/org/holoeverywhere/internal/AlertController.java#L467

If I use a regular dialog rather than an alert dialog the view is cut off on the right side on some devices.

What's the purpose of that code?

**Comment by croemmich** [comment]
As a work around I added this to my base layout:

```
<EditText
            android:layout_width="0dip"
            android:layout_height="0dip"
            android:visibility="gone"/>
```

**Comment by Prototik** [comment]
Default behavior of AlertDialog.
