### ISSUE TITLE
Cant Get SharedPreferences from context

### ISSUE THREAD

**Issue by zenyagami** [Prototik/HoloEverywhere#547]
im using:
 public static void setLoginOkInPreferences(Context  context,boolean status)
     {

```
     SharedPreferences preferencias=   context.getSharedPreferences(Util.PREF_SESSION,Context.MODE_PRIVATE);
        Editor editor=preferencias.edit();                     
            editor.putBoolean(Util.PREF_GET_LOGIN_OK,status);                  
            editor.commit();

 }
```

but i cant get getSharedPreferences work,

**Comment by BraisGabin** [comment]
Did you import the preferences addon?
https://github.com/Prototik/HoloEverywhere/tree/master/addons/preferences

**Comment by zenyagami** [comment]
Yes i had it, the problem after re search a lot i found i have to do this way:
PreferenceManager.wrap(context,"pref_key", Context.MODE_MULTI_PROCESS);
this will return shared preference
