### ISSUE TITLE
Preference Screen does not show right in Gingerbread

### ISSUE THREAD

**Issue by zenyagami** [Prototik/HoloEverywhere#548]
im using the next code to show preferences

public class Preferencias extends org.holoeverywhere.preference.PreferenceActivity{

```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    getSupportActionBar().setDisplayHomeAsUpEnabled(true);
    addPreferencesFromResource(R.xml.preferences);
    final PreferenceScreen contactsPS =


}
```

}
My XML its:
<?xml version="1.0" encoding="utf-8"?>
<PreferenceScreen  xmlns:holo="http://schemas.android.com/apk/res-auto">
<PreferenceCategory
            holo:title="Some">

```
    <ListPreference holo:id="@+id/pref_key_intervalo"
    holo:title="Intervalo en Seguimiento"
    holo:summary="Interval"
     holo:entries="@array/intervalo"
      holo:entryValues="@array/intervalo_values"
      holo:defaultValue="5"
    /> 
```

.... and others preferences
in Manifest i use @style/Holo.Theme
(i already added the addon Preferences)
in my JB device working well but in gingerbread looks wierd, all are like this: not showing at all or just some part.
![device-2013-07-21-230131](https://f.cloud.github.com/assets/1240069/832974/435cf15e-f284-11e2-80c3-7dc861282353.png)

**Comment by Prototik** [comment]
Dupe #484
