### ISSUE TITLE
GIT cloning instructions

### ISSUE THREAD

**Issue by dylanseago** [Prototik/HoloEverywhere#550]
When importing to IDE I followed these instructions:
https://github.com/Prototik/HoloEverywhere/wiki/Import-in-IDE#eclipse

I'm having issues when it says
"Remove contrib/ActionBarSherlock/actionbarsherlock/libs/android-support-v4.jar"
and then
"Copy library/libs/android-support-v4-r13.1.jar to contrib/ActionBarSherlock/actionbarsherlock/libs/"

First of all there is no "contrib" folder, the "ActionBarSherlock" folder is in the root directory. I figured that out.

The main problem I'm having is finding android-support-v4-r13.1.jar. There is no "libs" folder inside the "library" folder.

Any help would be appreciated, Thanks.

**Comment by Prototik** [comment]
Wiki updated.
