### ISSUE TITLE
onCreateContextMenu Dialog Title

### ISSUE THREAD

**Issue by moodstubos** [Prototik/HoloEverywhere#552]
Hi, 

first off all: Many thanks for this wonderfull library!

I found a problem with following code (example)

```
public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Button btn = (Button) this.findViewById(R.id.button1);
        registerForContextMenu(btn);

    }

    @Override
    public void onCreateContextMenu(ContextMenu menu, View v, ContextMenuInfo menuInfo) {

        super.onCreateContextMenu(menu, v, menuInfo);

        menu.setHeaderTitle("Menu Title");
        menu.add(1, 1, 0, "Entry 1");
        menu.add(2, 2, 0, "Entry 2");   
    }

}
```

The result can be seen on the attached image. 
On Nexus 7 (Android 4) the Title Theme seems to be broken (wrong font size and color). 

![device-2013-07-23-123519](https://f.cloud.github.com/assets/5072232/840983/fe823232-f383-11e2-95d7-6111cc92ea5d.png)

On a Android 2.3 device it looks like it should. 

Can anybody confirm this issue?

regards
moods

**Comment by Prototik** [comment]
Attach also screenshot from 2.3 device

**Comment by moodstubos** [comment]
Screenshot of 2.3 device
![device-2013-07-23-130806](https://f.cloud.github.com/assets/5072232/841101/3fe7d8ae-f388-11e2-8ac3-54ce4a025cb1.png)

**Comment by IronicallyJesus** [comment]
This is what It looks like with a light theme
(Plus the dark line above the context menu)
![screenshot_2013-07-24-16-37-01](https://f.cloud.github.com/assets/3488086/851728/c4073304-f4a1-11e2-8d28-21a69a6277cb.png)

**Comment by IronicallyJesus** [comment]
The title thing even occurs when a webview creates an alertdialog. should probably reopen #393 and #429 as well since there is also a dark line above the dialog in the screenshot provided.
![img_20130725_015518](https://f.cloud.github.com/assets/3488086/853818/45753114-f4ef-11e2-9c5b-d00a86fb0797.JPG)

**Comment by ivannarino** [comment]
Hello,

I've got same issue on Genymotion with Galaxy Nexus 4.2.2 on it

**Comment by Prototik** [comment]
![device-2013-09-05-174945](https://f.cloud.github.com/assets/1416030/1087299/2df385fe-1614-11e3-8d0a-3911c13929ef.png)
![device-2013-09-05-181433](https://f.cloud.github.com/assets/1416030/1087300/2e3e262c-1614-11e3-879e-50f732ce130b.png)
