### ISSUE TITLE
little NumberPicker bug - width calculation wrong

### ISSUE THREAD

**Issue by MFlisar** [Prototik/HoloEverywhere#553]
If using a custom format, the width calculation of the NumberPicker is not working...

As far as I tested it, changing one line in "library / src / org / holoeverywhere / widget / NumberPicker.java" should solve that...

Replacing "String.valueOf(i)" with "formatNumber(i)" in line 1333/1334 should do the trick...

**Comment by Prototik** [comment]
Make a pull request.
