### ISSUE TITLE
Switch setChecked doesn't work inside OnCheckedChangeListener

### ISSUE THREAD

**Issue by eduardb** [Prototik/HoloEverywhere#554]
Hello,

I am trying to avoid the user turning on a service if a certain condition is not met by setting the switch back to off. It goes something like this:

``` android
mSwitchButton.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {

            @Override
            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                if (isChecked) {                    
                    if (condition) {                        
                        mSwitchButton.setChecked(false);
                        return;
                    }

                    // unrelated stuff
                }
            }
        });
```

The problem is that the switch position remains on On, and the text too. Only the color is gray, as it should be for Off.

**Comment by Prototik** [comment]
It's backport from Jelly Bean.
If you can provide fix without breaking of old code - do it.

Also you can just post your code in handler for processing in next ui tick.

**Comment by eduardb** [comment]
It seems that calling super.setChecked(checked); last in Switch.setChecked(boolean) resolves the problem. Works both on Android 2.1 and 4.2.2, and hopefully doesn't have any negative effects. This issue is present in Android source code too.
Should I make a pull request, or you will make the fix yourself? This is how the function should look:

``` android
@Override
    public void setChecked(boolean checked) {        
        mThumbPosition = checked ? getThumbScrollRange() : 0;
        invalidate(); 
        super.setChecked(checked);
    }
```

PS: Thanks for this awesome library :)
