### ISSUE TITLE
Update Support Library

### ISSUE THREAD

**Issue by gsingh93** [Prototik/HoloEverywhere#558]
Whenever I import HoloEverywhere and ABS into my project, I always have to right click on the ABS project and select Android Tools -> Add Support Library. Anyone who clones my project and downloads updates the submodules will have to do this, but they probably will not know they have to do this.

Can you update the version in your fork of ABS? Or is there a better way to fix this issue?

**Comment by Prototik** [comment]
Already updated to patched r18, no?

**Comment by gsingh93** [comment]
After doing a fresh clone today, I see this in actionbarsherlock/libs:
-rw-rw-r-- 1 gulshan gulshan 271754 Jul 25 23:00 android-support-v4.jar

After updating the support library the way I mentioned, I get this:
-rw-rw-r-- 1 gulshan gulshan 556198 Jul 25 23:00 android-support-v4.jar

So I don't think the library you have is the latest, based on the files size. I don't know how to check the actual versions of them though. Do you see either of these sizes in your version?

**Comment by Prototik** [comment]
Oops, i forgot update ABS reference to new commit. Fixed.

**Comment by gsingh93** [comment]
Thanks, I got the new version now. I'm glad you finally forked ABS, the support library stuff always gives me a headache.
