### ISSUE TITLE
Remove ActionBarSherlock?

### ISSUE THREAD

**Issue by ericps** [Prototik/HoloEverywhere#561]
With the v7 support library can ActionBarSherlock be removed from the project?

This would limit HoloEverywhere to android 2.1+ though. I think a separate branch can exist for the people wanting android 1.6+ compatibility that haven't already cloned this project

**Comment by Prototik** [comment]
android support library v4 - works with api level 4
android support library v7 - works with api level ... fuck, level 7!

ActionBar Compat available also only on 2.1+.

And no, now i have no plans about migration from ABS to ABC. Maybe later.

**Comment by ericps** [comment]
Okay, 2.1+ covers 99.9% of online android devices that connect at this point. I may fork this project instead

**Comment by Prototik** [comment]
@ericps Even if you fork project - you cannot just remove ABS and make it available on 1.6+: HoloEverywhere itself use 2.1+ features.

**Comment by ericps** [comment]
I don't want to make it available on 1.6+

I only want it to work on Android 2.x and Google's new support library for api level 7+ works on android 2.1+, so this is a match

**Comment by ericps** [comment]
woops, I thought that holoeverywhere went back to 1.6+ originally. Anyway it would be good to remove dependency on ABS

thanks

**Comment by Prototik** [comment]
@ericps Why? Are you think that new ActionBar Compat less buggy?
Give me one real reason.

**Comment by ericps** [comment]
The reason being that it is the official support one, it functions similarly to ActionBarSherlock and gives the functionality expected of the ActionBar in Android 3.0+ . Earlier versions of Android don't support Holo theme still, so this library being coupled with ActionBarSherlock instead of support.v7 now becomes the setback. ABS doesn't play nice with support.v7 in the same project/workspace because they redefine the same attributes.

**Comment by janoliver** [comment]
In equally good solutions, one should drop the third party dependency in favor of the official one. It is easier to include the Compatibility library since the android SDK supports it officially. It is also kept up to date with the rest of the SDK.

I really would love to see a HoloEverywhere version compatible with ABC. 

Otherwise, keep up the great work. You are making so many Android Devs very happy.

**Comment by Prototik** [comment]
@janoliver see `abc` branch

**Comment by juliocbcotta** [comment]
Is the HoloEveryWhere branch abc working?

**Comment by Prototik** [comment]
/partially/
