### ISSUE TITLE
How to override onCreateOptionsMenu in Activity if it's final

### ISSUE THREAD

**Issue by revkov** [Prototik/HoloEverywhere#563]
I read all issue's and topic's but not find a solution. Please how to create options menu from resources. Without holoeverywhere on >4.0 OS i did @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // TODO Auto-generated method stub
        getMenuInflater().inflate(R.menu.main, menu);
        return true;
    }

What doing now?

**Comment by Prototik** [comment]
Use `com.actionbarsherlock.view.Menu` instead `android.view.Menu` and `getSupportMenuInflater()` instead `getMenuInflater()`
