### ISSUE TITLE
error whit import

### ISSUE THREAD

**Issue by tasnim1281** [Prototik/HoloEverywhere#566]
How can I use the Holo everywhere?
when I want to import 4 Project
this error show

![untitled](https://f.cloud.github.com/assets/4892388/907021/c98007d0-fd01-11e2-87c7-0b7abf26d5ef.jpg)

??
Please help!

**Comment by MedicalGroupSoft** [comment]
Eclipse. I get the same error.

**Comment by gordonpro** [comment]
Intellij IDEA is well

**Comment by Prototik** [comment]
Use a project properties explorer and remove wrong source row in `buildpath` tab.
