### ISSUE TITLE
Unable to display new fragment content from inside another fragment while using the slider menu

### ISSUE THREAD

**Issue by Henriquedn** [Prototik/HoloEverywhere#567]
I am using the slider menu and it works fine with the fragments on the slidermenu added in the main activity. However when i start a new fragment using the code below the contentview does not change.

 FragmentManager fm = getSupportActivity().getSupportFragmentManager();
 FragmentTransaction ft =fm.beginTransaction();
MyFragment myFragment = new myFragment();
ft.add(viewNannyFragment "New Fragment");
ft.addToBackStack(null);
ft.commit();

**Comment by Prototik** [comment]
Use a [SliderMenu.replaceFragment()](https://github.com/Prototik/HoloEverywhere/blob/master/addons/slider/src/org/holoeverywhere/slider/SliderMenu.java#L683)

**Comment by Henriquedn** [comment]
am unable to create an instance of the sliderMenu.

MyFragment myFragment = new MyFragment();

new SliderMenu(new AddonSliderA()).replaceFragment(myFragment);

error :

java.lang.NullPointerException.

at org.holoeverywhere.slider.SliderMenu.<init>(SliderMenu.java :338

**Comment by Prototik** [comment]
You shouldn't create a addon instance by himself.

``` java
AddonSliderA addon = getSupportActivity().addon(AddonSlider.class);
SliderMenu menu = addon.obtainSliderMenu();
menu.replaceFragment(myFragment);
```

**Comment by Henriquedn** [comment]
Thank you. Its now working well.

Is there a way to add icons to the slider menu items?

_Regards,_
*
*
*
*
*
*
_Henry Maina_
_+254 725 987 342_
_Twitter @HenrieDn https://twitter.com/HenrieDn_
_Facebook henrique.maina http://www.facebook.com/henrique.maina_

**Comment by Prototik** [comment]
Now - no, you haven't standard way for this, but you can simply provide custom item layout and behavior.

**Comment by Henriquedn** [comment]
I have tried using a custom layout but its crashing before even application finishes launching
