### ISSUE TITLE
PreferenceActivity

### ISSUE THREAD

**Issue by PaulAnnekov** [Prototik/HoloEverywhere#57]
Hi!

My app has preference activity with ListPreference, CheckBoxPreference and some my own custom preferences.
The problem is that preferences styles apply partially on Android 2.2. Here is screenshots:

[Invisible circle loader and badly-readable text color](http://www.gdriveurl.com/?idl=713464060806&out=1)
[Android 2.2 button images](http://www.gdriveurl.com/?idl=313464070036&out=1)
[Invisible dialog's title, Android 2.2 controls](http://www.gdriveurl.com/?idl=813464070965&out=1)

As I understand - you experience some problems with AlertDialog?

**Comment by Prototik** [comment]
Preference framework is not yet supported in HoloEverywhere.
Added to the TODO list.

**Comment by Prototik** [comment]
Porting state: 80%.
I has been push into my fork tommorow.

Thanks for idea:)

**Comment by Prototik** [comment]
95% ... it can be today :)

**Comment by PaulAnnekov** [comment]
> Thanks for idea:)

;)

**Comment by Prototik** [comment]
Please, test Preference Framework, his support is not full, but the main part is already working.

**Comment by PaulAnnekov** [comment]
I have downloaded latest version, added app theme - '@style/Theme.HoloEverywhereLight.Sherlock', but my preferences screen is the same. I don't see any changes :(

**Comment by Prototik** [comment]
See a HoloDemo. [preferences.xml](https://github.com/ChristopheVersieux/HoloEverywhere/blob/master/HoloDemo/res/xml/preferences.xml)
Required XML NS holo.

And Theme.HoloEverywhereLight.Sherlock a deprecated. Use Holo.Theme.Sherlock.Light

**Comment by otis23** [comment]
Hi,

i had the same issue, and added the holo NS. But I'm not using the Light Theme. In my Preference Screen everything is  dark, and when i select an listpreference the popup is white.
see: 
[preference screen](https://docs.google.com/open?id=0ByGA5UACOr1VUnlZeFlhVzUyNnM)
[open list preference](https://docs.google.com/open?id=0ByGA5UACOr1VX09xbjRPT1lCNVU)
[how it has to look like :)](https://docs.google.com/open?id=0ByGA5UACOr1VejVRVmNGUjBXT1k) 

[preference.xml](https://docs.google.com/open?id=0ByGA5UACOr1VWjBWQndKdkJJTmM)

**Comment by alaney** [comment]
I am having similar issues. My preference screen looks dark when I use Holo ns, but when I don't it looks fine except for the listpreference menu. when I select it, the popup menu is not holo themed, it looks stock.

**Comment by Prototik** [comment]
ListPreference (and MultiListPreference) temporary don't supported.

**Comment by otis23** [comment]
I will donate you 10 €, if you make it supported this week :) deal?

**Comment by StenaviN** [comment]
@otis23 Try to do it yourself for 10 € ;) deal?

**Comment by otis23** [comment]
I would it do for nothing, but i have no time, but i need this feature. Should i offer more? Say a price!

**Comment by Prototik** [comment]
:D
Donations in open-source projects a little strange.
Actually, everything depends on AlertDialog, it's almost ready, but there was one problem - he stretched to full screen, I'm trying to overcome it.

**Comment by Prototik** [comment]
@StenaviN кстати, низя предлагать такое на гитхабе, задушат ведь :D
AlertDialog уже этот в печенках сидит, буду двести просить, может и сделаю :D шучу.
@otis23 I'm going to torture dialog.

**Comment by otis23** [comment]
@Prototik большой cпасибо. ^^

**Comment by Prototik** [comment]
No-no-no, with you I prefer to speak in English, because "большой cпасибо" is not correct and tearing brain :D

**Comment by otis23** [comment]
@Prototik I know. I was bad in russian @ school :D

**Comment by Prototik** [comment]
Come on, a little mistake: большое спасибо.
Offtopic, I try to do as quickly as possible, I have one little idea ...

**Comment by Prototik** [comment]
ListPreference and MultiSelectListPreference now supported.

**Comment by otis23** [comment]
Thx that was fast! Its working well on Android 2.3. But wehn i try to open the ListPreference on ICS, an exception is thrown.

``` java
09-12 14:00:10.911: E/AndroidRuntime(19260): FATAL EXCEPTION: main
09-12 14:00:10.911: E/AndroidRuntime(19260): android.view.InflateException: Binary XML file line #89: Error inflating class <unknown>
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.view.LayoutInflater.createView(LayoutInflater.java:606)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at com.WazaBe.HoloEverywhere.LayoutInflater.onCreateView(LayoutInflater.java:138)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:653)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:678)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:269)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at com.WazaBe.HoloEverywhere.internal.AlertController.installContent(AlertController.java:451)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at com.WazaBe.HoloEverywhere.AlertDialog.onCreate(AlertDialog.java:348)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.app.Dialog.dispatchOnCreate(Dialog.java:384)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.app.Dialog.show(Dialog.java:280)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at com.WazaBe.HoloEverywhere.preference.DialogPreference.showDialog(DialogPreference.java:275)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at com.WazaBe.HoloEverywhere.preference.DialogPreference.onClick(DialogPreference.java:147)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at com.WazaBe.HoloEverywhere.preference.Preference.performClick(Preference.java:535)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at com.WazaBe.HoloEverywhere.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:105)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.widget.AdapterView.performItemClick(AdapterView.java:292)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.widget.AbsListView.performItemClick(AbsListView.java:1071)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.widget.AbsListView$PerformClick.run(AbsListView.java:2527)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.widget.AbsListView$1.run(AbsListView.java:3181)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.os.Handler.handleCallback(Handler.java:605)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.os.Handler.dispatchMessage(Handler.java:92)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.os.Looper.loop(Looper.java:154)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.app.ActivityThread.main(ActivityThread.java:4945)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at java.lang.reflect.Method.invokeNative(Native Method)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at java.lang.reflect.Method.invoke(Method.java:511)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at dalvik.system.NativeStart.main(Native Method)
09-12 14:00:10.911: E/AndroidRuntime(19260): Caused by: java.lang.reflect.InvocationTargetException
09-12 14:00:10.911: E/AndroidRuntime(19260):    at java.lang.reflect.Constructor.constructNative(Native Method)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.view.LayoutInflater.createView(LayoutInflater.java:586)
09-12 14:00:10.911: E/AndroidRuntime(19260):    ... 30 more
09-12 14:00:10.911: E/AndroidRuntime(19260): Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f010069 a=-1}
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.content.res.Resources.loadDrawable(Resources.java:2015)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.view.View.<init>(View.java:2823)
09-12 14:00:10.911: E/AndroidRuntime(19260):    at android.view.View.<init>(View.java:2760)
09-12 14:00:10.911: E/AndroidRuntime(19260):    ... 33 more
```

can you help me please with this issue? Do I have to implement two diffrent PreferenceActivities for that?

If you want the 10 bucks, mail me your paypal-adress :)

**Comment by Prototik** [comment]
Are you fast :D
Just been corrected.

**Comment by Prototik** [comment]
Damn, accidentally closed

**Comment by otis23** [comment]
Something went wrong. I can't compile now. Because: 

``` java
error: Error retrieving parent for item: No resource found that matches the given name 'Holo.TextView'. styles.xml  /HoloEverywhereLib/res/values   line 325    Android AAPT Problem
```

**Comment by Prototik** [comment]
@otis23 You VERY fast. Already fixed :)

**Comment by otis23** [comment]
you are faster :) Now its working on my Testdevices. 1000x thank you.
Do you have paypal? I don't want to break a promise.

**Comment by Prototik** [comment]
@otis23 I have paypal, but I will not accept money. I work for the benefit of Open-Source, and not for money.

**Comment by otis23** [comment]
Ok. Nice attitude :)

**Comment by alaney** [comment]
Thank you for making this work! My listpreference menu does pop-up but it does not look holo themed. It still looks like my stock theme. What am I doing wrong

**Comment by Prototik** [comment]
@alaney Show you xml and code. And see demo, of course.

**Comment by otis23** [comment]
You have to use PreferenceActivity from HoloEveryWhereLib, and use the holo NS in preference.xml. You can look it up in the HoloDemo Project.

**Comment by alaney** [comment]
I fixed it. Thank You!

**Comment by cagcak** [comment]
what are the steps to add HoloEverywhere to any project in Android Studio
