### ISSUE TITLE
Duplicate definitions in ABC branch

### ISSUE THREAD

**Issue by janoliver** [Prototik/HoloEverywhere#570]
Hi, I cannot compile HoloEverywhere together with ActionBarCompat. There are three attributes that are already defined in ABC:

```
.../build/res/all/debug/values/values.xml:1143: error: Attribute "spinnerMode" has already been defined
.../build/res/all/debug/values/values.xml:1174: error: Attribute "popupPromptView" has already been defined
.../build/res/all/debug/values/values.xml:1181: error: Attribute "disableChildrenWhenDisabled" has already been defined
```

As far as I can tell, they are not included in ABS, so maybe they can just be removed?

**Comment by BraisGabin** [comment]
Did you use the abc branch?

**Comment by janoliver** [comment]
Yes of course. This is my build.gradle. HoloEverywhere is in the local maven repo.

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:0.5.+'
    }
}

repositories {
    mavenLocal()
}

apply plugin: 'android'

dependencies {
    compile ('com.android.support:support-v4:18.0.+')
    compile ('com.android.support:appcompat-v7:18.0.0@aar')
    compile ('org.holoeverywhere:library:1.6.2')
    compile ('org.holoeverywhere.addons:preferences:1.6.2')
    compile ('org.holoeverywhere.addons:slider:1.6.2')
}

android {
    compileSdkVersion 18
    buildToolsVersion "18.0.1"

    defaultConfig {
        minSdkVersion 7
        targetSdkVersion 18
    }
}
```

**Comment by Prototik** [comment]
In build file in `abc` branch version of library is `1.6.2-SNAPSHOT`, not 1.6.2. Are you use correct version?

**Comment by janoliver** [comment]
Hi, I only added everything a second time as 1.6.2 to check, whether the -SNAPSHOT might have had anything to do with it. (I really have little idea of maven. :D )

So yes, I have the correct version.

**Comment by Prototik** [comment]
I shall be free in two weeks. Prior to that, I would not have even the possibility to help.

**Comment by grendell** [comment]
I'm also seeing duplicate definitions on the abc branch in attrs.xml after importing the HoloEverywhere library and v7-appcompat into Eclipse.  Am I doing something obviously wrong?  Thanks for the help.

![screen shot 2013-08-26 at 10 03 15 pm](https://f.cloud.github.com/assets/1158912/1031201/1888b9cc-0ed6-11e3-8406-52bede771984.png)

**Comment by Prototik** [comment]
Rejected. Library compiles normally via Android Studio. Maven/Eclipse build i'll fix.

**Comment by cataliniacob** [comment]
@Prototik Please consider reopening; as far as I can tell this is a real issue that's currently stopping everyone from using holoeverywhere together with ActionBarCompat.

Holoeverywhere **itself** compiles, but **apps** that include reference both holoeverywhere and ActionBarCompat **fail** when compiled with gradle (and therefore Android Studio). I'm experiencing exactly the same issue as @janoliver.

I built holoeverywhere (current master, commit 5615a34), I then get an aar that I install with maven to a local repository as version 1.6.8-43-g5615a34 (version generated by `git describe`). In my `build.gradle` I have:

```
dependencies {
    compile 'com.android.support:appcompat-v7:18.0.0'
    compile 'org.holoeverywhere:holoeverywhere:1.6.8-43-g5615a34@aar'
}
```

When running `gradlew build` from the command line I get:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mexx:processDebugResources'.
> Failed to run command:
        D:\android-studio\sdk\build-tools\18.0.1\aapt.exe package -f --no-crunch -I D:\android-studio\sdk\platforms\android-18\android.jar -M D:\android\mexx-android\mexx\build\manifests\debug\AndroidManifest.xml -S D:\android\mexx-android\mexx\build\res\all\debug -A D:\android\mexx-android\mexx\build\assets\debug -m -J D:\android\mexx-android\mexx\build\source\r\debug -F D:\android\mexx-android\mexx\build\libs\mexx-debug.ap_ --debug-mode --custom-package nl.appvantages.mexx --output-text-symbols D:\android\mexx-android\mexx\build\symbols\debug
Error Code:
        1
Output:
        D:\android\mexx-android\mexx\build\res\all\debug\values\values.xml:767: error: Attribute "spinnerMode" has already been defined
        D:\android\mexx-android\mexx\build\res\all\debug\values\values.xml:798: error: Attribute "popupPromptView" has already been defined
        D:\android\mexx-android\mexx\build\res\all\debug\values\values.xml:805: error: Attribute "disableChildrenWhenDisabled" has already been defined
```

**Comment by Prototik** [comment]
You don't should include appcompat with latest master branch. It already contain built-in appcompat with some fixes

**Comment by cataliniacob** [comment]
@Prototik Indeed, thanks for the comment. If I remove the `compile 'com.android.support:appcompat-v7:18.0.0'` line it works.

I think it's not ideal though that holoeverywhere bundles appcompat. For example if another library would also do the bundling an app couldn't use both holoeverywhere and that library. For now it works for me as is but are there any plans to get rid of the bundling?

**Comment by Prototik** [comment]
No, some places in appcompat should be changed for full integration with HE
