### ISSUE TITLE
nested PreferenceScreen+Holo.Theme.Dialog: ActionBarImpl can only be used with a compatible window decor layout

### ISSUE THREAD

**Issue by metinkale38** [Prototik/HoloEverywhere#573]
I get a "E/AndroidRuntime(29790): java.lang.IllegalStateException: ActionBarImpl can only be used with a compatible window decor layout" when clicking nested PreferenceScreens with Holo.Theme.Dialog. 

To fix it you need a Theme check prior "dialog.requestWindowFeature(Window.FEATURE_ACTION_BAR)" at org.holoeverywhere.preference.PreferenceScreen.showDialog(PreferenceScreen.java:263) to make sure that the Theme supports ActionBar(/is not a Dialog)

**Comment by Prototik** [comment]
/Make/ a pull request, man.

**Comment by metinkale38** [comment]
never done/do not know how to do a pull request, i just wanted to help others may having the same issue

i have solved it for me...

Edit: finally made a pull request :)
