### ISSUE TITLE
In onPrepareOptionsMenu, calling menu.findItem  returns null  when pressing "menu" key

### ISSUE THREAD

**Issue by isayamayomi** [Prototik/HoloEverywhere#577]
My code is something like this:

```
@Override
public boolean onCreateOptionsMenu(Menu menu) {
    getSupportMenuInflater().inflate(R.menu.menu_main);
    return true;
}

@Override
public boolean onPrepareOptionsMenu(Menu menu) {
    MenuItem menu_share = menu.findItem(R.id.menu_share);
    menu_share.setVisible(mEnableShare);
    return true;
}
```

the code works well on android 4.x, but crash on android 2.x if user presses the 'menu' key of the handset. Digging into this problem, i found onPrepareOptionsMenu()  was called twice on android 2.x. At the first time, the menu is an instance of MenuBuilder and things go well, but at the second time, it become an instance of MenuWrapper, and menu.findItem() returns null, causing crash.

Duplicate issue of https://github.com/Prototik/HoloEverywhere/issues/440, but that issue was closed and no solution provided.(I can't understand russian).

**Comment by httpdispatch** [comment]
@isayamayomi do you have the issue on any android 2.x environment? I couldn't reproduce it on emulator but keep receiving NPE errors reports from devices like Samsung GT-I9000B Galaxy S Vibrant, Motorola MB860 Atrix, ZTE X501 Groove, Samsung GT-I9100 Galaxy S II, Samsung GT-S5830 Galaxy Ace, Samsung GT-S5300B Galaxy Pocket, Samsung GT-I9003 Galaxy SL, LG P990 Optimus 2X, HTC Desire X0H6T, Motorola MB525 DEFY, HTC Desire S. All of them has android version 2.3.3-2.3.7

**Comment by isayamayomi** [comment]
@httpdispatch The issue can be reproduced on real android 2.x devices when hardware menu key pressed as well as  as on emulator.

crash stack from android 2.3 emulator:
08-15 07:30:52.722: E/ACRA(480): com.android.test fatal error : null
08-15 07:30:52.722: E/ACRA(480): java.lang.NullPointerException
08-15 07:30:52.722: E/ACRA(480):    at com.android.test.ui.main.MainActivity.onPrepareOptionsMenu(MainActivity.java:279)
08-15 07:30:52.722: E/ACRA(480):    at org.holoeverywhere.app.Activity.onPrepareOptionsMenu(Activity.java:415)
08-15 07:30:52.722: E/ACRA(480):    at android.app.Activity.onPreparePanel(Activity.java:2174)
08-15 07:30:52.722: E/ACRA(480):    at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:469)
08-15 07:30:52.722: E/ACRA(480):    at org.holoeverywhere.app.Activity.access$8(Activity.java:1)
08-15 07:30:52.722: E/ACRA(480):    at org.holoeverywhere.app.Activity$20.post(Activity.java:434)
08-15 07:30:52.722: E/ACRA(480):    at org.holoeverywhere.addon.IAddonBasicAttacher.performAddonAction(IAddonBasicAttacher.java:81)
08-15 07:30:52.722: E/ACRA(480):    at org.holoeverywhere.app.Activity.performAddonAction(Activity.java:522)
08-15 07:30:52.722: E/ACRA(480):    at org.holoeverywhere.app.Activity.onPreparePanel(Activity.java:426)
08-15 07:30:52.722: E/ACRA(480):    at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:332)
08-15 07:30:52.722: E/ACRA(480):    at com.android.internal.policy.impl.PhoneWindow.onKeyDownPanel(PhoneWindow.java:568)
08-15 07:30:52.722: E/ACRA(480):    at com.android.internal.policy.impl.PhoneWindow.onKeyDown(PhoneWindow.java:1210)
08-15 07:30:52.722: E/ACRA(480):    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1668)
08-15 07:30:52.722: E/ACRA(480):    at android.view.ViewRoot.deliverKeyEventToViewHierarchy(ViewRoot.java:2560)
08-15 07:30:52.722: E/ACRA(480):    at android.view.ViewRoot.handleFinishedEvent(ViewRoot.java:2535)
08-15 07:30:52.722: E/ACRA(480):    at android.view.ViewRoot.handleMessage(ViewRoot.java:1867)
08-15 07:30:52.722: E/ACRA(480):    at android.os.Handler.dispatchMessage(Handler.java:99)
08-15 07:30:52.722: E/ACRA(480):    at android.os.Looper.loop(Looper.java:123)
08-15 07:30:52.722: E/ACRA(480):    at android.app.ActivityThread.main(ActivityThread.java:3683)
08-15 07:30:52.722: E/ACRA(480):    at java.lang.reflect.Method.invokeNative(Native Method)
08-15 07:30:52.722: E/ACRA(480):    at java.lang.reflect.Method.invoke(Method.java:507)
08-15 07:30:52.722: E/ACRA(480):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
08-15 07:30:52.722: E/ACRA(480):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
08-15 07:30:52.722: E/ACRA(480):    at dalvik.system.NativeStart.main(Native Method)

**Comment by Prototik** [comment]
HoloEverywhere start's migration on ABC, checkout new version of library in `abc` branch and report if issue stayed.
