### ISSUE TITLE
Nested Fragments in TabSwipeFragment are not shown

### ISSUE THREAD

**Issue by ekinlyw** [Prototik/HoloEverywhere#579]
I'm using a class inherited from TabSwipeFragment. And the class has two fragments inside it.

The nested fragments are shown well at first launch. But the TabSwipeFragment is replaced to other Fragment by FragmentTransaction#replace().
And then when the other fragment is replaced to TabSwipeFragment, the nested fragments in TabSwipeFragment are not shown.

I think it's very related to Android fragment management. 
I'm not sure but it seems to remain the TabSwipeFragment instance in heap to reuse it next time when it is replaced.

Anyway, in my humble opinion, the code should be modified as below for this issue.

diff --git a/library/src/org/holoeverywhere/addon/AddonTabber.java b/library/src/org/holoeverywhere/addon/AddonTabber.java
index 26ebb74..675a7bb 100644
--- a/library/src/org/holoeverywhere/addon/AddonTabber.java
+++ b/library/src/org/holoeverywhere/addon/AddonTabber.java
@@ -199,7 +199,7 @@

```
         protected TabSwipeController createController() {
             return new TabSwipeController(get().getActivity(),
-                    get().getFragmentManager(), get().getSupportActionBar()) {
+                    get().getChildFragmentManager, get().getSupportActionBar()) {
                 @Override
                 protected void onHandleTabs() {
                     AddonTabberF.this.onHandleTabs();
```

Could you please check above code?

**Comment by Prototik** [comment]
Wow, yeah, of course this should be child fragment manager. Could you make a pull request?
