### ISSUE TITLE
com.WazaBe.HoloEverywhere.Switrch nullpointer

### ISSUE THREAD

**Issue by josh1408** [Prototik/HoloEverywhere#581]
Hi.

i recieve this nullpointer error when i try to use the Switch Widget component.

Below is the full stack trace error:

08-19 14:10:37.449: E/AndroidRuntime(31703): java.lang.NullPointerException
08-19 14:10:37.449: E/AndroidRuntime(31703):    at com.WazaBe.HoloEverywhere.Switch.jumpDrawablesToCurrentState(Switch.java:269)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:5256)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:5256)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at android.widget.FrameLayout.jumpDrawablesToCurrentState(FrameLayout.java:189)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at android.view.View.onAttachedToWindow(View.java:12016)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at android.view.View.dispatchAttachedToWindow(View.java:12405)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2511)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at android.view.ViewGroup.addViewInner(ViewGroup.java:3474)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at android.view.ViewGroup.addView(ViewGroup.java:3306)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at android.view.ViewGroup.addView(ViewGroup.java:3251)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at android.view.ViewGroup.addView(ViewGroup.java:3227)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:938)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1460)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:440)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at android.os.Handler.handleCallback(Handler.java:725)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at android.os.Handler.dispatchMessage(Handler.java:92)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at android.os.Looper.loop(Looper.java:137)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at android.app.ActivityThread.main(ActivityThread.java:5328)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at java.lang.reflect.Method.invokeNative(Native Method)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at java.lang.reflect.Method.invoke(Method.java:511)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
08-19 14:10:37.449: E/AndroidRuntime(31703):    at dalvik.system.NativeStart.main(Native Method)

Here is my XML file using the switch

```
<com.WazaBe.HoloEverywhere.Switch
    android:id="@+id/switchOnOff"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_alignParentRight="true"
    android:layout_below="@+id/titleText"
    android:track="@drawable/abs__ab_bottom_solid_dark_holo"
    android:thumb="@drawable/abs__ab_bottom_solid_dark_holo"
    android:textOff="OFF"
    android:textOn="ON" />
```

i manually added         android:track="@drawable/abs__ab_bottom_solid_dark_holo"
        android:thumb="@drawable/abs__ab_bottom_solid_dark_holo" on the switch to try and fix the error but it still throws the same nullpointer error.

Thanks

**Comment by Prototik** [comment]
You are should sometimes update a library. Eg once in half-year.
