### ISSUE TITLE
Importing into eclipse, holoeverywhere library.jar missing

### ISSUE THREAD

**Issue by angwenyi** [Prototik/HoloEverywhere#582]
![error](https://f.cloud.github.com/assets/3678103/992632/ec019372-0982-11e3-84ba-6f4a16e9fb32.jpg)
When i go to Properties->Java Build path, libraries tab, Android dependencies, holoeverywhere library.jar is missing. How do i correct this error.

Thanks in advance.

**Comment by BraisGabin** [comment]
Go to _Order and Export_ and check _Android private Libraries_.

**Comment by angwenyi** [comment]
It's checked, still there there is error.

**Comment by hungnguyenvan** [comment]
Hi !
I have check all item in  Order and Export but it still error.
![holoeverywhere_missing](https://f.cloud.github.com/assets/1708448/999017/90ae2192-0a19-11e3-84fe-8ba111eb70a9.png)
Can you help me to resolve this problem.
Thanks in advance!

**Comment by ekinlyw** [comment]
As you know, HoloEverywhere is using ActionBarSherlock as a reference library.
I think it seems that HoloEverywhere in your workspace doesn't have the ActionBarSherlock as a reference.
Could you please check whether to reference it ? (Project - Properties - Android - Library )

**Comment by BraisGabin** [comment]
> Unable to resolve target android-17

Download the sdk 17 or select a sdk that you have at your local environment.

This is a common error importing libraries, please, use Google before open an issue.

**Comment by hungnguyenvan** [comment]
i have resolved this problem. after select all item in Order and Export, i selecte build target for Holoeverywhere projects. the error dissappeared. Many thanks!
