### ISSUE TITLE
AddonSlider - get selected index

### ISSUE THREAD

**Issue by sebaroesch** [Prototik/HoloEverywhere#584]
Hey and thanks for this amazing piece of code!

I´m currently working on an app which uses ABS, HoloEverywhere and the AddonSlider. I am looking for a way to detect the currently chosen fragment but was not able to find an "easy" way, e.g. by retrieving the selected SliderItem / its index.

Did I just miss the corresponding method or is there no way two to receive it?

It case it is not possible, is there some kind of "best practice" to hold information about the currently selected / active fragment in this use case?

Thanks!

**Comment by Prototik** [comment]
Argh, i said 'close #584'
