### ISSUE TITLE
the text color is abnormal of the drop down item of theAutoCompleteTextView 

### ISSUE THREAD

**Issue by laysion** [Prototik/HoloEverywhere#585]
![screenshot from 2013-08-23 21 28 46](https://f.cloud.github.com/assets/3462692/1016361/4640541e-0bf8-11e3-8f19-ddb5aaa1675f.png)

using the Holo.Theme.Light

thanks in advance!

**Comment by Prototik** [comment]
Fixed, i think :) If you can reproduce this bug again with new version of library - report here and reopen this issue.
