### ISSUE TITLE
NumberPicker displayed abnormal on Sumsung Galaxy S4

### ISSUE THREAD

**Issue by whanjiang** [Prototik/HoloEverywhere#587]
The unselected items are displayed with highlight color, they should show with semi-transparent. It just happens on Sumsung Galaxy S4 so far.

![image](https://f.cloud.github.com/assets/2517949/1023930/00a9058c-0e13-11e3-8df2-042c0e593a7f.png)

**Comment by Prototik** [comment]
It's not HoloEverywhere's NumberPicker, my NP doesn't draw arrows. Maybe you use NP by @SimonVT? Anyway it's not library bug.

**Comment by whanjiang** [comment]
No. It's just HoloEverywhere's NumberPicker, the arrows are added by myself. But the problem is the text displayed. On almost all devices, it displayed well but S4.
