### ISSUE TITLE
size DatePickerFragment

### ISSUE THREAD

**Issue by anleibro** [Prototik/HoloEverywhere#588]
I'm using the Holoeverywhere library and I show a datepickerfragment but it will see very little like in the image.
![screenshot_2013-07-23-17-03-50](https://f.cloud.github.com/assets/4436920/1025493/42ce9120-0e45-11e3-8872-91a19beca5de.png)

The source of the dialog fragment is:

import java.util.Calendar;
import java.util.Date;

import org.holoeverywhere.LayoutInflater;
import org.holoeverywhere.app.Activity;
import org.holoeverywhere.app.AlertDialog;
import org.holoeverywhere.app.DatePickerDialog;
import org.holoeverywhere.app.Dialog;
import org.holoeverywhere.app.DialogFragment;
import org.holoeverywhere.app.Fragment;
import org.holoeverywhere.app.TimePickerDialog;
import org.holoeverywhere.widget.Button;
import org.holoeverywhere.widget.DatePicker;
import org.holoeverywhere.widget.Switch;
import org.holoeverywhere.widget.TimePicker;

import android.content.Context;
import android.content.DialogInterface;
import android.database.Cursor;
import android.os.Build;
import android.os.Bundle;
import android.text.format.DateFormat;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.view.WindowManager;
import android.view.WindowManager.LayoutParams;
import android.widget.CompoundButton;
import android.widget.CompoundButton.OnCheckedChangeListener;

public static class DatePickerFragment extends DialogFragment implements
        DatePickerDialog.OnDateSetListener {

```
private String fechaInicio;
private Button btnDato;

private int year;
private int month;
private int day;

public DatePickerFragment(String fechaInicio, Button btnDato){
    this.fechaInicio = fechaInicio;
    this.btnDato = btnDato;
}

private void inicializaFecha(){
    final Calendar c = Calendar.getInstance();
    year = c.get(Calendar.YEAR);
    month = c.get(Calendar.MONTH);
    day = c.get(Calendar.DAY_OF_MONTH);
}

@Override
public Dialog onCreateDialog(Bundle savedInstanceState) {
    // Si no hemos filtrado ponemos la fecha de hoy
    if (fechaInicio.equals("")) {
        inicializaFecha();
    } else { // Ponemos la fecha filtrada
        Date fechaFiltro = Utilidades.strToDate(fechaInicio,
                InfoApp.formatoVistaDate);
        if (fechaFiltro != null){
            final Calendar c = Calendar.getInstance();
            c.setTime(fechaFiltro);
            year = c.get(Calendar.YEAR);
            month = c.get(Calendar.MONTH);
            day = c.get(Calendar.DAY_OF_MONTH);
        }
        else
            inicializaFecha();
    }

    setCancelable(true);

    // Create a new instance of DatePickerDialog and return it
    Dialog dateDialog = new DatePickerDialog(getActivity(), this, year,
            month, day);

    ((AlertDialog) dateDialog)
            .setOnDismissListener(new DialogInterface.OnDismissListener() {

                @Override
                public void onDismiss(DialogInterface dialog) {
                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1)
                        cancelar = true;
                }
            });

    ((AlertDialog) dateDialog).setButton(
            DialogInterface.BUTTON_NEGATIVE,
            getString(R.string.cancelar),
            new DialogInterface.OnClickListener() {
                @Override
                public void onClick(DialogInterface dialog, int which) {
                    btnDato.setText(fechaInicio);

                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1)
                        cancelar = true; // Necesario pq en la v.4.2
                                            // vuelve a pasar por
                                            // onDateSet
                }
            });

    return dateDialog;
}

public void onDateSet(DatePicker view, int year, int month, int day) {
    if (!cancelar) {
        // Filtramos por la fecha seleccionada
        String monthStr = Integer.toString(month + 1);
        if (monthStr.length() == 1)
            monthStr = "0" + monthStr;

        String dayStr = Integer.toString(day);
        if (dayStr.length() == 1)
            dayStr = "0" + dayStr;

        btnDato.setText(dayStr + "/" + monthStr + "/" + year);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1)
            cancelar = true; // pq lo llama dos veces v4.2
    } else
        cancelar = false;
}
```

}
And I call it:

DialogFragment newFragment;
    newFragment = new DatePickerFragment(boton.getText().toString(), boton);
    newFragment.show(getFragmentManager(), getString(texto));
I have similar code with a TimePickerFragment and it works correctly.

I have generate the styles with the Android Assets Studio.

Thank you!

**Comment by Prototik** [comment]
DatePickerFragment - port from aosp. You can hide title manually or find workaround on stackoverflow/android devs mail list.
