### ISSUE TITLE
classNotFoundException : fragment

### ISSUE THREAD

**Issue by jvanz** [Prototik/HoloEverywhere#589]
Hello, Everybody

First of all, I'm sorry with this is not correct place to put my problem. But I did not find any mail list to ask.

In my app, I have a layout where I change the fragments according as user selection. Well, I have a specific fragment that always throws a exception when I try to put it on the layout.

This is the exception:
http://pastebin.com/UGNxE5q3

I saw on the logcat that system.err throw a exception too, it is:
http://pastebin.com/v8Y9zjme

The XML that we can see on the trace is:
http://pastebin.com/RVDpwtiW

May you help me to discovery what is the problem?
Thank you

**Comment by Prototik** [comment]
Library is too old.

**Comment by jvanz** [comment]
Holo library?

**Comment by Prototik** [comment]
Yes
