### ISSUE TITLE
mChildFragmentManager cannot be resolved to a variable	_HoloFragment.java	

### ISSUE THREAD

**Issue by josh1408** [Prototik/HoloEverywhere#595]
Getting the above error on the latest version of the holoEverywhere library.

i read how you need to update the android support library from action bar sherlock. how can you do that when HoloEverywhere automatically pulls action bar sherlock?

One way i see is that to manually just download the src code for holoeverwhere and actiobar and make the changes there but that defeats the purpose of just calling this library from the pom files dependency?

Can you commit and push this update for us so that the library has the fix?

**Comment by Prototik** [comment]
You are use a standart version of ABS with old support library. HoloEverywhere provide a patched ABS and support library for max integration in the project. You can obtain this version of ABS (with bundled support library) by executing `git submodule update --init` or [download](/Prototik/ActionBarSherlock) it manually.
