### ISSUE TITLE
ListView background turns black while scrolling on non ICS

### ISSUE THREAD

**Issue by jophde** [Prototik/HoloEverywhere#6]
I tried adding a cacehColorHint, but the issue still remains.  

<style name="Theme.HoloEverywhereDark.Sherlock" parent="Theme.Sherlock">
        <item name="android:windowBackground">@drawable/background_holo_dark</item>
        <item name="android:cacheColorHint">#00000000</item>
        <item name="android:buttonStyle">@style/ButtonHoloDark</item>
        <item name="android:editTextStyle">@style/EditTextHoloDark</item>
        <item name="android:alertDialogStyle">@style/alertDialogHoloDark</item>
        <item name="android:radioButtonStyle">@style/radioHoloDark</item>
</style>

**Comment by ChristopheVersieux** [comment]
You may read this great article by Romain Guy: http://android-developers.blogspot.com/2009/01/why-is-my-list-black-android.html

I need to think a little bit before using cacheColorHint, if you want to use it, you can set this property directly in your ListView.

**Comment by ChristopheVersieux** [comment]
Commited: https://github.com/ChristopheVersieux/HoloEverywhere/commit/2c331b04ab3bae6c23bd680da74aa2e0c544da4f
