### ISSUE TITLE
API-11 in Layouts?

### ISSUE THREAD

**Issue by Michael-Zinn** [Prototik/HoloEverywhere#603]
What's with the lint errors in layout files about api level 11? E.g.

HoloEverywhere / library / res / layout-xlarge / select_dialog_item_holo.xml

has an error about the text color since it won't work api < 11?

**Comment by Prototik** [comment]
Am... Thanks. If you'll find some errors - report to this issue please.

**Comment by Michael-Zinn** [comment]
There are many errors similar to this one. Please run a Lint check on the project to see them all. Some of them might be related to already raised issues, e.g. the numberpicker problem.

There are around 66 errors and 370 warnings.
