### ISSUE TITLE
LinearLayout.setSelected() has no effect

### ISSUE THREAD

**Issue by 4nd3250n** [Prototik/HoloEverywhere#605]
Invoking method setSelected(true) has no efeect. The LinearLayout is not marked as selected.

**Comment by Prototik** [comment]
Works perfectly:
![device-2013-09-15-181012](https://f.cloud.github.com/assets/1416030/1145069/188d7822-1def-11e3-9c55-1e5d49f4d7ce.png)

Any default state (exclude state_activated, of course) should work for any view even without HE. If you have a issues with it: bug in your code or platform, but not in in library,

**Comment by 4nd3250n** [comment]
I disagree. A simple LinearLayout inside ListView with default selector does not respond to setSelected(), niether setChecked().
It does work on its own though. In other issue about nine months ago I described that, but nothing until know. Issue was simply closed without resolution.

**Comment by ianhanniballake** [comment]
setItemChecked() is the appropriate method for changing an item to the activated state.

**Comment by Prototik** [comment]
Yeah, ListView control selected state for childs, you don't should to do it manually. End of story.
