### ISSUE TITLE
How to correctly indicate that a View is selected (or activated)

### ISSUE THREAD

**Issue by 4nd3250n** [Prototik/HoloEverywhere#607]
Calling setSelected() does nothing.
Calling setActivated() raises NoSuchMethodException.

What is the correct way to indicate that a View (LinearLayout) is selected and that a user interacts with that particular view.

I have tried a lot of things and nothing works. And it seems wrong to have to manage View states by myself.

**Comment by Prototik** [comment]
Dupe #605

**Comment by 4nd3250n** [comment]
Yet, we still do not have an answer. And this is critical UI issue.

**Comment by croemmich** [comment]
@4nd3250n, give @Prototik some time, he's a busy man. The project is open source, if you want a time frame on a fix, do it yourself.

**Comment by 4nd3250n** [comment]
@croemmich Thank you very much for a completely useless comment. You do not have to state the obvious. Take it as a good natured advice.
My previous comment was related to the fact that issues around this subject appear to be closed yet there is no solution. I do not like the idea of workaround on such a basic feature and I think I am not the only one.
