### ISSUE TITLE
Disable silderMenu and re-enable again

### ISSUE THREAD

**Issue by ScottEAdams** [Prototik/HoloEverywhere#608]
Is it possible to disable the slidermenu for a specific fragment and then re-enable it again when switching back to another fragment. For example in a login screen I can set getSupportActionBar().setDisplayHomeAsUpEnabled(false) to disable the home button but the slidermenu is still active.

**Comment by Prototik** [comment]
You can disable DrawerLayout by invoking `addonSlider().getDrawerLayout().setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED)`.
And reenable again with `DrawerLayout.LOCK_MODE_UNLOCKED`.

**Comment by ScottEAdams** [comment]
thanks btw. Works great.

**Comment by ScottEAdams** [comment]
I seem to have run into the opposite of this problem with the latest release now that its using the navigation items for the slidermenu. The DrawerLayout.LOCK_MODE_LOCKED_CLOSED works for locking the swipe but setDisplayHomeAsUpEnabled(false) doesnt disable the slidermenu. Any ideas?

**Comment by ScottEAdams** [comment]
my bad. works as it should.
