### ISSUE TITLE
Problems with resources on import project

### ISSUE THREAD

**Issue by fintara** [Prototik/HoloEverywhere#612]
When importing the 4 projects from Git (Eclipse), I get many errors, such as 

```
attrs.xml:142: error: Attribute "windowMinWidthMajor" has already been defined
themes-core.xml:2: error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat'.
```

The full list is here http://pastebin.com/W3wpHeBy .
Any thoughts? :/

**Comment by Prototik** [comment]
Eclipse build is broken now. Wait for official support.
