### ISSUE TITLE
Problem with "res-abc" folder in Eclipse

### ISSUE THREAD

**Issue by waninkoko** [Prototik/HoloEverywhere#613]
Hi,

I'm having issues when I try to use the latest master branch in Eclipse. The problem is that Eclipse doesn't parse the resources inside the "res-abc" folder.

I tried to find a way to make Eclipse parse that folder, but I couldn't find anything.

Any solutions?

Thanks.

**Comment by waninkoko** [comment]
As a workaround I copied everything from "res-abc" to "res" (and I added the 'abc_' prefix to some files).

**Comment by kkazakov** [comment]
Is it possible to add support for ant build system (as I see it, works great under gradle), or at least tell us how to proceed in this situation? It's pretty ugly to copy files like this.

**Comment by josear** [comment]
Even copying this file I am not able to build holoeverywhere using Eclipse... and the Wiki is not up to date (the reference to ABS is still in the document). So build in Eclipse is broken?

**Comment by waninkoko** [comment]
I can push my repo that works with Eclipse if needed.

**Comment by josear** [comment]
What did you do to make it work? Only copy the res-abc directory?
It seems there is a problem with the support library. I even tried to add the v7 but it didn't work.

**Comment by Prototik** [comment]
Yes, Eclipse and maven build is broken now. Wait an official support of it.

**Comment by waninkoko** [comment]
If anyone wants to use the latest HoloEverywhere with Eclipse, you can try my fork for now: https://github.com/lowlevel-studios/HoloEverywhere
