### ISSUE TITLE
HoloThemeException when Theme extends from Holo.Theme

### ISSUE THREAD

**Issue by william-ferguson-au** [Prototik/HoloEverywhere#623]
I have a theme whose parent is Holo.Theme
   <style name="JumbleeTheme" parent="Holo.Theme"> 

But I'm seeing instances of the following when starting my app for a small range of devices. Specifically for
  Galaxy Tab 10.1 P7510 10.1" 800_1280 149ppi Android#4.0 .4
  HT EVO 4G 4.3" 480_800 217ppi Android#2.3.5
  Galaxy S2 4.3" 480*800 217ppi Android#2.3.5

android.support.v4.app._HoloActivity$HoloThemeException: You must apply Holo.Theme, Holo.Theme.Light or Holo.Theme.Light.DarkActionBar theme on the activity (SplashActivity) for using HoloEverywhere
at android.support.v4.app._HoloActivity.onInit(SourceFile:482)
at android.support.v4.app._HoloActivity.forceInit(SourceFile:223)
at org.holoeverywhere.app.Activity.onCreate(SourceFile:215)
at au.com.xandar.jumblee.AbstractAppActivity.onCreate(SourceFile:80)
at au.com.xandar.jumblee.splash.SplashActivity.onCreate(SourceFile:34)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1615)

**Comment by Prototik** [comment]
How i can reproduce this bug? Code? Or something?

**Comment by william-ferguson-au** [comment]
Sergey, I wish I knew.
As far as I can tell it is crashing on starting up my Main Launcher
Activity, but only sometimes and only for those few devices that I listed.

There is no strange code. I am simply extending Holo.Theme in HE-1.6.8

**Comment by Prototik** [comment]
Well, you can disable this exception like this:

``` java
@Override
protected Holo onCreateConfig(Bundle savedInstanceState) {
  Holo config = super.onCreateConfig(savedInstanceState);
  config.ignoreThemeCheck = true;
  return config;
}
```

**Comment by william-ferguson-au** [comment]
What is the fallout of ignoring that check going to be?

Doesn't it mean that there is no "Holo.Theme" attribute for the Activity's
style? In which case it's hard to know what other style attribute might be
missing/mangled.

**Comment by Prototik** [comment]
I /don't know/. Really. In AOSP this code absolutely right. Fucked android by gnusmaS i hate.

**Comment by william-ferguson-au** [comment]
:-) OK thanks.

I'll switch off the check and see what happens.
It can't be any worse than at the moment.
