### ISSUE TITLE
Maven...

### ISSUE THREAD

**Issue by rsimoni** [Prototik/HoloEverywhere#627]
Hello, would you mind telling me what I'm doing wrong?

In the Maven page, I read to use support-v4 r18 and then to follow istructions for the preferred IDE.
In Eclipse, I read at step 8:

 File - New - Other - Android Project from Existing Code, specify ActionBarSherlock/actionbarsherlock folder. Press Finish 

but I don't see any ActionbarSherlock folder?!?

Thanks in advance
Bye

**Comment by Prototik** [comment]
> Warning! Eclipse and Maven build is broken, now work only AStudio/Idea via Gradle. Eclipse support will be re-add in 2.0.0 release

Yeah, all guides about Eclipse/Maven deprecated now until 2.0 release.

**Comment by rsimoni** [comment]
Sorry I haven't read it.
I have found a document in Wiki https://github.com/Prototik/HoloEverywhere/wiki/Maven on how to use it with 1.6.8
Would you mind telling me if it is broken too?
Thanks
Bye

**Comment by Prototik** [comment]
Well, yeah, use a power of git! :)
Something like this: `git clone https://github.com/Prototik/HoloEverywhere.git --branch holoeverywhere-1.6.8`
And next by the manual...

**Comment by rsimoni** [comment]
Thanks
