### ISSUE TITLE
Gradle build fail with actionbarcompat

### ISSUE THREAD

**Issue by emptywee** [Prototik/HoloEverywhere#629]
Hi!
Could you read this issue https://github.com/chrisbanes/ActionBar-PullToRefresh/issues/116 ? Chris says that it's the problem of HoloEverywhere with ActionBarCompat library. Is it true and what can be done about it?

Thank you.

**Comment by Prototik** [comment]
HoloEverywhere contains a built-in patched version of abc. AB-PTR use a standard abc version by google. You should exclude a abc in extra-abc module and build it under HoloEverywhere library.

**Comment by emptywee** [comment]
Спасибо, Сергей. Я немного нуб еще во всем этом, поэтому попробую Криса уговорить помочь :)

**Comment by Prototik** [comment]
Грубо говоря, надо скопировать прослойку extra-abc и собрать ее поверх только лишь HE.

**Comment by emptywee** [comment]
Да в этой кривущей на сей момент Андроид Студии надо еще постараться, чтобы проект не развалился :) Но буду пробовать, спасибо за совет!

**Comment by emptywee** [comment]
Хм, сделал такие зависимости в build.gradle у AB-PTR extra-abc:

```
dependencies {
//    compile project(':library')
    compile 'com.github.chrisbanes.actionbarpulltorefresh:library:0.7.+'

//    compile "com.android.support:appcompat-v7:18.0.+"
      compile project(':HoloEverywhere-library')

}
```

И проект сбилдился нормально. Уже прогресс :)

**Comment by flocsy** [comment]
can you help for those that don't speak Russian? What is the correct way to use HE + AB-PTR? Currently I tried this:

<code>
apply plugin: 'holoeverywhere-app'
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.holoeverywhere:plugin:0.2.+'
    }
}
holoeverywhere {
    addons {
        preferences
    }
    library {
        version = '2.0.+'
    }
    supportV4 {
        version = '19.0.1'
    }
}
</code>

// until this point everything compiles, however if I add:
<code>
dependencies {
    compile 'com.github.chrisbanes.actionbarpulltorefresh:extra-abc:+'
}
</code>

// then I get the following errors:
Attribute "spinnerMode" has already been defined
Attribute "popupPromptView" has already been defined
Attribute "disableChildrenWhenDisabled" has already been defined

if instead the extra-abc dependency I use the one mentioned here in Russian, will I be able to use it with API v7 or only v14 (which kind of makes both appcompat and holoeverywhere irrelevant)?
<code>
compile 'com.github.chrisbanes.actionbarpulltorefresh:library:+'
</code>

**Comment by Prototik** [comment]
You should exclude any 'com.android.support:appcompat-v7' dependencies from all libraries which you are used. Like this:

```
dependencies {
  compile 'com.github.chrisbanes.actionbarpulltorefresh:extra-abc:+' {
    exclude group: 'com.android.support', module: 'appcompat-v7'
  }
}
```

**Comment by flocsy** [comment]
compile ('com.github.chrisbanes.actionbarpulltorefresh:extra-abc:+') {
        exclude group: 'com.android.support', module: 'appcompat-v7'
}
this worked eith the "(", ")" added
