### ISSUE TITLE
Menu in TabSwipeFragment

### ISSUE THREAD

**Issue by anleibro** [Prototik/HoloEverywhere#630]
I have a TabSwipeFragment with three Fragment. I want a menu but the onCreateOptionsMenu function is not called.

I put the property setHasOptionsMenu to true in the Fragment
@Override
    public void onCreate(Bundle savedInstanceState) {
        setHasOptionsMenu(true);
        setMenuVisibility(true);
        super.onCreate(savedInstanceState);
    }

And the load of the menu in onCreateOptionsMenu. I tried in the Fragment and in the TabSwipeFragment but doesn't appear.

@Override
    public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
        inflater.inflate(R.menu.menu_calendario_detalle, menu);
        super.onCreateOptionsMenu(menu, inflater);
    }

The imports are:
import com.actionbarsherlock.view.Menu;
import com.actionbarsherlock.view.MenuInflater;
import com.actionbarsherlock.view.MenuItem;

Thank you!

**Comment by Prototik** [comment]
HE 1.6.8 use a ABS. ABS build with support library v4 r7. Nested fragments was added only in r11. You can patch a ABS manually or switch to latest version of HE library which build under appcompat, not ABS.

**Comment by anleibro** [comment]
And how can I patch the ABS? 
Changing the support library or it is more dificult?
I have ABS 4.3.1.

Thank you

**Comment by Prototik** [comment]
See JakeWharton/ActionBarSherlock#828

**Comment by anleibro** [comment]
Thank you. I will see this post.
