### ISSUE TITLE
black dialog boxes in alert dialogs in android 2.x versions 

### ISSUE THREAD

**Issue by mehdifanai** [Prototik/HoloEverywhere#631]
I am currently using crashlytics to log reports but what i see is a black dialog. I had the same issue with Apprater which was importing native android dialog and not the holoeverywhere's. How can this issue be fixed?
Changing crashlytics library source is not an option because i dont have access.
How can they fix the issue?
here is the photo of the issue:
![device-2013-09-17-202207](https://f.cloud.github.com/assets/979068/1174818/4c4d3fdc-214e-11e3-861f-33ff1fae0103.png)

**Comment by Prototik** [comment]
Well, /all/ other libraries not supported with HoloEverywhere. All closed-source libraries. You can ask crashlytics team for special version of library with bindings on HE library. I cannot help you anyway.
