### ISSUE TITLE
Gradle build problem on 'version' field

### ISSUE THREAD

**Issue by almozavr** [Prototik/HoloEverywhere#634]
Using preferences and library as a 'compile project(...)' dependency gives gradle build error "specified for property 'bundle' does not exist" due to allprojects' field 'version' value – removing this field helps building successfully.
Seems like android-plugin bug, gradle generates wrong name .aar, see [google group thread](https://groups.google.com/d/msg/adt-dev/CSDCNB3j7Ms/xpshHsfZGMoJ)

My structure

```
/MyAppRoot
--MyApp
--libs
----HoloEverywhere
------library
------addons/preferences
```

`settings.gradle`

``` xml
include 'library'
include 'libs:HoloEverywhere:addons:preferences'
// Define global folder references
project(':library').projectDir = new File(settingsDir, 'libs/HoloEverywhere/library')
```

_the problem is_
`HoloEverywhere/build.gradle`

```
allprojects {
  group = 'org.holoeverywhere'
  version = '2.0.0-SNAPSHOT' // <= generates wrong aar (with '2.0.0-snapshot' prefix)

  ...
}

```

**Comment by Prototik** [comment]
In latest versions of android-gradle plugin it's fixed.

**Comment by bobbyflowstate** [comment]
I just recently installed Android Studio and the bug still exists.  Or is there something else I'm doing wrong?

**Comment by jaredpetker** [comment]
I also ran into the same issue, removing the version line fixed my compilation.

**Comment by Guihgo** [comment]
i also.....

Could not find property 'Compile' on root project 'HoloEverywhere'.

Consult IDE log for more details (Help | Show Log)
