### ISSUE TITLE
Roboto fonts sometimes hold the entire ativity in memory

### ISSUE THREAD

**Issue by cinash** [Prototik/HoloEverywhere#638]
The last activity in which roboto fonts were used is held in memory by font (for example
ROBOTO_REGULAR class org.holoeverywhere.FontLoader is a gc root).
This is causing nasty memory leaks :(

**Comment by BraisGabin** [comment]
Yes, in fact I was implementing a fix to this problem this weekend. I think that I will be able to push it tomorrow.
