### ISSUE TITLE
Overflow with black text when using mixed theme.

### ISSUE THREAD

**Issue by HenriqueRocha** [Prototik/HoloEverywhere#639]
I've updated to the new HE2.0 and I'm experiencing one bug in the overflow menu that was only happening before on some 2.x devices.

Also happens in the latest demo if using the mixed theme.

![bug_black_on_grey](https://f.cloud.github.com/assets/140122/1191252/e3a72338-244c-11e3-826b-868d25472958.png)
![he_demo_bug](https://f.cloud.github.com/assets/140122/1191259/fbec74ac-244c-11e3-860e-5bdf3aeffc0d.png)

**Comment by Prototik** [comment]
Duplicate #636. Also it's only 2.0 snapshot, i don't recommend use it for release application.
