### ISSUE TITLE
IllegalStateException in ListView

### ISSUE THREAD

**Issue by HenriqueRocha** [Prototik/HoloEverywhere#641]
Hi, I'm freaking out with this bug for some hours and I can't solve it.

It happens on my app when I scroll down to the end of a list, show a loading spinning wheel, go back up fast and down again.

I think it might be related to the removeFooterView method of the ListView (might help you see if the bug is on your side).

Please let me know if you need more information.

Thanks very much in advance.

java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. [in ListView(16908298, class org.holoeverywhere.widget.ListView) with Adapter(class org.holoeverywhere.widget.HeaderViewListAdapter)]
E/AndroidRuntime(17388):    at android.widget.ListView.layoutChildren(ListView.java:1545)
E/AndroidRuntime(17388):    at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4082)
E/AndroidRuntime(17388):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
E/AndroidRuntime(17388):    at android.view.Choreographer.doCallbacks(Choreographer.java:562)
E/AndroidRuntime(17388):    at android.view.Choreographer.doFrame(Choreographer.java:531)
E/AndroidRuntime(17388):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
E/AndroidRuntime(17388):    at android.os.Handler.handleCallback(Handler.java:730)
E/AndroidRuntime(17388):    at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(17388):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(17388):    at android.app.ActivityThread.main(ActivityThread.java:5103)
E/AndroidRuntime(17388):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(17388):    at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime(17388):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
E/AndroidRuntime(17388):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime(17388):    at dalvik.system.NativeStart.main(Native Method)

**Comment by Prototik** [comment]
I cannot reproduce this bug. You can modify issue project for cause this crash.

**Comment by kofi-de-com** [comment]
Hi Prototik,
just came across the solution for this bug. You can for example reproduce that bug by removing a footer view from a list while scrolling. A simple solution is to call notifyDataSetChanged() like this:

```
public boolean removeFooter(View v) {
    for (int i = 0; i < mFooterViewInfos.size(); i++) {
        ViewInfo info = mFooterViewInfos.get(i);
        if (info.view == v) {
            mFooterViewInfos.remove(i);
            mAreAllFixedViewsSelectable =
                    areAllListInfosSelectable(mHeaderViewInfos)
                    && areAllListInfosSelectable(mFooterViewInfos);
            notifyDataSetChanged();
            return true;
        }
    }
    return false;
}

public boolean removeHeader(View v) {
    for (int i = 0; i < mHeaderViewInfos.size(); i++) {
        ViewInfo info = mHeaderViewInfos.get(i);
        if (info.view == v) {
            mHeaderViewInfos.remove(i);
            mAreAllFixedViewsSelectable =
                    areAllListInfosSelectable(mHeaderViewInfos)
                    && areAllListInfosSelectable(mFooterViewInfos);
            notifyDataSetChanged();
            return true;
        }
    }
    return false;
}
```
