### ISSUE TITLE
ClassCastException when use custom menu issued#632.

### ISSUE THREAD

**Issue by hungnguyenvan** [Prototik/HoloEverywhere#646]
Hi!
I have update new issue. But when i run demo ,it crashed. Log cat bellow:
FATAL EXCEPTION: main
09-29 22:11:42.549: E/AndroidRuntime(3954): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.holoeverywhere.issues/org.holoeverywhere.issues.i632.MainActivity}: java.lang.ClassCastException: org.holoeverywhere.slider._SliderMenuFragment
09-29 22:11:42.549: E/AndroidRuntime(3954):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2669)
09-29 22:11:42.549: E/AndroidRuntime(3954):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2685)
09-29 22:11:42.549: E/AndroidRuntime(3954):     at android.app.ActivityThread.access$2300(ActivityThread.java:126)
09-29 22:11:42.549: E/AndroidRuntime(3954):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)
09-29 22:11:42.549: E/AndroidRuntime(3954):     at android.os.Handler.dispatchMessage(Handler.java:99)
09-29 22:11:42.549: E/AndroidRuntime(3954):     at android.os.Looper.loop(Looper.java:123)
09-29 22:11:42.549: E/AndroidRuntime(3954):     at android.app.ActivityThread.main(ActivityThread.java:4633)
09-29 22:11:42.549: E/AndroidRuntime(3954):     at java.lang.reflect.Method.invokeNative(Native Method)
09-29 22:11:42.549: E/AndroidRuntime(3954):     at java.lang.reflect.Method.invoke(Method.java:521)
09-29 22:11:42.549: E/AndroidRuntime(3954):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
09-29 22:11:42.549: E/AndroidRuntime(3954):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-29 22:11:42.549: E/AndroidRuntime(3954):     at dalvik.system.NativeStart.main(Native Method)
09-29 22:11:42.549: E/AndroidRuntime(3954): Caused by: java.lang.ClassCastException: org.holoeverywhere.slider._SliderMenuFragment
09-29 22:11:42.549: E/AndroidRuntime(3954):     at org.holoeverywhere.slider.SliderMenu.makeDefaultMenu(SliderMenu.java:395)
09-29 22:11:42.549: E/AndroidRuntime(3954):     at org.holoeverywhere.addon.AddonSlider$AddonSliderA.obtainDefaultSliderMenu(AddonSlider.java:156)
09-29 22:11:42.549: E/AndroidRuntime(3954):     at org.holoeverywhere.addon.AddonSlider$AddonSliderA.obtainDefaultSliderMenu(AddonSlider.java:143)
09-29 22:11:42.549: E/AndroidRuntime(3954):     at org.holoeverywhere.issues.i632.MainActivity.onCreate(MainActivity.java:17)
09-29 22:11:42.549: E/AndroidRuntime(3954):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
09-29 22:11:42.549: E/AndroidRuntime(3954):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2633)
09-29 22:11:42.549: E/AndroidRuntime(3954):     ... 11 more
Can you help me to fix it!
Many thanks!

**Comment by hungnguyenvan** [comment]
i fixed it. _SliderMenuFragment must be extended from org.holoeverywhere.app.ListFragment; not org.holoeverywhere.app.Fragment;

**Comment by youxiachai** [comment]
I have the same problem ....

**Comment by youxiachai** [comment]
I fix it ! you can see the pull request .
