### ISSUE TITLE
Duplicate Fragments break View on device rotate 

### ISSUE THREAD

**Issue by davidp3** [Prototik/HoloEverywhere#647]
To begin, I'm using the TabSwipeActivity in the latest release (1.6.8) with my Fragments... augmented with the fix for TabSwipeActivity that I spelled out in bug #569.  (The fix was to add a constructor to TabSwipeActivity that calls addonTabber() ).

There is nothing special going on with my TabSwipeActivity or my Fragments.  Specifically, my Fragments and Activity are NOT labeled to be preserved on device rotation or keyboardHidden.

At first, the view looks fine on a device rotation  The view reorients and the layout is redone to fit the new aspect ratio.  The only immediately noticable issue is that the  view returns to the first tab.  

I can tell from the debugger that the Fragments are both recreated by the correct Fragment save/restore mechanism in the Activity AND by the TabSwipeController::reloadTabs() calling onHandleTabs.  This means that, on rotate, I end up with two copies of each Fragment.

The menu associated with my Fragments shows up fine, but the biggest problem is that they are apparently wired to the Fragment instance that is not on screen.  So, for example, my onOptionsItemSelected routine is called when I press a button but it controls an invisible Fragment -- the screen isn't affected by my menu handler.

I haven't been able to figure out how TabSwipeActivity is supposed to work but it looks like reloadTabs() is supposed to destroy the old tabs and then create brand new ones.  This seems like it would be a problem for data since the new instances are not restored from a Bundle or anything... they are just brand new.

I have been able to cheat and resolve the multiple Fragment instance problem by not calling the super instance of onSaveInstanceState in my TabSwipeActivity.  This dodges the system's Fragment save/restore mechanism (correct by Android docs) but allows the reloadTabs() setup to create new instances.  This actually works... except, of course, that the new Fragments don't have the right instance data, as I said in the last paragraph.  (Also, who knows what other problems would arise from not calling super.onSaveInstanceState().)

**Comment by Prototik** [comment]
Hm... Yeah, for each rotation (or any other configuration change, like locale switch) activity is recreate all fragments (not only in TabSwipeActivity/Fragment). For saving state fragments respond a FragmentStatePagerAdapter, for saving a current position in tabs - ABC. If you have some issues with it - probably you're doing something wrong.
