### ISSUE TITLE
Use themes created with http://android-holo-colors.com/

### ISSUE THREAD

**Issue by intrications** [Prototik/HoloEverywhere#65]
Can HoloEverywhere be used (easily) with this Holo theme creator?

http://android-holo-colors.com/

The themes created look similar but I can't test it at the moment because I'm having trouble getting HoloEverywhere to work at the moment due to all the changes.

I think just overwriting the images will work since they are all named with the Android default names.

If it works then it might be worth adding to the Readme.

**Comment by Prototik** [comment]
Do you mean replacing the default images on Holo counterparts? No, it is not possible for this application must have the package 'android'.
