### ISSUE TITLE
Wrong layout with android:layout_margin*

### ISSUE THREAD

**Issue by nmakoto** [Prototik/HoloEverywhere#654]
There is a problem on old devices (tested on 2.3.3) with layout when added **android:layout_margin** attributes. **marginLeft** added to the right.

``` lang=xml
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
     android:layout_width="match_parent"
     android:layout_height="wrap_content"
     android:layout_marginLeft="20dp"
     android:layout_marginRight="20dp"
     android:background="@android:color/background_light">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="@string/hello_world"
        android:color="@android:color/darker_gray"/>
</LinearLayout>
```

Result (left part is _4.1.2_, right is _2.3.3_):
![2013-10-03--16-20-04--screenshot](https://f.cloud.github.com/assets/183187/1260778/e0897bc6-2c15-11e3-8ce0-a30a39f69915.png)

**Comment by Prototik** [comment]
When you set a content view you inflate this layout into FrameLayout.
FL have a very strange behavior with margins. [You can read it.](http://stackoverflow.com/questions/15000225/layout-marginleft-works-as-right-on-android-api-11-when-view-in-framelayout)
Just use a padding instead margin. Or nested layouts.
