### ISSUE TITLE
java.lang.NoSuchFieldError: org.holoeverywhere.preference.R$id.prefs_frame

### ISSUE THREAD

**Issue by hungnguyenvan** [Prototik/HoloEverywhere#656]
Hi everybody!
I use PreferenceActivity of Holoeverywhere lib. But i can't start preferecen activity, it throws java.lang.NoSuchFieldError: org.holoeverywhere.preference.R$id.prefs_frame.
Some one help me to solve it!
Thanks!

**Comment by Prototik** [comment]
Full stacktrace please.

**Comment by hungnguyenvan** [comment]
Full stacetrace here:
10-04 22:30:21.592: E/AndroidRuntime(30605): FATAL EXCEPTION: main
10-04 22:30:21.592: E/AndroidRuntime(30605): java.lang.NoSuchFieldError: org.holoeverywhere.preference.R$id.prefs_frame
10-04 22:30:21.592: E/AndroidRuntime(30605):    at org.holoeverywhere.preference.PreferenceActivity.onCreate(PreferenceActivity.java:581)
10-04 22:30:21.592: E/AndroidRuntime(30605):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
10-04 22:30:21.592: E/AndroidRuntime(30605):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2633)
10-04 22:30:21.592: E/AndroidRuntime(30605):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2685)
10-04 22:30:21.592: E/AndroidRuntime(30605):    at android.app.ActivityThread.access$2300(ActivityThread.java:126)
10-04 22:30:21.592: E/AndroidRuntime(30605):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)
10-04 22:30:21.592: E/AndroidRuntime(30605):    at android.os.Handler.dispatchMessage(Handler.java:99)
10-04 22:30:21.592: E/AndroidRuntime(30605):    at android.os.Looper.loop(Looper.java:123)
10-04 22:30:21.592: E/AndroidRuntime(30605):    at android.app.ActivityThread.main(ActivityThread.java:4633)
10-04 22:30:21.592: E/AndroidRuntime(30605):    at java.lang.reflect.Method.invokeNative(Native Method)
10-04 22:30:21.592: E/AndroidRuntime(30605):    at java.lang.reflect.Method.invoke(Method.java:521)
10-04 22:30:21.592: E/AndroidRuntime(30605):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
10-04 22:30:21.592: E/AndroidRuntime(30605):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-04 22:30:21.592: E/AndroidRuntime(30605):    at dalvik.system.NativeStart.main(Native Method)

Thanks you in advance!
