### ISSUE TITLE
How to remove the action to open the slider menu from swipe ?

### ISSUE THREAD

**Issue by tzmst** [Prototik/HoloEverywhere#659]
I have a bit of a struggle to remove the action of swiping to open the slider menu. 

Can someone point me in what class the event is handled ? It would be much appreciated.

Thanks in advance,
Vlad

**Comment by Prototik** [comment]
`addonSlider().getDrawerLayout().setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED)`

SliderMenu - wrapper under Slider Addon, which uses DrawerLayout from support package by default.

**Comment by tzmst** [comment]
thx
