### ISSUE TITLE
Wrong dialog position with app, using maven and build in idea-13 with idea-maven-import

### ISSUE THREAD

**Issue by Rutton** [Prototik/HoloEverywhere#660]
```
  Hello,
```

I understand that time for maintaining he is limited. So thanks for your fine work. 

My app uses he-1.6.8, is maven based and I want to build it also in Intellij-13. The maven build app runs fine on Android 4.2 genymotion. The app build done by idea shows the wrong position of a fragment with an alert dialog (at the top of the screen, not centered vertical). Compared to that, the same procedure (he-1.6.8 imported via maven importer, and he-demo build in idea-13) positions the dialogs fine. Also example alert dialog code from he-demo shows the wrong position.

I would guess resource/style problems, but e.g. using he-default themes (I use a custom one from abs styler) in manifest did not change the situation. Anybody a suggestion under what circumstances he might fail with positioning Dialogs?

**Comment by Prototik** [comment]
show code for dialogfragment

**Comment by Rutton** [comment]
https://github.com/sozialhelden/wheelmap-android/blob/master/wheelmap/wheelmap/src/main/java/org/wheelmap/android/fragment/SearchDialogFragment.java
(one of them - all of them are alert dialog fragments)

I know that there is a setDialogType, but adding that like in the sample
public DialogsAlertDialogFragment() {
        setDialogType(DialogType.AlertDialog);
    }
did not make a difference.

**Comment by Prototik** [comment]
Genymotion bug, i can reproduce this issue only with it.
