### ISSUE TITLE
The Tab with Actionbar

### ISSUE THREAD

**Issue by LiuCao** [Prototik/HoloEverywhere#661]
Hi. Everybody
---When i add "getSupportActionBar().setDisplayShowHomeEnabled(false);" in DemoActivity .

---Then select "Other-Addon:Tabber-Tab navigation" , Why tab exchanged positions with actionbar

--- See screenshot : https://github.com/LiuCao/test/blob/master/README.md

Thanks!!

**Comment by Prototik** [comment]
Bug of Android API, which [was already reported](https://code.google.com/p/android/issues/detail?id=36191) to tracker. Support library also have a this bug because library port all behavior of ICS.

You can try solution by @RedNifre from JakeWharton/ActionBarSherlock#674:

> We dealt with this by using a transparent icon with width = 0.

**Comment by LiuCao** [comment]
@Prototik 
Oh!
I had not seen this reported.
Thank you for your help!
