### ISSUE TITLE
Troubles with dialogs, and layouts on Sony devices

### ISSUE THREAD

**Issue by anuf** [Prototik/HoloEverywhere#662]
I am using Holoeverywhere version 1.6.8 and I have found some issues with old Sony devices (ST18i, ST27a, WT19a, R800i, MT27i). The problems I am having are:
Dialogs do not show contents. 
LinearLayout leave a long empty space at the bottom, after last element.
RelativeLayout takes more height than indicated

**Comment by BraisGabin** [comment]
Duplicate #484.
