### ISSUE TITLE
error: Attribute "titleTextStyle" has already been defined

### ISSUE THREAD

**Issue by AntonKosov** [Prototik/HoloEverywhere#663]
Здравствуйте!

Возникла проблема с использованием HoloEverywhere. Не получается откомпилироваться. Для сборки проекта использую maven.

Взял последние исходники HoloEverywhere и вашего форка ActionBarSherlock. Откомпилировал их (не без бубна :) ). Инсталлировал в локальный maven репозиторий проекта:
1. Саму библиотеку holoeverywhere (library-2.0.0-SNAPSHOT.apklib).
2. addon-preferences-2.0.0-SNAPSHOT.apklib
3. actionbarsherlock-4.3.2-SNAPSHOT.apklib
Для модифицированного support library подключил репозиторий https://raw.github.com/Prototik/HoloEverywhere/repo

В pom.xml подключаю:

```
    <dependency>
        <groupId>com.actionbarsherlock</groupId>
        <artifactId>actionbarsherlock</artifactId>
        <version>4.3.2-SNAPSHOT</version >
        <type>apklib</type>
        <exclusions>
            <exclusion>
                <groupId>com.google.android</groupId>
                <artifactId>support-v4</artifactId>
            </exclusion>
        </exclusions>
    </dependency>

    <dependency>
        <groupId>org.holoeverywhere</groupId>
        <artifactId>library</artifactId>
        <version>2.0.0-SNAPSHOT</version>
        <type>apklib</type>
        <exclusions>
            <exclusion>
                <groupId>com.android.support</groupId>
                <artifactId>support-v4</artifactId>
            </exclusion>
        </exclusions>
    </dependency>

    <dependency>
        <groupId>org.holoeverywhere</groupId>
        <artifactId>addon-preferences</artifactId>
        <version>2.0.0-SNAPSHOT</version >
        <type>apklib</type>
        <exclusions>
            <exclusion>
                <groupId>com.android.support</groupId>
                <artifactId>support-v4</artifactId>
            </exclusion>
        </exclusions>
    </dependency>

    <dependency>
        <groupId>com.android.support</groupId>
        <artifactId>support-v4</artifactId>
        <version>18.0.1</version>
    </dependency>
```

При компиляции (mvn clean verify) получаю кучу ошибок типа
/home/.../target/unpack/apklibs/com.actionbarsherlock_actionbarsherlock_apklib_4.3.2-SNAPSHOT/res/values/abs__attrs.xml:4: error: Attribute "titleTextStyle" has already been defined

Т.е. на сколько понимаю, эти атрибуты определены и в holoeverywhere, и в actionbarsherlock.

Мне кажется, что я делаю что-то не так при подключении holoeverywhere. Support library мне нужна обязательно.

Что я делаю не так? Где я ошибся?

**Comment by Prototik** [comment]
2.0.0 собирается без шерлока. Вы или его выкиньте, либо 1.6.8 используйте.

**Comment by AntonKosov** [comment]
Т.е. теперь нужно выбрать либо шерлок либо holoeverywhere?
Т.е. весь функционал шерлока у вас будет?

**Comment by Prototik** [comment]
Т.е. теперь master ветка базируется на ActionBarCompat, а не на ABS.
Ну и советую на будущее все-таки писать на англицком, у нас тут еще @BraisGabin рулит репозиторием и ему не очень удобно постоянно терзать переводчик :)

**Comment by AntonKosov** [comment]
Спасибо за ответ! Отлично, я всё понял. Про английский тоже :)

**Comment by AntonKosov** [comment]
Is it safe to use version from master branche in the final release?

**Comment by Prototik** [comment]
No, -snapshot postfix should to warn you.

**Comment by AntonKosov** [comment]
When the expected release of the final version holoeverywhere 2.0.0?
