### ISSUE TITLE
ActionBar Menu text items are black text on black background (Light DarkActionBar Theme)

### ISSUE THREAD

**Issue by simone201** [Prototik/HoloEverywhere#664]
I had been using the library for a while, with ABS, and now changed to the newest on github sources.
I got working everything except that submenus in ActionBar have a black text on a black background (text items in menus), while before it was perfect.

I am using Holo.Theme.Light.DarkActionBar in my app as base theme, and also tried to declare actionMenuTextColor as white in the styles xml, but nothing changes.

Any ideas?

Thanks a lot in advance!

PS: if you need some screenshots, let me know! I'm testing on Android 4.3 on my Nexus 4 and also 4.3 on my Nexus 7 2012.

**Comment by Prototik** [comment]
Duplicate #636
