### ISSUE TITLE
onSearchRequested() not called when search icon is pressed

### ISSUE THREAD

**Issue by HenriqueRocha** [Prototik/HoloEverywhere#666]
I assume this is a HoloEverywhere bug.
I'm overriding onSearchRequested() because I need to add an integer to the intent fired when I start a search but the method never gets called.
Please let me know if you need further information on this.
Thanks.

**Comment by Prototik** [comment]
onSearchRequested and other hooks of SearchManager isn't part of HoloEverywhere. You can use SearchView backport and proceed search manually. I cannot help you with it.
