### ISSUE TITLE
Using ChooserActivity to customize view!

### ISSUE THREAD

**Issue by TheFinestArtist** [Prototik/HoloEverywhere#669]
I want to change share activity using holoeverywhere's chooseractivity. Added chooseractivity in manifest.xml but android share doesn't seem to using holoeverywhere's chooseractivity.

I also want my share activity looks like this image, is there any comments for me?

Thanks.
![share-text-screenshot](https://f.cloud.github.com/assets/3123741/1414243/d9274aa0-3e73-11e3-8b38-352cf506b5c4.png)

```
            Intent sendIntent = new Intent(Intent.ACTION_SEND);
            sendIntent.putExtra(Intent.EXTRA_TEXT, getString(R.string.share_music_off_text));
            sendIntent.setType("text/plain");
            Intent chooser = IntentCompat.createChooser(sendIntent, getResources().getText(R.string.share_music_off));
            startActivity(chooser);
```

**Comment by Prototik** [comment]
Holoeverywhere's ChooserActivity works only with IntentCompat.createChooser, nothing other (including Intent.createChooser and share providers).
