### ISSUE TITLE
AlertDialog Buttons with setItems

### ISSUE THREAD

**Issue by toadzky** [Prototik/HoloEverywhere#67]
When using setItems, the buttons don't show up. It's a quick fix really, you just need to apply a layout weight to the list so it only fills left over space after the other views are allocated.

I added 

``` java
list.setLayoutParams(new LinearLayout.LayoutParams(MATCH_PARENT, MATCH_PARENT, 1.f));
```

to the setItems methods.

**Comment by Prototik** [comment]
f77568910d379545b1d17cfebda6bff62145ef31
