### ISSUE TITLE
NumberPicker is displayed 'Dark' with Light theme at Android 2.3.3

### ISSUE THREAD

**Issue by mspapant** [Prototik/HoloEverywhere#670]
I am using the holoeverywhere number picker & dialog (to display the number picker). In  android > 3 is working as expected, but in 2.3 is dispayed dark despite the fact that i inherit from 'Holo.Theme.Light'

My code is:

<style name="...." parent="Holo.Theme.Light">

final org.holoeverywhere.widget.NumberPicker np = new org.holoeverywhere.widget.NumberPicker(context);
        np.setMinValue(min);
        np.setMaxValue(max);
        if (values != null) {
            np.setDisplayedValues(values);
        }
        if (value != -1) {
            np.setValue(value);
        } else {
            np.setValue(min);
        }
        dialog = new org.holoeverywhere.app.AlertDialog.Builder(context);
        dialog.setPositiveButton(context.getResources().getString(R.string.button_ok), new DialogInterface.OnClickListener() {
            @Override
            public void onClick(final DialogInterface dialog, final int which) {
                valueListener.onSelect(np.getValue());
            }
        });
        dialog.setTitle(title);
        dialog.setView(np);

**Comment by Prototik** [comment]
Make a issue project at issues dir at master branch.

**Comment by mspapant** [comment]
How can i do this? (sorry i am new with github :))

**Comment by Prototik** [comment]
Clone a repo (google is your friend) and add activity to `issues` project in root dir of repo. This project already contains some issue's projects and you can do simply copy-paste existing activity and modify it.

**Comment by mspapant** [comment]
It was my mistake, i was using the android AlertBuilder (android.app.AlertDialog) instead of holoeverywhere. Sorry for the inconvenience
