### ISSUE TITLE
Problems withe every HoloEverywhere projects.

### ISSUE THREAD

**Issue by ghost** [Prototik/HoloEverywhere#674]
By looking at GUI(which finally cannot render) in Eclipse, I get this error:

Exception raised during rendering: com.android.layoutlib.bridge.MockView cannot be cast to android.view.ViewGroup
Exception details are logged in Window > Show View > Error Log
The following classes could not be found:
- WidgetContainer (Change to org.holoeverywhere.demo.widget.WidgetContainer, Fix Build Path, Edit XML)

**Comment by Prototik** [comment]
**Use a power, Luke!**
Of course you can click `Change to org.holoeverywhere.demo.widget.WidgetContainer` and be happy. But for what?
I do not even remember the last time I opened GUI editor.

In demo layout i'll keep WidgetContainer and nothing other, end of topic,
