### ISSUE TITLE
registerForContextMenu keeps listener in weak reference, may silently lose it

### ISSUE THREAD

**Issue by tomekziel** [Prototik/HoloEverywhere#677]
observed with v1.6.8, using ActionBarSherlock

Following code will undeterministically fail (most likely unnoticed), when GC will remove ContextMenuListener kept internally in weak reference (WeaklyMap)

`registerForContextMenu(list, new ContextMenuListener(){ ... impl... });`

Expected: anynymous ContextMenuListener won't loose only reference to ContextMenuListener object.

**Comment by tomekziel** [comment]
I just realized the `registerForContextMenu(View, ContextMenuListener)` only works for old devices, so it is probably supposed to be called internally and should not be public. In such case ContextMenuListener will be implemented by Activity and WeaklyMap will then make sense.

**Comment by Prototik** [comment]
@tomekziel It's right for 1.6.8, 2.0.0 have other behavior for context menu and all things (like anonymous callback) works nice.
