### ISSUE TITLE
ListView won't show context menu defined with list.setOnCreateContextMenuListener() on Android 2.x devices

### ISSUE THREAD

**Issue by tomekziel** [Prototik/HoloEverywhere#678]
observed with v1.6.8, using ActionBarSherlock

If ExpandableListView has context menu defined with `list.setOnCreateContextMenuListener(listener)`, it won't be shown in Android 2.x devices because `ContextMenuDecorView.showContextMenuForChild()` method will exit through initial 
`mListener = mProvider.getContextMenuListener(originalView);
        if (mListener == null) {
            return false;
        }`

Expected: the same behavior on all devices or clearly marked incompatibility

Workaround: use `Activity.registerForContextMenu()` and keep in mind #677

**Comment by Prototik** [comment]
Like #677, this occurs only in 1.6.8.
