### ISSUE TITLE
Not working with ActionbarSherlock?

### ISSUE THREAD

**Issue by Slim1991** [Prototik/HoloEverywhere#680]
Attribute duplication importing HoloEverywhere and ActionbarSherlock in eclipse.

Example:
D:\projects\android\HoloEverywhere-master\library\res\values\abc_attrs.xml:32: error: Attribute "windowActionBar" has already been defined
D:\projects\android\HoloEverywhere-master\library\res\values\abc_attrs.xml:33: error: Attribute "windowActionBarOverlay" has already been defined
and etc.

**Comment by trietbui85** [comment]
Is the following answer helpful? 
https://github.com/Prototik/HoloEverywhere/issues/650

**Comment by Prototik** [comment]
For HE + ABS use v1.6.8. That's end.
