### ISSUE TITLE
Whether HoloEverywhere can be merged with SlidingMenu or not?

### ISSUE THREAD

**Issue by liqi1982** [Prototik/HoloEverywhere#683]
I just want to know if and how HoloEverywhere can be merged with SlidingMenu. I have noticed Prototik said that HoloEverywhere doesn't support SlidingMenu. However, I also find some guys say that they are using HoloEverywhere and SlidingMenu together. I also don't know how to merge this two libs, could anyone help?

**Comment by Prototik** [comment]
Use StackOverflow for questions about library, issue tracker - bad place for it. btw SM and HE using some hack which do this libraries is imcompatible, but I don't see any reasons for using SM instead Slider addon of HE library.
