### ISSUE TITLE
error: Attribute "ATTRIBUTE_NAMES_HERE" has already been defined

### ISSUE THREAD

**Issue by Shajeel-Afzal** [Prototik/HoloEverywhere#684]
I have just updated the HoloEveryWhere Library to Sunrise release. After doing so i have included it in my Android project in Eclipse and now i am getting a long list error in my project that state that attributes already defined. One of them is as follows:

library\res\values\abs__attrs.xml:4: error: Attribute "titleTextStyle" has already been defined

**Comment by Prototik** [comment]
You incorrectly update library, without version control, just replacing a files. Fully remove library and try again.
