### ISSUE TITLE
Can't build HoloEverywhere

### ISSUE THREAD

**Issue by HenriqueRocha** [Prototik/HoloEverywhere#685]
Could not resolve all dependencies for configuration ':demo:runtime'.

> Could not download artifact 'android:android:4.3_r2@jar'
> Could not GET 'https://raw.github.com/Prototik/HoloEverywhere/repo/android/android/4.3_r2/android-4.3_r2.jar'. Received status code 403 from server: Forbidden

**Comment by Prototik** [comment]
Oh, something is broken on github...
Try to replace repo url to `https://github.com/Prototik/HoloEverywhere/raw/repo/`

**Comment by Prototik** [comment]
Also you don't need more build library from sources, you can use aar from repo.

**Comment by HenriqueRocha** [comment]
Replacing the repo didn't work.
I'm currently using: 
compile 'org.holoeverywhere:library:2.0.0-SNAPSHOT'
because I've added the aar that I built to my own github maven repo.

What are you using for the compile string?

Thanks.

**Comment by HenriqueRocha** [comment]
I tried 

compile 'org.holoeverywhere:library:2.0.0' and I get this error:

Could not GET 'https://github.com/Prototik/HoloEverywhere/raw/repo/android/android/4.3_r2/android-4.3_r2.jar'. Received status code 403 from server: Forbidden

**Comment by Prototik** [comment]
```
[prok@prok-pc ~]$ curl -I https://raw.github.com/Prototik/HoloEverywhere/repo/android/android/4.3_r2/android-4.3_r2.jar
HTTP/1.1 403 Forbidden
[prok@prok-pc ~]$ curl -I https://github.com/Prototik/HoloEverywhere/raw/repo/android/android/4.3_r2/android-4.3_r2.jar
HTTP/1.1 302 Found
```

Strange...

**Comment by Prototik** [comment]
You can use [maven-android-sdk-deployer](https://github.com/mosabua/maven-android-sdk-deployer) and install this artifact  to local maven repo manually by invoking `mvn install -P 4.3`

**Comment by HenriqueRocha** [comment]
Doesn't work also, maven-android-sdk-deployer throws this error:

[INFO] Maven Android SDK Deployer ........................ SUCCESS [0.125s]
[INFO] Android Platforms ................................. SUCCESS [0.003s]
[INFO] Android Platform 4.3 API 18 ....................... SUCCESS [0.213s]
[INFO] Android Add-Ons ................................... SUCCESS [0.005s]
[INFO] Android Add-On Google Platform 4.3 API 18 (Maps and USB)  SUCCESS [0.017s]
[INFO] Android Extras .................................... SUCCESS [0.006s]
[INFO] Android Compatibility Extra V4 .................... SUCCESS [0.683s]
[INFO] Android Compatibility Extra V7 Gridlayout Library . FAILURE [10.301s]

I checked the SDK Manager and I think I have everything that I need.

**Comment by otro678** [comment]
The same for me:

> Failed to notify project evaluation listener.
> Could not download artifact 'android:android:4.3_r2@jar'
> Could not GET 'https://github.com/Prototik/HoloEverywhere/raw/repo/android/android/4.3_r2/android-4.3_r2.jar'. Received status code 403 from server: Forbidden

Maybe, GitHub has some limits for raw files requests?

**Comment by otro678** [comment]
Here is workaround:
Clone HoloEverywhere into projectRoot/repo, checkout branch to repo. Add this into your project's build.gradle:

```
allprojects {
    repositories {
        maven { url "${rootProject.projectDir}/repo" }
        mavenCentral()
        mavenLocal()
    }
}
```
