### ISSUE TITLE
Problem with relayout

### ISSUE THREAD

**Issue by max-kammerer** [Prototik/HoloEverywhere#686]
I have spinner with several choices (image 1) and linear layout with image button, editText, imageButton, and spinner.
When i select non-custom value i hide imageButton with setVisibility(View.GONE) and show only editText and spinner, but they don't relayouted (image 2). On reselected same value from spinner i get proper result (image 3). But if select 'custom' value (which show + and - buttons) again i get tottally corrupted layout (image 4). Invocation of requesLayout and invalidation doesn' help. With standart android widgets all is right. and works properly 
![1](https://f.cloud.github.com/assets/1205032/1484468/64ede2c4-4707-11e3-8946-965971b3f3be.png)
![2](https://f.cloud.github.com/assets/1205032/1484471/67d3607c-4707-11e3-991e-1e6bd7ad6f7c.png)
![3](https://f.cloud.github.com/assets/1205032/1484473/6a4754d0-4707-11e3-8c6b-d6e1df4c6863.png)
![4](https://f.cloud.github.com/assets/1205032/1484475/6ca38884-4707-11e3-854d-333d7fbe6624.png)

**Comment by max-kammerer** [comment]
I made some investigation it seems that requestLayout() sometimes not work:

`````` java
spiner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                final LinearLayout parent1 = (LinearLayout) zoomText.getParent();

                //!!! !this is ui thread and this method do nothing - layout still corrupted
                parent1.requestLayout();
                //but if replace it with
                parent1.post(new Runnable() {
                    @Override
                    public void run() {
                        //!!!!this is ui thread too and this method works!!!!!!!!!!!!!!!!!!!!!!
                        parent1.requestLayout();
                    }
                });               

            }```
``````

**Comment by Prototik** [comment]
Try latest master with simplified LL

Алсо: Android не любит Erlang :P

**Comment by max-kammerer** [comment]
It's still corrupted

**Comment by melkonyan** [comment]
I have faced the same problem, as described here. The provided "solution" worked for me.
