### ISSUE TITLE
Problem with menu items on Lower versions than API 11

### ISSUE THREAD

**Issue by Shajeel-Afzal** [Prototik/HoloEverywhere#689]
I am using android:theme="@style/Holo.Theme.Light.DarkActionBar" theme in my application.

And i am using the following xml to inflate menu in my application. But the only first two menu item are displayed correctly, on pressing the hardware menu button other menu items display and hide quickly.

My Activity is extending org.holoeverywhere.activity

After reading Android documentation i cam to know that i have to replace android:showAsAction prefix with my app name. I have replaced the prefix but it gives me error there.

error: No resource identifier found for attribute 'showAsAction' in package 'com.gcuf.my_study_manager'

Please solve this issue. 

<menu xmlns:android="http://schemas.android.com/apk/res/android" >

```
<item        
    android:icon="@drawable/ic_menu_add"
    android:orderInCategory="1"
    android:showAsAction="always"
    android:title="Menu 1"/>
<item
    android:icon="@drawable/ic_menu_preferences"
    android:orderInCategory="2"
    android:showAsAction="ifRoom"
    android:title="2">
</item>
<item
    android:icon="@drawable/ic_menu_preferences"
    android:orderInCategory="3"
    android:showAsAction="ifRoom"
    android:title="3">
</item>
<item
    android:icon="@drawable/ic_menu_preferences"
    android:orderInCategory="4"
    android:showAsAction="ifRoom"
    android:title="4">
</item>
```

</menu>

**Comment by BraisGabin** [comment]
What is the issue: the quick hidden or the menu button? The overflow at menu button is the native behavior.

**Comment by Shajeel-Afzal** [comment]
The quick hidden is the problem i am facing right now.

**Comment by Prototik** [comment]
Create a issue project. I cannot reproduce bug.

**Comment by Prototik** [comment]
Rejected

**Comment by Shajeel-Afzal** [comment]
What does it mean? I could not understand why you said rejected.

**Comment by Shajeel-Afzal** [comment]
I also dont know about creating an issue project?
