### ISSUE TITLE
Switch doesn't work under 4.0

### ISSUE THREAD

**Issue by xavifc** [Prototik/HoloEverywhere#69]
I'm using the new switch button, with the KFramework-SW library, and it's working under 2.1, but under 4.0 crashes.

That's how i'm using it in the xml:

< k.framework.lib.sw.Switch
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:layout_centerVertical="true" />

**Comment by intrications** [comment]
I think this is also causing the Preferences demo to crash on Jellybean.

Should the native Switch be used on API v14+?

`11:25:14.554 25902/25902            AndroidRuntime  E   FATAL EXCEPTION: main
11:25:14.554 25902/25902            AndroidRuntime  E   java.lang.NullPointerException
11:25:14.554 25902/25902            AndroidRuntime  E       at k.framework.lib.sw.Switch.jumpDrawablesToCurrentState(Switch.java:269)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:5147)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.ViewGroup.jumpDrawablesToCurrentState(ViewGroup.java:5147)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.View.onAttachedToWindow(View.java:11436)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.View.dispatchAttachedToWindow(View.java:11755)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2417)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.ViewGroup.addViewInner(ViewGroup.java:3417)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.ViewGroup.addViewInLayout(ViewGroup.java:3354)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.widget.ListView.setupChild(ListView.java:1817)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.widget.ListView.makeAndAddView(ListView.java:1772)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.widget.ListView.fillDown(ListView.java:672)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.widget.ListView.fillFromTop(ListView.java:733)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.widget.ListView.layoutChildren(ListView.java:1622)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.widget.AbsListView.onLayout(AbsListView.java:2102)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.View.layout(View.java:13754)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.ViewGroup.layout(ViewGroup.java:4362)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.View.layout(View.java:13754)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.ViewGroup.layout(ViewGroup.java:4362)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1638)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.widget.LinearLayout.onLayout(LinearLayout.java:1422)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.View.layout(View.java:13754)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.ViewGroup.layout(ViewGroup.java:4362)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.View.layout(View.java:13754)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.ViewGroup.layout(ViewGroup.java:4362)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.View.layout(View.java:13754)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.ViewGroup.layout(ViewGroup.java:4362)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.View.layout(View.java:13754)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.ViewGroup.layout(ViewGroup.java:4362)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.View.layout(View.java:13754)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.ViewGroup.layout(ViewGroup.java:4362)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1866)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1687)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4212)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.Choreographer.doFrame(Choreographer.java:525)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.os.Handler.handleCallback(Handler.java:615)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.os.Handler.dispatchMessage(Handler.java:92)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.os.Looper.loop(Looper.java:137)
11:25:14.554 25902/25902            AndroidRuntime  E       at android.app.ActivityThread.main(ActivityThread.java:4745)
11:25:14.554 25902/25902            AndroidRuntime  E       at java.lang.reflect.Method.invokeNative(Native Method)
11:25:14.554 25902/25902            AndroidRuntime  E       at java.lang.reflect.Method.invoke(Method.java:511)
11:25:14.554 25902/25902            AndroidRuntime  E       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
11:25:14.554 25902/25902            AndroidRuntime  E       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
11:25:14.554 25902/25902            AndroidRuntime  E       at dalvik.system.NativeStart.main(Native Method)`

**Comment by Prototik** [comment]
f77568910d379545b1d17cfebda6bff62145ef31
