### ISSUE TITLE
Can't use HoloEverywhere from build.gradle

### ISSUE THREAD

**Issue by HenriqueRocha** [Prototik/HoloEverywhere#691]
Building HE from the sources is fine now but trying to use the AAR directly from the repo doesn't work.
I still get this error 

> Could not download artifact 'android:android:4.3_r2@jar'
>       > Artifact 'android:android:4.3_r2@jar' not found.

when I add compile 'org.holoeverywhere:library:2.1.0' to my build.gradle file having
    maven { url "https://github.com/Prototik/HoloEverywhere/raw/repo" }
in my repositories.

As a workaround, I'll continue uploading the aar to my github repository.

**Comment by Prototik** [comment]
... What? Now aar and apklib just hasn't android:android in dependencies list. Just nowhere.
Only in sources pom's, but in repo placed generated poms without this dependency.

**Comment by HenriqueRocha** [comment]
I pushed version 2.1.1 to my github repo but now I get this error when I start the app:

```
E/AndroidRuntime(26490): java.lang.NoClassDefFoundError: android.support.v4.app._HoloFragmentInflater$1
E/AndroidRuntime(26490):    at android.support.v4.app._HoloFragmentInflater.<clinit>(_HoloFragmentInflater.java:18)
E/AndroidRuntime(26490):    at org.holoeverywhere.app.Application.<clinit>(Application.java:34)
E/AndroidRuntime(26490):    at java.lang.Class.newInstanceImpl(Native Method)
E/AndroidRuntime(26490):    at java.lang.Class.newInstance(Class.java:1130)
E/AndroidRuntime(26490):    at android.app.Instrumentation.newApplication(Instrumentation.java:990)
E/AndroidRuntime(26490):    at android.app.Instrumentation.newApplication(Instrumentation.java:975)
E/AndroidRuntime(26490):    at android.app.LoadedApk.makeApplication(LoadedApk.java:504)
E/AndroidRuntime(26490):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4417)
E/AndroidRuntime(26490):    at android.app.ActivityThread.access$1300(ActivityThread.java:141)
E/AndroidRuntime(26490):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
E/AndroidRuntime(26490):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(26490):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(26490):    at android.app.ActivityThread.main(ActivityThread.java:5103)
E/AndroidRuntime(26490):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(26490):    at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime(26490):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
E/AndroidRuntime(26490):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime(26490):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  538):   Force finishing activity de.androidpit.app/de.androidpit.ui.HomeActivity
```

**Comment by Prototik** [comment]
*2.1.0
2.1.0 requires com.android.support:support-v4:18.0.3

**Comment by HenriqueRocha** [comment]
Gradle doesn't find 18.0.3 and in the SDK Manager I have everything up to date! Strange!
The generated AAR built from the sources says 2.1.1.

**Comment by Prototik** [comment]
[repo](https://github.com/Prototik/HoloEverywhere/tree/repo/com/android/support/support-v4/18.0.3)
Also please do `git checkout v2.1.0` :)

**Comment by HenriqueRocha** [comment]
I don't understand, I always get this error:

Could not download artifact 'android:android:4.3_r2@jar'
Artifact 'android:android:4.3_r2@jar' not found.

**Comment by Prototik** [comment]
Please do `gradle dependencies`/`gradle androidDependencies`. I just now tested 2.1.0 aar and it doesn't require android:android artifact.

**Comment by HenriqueRocha** [comment]
Okay, I'll try to solve the problem because I still get the same error.

**Comment by HenriqueRocha** [comment]
I even deleted my .m2 and .gradle directories just in case but I still get this:

Could not resolve all dependencies for configuration ':_DebugCompile'.
Could not find android:android:4.3_r2.
Required by:
:androidpit-app-2:unspecified > com.android.support:support-v4:18.0.3

Are you sure that your com.android.support:support-v4:18.0.3 dependency doesn't require android:android:4.3_r2?

**Comment by HenriqueRocha** [comment]
You have android:android:4.3_r2 dependency in your pom.xml
https://github.com/Prototik/HoloEverywhere/blob/repo/com/android/support/support-v4/18.0.3/support-v4-18.0.3.pom

**Comment by Prototik** [comment]
Pushed 18.0.4 with correct pom.

**Comment by HenriqueRocha** [comment]
Did you apply the change to 2.1.0 also? I only see it in 2.1.1-SNAPSHOT. Thanks for fixing.

**Comment by Prototik** [comment]
Not, i cannot modify already pushed artifacts. But something like this:

```
dependencies {
  compile 'com.android.support:support-v4:18.0.4@jar'
  compile 'org.holoeverywhere:library:2.1.0@aar'
}
```

should works.

**Comment by HenriqueRocha** [comment]
Woohoo! Compiles and runs! \o/
Have a very nice day. Thanks very much.
