### ISSUE TITLE
SearchView and ShareActionProvider not working with version 2.1.1

### ISSUE THREAD

**Issue by HenriqueRocha** [Prototik/HoloEverywhere#692]
After updating to version 2.1.1 I can't compile my project.

I get the following errors:

Gradle: No resource identifier found for attribute 'actionViewClass' in package 'de.androidpit.app'
Gradle: No resource identifier found for attribute 'showAsAction' in package 'de.androidpit.app'
Gradle: No resource identifier found for attribute 'actionProviderClass' in package 'de.androidpit.app'

Here is a sample of my xml file:

<menu xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:androidpit="http://schemas.android.com/apk/res-auto">
    <item
        android:id="@+id/menu_share"
        android:title="@string/button_share"
        androidpit:actionProviderClass="android.support.v7.widget.ShareActionProvider"
        androidpit:showAsAction="ifRoom" />
</menu>

**Comment by Prototik** [comment]
Use android namespace instead.
