### ISSUE TITLE
Getting NullPointerException with addonSlider

### ISSUE THREAD

**Issue by tzmst** [Prototik/HoloEverywhere#693]
So a customer tested current app i develop and i'm getting a null pointer exception when adding and setting the drawer lock mode:

final SliderMenu sliderMenu = addonSlider().obtainDefaultSliderMenu(R.layout.menu);

addonSlider().getDrawerLayout().setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED);

This happens only on Motorola Xoom. The device is running on android 4.1.2. Someone knows what might cause the addonSlider() to throw a null pointer exception ?

The app runs with no problems on devices like Samsung Galaxy S2, S3, Galaxy Nexus and many other.

Edit: To rectify what i said. The problem is the drawer layout, because when i call addonSlider().getDrawerLayout() it returns null

**Comment by tzmst** [comment]
So checking the addon layouts to see what might cause not to set the drawer layout. I found that for the 720dp tablets the layout was a linearlayout, not a drawerlayout, this is intended ? (For my case i changed to the normal layout with the drawer and everything works fine.

SW-720dp layout file:

<?xml version="1.0" encoding="utf-8"?>
<"LinearLayout" xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:baselineAligned="false"
    android:orientation="horizontal">

```
<fragment
    android:id="@id/leftView"
    android:name="org.holoeverywhere.slider.SliderMenu$SliderMenuFragment"
    android:layout_width="@dimen/menu_width"
    android:layout_height="match_parent" />

<FrameLayout
    android:id="@id/contentView"
    android:layout_width="0dp"
    android:layout_height="match_parent"
    android:layout_weight="1" />
```

</"LinearLayout">

and normal layout file:

<"DrawerLayout" xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

```
<FrameLayout
    android:id="@id/contentView"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />

<fragment
    android:id="@id/leftView"
    android:name="org.holoeverywhere.slider.SliderMenu$SliderMenuFragment"
    android:layout_width="@dimen/menu_width"
    android:layout_height="match_parent" />
```

</"DrawerLayout">

**Comment by Prototik** [comment]
Yeah, for tablets using static layout, without DrawerLayout (like a last screenshot on main page).
You should check that drawer layout not null, or use a custom layout with drawerlayout for any dimensions,
