### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "Internal.NumberPickerEditText"

### ISSUE THREAD

**Issue by josear** [Prototik/HoloEverywhere#694]
After I upgraded to the last version of HoloEverywhere I'm getting this error when executing my app (exported as signed app and using proguard):

E/AndroidRuntime( 2107): java.lang.RuntimeException: Unable to start activity ComponentInfo{jp.rodriguez.kanjisenpai.android/jp.rodriguez.kanjisenpai.android.IntroActivity}: android.view.InflateException: Binary XML file line #36: Error inflating class public org.holoeverywhere.preference.NumberPickerPreference(android.content.Context,android.util.AttributeSet)
E/AndroidRuntime( 2107):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
E/AndroidRuntime( 2107):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
E/AndroidRuntime( 2107):    at android.app.ActivityThread.access$600(ActivityThread.java:141)
E/AndroidRuntime( 2107):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
E/AndroidRuntime( 2107):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 2107):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 2107):    at android.app.ActivityThread.main(ActivityThread.java:5041)
E/AndroidRuntime( 2107):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2107):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 2107):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime( 2107):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
E/AndroidRuntime( 2107):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 2107): Caused by: android.view.InflateException: Binary XML file line #36: Error inflating class public org.holoeverywhere.preference.NumberPickerPreference(android.content.Context,android.util.AttributeSet)
E/AndroidRuntime( 2107):    at org.holoeverywhere.app.GenericInflater.createItem(GenericInflater.java:81)
E/AndroidRuntime( 2107):    at org.holoeverywhere.app.GenericInflater.onCreateItem(GenericInflater.java:226)
E/AndroidRuntime( 2107):    at org.holoeverywhere.app.GenericInflater.createItemFromTag(GenericInflater.java:104)
E/AndroidRuntime( 2107):    at org.holoeverywhere.app.GenericInflater.rInflate(GenericInflater.java:261)
E/AndroidRuntime( 2107):    at org.holoeverywhere.app.GenericInflater.rInflate(GenericInflater.java:263)
E/AndroidRuntime( 2107):    at org.holoeverywhere.app.GenericInflater.inflate(GenericInflater.java:194)
E/AndroidRuntime( 2107):    at org.holoeverywhere.app.GenericInflater.inflate(GenericInflater.java:164)
E/AndroidRuntime( 2107):    at org.holoeverywhere.app.GenericInflater.inflate(GenericInflater.java:158)
E/AndroidRuntime( 2107):    at org.holoeverywhere.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:384)
E/AndroidRuntime( 2107):    at org.holoeverywhere.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:103)
E/AndroidRuntime( 2107):    at org.holoeverywhere.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:84)
E/AndroidRuntime( 2107):    at jp.rodriguez.kanjisenpai.android.IntroActivity.onCreate(IntroActivity.java:42)
E/AndroidRuntime( 2107):    at android.app.Activity.performCreate(Activity.java:5104)
E/AndroidRuntime( 2107):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
E/AndroidRuntime( 2107):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
E/AndroidRuntime( 2107):    ... 11 more
E/AndroidRuntime( 2107): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 2107):    at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime( 2107):    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
E/AndroidRuntime( 2107):    at org.holoeverywhere.app.GenericInflater.createItem(GenericInflater.java:73)
E/AndroidRuntime( 2107):    ... 25 more
E/AndroidRuntime( 2107): Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class Internal.NumberPickerEditText
E/AndroidRuntime( 2107):    at org.holoeverywhere.LayoutInflater.createViewFromTag(LayoutInflater.java:322)
E/AndroidRuntime( 2107):    at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:604)
E/AndroidRuntime( 2107):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:407)
E/AndroidRuntime( 2107):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:372)
E/AndroidRuntime( 2107):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:145)
E/AndroidRuntime( 2107):    at org.holoeverywhere.widget.NumberPicker.<init>(NumberPicker.java:190)
E/AndroidRuntime( 2107):    at org.holoeverywhere.widget.NumberPicker.<init>(NumberPicker.java:131)
E/AndroidRuntime( 2107):    at org.holoeverywhere.widget.NumberPicker.<init>(NumberPicker.java:127)
E/AndroidRuntime( 2107):    at org.holoeverywhere.preference.NumberPickerPreference.onCreateNumberPicker(NumberPickerPreference.java:135)
E/AndroidRuntime( 2107):    at org.holoeverywhere.preference.NumberPickerPreference.<init>(NumberPickerPreference.java:84)
E/AndroidRuntime( 2107):    at org.holoeverywhere.preference.NumberPickerPreference.<init>(NumberPickerPreference.java:69)
E/AndroidRuntime( 2107):    ... 28 more
E/AndroidRuntime( 2107): Caused by: java.lang.ClassNotFoundException: Didn't find class "Internal.NumberPickerEditText" on path: /data/app/jp.rodriguez.kanjisenpai.android-1.apk
E/AndroidRuntime( 2107):    at dalvik.system.BaseDexClassLoad

I added the proguard rules used in the demo that contains a rule to this "Internal.NumberPickerEditText" but no luck...

Any ideas?

**Comment by josear** [comment]
Self answer...

Problem was that simple name of inner classes were renamed.

Using "-keepattributes InnerClasses" on ProGuard configuration solved the problem.

**Comment by stevosaurus** [comment]
I was seeing the same issue with Internal.DialogTitle and your fix worked great. Commenting here in case others run into my problem.

Thank you!

**Comment by LiuJQ** [comment]
Thank God !
That's it !
Just like that:
Using "-keepattributes InnerClasses" on ProGuard configuration solved the problem.

**Comment by 8Duke8** [comment]
I had a problem with Internal.DialogTitle. Thanks a lot. :-)
