### ISSUE TITLE
Error in _HoloFragmentInflater.java after clean-Building Library in Eclipse

### ISSUE THREAD

**Issue by Shajeel-Afzal** [Prototik/HoloEverywhere#697]
I just include this library in my existing workspace and got this message after clean-Build in Eclipse. 

_HoloFragmentInflater.java Public class _HoloFragmentInflater { static { NoSaveStateFrameLayout.sNoSaveStateFrameLayoutCreator = New NoSaveStateFrameLayout.NoSaveStateFrameLayoutCreator () sNoSaveStateFrameLayoutCreator cannot be resolved or is not A field NoSaveStateFrameLayout . NoSaveStateFrameLayoutCreator cannot be resolved to a type 

I can not figure out what was wrong.

**Comment by renaudcerrato** [comment]
Same problem here. Some files are probably missing from the commit...

**Comment by HenriqueRocha** [comment]
If you're using version 2.1 of the library, use this in your build.gradle file to the dependencies
    compile 'com.android.support:support-v4:18.0.4@jar'
    compile 'org.holoeverywhere:library:2.1.0@aar'

And this to the repositories section:
    maven { url "https://github.com/Prototik/HoloEverywhere/raw/repo" }

**Comment by renaudcerrato** [comment]
I'm not using Gradle, and this not related at all : NoSaveStateFrameLayout doesn't exist in HE's android.support.v4.app tree. It does exist in support library, but there's no sNoSaveStateFrameLayoutCreator  field at all.

**Comment by Prototik** [comment]
For HE 2.1 required support-v4 18.0.4. You can grab it [here](https://github.com/Prototik/HoloEverywhere/blob/repo/com/android/support/support-v4/18.0.4/support-v4-18.0.4.jar) and replace all version of support library (in `libs` folder) by this version.

**Comment by renaudcerrato** [comment]
That fixed it, but the issue is still valid for the 2.1.0 release : your commited version is 18.0.2!

**Comment by Prototik** [comment]
@nono240 Yeah, i know, sorry. (valid only for eclipse/ant build)

**Comment by asloobq** [comment]
The 2.1.0 release version still has old support-v4-18.0.2.jar and I am seeing the same error reported by @Shajeel-Afzal . Please fix the release. I was able to resolve it by using the latest library from the developement branch.
