### ISSUE TITLE
Overlay Actionbar and fill_parent on android 2.1 problem

### ISSUE THREAD

**Issue by max-kammerer** [Prototik/HoloEverywhere#699]
Problem with relayout and fill_parent on anroid 2.1 (reproduced on Nook Simple Touch, 600x800).
When actionbar enabled in overlay moded (windowActionBarOverlay=true) nested view resized to 600x460. But if enable action bar in general mode (windowActionBarOverlay=false) it resized to 600x752.

``` xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                android:layout_width="fill_parent" android:layout_height="fill_parent">

    <View android:id="@+id/view"
                   android:textColor="#000000"
                   android:background="#FFFFFF"
                   android:layout_width="fill_parent"
                   android:layout_height="fill_parent">
    </View>

</RelativeLayout>
```

**Comment by max-kammerer** [comment]
Same if substitute RelativeLayout with LinearLayout. It seems that layout itself not fill all avaliable space.

I substitute holoEverywhere with support lib 19.0 and all works fine with it.

**Comment by Prototik** [comment]
As you said it's bug of support lib v4 r18, after official migrating on r19 this issue will gone.
