### ISSUE TITLE
Change AlertDialog's title text  & button pressed colors

### ISSUE THREAD

**Issue by AmitJayant** [Prototik/HoloEverywhere#701]
Is it possible to change the default blue title & button press color of alert dialog?

I managed to change the color of blue line in the dialog by doing this:
![capture](https://f.cloud.github.com/assets/6032174/1614187/071aaa80-55e7-11e3-9f1b-36ded479a9ed.PNG)

**Comment by Prototik** [comment]
![device-2013-12-18-224348](https://f.cloud.github.com/assets/1416030/1774023/f08f6f62-67f2-11e3-8b2b-3d69d993e5a9.png)
