### ISSUE TITLE
No resource identifier found for attribute 'showAsAction' in package 'com.mypackage'

### ISSUE THREAD

**Issue by InsanityOnABun** [Prototik/HoloEverywhere#702]
Stated here: http://developer.android.com/guide/topics/ui/actionbar.html#ActionItems

> To request that an item appear directly in the action bar as an action button, include showAsAction="ifRoom" in the <item> tag. For example:

```
<menu xmlns:android="http://schemas.android.com/apk/res/android"
      xmlns:yourapp="http://schemas.android.com/apk/res-auto" >
    <item android:id="@+id/action_search"
          android:icon="@drawable/ic_action_search"
          android:title="@string/action_search"
          yourapp:showAsAction="ifRoom"  />
    ...
</menu>`
```

> If there's not enough room for the item in the action bar, it will appear in the action overflow.
> 
> **Using XML attributes from the support library**
> Notice that the showAsAction attribute above uses a custom namespace defined in the &lt;menu&gt; tag. This is necessary when using any XML attributes defined by the support library, because these attributes do not exist in the Android framework on older devices. So you must use your own namespace as a prefix for all attributes defined by the support library.

Since HoloEverywhere seems to have ABC and support-v4 libraries built into it, I am not importing the ABC library into my project (in fact, I get a ton of errors if I do.) However, I receive the error in the title whenever I try to follow the above instructions on using ABC.

**Comment by Prototik** [comment]
With HoloEverywhere's support-library-v4 you should use only android namespace in menu xml (and for nodes showAsAction/actionViewClass/actionProviderClass/actionLayout too only android namespace). It will work on 2.1.

**Comment by 4nd3250n** [comment]
Could you please explain how this works behind the scenes? How is this achieved to use android namespace prefix?

**Comment by Prototik** [comment]
@4nd3250n some kind of magic. All new properties (included 5.x, 6.x specific) could be obtained on older version, but anyway some code should process this entries. HoloEverywhere processing some entires (like showAsAction, actionViewClass, /etc) and build proper menu in this case.
