### ISSUE TITLE
splitActionBarWhenNarrow not working for support

### ISSUE THREAD

**Issue by tzmst** [Prototik/HoloEverywhere#704]
setting the splitActionBarWhenNarrow property to the activity in the manifest having no effect on support (API 9 and 10).

Tested with Samsung galaxy S (2.3.6) and LGP500 (2.3.3) and the splitActionBarWhenNarrow its not working.

Here is the activity declaration in the manifest:

```
    <activity
        android:name="com.adonissoft.yoosend.activity.YSFilesActivity"
        android:icon="@drawable/img_back_files"
        android:screenOrientation="portrait"
                  android:theme="@style/Holo.ShareApp.Theme.Light.DarkActionBar.Fullscreen"
        android:uiOptions="splitActionBarWhenNarrow" />
```

Tested on devices with 4.0 and newer the action bar seems to work fine.

In the theme i didn't set any backgroundSplit attribute so it should be default.

**Comment by Prototik** [comment]
For appcompat you should use meta-data tag:

``` xml
<activity ... >
            <meta-data android:name="android.support.UI_OPTIONS"
                android:value="splitActionBarWhenNarrow" />
</activity>
```

You should have both android:uiOptions and meta-data for supporting all platforms.

**Comment by tzmst** [comment]
oh ... didn't know about that ... thanx

**Comment by IvoryAguado** [comment]
Im using 4.4 Kitkat and I add that to applicantion or activity and doesnt work could please say my what Im doing wrong? Thanks!
