### ISSUE TITLE
Problem setting slider menu width for menu/shadow

### ISSUE THREAD

**Issue by tzmst** [Prototik/HoloEverywhere#707]
Is there a simpler method of setting the slider menu menu/shadow width without changing the library code ?

**Comment by Prototik** [comment]
Any standard way for setting-up shadow for DrawerLayout:

``` java
DrawerLayout drawerLayout = addonSlider.getDrawerLayout();
if(drawerLayout != null) {
  drawerLayout.setDrawerShadow(R.drawable.my_shadow, Gravity.LEFT)
}
```

(so you should create a custom shadow drawable)

**Comment by tzmst** [comment]
i was not wanting to set the shadow layout, i want to set the width of the drawer

**Comment by Prototik** [comment]
You can override `@dimen/menu_width` over project level.
Create a `project/res/values/dimes.xml` (or append to exists):

``` xml
  <dimen name="menu_width">200dp</dimen>
```

Also you can may need to override default menu width with modifiers `-land` and `-w720dp`

**Comment by tzmst** [comment]
thx .. that worked ... sorry for the annoyance
