### ISSUE TITLE
Does not start app from Android Studio (Could not find class 'android.test.mock.MockApplication')

### ISSUE THREAD

**Issue by AntonKosov** [Prototik/HoloEverywhere#708]
Does not start app from Android Studio on emulator 4.2:

Logs:
E/dalvikvm﹕ Could not find class 'android.test.mock.MockApplication', referenced from method android.support.v4.app._HoloActivity.onInit
W/dalvikvm﹕ VFY: unable to resolve instanceof 823 (Landroid/test/mock/MockApplication;) in Landroid/support/v4/app/_HoloActivity;

Android Studio: 0.3.6
HoloEverywhere: 2.1.0 (attach as sources)
Maven: 3.1.1

**Comment by AntonKosov** [comment]
Oops! I am sorry!
I have option in Android Studio: Do not launch Activity.

**Comment by waylife** [comment]
I got this problem too,so how I can solve it? Please give me a help,Thanks.

**Comment by larrymeng** [comment]
I got this problem too,so how I can solve it?
Do not launch Activity?

Device: Android 4.4.4
