### ISSUE TITLE
SharedPreferences not working

### ISSUE THREAD

**Issue by ksennoun** [Prototik/HoloEverywhere#709]
Hello and thank you for your work.

I'm having troubles with the Preferences Addon and I think there is either a bug or a lack of documentation.

I've added the addon as depedency to my project but I still get a crash when trying to use this : 

`SharedPreferences myPrefs =  this.getSharedPreferences("test",      Context.MODE_PRIVATE);`

Logcat : 

```
12-02 10:26:29.333: E/AndroidRuntime(25235): FATAL EXCEPTION: main
12-02 10:26:29.333: E/AndroidRuntime(25235): java.lang.UnsatisfiedLinkError: HoloEverywhere: PreferenceFramework not found
12-02 10:26:29.333: E/AndroidRuntime(25235):    at org.holoeverywhere.preference.PreferenceManagerHelper.checkImpl(PreferenceManagerHelper.java:37)
12-02 10:26:29.333: E/AndroidRuntime(25235):    at org.holoeverywhere.preference.PreferenceManagerHelper.wrap(PreferenceManagerHelper.java:58)
12-02 10:26:29.333: E/AndroidRuntime(25235):    at org.holoeverywhere.preference.PreferenceManagerHelper.wrap(PreferenceManagerHelper.java:64)
12-02 10:26:29.333: E/AndroidRuntime(25235):    at android.support.v4.app._HoloActivity.getSharedPreferences(_HoloActivity.java:262)
12-02 10:26:29.333: E/AndroidRuntime(25235):    at com.apec.jobboard.ui.activity.MainActivity.useElements(MainActivity.java:77)
12-02 10:26:29.333: E/AndroidRuntime(25235):    at com.apec.jobboard.ui.activity.MainActivity_.afterSetContentView_(MainActivity_.java:39)
12-02 10:26:29.333: E/AndroidRuntime(25235):    at com.apec.jobboard.ui.activity.MainActivity_.setContentView(MainActivity_.java:45)
12-02 10:26:29.333: E/AndroidRuntime(25235):    at com.apec.jobboard.ui.activity.MainActivity_.onCreate(MainActivity_.java:30)
12-02 10:26:29.333: E/AndroidRuntime(25235):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
12-02 10:26:29.333: E/AndroidRuntime(25235):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1623)
12-02 10:26:29.333: E/AndroidRuntime(25235):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1675)
12-02 10:26:29.333: E/AndroidRuntime(25235):    at android.app.ActivityThread.access$1500(ActivityThread.java:121)
12-02 10:26:29.333: E/AndroidRuntime(25235):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:943)
12-02 10:26:29.333: E/AndroidRuntime(25235):    at android.os.Handler.dispatchMessage(Handler.java:99)
12-02 10:26:29.333: E/AndroidRuntime(25235):    at android.os.Looper.loop(Looper.java:130)
12-02 10:26:29.333: E/AndroidRuntime(25235):    at android.app.ActivityThread.main(ActivityThread.java:3701)
12-02 10:26:29.333: E/AndroidRuntime(25235):    at java.lang.reflect.Method.invokeNative(Native Method)
12-02 10:26:29.333: E/AndroidRuntime(25235):    at java.lang.reflect.Method.invoke(Method.java:507)
12-02 10:26:29.333: E/AndroidRuntime(25235):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
12-02 10:26:29.333: E/AndroidRuntime(25235):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
12-02 10:26:29.333: E/AndroidRuntime(25235):    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Prototik** [comment]
How to you attach PreferenceFramework? Did you setup an order/export properties? More info please.

**Comment by ksennoun** [comment]
I've attached it by importing the HoloEverywhere Addon Preferences project into my Eclipse workspace. Then right clicked on my project /properties/android and added the Addon Preference project as a library. After that, Eclipse is able to resolve the following import:

<code>import org.holoeverywhere.preference.SharedPreferences;</code>

I'm not using any preferenceFragment or whatever, the only thing I tried is the code I posted in the issue in my MainActivity.

**Comment by Prototik** [comment]
Export settings?

**Comment by ksennoun** [comment]
addon-preferences-1.6.8.jar is present in the Order and Export tab of eclipse. It's the last in the list, I've tried to put it at the top but same result.

**Comment by Prototik** [comment]
I just now run eclipse and i found library dependencies only in `libraries` tab. In order & export tab you should have only two checked entries: Android Dependencies (which should contains your project's dependencies) and Android Private Libraries.
Please check out you project structure, try to create a new project or send this project on my email.
![screenshot from 2013-12-02 21 35 39](https://f.cloud.github.com/assets/1416030/1654871/bba105a2-5b56-11e3-9439-e82066e4b469.png)
![screenshot from 2013-12-02 21 35 42](https://f.cloud.github.com/assets/1416030/1654872/bba8c922-5b56-11e3-9c2d-8beb8b07259b.png)

**Comment by ksennoun** [comment]
Ok apologies! My maven build was overriding the eclipse dependencies. I should have checked better before disturbing you... Thank you anyway for fast answer.
