### ISSUE TITLE
NumberPicker Resource Not Found Exc.

### ISSUE THREAD

**Issue by danoz73** [Prototik/HoloEverywhere#711]
android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f01007d a=2}
at android.content.res.Resources.loadDrawable(Resources.java:2068)
at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
at org.holoeverywhere.widget.NumberPicker.<init>(NumberPicker.java:185)
at org.holoeverywhere.widget.NumberPicker.<init>(NumberPicker.java:131)

I am trying to just use NumberPicker from HoloEverywhere, but I keep getting the above error. I noticed that in the xml for the demo app the standard NumberPicker is used. Is this allowed because it is used within the context of a HoloEverywhere Activity/Fragment, or does this not matter?

**Comment by Prototik** [comment]
Of course it have sense which context is used. Without HoloEverywhere's theme widgets cannot be initialized.

**Comment by danoz73** [comment]
Well, I am using the Holo.Theme.Light.NoActionBar theme in my application, but its just that the individual fragments/activities are not holoeverywhere versions. For instance, when I want to use Holo EditTexts, I simply assign the style as such:

<EditText
....
style="@style/Holo.EditText"
.../>

This works fine.

But I guess this won't work with the NumberPicker because I want to use the whole widget as opposed to just styling? I was seeking an alternative to SimonVT's NumberPicker backport.
