### ISSUE TITLE
Old DatePickerDialog?

### ISSUE THREAD

**Issue by hundeva** [Prototik/HoloEverywhere#713]
Is there any way to access the old DatePickerDialog in either 2.0 or 2.1? I am thinking about this one: https://raw.github.com/Prototik/HoloEverywhere/gh-pages/img/screenshots/7.png

Since migrating to 2.x, I had to adjust my code, and I am getting a new themed DatePickerDialog, this one: http://i.imgur.com/Pw03LV0.png . It is nice and all, but the old theme fits my app perfectly, more neat and clean. So my question is, can I use the old themed dialog in 2.x? Not a real issue, but I guess this is the best place to ask this. Thanks!

**Comment by Prototik** [comment]
No, old-styled dialog was removed in 2.0.

**Comment by DEvil0000** [comment]
same for me - on some places in my app the old date picker fits much better.
for example if you pick a birthdate - you don't want to know the day of week so the old style has a better feel...
pls bring back the old dialogs as alternative, maybe switching style with a setter.
