### ISSUE TITLE
Get Error in BaseAdapter Listview on 2.2 (Froyo), but on JB work

### ISSUE THREAD

**Issue by amaydiam** [Prototik/HoloEverywhere#714]
I Get Error in BaseAdapter Listview on 2.2 (Froyo), but on JB work , how to fix it ? thanks

**this my code define holoeverywhere**

```
import org.holoeverywhere.app.Activity;
import org.holoeverywhere.app.AlertDialog;
import android.app.ProgressDialog;
import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.os.AsyncTask;
import android.os.Bundle;
import android.os.Handler;
import android.text.Html;
import android.util.Log;
import org.holoeverywhere.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.view.animation.Animation;
import android.view.animation.AnimationUtils;
import android.widget.BaseAdapter;
import org.holoeverywhere.widget.ImageButton;
import android.widget.ImageView;
import org.holoeverywhere.widget.LinearLayout;
import org.holoeverywhere.widget.TextView;
import org.holoeverywhere.widget.Toast;

public class LazyAdapter extends BaseAdapter {
.....

}
```

**this error**

> 12-05 17:54:44.130: E/AndroidRuntime(342): FATAL EXCEPTION: main 12-05
> 17:54:44.130: E/AndroidRuntime(342): java.lang.StackOverflowError
> 12-05 17:54:44.130: E/AndroidRuntime(342):    at
> android.view.ViewGroup.drawChild(ViewGroup.java:1551) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.View.draw(View.java:6743) 12-05 17:54:44.130:
> E/AndroidRuntime(342):    at
> android.view.ViewGroup.drawChild(ViewGroup.java:1640) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.View.draw(View.java:6743) 12-05 17:54:44.130:
> E/AndroidRuntime(342):    at
> android.view.ViewGroup.drawChild(ViewGroup.java:1640) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.View.draw(View.java:6743) 12-05 17:54:44.130:
> E/AndroidRuntime(342):    at
> android.view.ViewGroup.drawChild(ViewGroup.java:1640) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.View.draw(View.java:6743) 12-05 17:54:44.130:
> E/AndroidRuntime(342):    at
> android.view.ViewGroup.drawChild(ViewGroup.java:1640) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.View.draw(View.java:6743) 12-05 17:54:44.130:
> E/AndroidRuntime(342):    at
> android.view.ViewGroup.drawChild(ViewGroup.java:1640) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.View.buildDrawingCache(View.java:6500) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1322) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.widget.AbsListView.dispatchDraw(AbsListView.java:1365) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.widget.ListView.dispatchDraw(ListView.java:3046) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.View.draw(View.java:6743) 12-05 17:54:44.130:
> E/AndroidRuntime(342):    at
> android.widget.AbsListView.draw(AbsListView.java:2257) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.drawChild(ViewGroup.java:1640) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.drawChild(ViewGroup.java:1638) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.View.draw(View.java:6743) 12-05 17:54:44.130:
> E/AndroidRuntime(342):    at
> android.view.ViewGroup.drawChild(ViewGroup.java:1640) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.drawChild(ViewGroup.java:1638) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.View.draw(View.java:6743) 12-05 17:54:44.130:
> E/AndroidRuntime(342):    at
> android.widget.FrameLayout.draw(FrameLayout.java:352) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.drawChild(ViewGroup.java:1640) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.drawChild(ViewGroup.java:1638) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.drawChild(ViewGroup.java:1638) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.View.draw(View.java:6743) 12-05 17:54:44.130:
> E/AndroidRuntime(342):    at
> android.view.ViewGroup.drawChild(ViewGroup.java:1640) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.View.draw(View.java:6743) 12-05 17:54:44.130:
> E/AndroidRuntime(342):    at
> android.view.ViewGroup.drawChild(ViewGroup.java:1640) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.drawChild(ViewGroup.java:1638) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.View.draw(View.java:6743) 12-05 17:54:44.130:
> E/AndroidRuntime(342):    at
> android.view.ViewGroup.drawChild(ViewGroup.java:1640) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.drawChild(ViewGroup.java:1638) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.View.draw(View.java:6743) 12-05 17:54:44.130:
> E/AndroidRuntime(342):    at
> android.view.ViewGroup.drawChild(ViewGroup.java:1640) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.drawChild(ViewGroup.java:1638) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.View.draw(View.java:6743) 12-05 17:54:44.130:
> E/AndroidRuntime(342):    at
> android.widget.FrameLayout.draw(FrameLayout.java:352) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.drawChild(ViewGroup.java:1640) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewGroup.dispatchDraw(ViewGroup.java:1367) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.View.draw(View.java:6743) 12-05 17:54:44.130:
> E/AndroidRuntime(342):    at
> android.widget.FrameLayout.draw(FrameLayout.java:352) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1842)
> 12-05 17:54:44.130: E/AndroidRuntime(342):    at
> android.view.ViewRoot.draw(ViewRoot.java:1407) 12-05 17:54:44.130:
> E/AndroidRuntime(342):    at
> android.view.ViewRoot.performTraversals(ViewRoot.java:1163) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.view.ViewRoot.handleMessage(ViewRoot.java:1727) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.os.Handler.dispatchMessage(Handler.java:99) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at
> android.os.Looper.loop(Looper.java:123) 12-05 17:54:44.130:
> E/AndroidRuntime(342):    at
> android.app.ActivityThread.main(ActivityThread.java:4627) 12-05
> 17:54:44.130: E/AndroidRuntime(342):  at j

**Comment by Prototik** [comment]
Dupe #481
Pre-HC devices have a very small stack size, not enough for too many view. You can simplify layouts or do something other which decrease a stack usage.
