### ISSUE TITLE
Class DatePickerDialog is broken

### ISSUE THREAD

**Issue by 4nd3250n** [Prototik/HoloEverywhere#716]
I have the code that compiled ok:

```
@Override
protected org.holoeverywhere.app.Dialog onCreateDialog(int id) {
    switch (id) {
        case DATE_PICKER_DIALOG_ID:
            return new DatePickerDialog(this, new OnDateSetListener(), 2012, 0, 1);
    }
    return null;
}
```

After upgrading to version 2.1 this code does not compile.
The problem is that class DatePickerDialog no longer extends Dialog. Instead it extends DialogFragment which is wrong.

**Comment by Prototik** [comment]
No, it's not broken. It will be dialogfragment and I wouldn't provide a pure-dialog variation.

**Comment by 4nd3250n** [comment]
Regarding this issue I would politely like to ask something.
In android  documentation it is stated that the preferred method of using DatePickerDialog (in regular android) is to extend DialogFragment and wrap DatePickerDialog inside it. (source: http://developer.android.com/guide/topics/ui/controls/pickers.html#TimePickerFragment)

However in HoloEverywhere, as stated in this topic, you have extended DatiPickerDialog from DialogFragment. Is there a reason behind it?
The usage as far as I could get it is to extend DatePickerDialog as this one is in itself already extended from fragment. How to initialize it I haven't figured yet. Wouldn't it be then more intuitive to name DatePickerDialog to something like DatePickerDialogFragment?

For information I have included packages and hierarchies of DatePickerDialog class in both Android and HoloEverywhere.

Android

```
Package
android.app.DatePickerDialog.OnDateSetListener

Hierarchy
android.app.Dialog
    android.app.AlertDialog
        android.app.DatePickerDialog
```

HoloEverywhere

```
Package
org.holoeverywhere.widget.datetimepicker.date.DatePickerDialog

Hierarchy
android.support.v4.app._HoloFragment
    org.holoeverywhere.app.Fragment
        org.holoeverywhere.app.DialogFragment
            org.holoeverywhere.widget.datetimepicker.date.DatePickerDialog
```

What bothers is that there is no parallel between android and holoeverywhere classes. This is not useful for making use of regular android patterns and documentation. Such parallelism makes it a lot easier to convert an application to holoeverywhere and to convert it back to regular android in the future, when there are few enough older devices.
But I guess holoeverywhere will support android 7.x look an 4.y devices by then.
