### ISSUE TITLE
Action bar below tabs

### ISSUE THREAD

**Issue by tzmst** [Prototik/HoloEverywhere#717]
I see that on some phone the action bar is below the tabs section. I did some research and i found that this is "a known bug" and i guess the holo support library mimics the real action bar, but is there a work around to make the action bar to be on top all the time ? I tried some suggestions found on stackoverflow but nothing seems to work.

**Comment by Prototik** [comment]
It is `a known bug` of ICS. We cannot modify native (ICS+) behavior because... because it is native O_o
Of course, we can force use of custom implementation of ActionBar, but it out of this library.

**Comment by tzmst** [comment]
y ... i wasn't talking about the devices that was using the support ... ofc we cant change this for the devices that uses the ICS behavior.

So in other words it stays as it is. thx for information
