### ISSUE TITLE
aapt duplicate keys with new maven apklib

### ISSUE THREAD

**Issue by Rutton** [Prototik/HoloEverywhere#73]
Hello,

I had the problem that aapt during maven compile reports duplicate resource entries in the holoeverywhere resources. Thats not wrong, the duplicate resource entries are really there. But I found out that this error only occurs, if the holoeverywhere apklib dependency (v1.2.0 from the sonatype repository) is listed after the actionbarsherlock dependency in the pom.xml. Reversing the order of the both dependencies (holoeverywhere-library before actionbarsherlock) solves the problem.
Cheers, R.

**Comment by neoasket** [comment]
holoeverywhere-library depends on actionbarsherlock itself, so you don't need to add actionbarsherlock dependency to your pom.xml at all
