### ISSUE TITLE
Slider Addon - Using ExpandableListView (SliderSubItem)

### ISSUE THREAD

**Issue by Alexwijn** [Prototik/HoloEverywhere#733]
I'm unable to use the ExpandableListView as a replacement of the regularly ListView in the layout. I tried to modify the SliderItem class. But I think I will break a lot of functions if I change that to a BaseExpandableListAdapter.

UPDATE: I just noticed SliderSubItem. I'm not familiar with Parcelables. But that class looks kind a empty. Is that a work in progress or am I missing something?

**Comment by Prototik** [comment]
It's WIP,  you right, support for subitems will added later.
