### ISSUE TITLE
AlertDialog FullScreen

### ISSUE THREAD

**Issue by Henriquedn** [Prototik/HoloEverywhere#740]
Hi,

Been using holoeverywhere and its aesome.

However i cant get an AlertDialog using the AlertDialog.Builder to fill the whole screen such that it doesnt look like a dialog but am not able to do so.

I tried this builder.setTheme(ThemeManager.DIALOG_WHEN_LARGE).

Please assist

**Comment by Prototik** [comment]
You can use a dialog and any activity theme without actionbar (eg Holo.Theme.Light.NoActionBar).
