### ISSUE TITLE
ActionBar Tabs overlap ActionBar API 10

### ISSUE THREAD

**Issue by BraisGabin** [Prototik/HoloEverywhere#741]
I think that with the image the issue is clear.

![device-2013-12-28-204232](https://f.cloud.github.com/assets/721244/1818346/3d408c8a-6ff8-11e3-8552-a75a64db0567.png)

I can reproduce the issue with a Galaxy Ace (2.3.6). this works fine with my Nexus 5 (4.4.2).

**Comment by Prototik** [comment]
See a [comment](https://github.com/Prototik/HoloEverywhere/commit/a4b852202c6375d0170d6d3988c21cea6b49da2c#commitcomment-4975540). btw for tabs you can use a TabSwipeActivity with proper tab handling.

**Comment by BraisGabin** [comment]
F***, novice error, sorry. Yes, I know it. But I implemented this code before that class existed and when I was updating it began to fail. Any way, thanks and I'll try TabSwipeActivity.
