### ISSUE TITLE
The future of Holoeverywhere

### ISSUE THREAD

**Issue by mehdifanai** [Prototik/HoloEverywhere#742]
The creator of ActionBarSherlock, Jake Wharton, announced on Google+ that further development of ActionBarSherlock has been stopped. ActionBarSherlock 4.4 is the last release and might get bug fixes – but there won’t be any new features:

While there may be a dot release or two in the coming weeks, version 4.4 is shaping up to be The Last Release™.
https://plus.google.com/+JakeWharton/posts/F3HkWY9J8fK

I have both holoeverywhere and ABS on my project and i want to know what should i do for now?
should i remove ABS and then use ActionbarCompat instead? Holoeverywhere depends on ABS.
What will the future of Holoeverywhere be like?

**Comment by BraisGabin** [comment]
HoloEverywhere doesn't have any dependency with ABS since v2.0. If you want to update HE you must change to ABS.

**Comment by felipecsl** [comment]
I guess @BraisGabin meant "you must change to **ABC**"

**Comment by BraisGabin** [comment]
Yes, you're right. A typo.
