### ISSUE TITLE
How to get currently visible fragment from activity when using slider addon?

### ISSUE THREAD

**Issue by mehdifanai** [Prototik/HoloEverywhere#747]
I want to know how to perform these actions:
1. Get reference to the currently visible and active fragment from the activity when using slider addon in combination with tabber.
2. Get reference to TabsTabsSwipeFragment from the activity/other fragments and dynamically disable/enable swiping.

Thank you

PSS: link to my qs on stackoverflow is: http://stackoverflow.com/questions/20926763/how-to-get-currently-visible-fragment-from-activity-when-using-holoeverywhere-sl

**Comment by Prototik** [comment]
You can provide tag for fragments like this:
`sliderMenu.add("tab2", Fragment2.class, SliderMenu.GREEN).setTag("mynavigation-2");`
Also you can get current page number by `sliderMenu.getCurrentPage()`.
You have no way for obtaining current fragment directly, but you can combine this two methods and find fragment via fragment manager: `getSupportFragmentManager().findFragmentByTag("mynavigation-" + sliderMenu.getCurrentPage())`

**Comment by mehdifanai** [comment]
Thanks @Prototik but how can i get the tab fragments which are a child of TabsTabsSwipeFragment fragment?
another issue i face is that onActivityResult is not called in tab fragments.

**Comment by mehdifanai** [comment]
http://stackoverflow.com/a/21081110/623694
