### ISSUE TITLE
how to add icons to holoeverywhere slider listview items?

### ISSUE THREAD

**Issue by mehdifanai** [Prototik/HoloEverywhere#748]
how to add icons to every holoeverywhere slider listview item?
Threre is no setIcon() method.
Thank you

**Comment by Prototik** [comment]
Please test this feature in latest master branch.

**Comment by mehdifanai** [comment]
I tested this new feature and its working like a charm. The only issue i face is that i cant chain methods.eg:

```
sliderMenu.add(R.string.ee, TabsTabsSwipeFragment.class,
                    SliderMenu.BLUE)
            .setIcon(R.drawable.ic_menu__holo_dark)
            .setTag("steTag");
```

the setIcon method needs to return this to allow method chaining
