### ISSUE TITLE
HoloEveryWhere support SwitchButton in API 10 ?

### ISSUE THREAD

**Issue by blitz33** [Prototik/HoloEverywhere#749]
Hi ,

I have seen on some pages that holoeverywhere support switch button in gingerbread, but when i had the switch button in my fragment i got this error : 

01-11 13:58:43.920: E/AndroidRuntime(26098): android.view.InflateException: Binary XML file line #54: Error inflating class Switch
01-11 13:58:43.920: E/AndroidRuntime(26098):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:581)
01-11 13:58:43.920: E/AndroidRuntime(26098):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
01-11 13:58:43.920: E/AndroidRuntime(26098):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:626)

HoloEveryWhere work with ABS on 1.6.5.

What is wrong ?

**Comment by Prototik** [comment]
you don't use holoeverywhere's layoutinflater, which handle all widget overrides, including override switch - org.holoeverywhere.widget.switch. please use layoutinflater passed to oncreateview method.
