### ISSUE TITLE
Button: Padding and Font-Size  on Android <4

### ISSUE THREAD

**Issue by M1cha** [Prototik/HoloEverywhere#75]
http://farm9.staticflickr.com/8037/7979594973_d7dbe05443_b.jpg
left: 2.1(but looks the thame in 2.3 and 3.0); right: Jellybean.

**Comment by Prototik** [comment]
Okay, i fix it in update to 1.2.2, tommorow.

**Comment by Prototik** [comment]
48d3fe01092a822feea3b997b83061b7284d8603
