### ISSUE TITLE
onActivityResult is not called in tab fragments

### ISSUE THREAD

**Issue by mehdifanai** [Prototik/HoloEverywhere#750]
onActivityResult is not called in tab fragments.When i start and activity inside a fragment which is a child fragment of Tab swipe fragment onActivityResult is not called.
I have tried all of the below combinations to start the activity and get the results but the results are only returned to the main activity and not the calling fragment:
1. startActivityForResult();
   2.getSupportActivity.startActivityForResult();
   3.getFragmentManager.startActivityForResult();;
   4.getChildFragmentManager().startActivityForResult();
   5.getParentFragment().startActivityForResult();

**Comment by Prototik** [comment]
It's limitation of support library. I can provide patch for this issue if you want.

**Comment by mehdifanai** [comment]
I will be grateful if you do so and if you think there is a better way please guide me.
Thank you

**Comment by Prototik** [comment]
Into HoloEverywhere's repo pushed artifact support-v4:19.0.3 (which based on Google's 19.0.1), please switch to this version in our build script.
