### ISSUE TITLE
how to use android-holo-colors in combinataion with holoeverywhere?

### ISSUE THREAD

**Issue by mehdifanai** [Prototik/HoloEverywhere#751]
According to this link: http://android-holo-colors.com/faq.html#holoeverywhere i can use both libs for good. But idont know what the "Theme name" and "Compatibility" must be set. I left the theme name blank but i see an underline in the start of generated assets.Some file names are different than holoeverywhere drawables.
And when i rebuild the project, i dont see any change in colors

I think the faq must be updated.

**Comment by Prototik** [comment]
I did send a [pull request](/jeromevdl/android-holo-colors/pull/77) which add holoeverywhere support to android-holo-colors.
Please wait for merging it into base repo and next release of android-holo-colors.
