### ISSUE TITLE
ListView.getCheckedItemIds() returns invalid array after deleting a record

### ISSUE THREAD

**Issue by 4nd3250n** [Prototik/HoloEverywhere#755]
I have observed a following problem in a ListView. Not sure if this is a holoeverywhere issue or is it inherited from stock android code.

I have:
a ListView with singleChoice mode
ListView uses an custom adapter extended from CursorAdapter

Course of action:
action mode is activated
a click on listviewitem implicitly calls sets the checked state for this item
an item is deleted via ContentProvider

My observation afterwards:
Method listView.getCount() returns correct number. One less as before delete. OK
Method listView.getCheckedPosition() returns position of newly checked item. OK
Method listView.getItemIdAtPosition(listView.getCheckedItemPosition()) returns correct ID. OK
But method listView.getCheckedItemIds() returns an array of lenght 1 which is OK since we have singleChoice mode. But an element at index 0 (i.e.   listView.getCheckedItemIds()[0]) contains an ID of element we just erased instead of the element which became checked instead of it. This is WRONG.

It seems that member mCheckedIdStates of class ListView is not maintained correctly.
Please note if one clicks on an item in listView and then back on an item on position which had wrong ID it somehow gets corrected. I guess there is an implicit call to setChecked() which takes care of that.

Once again, I am not sure if this is a holoeverywhere issue or something transferred from android code.

EDIT:
Another observation:
If one deletes the last record then the listview is empty. OK. But if one calls getCheckedItemPosition() it returns 0 which is wrong.

EDIT:
Extension of previous observation:
In ListView in singleChoice an item is checked at position x. If one deletes this item the item which is now in position x gets checked. In effect, item right beneath the deleted gets checked. But, if one deletes the last item in ListView then method getItemCheckedPosition() return also x, which now points beyond end of list. Visually no item is checked. It just causes problems when one does stuff relying on correct getItemCheckedPosition() result. In that case getItemCheckedPosition() should return the position od last item and display it as checked or it should return ListView.INVALID_POSITION.

**Comment by Prototik** [comment]
It's not holoeverywhere bug, inherited behavior of pure android.

Nothing checks for selection changed over invalidates datasetobserver,
BTW datasetobserver doesn't know about 'deletion' of items. He can only notify adapterview about items modification. Definitely you should delete rows via helper method which will be also uncheck needed items.
