### ISSUE TITLE
Can't find attributes: dialogButton and dialogButtonBorder

### ISSUE THREAD

**Issue by toadzky** [Prototik/HoloEverywhere#76]
Just got the latest version from git and it won't build.

**Comment by Prototik** [comment]
dialogButton(Border) and DialogButtonBar was a custom components. With porting AlertDialog from Jelly Bean DialogButtonBar no longer needed. DialogButtonBar and dialogButton attribute removed in 1.2.1. Completely. You do not have the latest version.

**Comment by toadzky** [comment]
My bad. I cloned to a separate directory and copied the files over so I didn't have to reset everything up on my CVS repository. The old files didn't get removed, and one of them was throwing the error.
