### ISSUE TITLE
Specifing custom debug storeFile location

### ISSUE THREAD

**Issue by saladinkzn** [Prototik/HoloEverywhere#765]
How do I specify custom debug storeFile location?
With android plugin I can use singingConfigs:

```
signingConfigs {
        debug {
            storeFile file("etc\\keys\\debug\\debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }
```

But as far as I can see from sources holoeverywhere-app implements its own singing process so my app is signed using default (~/.android/debug.keystore). How do I configure that or is there any workaround for doing this?

**Comment by Prototik** [comment]
In Plugin 0.2.10 (will available in maven central for couple hours) like this:

```
holoeverywhere {
  signing.key 'myUniqueName'
  // or split for build variants:
  // signing {
  //   release.key 'releaseName'
  //   debug.key 'debugName'
  // }
}
```

Then put in ~/.gradle/gradle.properties (on Windows - C:\Users\<username>\.gradle\gradle.properties:

```
myUniqueNameStoreFile=/full/path/to/keystore
myUniqueNameStorePassword=Password
myUniqueNameKeyAlias=Alias
myUniqueNameKeyPassword=Password
```

Also you can provide this values directly in .gradle file:

```
holoeverywhere {
  signing {
    debug {
      storeFile = ...
      storePassword = ...
      keyAlias = ...
      keyPassword = ...
    }
    release {
      ...
    }
  }
}
```
