### ISSUE TITLE
404 for https://raw.github.com/Prototik/HoloEverywhere/repo

### ISSUE THREAD

**Issue by pinglamb** [Prototik/HoloEverywhere#766]
The repo https://raw.github.com/Prototik/HoloEverywhere/repo is 404 now,
which makes Android Studio complaining HoloEverywhere can't be found.

**Comment by n3utrino** [comment]
I am having the same issue. I tried to use the gradle plugin but it gives me 

```
   Cannot add task ':validateDebugSigning' as a task with that name already exists.
```

**Comment by pinglamb** [comment]
I am using https://raw.github.com/tushroy/HoloEverywhere/repo for release 2.1.0 temporarily.
The https://github.com/tushroy/HoloEverywhere still has the repo branch.

**Comment by alexleutgoeb** [comment]
The plugin is working for me with the following build.gradle, however packaging gives an error cause of duplicate AndroidManifest.xml file (in app and in apklib of HE). :-/

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:0.7.+'
        classpath 'org.holoeverywhere:plugin:0.2.+'
    }
}

apply plugin: 'holoeverywhere-app'

repositories {
    mavenCentral()
}

android {
    compileSdkVersion 19
    buildToolsVersion '19.0.0'
}

holoeverywhere {
    addons {
        preferences
    }
    library {
        version = 'snapshot'
    }
}
```

**Comment by Prototik** [comment]
Good news guys: you can use normal repositories:
http://192.241.191.41/repo/
http://192.241.191.41/snapshot/

**Comment by alexleutgoeb** [comment]
Thanks a lot for the new repo!

I'm still stuck with the new snapshot, using this minimal build file (testing on Android 4.0):

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:0.7.+'
    }
}

apply plugin: 'android'

repositories {
    mavenCentral()

    maven {
        url 'http://192.241.191.41/snapshot'
    }
}

android {
    compileSdkVersion 19
    buildToolsVersion '19.0.0'
}

dependencies {
    compile 'com.android.support:support-v4:19.0.+'
    compile 'org.holoeverywhere:library:2.1.1-SNAPSHOT@aar'
    compile 'org.holoeverywhere:addon-preferences:2.1.1-SNAPSHOT@aar'
}
```

the app crashes on startup with following log output:

```
Failed resolving Landroid/support/v4/app/_HoloFragmentInflater$1; interface 253 'Landroid/support/v4/app/NoSaveStateFrameLayout$NoSaveStateFrameLayoutCreator;'
Link of class 'Landroid/support/v4/app/_HoloFragmentInflater$1;' failed
Could not find class 'android.support.v4.app._HoloFragmentInflater$1', referenced from method android.support.v4.app._HoloFragmentInflater.<clinit>
...
     Caused by: java.lang.NoClassDefFoundError: android.support.v4.app._HoloFragmentInflater$1
            at android.support.v4.app._HoloFragmentInflater.<clinit>(_HoloFragmentInflater.java:18)
            at org.holoeverywhere.app.Application.<clinit>(Application.java:34)
```

So apparently there is still something wrong with the support library in my project. Anyone successfully using the new repo?

Thanks,
Alex

**Comment by Prototik** [comment]
Include _both_ repos for snapshot versions and _only first_ for release versions

**Comment by alexleutgoeb** [comment]
:+1: Perfect, this explains a lot about the repo structure, thanks a lot for your work + support!

**Comment by Prototik** [comment]
Well, you can support server by donations :D Distribution of files - hard work :)
