### ISSUE TITLE
HoloEverywhere dependency not working

### ISSUE THREAD

**Issue by HenriqueRocha** [Prototik/HoloEverywhere#767]
My project is not building because of the following error:

> Could not resolve all dependencies for configuration ':_debugCompile'.
> Could not find android:android:4.3_r2.
>      Required by:
>          :androidpit-app-2:unspecified > org.holoeverywhere:library:2.1.0 > com.android.support:support-v4:18.0.3

I have this one my current build.gradle:

```
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:0.8.+'
        classpath 'org.holoeverywhere:plugin:0.2.+'
    }
}

apply plugin: 'holoeverywhere-app'

repositories {
    mavenCentral()
    maven { url "https://github.com/AndroidPIT/mvn-repo/raw/v2.1" }
}

```

**Comment by almozavr** [comment]
You can use 'manual' mode with following repos:
http://192.241.191.41/repo/
http://192.241.191.41/snapshot/
See details: https://github.com/Prototik/HoloEverywhere/issues/766

**Comment by Prototik** [comment]
Artifact `android:android:4.3_r2` has been deployed to main repo.

_btw holoeverywhere plugin include both repos by default_
