### ISSUE TITLE
AlertDialog light style

### ISSUE THREAD

**Issue by toadzky** [Prototik/HoloEverywhere#77]
So the dialogs are showing up, but they are holo-dark style instead of holo-light

**Comment by Prototik** [comment]
Yes, it is bug. Will be fixed in 1.2.2

**Comment by Prototik** [comment]
48d3fe01092a822feea3b997b83061b7284d8603

**Comment by jbellander** [comment]
Is this really fixed? I get the dark theme in both my project and the demo.

**Comment by Prototik** [comment]
@jbellander Yes, you may see it on screenshots

**Comment by jbellander** [comment]
The screenshot of the AlertDialog is only in Dark Theme (or am I looking in the wrong place?)

**Comment by Prototik** [comment]
Yes, light AlertDialog contains in screenshots to 1.2.2 release: https://github.com/ChristopheVersieux/HoloEverywhere/blob/48d3fe01092a822feea3b997b83061b7284d8603/website/screen6.png

**Comment by jbellander** [comment]
Hmm.. got it working in the demo, must be something I'm doing wrong. Thanks for your (very quick) help!
