### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by Lakedaemon** [Prototik/HoloEverywhere#771]
This might not be related, but since I migrated my code from holoeverywhere 1.6.8 
to holoeverywhere 2.0/2.1/latest, I have been experimenting crashes due to out of memory error with gingerbread devices (but not with ICS/JB/KK -> it is probably related to bitmaps)

I recorded a heap dump and took a few screenshot in MAT while investigating the issue, Trying to find if this comes from my code (probably) or from a library (support or  holoeverywhere).

It looks like there is a problem with finalizers and/or with bitmaps (in relation with listView/ProgressBar) especially since I use few  bitmaps in my app (and they are small)
What do you think ? 

![screenshot from 2014-01-25 11 56 27](https://f.cloud.github.com/assets/103175/2001542/68fab27e-85b5-11e3-940f-6631d1c7136e.png)

![screenshot from 2014-01-25 11 58 00](https://f.cloud.github.com/assets/103175/2001544/7c33e3ce-85b5-11e3-9f2a-222e2aba633f.png)

![screenshot from 2014-01-25 11 57 21](https://f.cloud.github.com/assets/103175/2001546/834d6248-85b5-11e3-8c64-c5b81c8b63ce.png)

**Comment by Prototik** [comment]
It's very funny, but holoeverywhere's widgets doesn't modify glow effect.
Anyway I see that ViewRootImpl hold on ListView widget in internal containers, so I cannot fix this issue.

**Comment by Lakedaemon** [comment]
You are right, the fault didn't lie with holoeverywhere :  
I thought that the big 1MB bitmap that I discovered in MAT was a memory leak, but it was actually an android system bitmap (shared by the zygotte process) to provide a nice background for the listviews. Those stackoverflow thread made this clear : 
http://stackoverflow.com/questions/18594576/android-edgeeffect-appears-to-allocate-a-1-meg-bitmap
http://stackoverflow.com/questions/18515647/strange-bitmap-using-1-mb-of-heap
