### ISSUE TITLE
Support library partly compiled with JDK 7

### ISSUE THREAD

**Issue by pszalanski** [Prototik/HoloEverywhere#774]
Due to some of the classes in the support library being built using JDK 7, the demo and my app crash with a class not found error. This is most probably caused by these errors during launch:

```
Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing android/support/v4/view/MotionEventCompatEclair.class
...while processing android/support/v4/view/MotionEventCompatEclair.class
```

I checked some of these classes with `javap` and they have the version number 51 (jdk 7) and not 50 (jdk 6). Can you please rebuild the support library exclusively using jdk 6?

**Comment by Prototik** [comment]
Wargh. I'd recompile it only for your avatar with ArchLinux ;)

`com.android.support:support-v4:19.1.0` available in HoloEverywhere's Repo. 

```
Classfile /home/prok/git/SupportLibrary/build/libs/z/android/support/v4/view/MotionEventCompatEclair.class
  Last modified Jan 29, 2014; size 1023 bytes
  MD5 checksum 403684559c787b4533ec8e7bfbf0ced1
  Compiled from "MotionEventCompatEclair.java"
class android.support.v4.view.MotionEventCompatEclair
  SourceFile: "MotionEventCompatEclair.java"
  minor version: 0
  major version: 50
  flags: ACC_SUPER
```

**Comment by pszalanski** [comment]
Thank you! It's fixed. I had to change the support lib version in the parent pom, though. But I guess you will fix that sooner or later.
