### ISSUE TITLE
Illegal theme exception

### ISSUE THREAD

**Issue by pszalanski** [Prototik/HoloEverywhere#776]
I am getting an error about me not using the Holo.Theme style in my Activity. But when I apply the fix mentioned in #623 I get another exception:

```
01-29 16:49:57.985: E/ACRA(15423): com.oneupmedia.utility.wrtdroid fatal error : Unable to start activity ComponentInfo{com.oneupmedia.utility.wrtdroid/com.oneupmedia.utility.wrtdroid.activities.RouterListActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
```

Although I have this in my styles definition:

``` xml
    <style name="AppBaseTheme" parent="@style/Theme.AppCompat.Light" >
        <item name="android:editTextStyle">@style/WrtEditText</item>

        <item name="actionBarStyle">@style/WrtActionBar</item>
        <item name="android:actionBarStyle" tools:ignore="NewApi">@style/WrtActionBar</item>
    </style>
```

When I apply the Theme.AppCompat.Light directly, it works, just not with my custom style. Any ideas?

**Comment by pszalanski** [comment]
@Prototik Did you have a chance to look into this issue?

**Comment by pszalanski** [comment]
So I got it working, at least on API level 10, by using the ThemeManager to set the theme in my Application class. I removed any theme directives from my activites in the `AndroidManifest.xml` This is what I did:

``` java
ThemeManager.setDefaultTheme(ThemeManager.MIXED);
ThemeManager.map(ThemeManager.MIXED, R.style.AppBaseTheme);
```

But this crashes on API 19 with this messsage:

```
android.support.v4.app._HoloActivity$HoloThemeException: You must apply Holo.Theme, Holo.Theme.Light or Holo.Theme.Light.DarkActionBar theme on the activity (RouterListActivity) for using HoloEverywhere

```

**Comment by Prototik** [comment]
It's logical - you using appcompat theme, not holoeverywhere theme.

**Comment by pszalanski** [comment]
I tried it all, nothing works. Except when I do this:

``` java
ThemeManager.setDefaultTheme(ThemeManager.MIXED);
ThemeManager.map(ThemeManager.MIXED, R.style.Holo_Theme_Light_DarkActionBar);
```

BTW, this is my style definition:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="AppBaseTheme" parent="Holo.Theme.Light.DarkActionBar" >
    </style>
</resources>
```

**Comment by pszalanski** [comment]
Oh damn it all to hell, the name `AppBaseTheme` was already declared somewhere, which caused a conflict. After changing the name of my custom theme it works. Thank you for your help!
