### ISSUE TITLE
You must apply Holo.... with Robolectric 2.2.

### ISSUE THREAD

**Issue by arichiardi** [Prototik/HoloEverywhere#777]
When I run my Activity through Robolectric and create it, I always receive:

```
android.support.v4.app._HoloActivity$HoloThemeException: You must apply Holo.Theme, Holo.Theme.Light or Holo.Theme.Light.DarkActionBar theme on the activity (GLarmMain) for using HoloEverywhere
    at android.support.v4.app._HoloActivity.onInit(_HoloActivity.java:292)
    at android.support.v4.app._HoloActivity.forceInit(_HoloActivity.java:105)
    at org.holoeverywhere.app.Activity.onCreate(Activity.java:142)
```

whatever I put in `android:theme` or `setTheme()`. I tracked down the issue and if I comment out the if in:

```
public static void applyTheme(Activity activity, boolean force) {
    if (force || ThemeManager.hasSpecifiedTheme(activity)) {
            activity.setTheme(ThemeManager.getThemeResource(activity));
    }
}
```

everything works fine. It seems that `hasSpecifiedTheme` makes use of Intents and they are not set by Robolectric's runtime. I don't know whether is a Holoeverywhere or Robolectric problem actually. Seeking some advice...thanks!

**Comment by Prototik** [comment]
Then Robolectric does set theme for activity. HoloEverywhere's runtime do it only if no other theme was specified, eg you have only basic activity declaration in manifest (without theme attribute).

I don't know exactly, how robolectric runs tests (i don't know even target platform for running, sorry), but it seems like robolectric's issue.

**Comment by arichiardi** [comment]
I see, I guess the way they handle the runtime is slightly different and my custom theme (that inherits from yours) is not correctly loaded. Thank you.
