### ISSUE TITLE
org.holoeverywhere.app.Activity does not support ActionBar in Overlay mode

### ISSUE THREAD

**Issue by Eng-Fouad** [Prototik/HoloEverywhere#779]
When I replace the super activity with ActionBarActivity, it works!

To produce the same behavior, create a normal Android project on eclipse and add these lines in the MainActivity:

```
super.onCreate(savedInstanceState);

requestWindowFeature(Window.FEATURE_ACTION_BAR_OVERLAY);

setContentView(R.layout.activity_main);

ActionBar actionBar = getSupportActionBar();
actionBar.setBackgroundDrawable(new ColorDrawable(Color.parseColor("#11000000")));
```

**Comment by Prototik** [comment]
Did you try call supportRequestWindowFeature? And you should call it before super.onCreate, as I remember.

**Comment by Eng-Fouad** [comment]
Ah indeed, supportRequestWindowFeature() did it!
