### ISSUE TITLE
addon slide full screen touch mode

### ISSUE THREAD

**Issue by icode** [Prototik/HoloEverywhere#782]
like SlidingMenu setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN),
menu hold place,push actionbar

like google+ slide menu hold place

**Comment by Prototik** [comment]
If you can find a way for doing it with DrawerLayout - then you implement this feature. If you can provide patches for this for support library - you are good guy and I'll merge it with pleasure.
