### ISSUE TITLE
AlertDialog Button text is wrong

### ISSUE THREAD

**Issue by pszalanski** [Prototik/HoloEverywhere#785]
When I build a dialog with a positive and negative button, they do not have the text I specified:

``` java
dialog.setPositiveButton(android.R.string.yes, ...);
dialog.setNegativeButton(android.R.string.no, ...);
```

When I set the buttons like that, the dialog still shows me buttons labeled "OK" and "Cancel".

**Comment by BraisGabin** [comment]
Android feature. Not related with HoloEverywhere.
