### ISSUE TITLE
Scrolling issues on ScrollView with nested ViewPager 

### ISSUE THREAD

**Issue by fmontano** [Prototik/HoloEverywhere#789]
I am currently working on a project on which we have a vertical ScrollView that holds a ViewPager. The problem is that when I try to swipe left or right for more pages, the motion has to be perfectly horizontal. I am scrolling horizontally, as soon as I move my finger just a little bit up or down, the scrollview takes the scroll and the page won't change.

I remove HoloEverywhere from my app, and it works flawlessly using android.support.v4.view.ViewPager, as it blocks any vertical scroll on the ScrollView during a horizontal scroll in the ViewPager. 

Any ideas on what's going on with HoloEverywhere? or where in the code I should look to try to find a solution for this issue?

Thanks

**Comment by Prototik** [comment]
It's very strange - have a viewpager inside scrollview.
HoloEverywhere hasn't modify touch behavior (only in viewpager with property swipeEnabled = false modified, but it's not related with this issue).

Try to change a UX/UI of your application, I cannot help you more.

**Comment by fmontano** [comment]
Thanks for your feedback. I feel exactly the same way, but the client is always right, right? :/
