### ISSUE TITLE
Spinner-Dialog Text-Color

### ISSUE THREAD

**Issue by M1cha** [Prototik/HoloEverywhere#79]
Since 1.2.2 system-dialogs like "Longpress EditText" aren't styled anymore.
I don't have a big problem with that, but the Spinner-Dialog still has a white text-colour(on white background). 
Tested on 2.1.

**Comment by Prototik** [comment]
Yes, i know. I work on porting Spinner.

**Comment by Prototik** [comment]
6416ba54efd999c908399798428a37c056aa8934
