### ISSUE TITLE
How to implement HoloEverywhere library and run application without errors?

### ISSUE THREAD

**Issue by dehcastro** [Prototik/HoloEverywhere#797]
Please somebody help me!

I'm trying to implement this library into my application, and even following the steps on basic migration my application still has errors.

Someone knows about any complete tutorial?

**Comment by Prototik** [comment]
Which errors are present? Concretize please.

And no, no one have a _complete tutorial_ by migrating.

**Comment by dehcastro** [comment]
I created a new application to test. I imported the libraries as the HoloeveryWhere Demo. I extended the only activity I have from: org.holoeverywhere.app.Activity as showed, then I put some widgets just to test.

I put also: android:name="org.holoeverywhere.app.Application" in <application> tag in manifest.

When I try to run, the following message shows on console:

[2014-02-28 12:32:51 - Dex Loader] Unable to execute dex: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
[2014-02-28 12:32:52 - TestHolo] Conversion to Dalvik format failed: Unable to execute dex: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;

Then, I deleted the file: android-support-v4 in libs folder and tried to run again, and an error appears:

02-28 15:44:15.631: E/AndroidRuntime(310): FATAL EXCEPTION: main
02-28 15:44:15.631: E/AndroidRuntime(310): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.testholo/com.example.testholo.MainActivity}: android.support.v4.app._HoloActivity$HoloThemeException: You must apply Holo.Theme, Holo.Theme.Light or Holo.Theme.Light.DarkActionBar theme on the activity (MainActivity) for using HoloEverywhere
02-28 15:44:15.631: E/AndroidRuntime(310):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2663)
02-28 15:44:15.631: E/AndroidRuntime(310):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2679)
02-28 15:44:15.631: E/AndroidRuntime(310):  at android.app.ActivityThread.access$2300(ActivityThread.java:125)
02-28 15:44:15.631: E/AndroidRuntime(310):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
02-28 15:44:15.631: E/AndroidRuntime(310):  at android.os.Handler.dispatchMessage(Handler.java:99)
02-28 15:44:15.631: E/AndroidRuntime(310):  at android.os.Looper.loop(Looper.java:123)
02-28 15:44:15.631: E/AndroidRuntime(310):  at android.app.ActivityThread.main(ActivityThread.java:4627)
02-28 15:44:15.631: E/AndroidRuntime(310):  at java.lang.reflect.Method.invokeNative(Native Method)
02-28 15:44:15.631: E/AndroidRuntime(310):  at java.lang.reflect.Method.invoke(Method.java:521)
02-28 15:44:15.631: E/AndroidRuntime(310):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
02-28 15:44:15.631: E/AndroidRuntime(310):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
02-28 15:44:15.631: E/AndroidRuntime(310):  at dalvik.system.NativeStart.main(Native Method)
02-28 15:44:15.631: E/AndroidRuntime(310): Caused by: android.support.v4.app._HoloActivity$HoloThemeException: You must apply Holo.Theme, Holo.Theme.Light or Holo.Theme.Light.DarkActionBar theme on the activity (MainActivity) for using HoloEverywhere
02-28 15:44:15.631: E/AndroidRuntime(310):  at android.support.v4.app._HoloActivity.onInit(_HoloActivity.java:292)
02-28 15:44:15.631: E/AndroidRuntime(310):  at android.support.v4.app._HoloActivity.forceInit(_HoloActivity.java:105)
02-28 15:44:15.631: E/AndroidRuntime(310):  at org.holoeverywhere.app.Activity.onCreate(Activity.java:142)
02-28 15:44:15.631: E/AndroidRuntime(310):  at com.example.testholo.MainActivity.onCreate(MainActivity.java:12)
02-28 15:44:15.631: E/AndroidRuntime(310):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
02-28 15:44:15.631: E/AndroidRuntime(310):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2627)
02-28 15:44:15.631: E/AndroidRuntime(310):  ... 11 more

**Comment by ghost** [comment]
I have this problem too.....

**Comment by dehcastro** [comment]
I fixed putting Holo.Theme, Holo.Theme.Light or Holo.Theme.Light.DarkActionBar theme in the Manifest file. Try it!

**Comment by ghost** [comment]
no changes
same error
<code>android:theme="@style/Holo.Theme"</code> 
<code>android:theme="@style/Holo.Theme.Light"</code> 
<code>android:theme="@style/Holo.Theme.Light.DarkActionBar"</code>

**Comment by HanderWei** [comment]
I  have the same problem,too...

If you solve this  problem ,please tell me.

**Comment by HanderWei** [comment]
@AndreDeCastro @hamedjj I have solved this problem.

Must delete the android-support v4.jar in your project's libs folder

Because the holoeverywhere lib has support-v4.jar already..

**Comment by dehcastro** [comment]
yes!!! I forgot to say that...the first thing I did was that (delete android-support v4.jar on libs folder) and after that I had the problem with the theme because I didn't set a Holo Theme.

**Comment by ghost** [comment]
thank you
i fixed it

**Comment by HanderWei** [comment]
@AndreDeCastro @hamedjj How to add holo fragment into activity?

Hander_Wei@163.com 
This  is  my  email.

**Comment by BraisGabin** [comment]
There are not differences between add a Fragment inside an Activity with or without HoloEverywhere. Please use StackOverflow. You will get better support.
