### ISSUE TITLE
Old DatePickerDialog? Pls bring it back as alternative!

### ISSUE THREAD

**Issue by DEvil0000** [Prototik/HoloEverywhere#801]
just to make sure someone reads this even if it is closed
this is a dup of -> "Old DatePickerDialog?" #713

old style pickers look & feel is better in some situations.
- like birthdate picking

a user is not used to pick his birthdate by calendar. there is no need to know the weekdays. selection with the old dialog is quite more intuitive and faster in this situation.

**Comment by andrehsouza** [comment]
I'm trying to implement this library (https://github.com/SimonVT/android-datepicker) as an alternative, but I'm having problems to inflate.

**Comment by BraisGabin** [comment]
Another option: https://github.com/derekbrameyer/android-betterpickers

I close this because, yes, it's a duplicate.

**Comment by Prototik** [comment]
_I'd started coming back a pickers in library as module, but @BraisGabin provide a cool solution_
