### ISSUE TITLE
How to add fragment into Activity?

### ISSUE THREAD

**Issue by HanderWei** [Prototik/HoloEverywhere#805]
The demo add Fragment into SliderMenu.

I want to kown how to add fragment into Activity.

Any help will be highly appreciate.

**Comment by Prototik** [comment]
Please read basic guides for support library before asking.

``` java
FragmentManager fm = activity.getSupportFragmentManager();
FragmentTransaction ft = fm.beginTransaction();
ft.add(R.id.content, new MyFragment());
ft.commit();
```
