### ISSUE TITLE
ListPreference not working on some devices

### ISSUE THREAD

**Issue by hieult** [Prototik/HoloEverywhere#807]
When I run HoloEverywhere Demo on my Sony Xperia S, go to Settings, click on "List" preference, the radio button on the list is not showed. Moreover, when I try to scroll the list, the app was crashed
Here is the error stack:

03-17 23:58:07.133: E/AndroidRuntime(13717): FATAL EXCEPTION: main
03-17 23:58:07.133: E/AndroidRuntime(13717): java.lang.IllegalArgumentException: bitmap size exceeds 32bits
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.graphics.Bitmap.nativeCreate(Native Method)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.graphics.Bitmap.createBitmap(Bitmap.java:477)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.View.buildDrawingCache(View.java:6683)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.View.getDrawingCache(View.java:6534)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.ViewGroup.drawChild(ViewGroup.java:1664)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1466)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.widget.AbsListView.dispatchDraw(AbsListView.java:1570)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.widget.ListView.dispatchDraw(ListView.java:3139)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.View.draw(View.java:7093)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.widget.AbsListView.draw(AbsListView.java:2699)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at org.holoeverywhere.widget.ListView.draw(ListView.java:192)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.ViewGroup.drawChild(ViewGroup.java:1739)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1466)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.View.draw(View.java:6989)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.ViewGroup.drawChild(ViewGroup.java:1739)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1466)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.View.draw(View.java:6989)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.ViewGroup.drawChild(ViewGroup.java:1739)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1466)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.ViewGroup.drawChild(ViewGroup.java:1737)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1466)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.ViewGroup.drawChild(ViewGroup.java:1737)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1466)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.View.draw(View.java:6989)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.widget.FrameLayout.draw(FrameLayout.java:361)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1862)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.ViewRoot.draw(ViewRoot.java:1546)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.ViewRoot.performTraversals(ViewRoot.java:1282)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.view.ViewRoot.handleMessage(ViewRoot.java:1884)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.os.Handler.dispatchMessage(Handler.java:99)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.os.Looper.loop(Looper.java:138)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at android.app.ActivityThread.main(ActivityThread.java:3701)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at java.lang.reflect.Method.invokeNative(Native Method)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at java.lang.reflect.Method.invoke(Method.java:507)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
03-17 23:58:07.133: E/AndroidRuntime(13717):    at dalvik.system.NativeStart.main(Native Method)

Please help to fix this issue.

Thank you

**Comment by hieult** [comment]
My device is running android 2.3.7, too much errors on real devices

**Comment by lgawin** [comment]
@hieult, can you please check the issue again using my branch (#816). Fast review of demo application showed, that all visual problems have been solved.
