### ISSUE TITLE
How to implement it?

### ISSUE THREAD

**Issue by claudiopastorini** [Prototik/HoloEverywhere#808]
How can I implement the library?
I followed the Android Studio / IntelliJ IDEA guide step by step, but now, what should I do in order to implement it in my preexisting app?

I use Android Studio with Gradle and I thought that I could implement it as I did other (few) times (i.e Gson) only adding dependencies in my build.gradle.

**Comment by BraisGabin** [comment]
Did you [read this](https://github.com/Prototik/HoloEverywhere/wiki/Basic-migration-on-HoloEverywhere)?

**Comment by claudiopastorini** [comment]
Yes but how can I refer to a package that does not belong to my project?

**Comment by Prototik** [comment]
Mmm... If I understand you right...
As usual. As with any other library. Do you use some other 3rd party libraries with your IDE?

**Comment by claudiopastorini** [comment]
I used only few times gradle in order to import libraries. If they are supported by maven, I will simply add a dependency in build.gradle; if they are file projects, instead, I will as usual do that:

<ol>
<li>I add the entire folder in my project in folder libs;
<li>I add the dependencies in setting.gradle: <b>include ':libs:HoloEverywhere', ':ProvaHolo';</b>
<li>I add the dependencies in build.gradle: <b>compile project(':libs:HoloEverywhere')</b>
<li>I start the sync...
</ol>

I receive always the same error:
<b>Gradle 'ProvaHolo' project refresh failed:
Configuration with name 'default' not found</b>

Why? What can you suggest me? I am unfamilair with using Gradle, sorry

**Comment by ghost** [comment]
This reminds me of my situation months ago, always getting this error when configuring projects. If you don't mind using maven, just go the maven way. Gradle made lots of changes on library management every now and then.

You can actually use maven inside your build.gradle to get HoloEverywhere compiled into an aar file for Android Studio.

```
repositories {
    mavenCentral()
    maven {
        url "http://192.241.191.41/repo/"
    }
}

dependencies {
    compile 'com.android.support:support-v4:19.0.+'
    //compile 'com.android.support:appcompat-v7:19.0.+'
    compile 'com.nineoldandroids:library:2.4.+@jar'
    compile 'org.holoeverywhere:library:2.1.+@aar'
    compile 'org.holoeverywhere:addon-preferences:2.1.+@aar'
    compile fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
}
```

**Comment by claudiopastorini** [comment]
Thanks a lot, it works!! (after some changes as theme and application type). 
How should I have done it following the way esplicateded in the wiki?

**Comment by ghost** [comment]
I guess the wiki is simply outdated :(

**Comment by claudiopastorini** [comment]
Prototik, give us some explanations, pleeeeeease

**Comment by Prototik** [comment]
Which explanations you are need? I just now tried execute steps on `Gradle` page and build some application - that's work. If you need a manual for usage this library - sorry, I have no it :-/ But you can always see a demo implementation and make similarly in your app.
