### ISSUE TITLE
SPreferenceActivity - Working on Android < 4, Not working on 4+

### ISSUE THREAD

**Issue by indieboyalex** [Prototik/HoloEverywhere#81]
I'm having an issue using SPreferenceActivity and a preference.xml file using the holo: namespace.  When I run my activity on older versions of Android (i.e. Gingerbread) it works fine and I get nice Holo style dialogs.  However, when I run it on ICS devices/emulator the activity fails.

This is the stacktrace:

E/AndroidRuntime(19900): FATAL EXCEPTION: main
E/AndroidRuntime(19900): android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
E/AndroidRuntime(19900):    at android.view.LayoutInflater.createView(LayoutInflater.java:606)
E/AndroidRuntime(19900):    at com.WazaBe.HoloEverywhere.LayoutInflater.onCreateView(LayoutInflater.java:135)
E/AndroidRuntime(19900):    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:653)
E/AndroidRuntime(19900):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:678)
E/AndroidRuntime(19900):    at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
E/AndroidRuntime(19900):    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
E/AndroidRuntime(19900):    at com.WazaBe.HoloEverywhere.preference.Preference.onCreateView(Preference.java:473)
E/AndroidRuntime(19900):    at com.WazaBe.HoloEverywhere.preference.Preference.getView(Preference.java:360)
E/AndroidRuntime(19900):    at com.WazaBe.HoloEverywhere.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:162)
E/AndroidRuntime(19900):    at android.widget.AbsListView.obtainView(AbsListView.java:2052)
E/AndroidRuntime(19900):    at android.widget.ListView.makeAndAddView(ListView.java:1820)
E/AndroidRuntime(19900):    at android.widget.ListView.fillDown(ListView.java:672)
E/AndroidRuntime(19900):    at android.widget.ListView.fillFromTop(ListView.java:732)
E/AndroidRuntime(19900):    at android.widget.ListView.layoutChildren(ListView.java:1673)
E/AndroidRuntime(19900):    at android.widget.AbsListView.onLayout(AbsListView.java:1882)
E/AndroidRuntime(19900):    at android.view.View.layout(View.java:11432)
E/AndroidRuntime(19900):    at android.view.ViewGroup.layout(ViewGroup.java:4232)
E/AndroidRuntime(19900):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1628)
E/AndroidRuntime(19900):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1486)
E/AndroidRuntime(19900):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1399)
E/AndroidRuntime(19900):    at android.view.View.layout(View.java:11432)
E/AndroidRuntime(19900):    at android.view.ViewGroup.layout(ViewGroup.java:4232)
E/AndroidRuntime(19900):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1628)
E/AndroidRuntime(19900):    at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1617)
E/AndroidRuntime(19900):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1401)
E/AndroidRuntime(19900):    at android.view.View.layout(View.java:11432)
E/AndroidRuntime(19900):    at android.view.ViewGroup.layout(ViewGroup.java:4232)
E/AndroidRuntime(19900):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1628)
E/AndroidRuntime(19900):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1486)
E/AndroidRuntime(19900):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1399)
E/AndroidRuntime(19900):    at android.view.View.layout(View.java:11432)
E/AndroidRuntime(19900):    at android.view.ViewGroup.layout(ViewGroup.java:4232)
E/AndroidRuntime(19900):    at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
E/AndroidRuntime(19900):    at android.view.View.layout(View.java:11432)
E/AndroidRuntime(19900):    at android.view.ViewGroup.layout(ViewGroup.java:4232)
E/AndroidRuntime(19900):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1628)
E/AndroidRuntime(19900):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1486)
E/AndroidRuntime(19900):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1399)
E/AndroidRuntime(19900):    at android.view.View.layout(View.java:11432)
E/AndroidRuntime(19900):    at android.view.ViewGroup.layout(ViewGroup.java:4232)
E/AndroidRuntime(19900):    at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
E/AndroidRuntime(19900):    at android.view.View.layout(View.java:11432)
E/AndroidRuntime(19900):    at android.view.ViewGroup.layout(ViewGroup.java:4232)
E/AndroidRuntime(19900):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1516)
E/AndroidRuntime(19900):    at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2505)
E/AndroidRuntime(19900):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(19900):    at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(19900):    at android.app.ActivityThread.main(ActivityThread.java:4945)
E/AndroidRuntime(19900):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(19900):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(19900):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
E/AndroidRuntime(19900):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
E/AndroidRuntime(19900):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(19900): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(19900):    at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime(19900):    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
E/AndroidRuntime(19900):    at android.view.LayoutInflater.createView(LayoutInflater.java:586)
E/AndroidRuntime(19900):    ... 52 more
E/AndroidRuntime(19900): Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x2
E/AndroidRuntime(19900):    at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
E/AndroidRuntime(19900):    at android.view.View.<init>(View.java:3046)
E/AndroidRuntime(19900):    at android.view.ViewGroup.<init>(ViewGroup.java:393)
E/AndroidRuntime(19900):    at android.widget.LinearLayout.<init>(LinearLayout.java:174)
E/AndroidRuntime(19900):    at android.widge

And this is the preferences.xml which works on pre-4 devices:

<?xml version="1.0" encoding="utf-8"?>
<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:holo="http://schemas.android.com/apk/res-auto" >

```
<PreferenceCategory
    holo:key="pref_category_ui"
    holo:title="@string/ui" >
    <ListPreference
        holo:defaultValue="red"
        holo:entries="@array/theme_names"
        holo:entryValues="@array/theme_keys"
        holo:key="pref_ui_theme"
        holo:persistent="true"
        holo:summary="Change colour scheme of app"
        holo:title="@string/app_theme" />

    <com.pocketwriters.widgets.ListPreferenceMultiSelect
        holo:defaultValue="new;popular;today;classic;draft;history"
        holo:dialogTitle="Select Lists to Display"
        holo:entries="@array/list_names"
        holo:entryValues="@array/list_keys"
        holo:key="pref_ui_tabs"
        holo:summary="Specify which lists to show on home screen"
        holo:title="Lists to Display" />
</PreferenceCategory>
<PreferenceCategory
    holo:key="pref_about_legal"
    holo:title="@string/legal" >
    <Preference
        holo:key="privacy"
        holo:title="@string/privacy" />
    <Preference
        holo:key="terms"
        holo:title="@string/terms_and_conditions" />
</PreferenceCategory>
```

</PreferenceScreen>

Any ideas what the issue could be?

**Comment by Prototik** [comment]
Version of library? 1.2.2?

And: com.pocketwriters.widgets.ListPreferenceMultiSelect extends from com.WazaBe.HoloEverywhere.preference.MultiSelectListPreference?

**Comment by indieboyalex** [comment]
It's on the dev branch, most recent push.

It's extending com.WazaBe.HoloEverywhere.preference.ListPreference

**Comment by Prototik** [comment]
http://i.imgur.com/CZf1c.png

Android 4.0.4, arm6, 256 mb, this is work! :)

Please, full stack trace. You cropped it.

**Comment by indieboyalex** [comment]
Oddly I just took the .ListPreferenceMultiSelect out of the XML and it still fails on ICS

E/AndroidRuntime( 1709): FATAL EXCEPTION: main
E/AndroidRuntime( 1709): android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
E/AndroidRuntime( 1709):        at android.view.LayoutInflater.createView(LayoutInflater.java:613)
E/AndroidRuntime( 1709):        at com.WazaBe.HoloEverywhere.LayoutInflater.onCreateView(LayoutInflater.java:136)
E/AndroidRuntime( 1709):        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
E/AndroidRuntime( 1709):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
E/AndroidRuntime( 1709):        at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
E/AndroidRuntime( 1709):        at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
E/AndroidRuntime( 1709):        at com.WazaBe.HoloEverywhere.preference.Preference.onCreateView(Preference.java:473)
E/AndroidRuntime( 1709):        at com.WazaBe.HoloEverywhere.preference.Preference.getView(Preference.java:360)
E/AndroidRuntime( 1709):        at com.WazaBe.HoloEverywhere.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:162)
E/AndroidRuntime( 1709):        at android.widget.AbsListView.obtainView(AbsListView.java:2267)
E/AndroidRuntime( 1709):        at android.widget.ListView.makeAndAddView(ListView.java:1769)
E/AndroidRuntime( 1709):        at android.widget.ListView.fillDown(ListView.java:672)
E/AndroidRuntime( 1709):        at android.widget.ListView.fillFromTop(ListView.java:733)
E/AndroidRuntime( 1709):        at android.widget.ListView.layoutChildren(ListView.java:1622)
E/AndroidRuntime( 1709):        at android.widget.AbsListView.onLayout(AbsListView.java:2102)
E/AndroidRuntime( 1709):        at android.view.View.layout(View.java:13754)
E/AndroidRuntime( 1709):        at android.view.ViewGroup.layout(ViewGroup.java:4362)
E/AndroidRuntime( 1709):        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
E/AndroidRuntime( 1709):        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
E/AndroidRuntime( 1709):        at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
E/AndroidRuntime( 1709):        at android.view.View.layout(View.java:13754)
E/AndroidRuntime( 1709):        at android.view.ViewGroup.layout(ViewGroup.java:4362)
E/AndroidRuntime( 1709):        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
E/AndroidRuntime( 1709):        at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1638)
E/AndroidRuntime( 1709):        at android.widget.LinearLayout.onLayout(LinearLayout.java:1422)
E/AndroidRuntime( 1709):        at android.view.View.layout(View.java:13754)
E/AndroidRuntime( 1709):        at android.view.ViewGroup.layout(ViewGroup.java:4362)
E/AndroidRuntime( 1709):        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
E/AndroidRuntime( 1709):        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
E/AndroidRuntime( 1709):        at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
E/AndroidRuntime( 1709):        at android.view.View.layout(View.java:13754)
E/AndroidRuntime( 1709):        at android.view.ViewGroup.layout(ViewGroup.java:4362)
E/AndroidRuntime( 1709):        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AndroidRuntime( 1709):        at android.view.View.layout(View.java:13754)
E/AndroidRuntime( 1709):        at android.view.ViewGroup.layout(ViewGroup.java:4362)
E/AndroidRuntime( 1709):        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
E/AndroidRuntime( 1709):        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
E/AndroidRuntime( 1709):        at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
E/AndroidRuntime( 1709):        at android.view.View.layout(View.java:13754)
E/AndroidRuntime( 1709):        at android.view.ViewGroup.layout(ViewGroup.java:4362)
E/AndroidRuntime( 1709):        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AndroidRuntime( 1709):        at android.view.View.layout(View.java:13754)
E/AndroidRuntime( 1709):        at android.view.ViewGroup.layout(ViewGroup.java:4362)
E/AndroidRuntime( 1709):        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1866)
E/AndroidRuntime( 1709):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1687)
E/AndroidRuntime( 1709):        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
E/AndroidRuntime( 1709):        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4212)
E/AndroidRuntime( 1709):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
E/AndroidRuntime( 1709):        at android.view.Choreographer.doCallbacks(Choreographer.java:555)
E/AndroidRuntime( 1709):        at android.view.Choreographer.doFrame(Choreographer.java:525)
E/AndroidRuntime( 1709):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
E/AndroidRuntime( 1709):        at android.os.Handler.handleCallback(Handler.java:615)
E/AndroidRuntime( 1709):        at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 1709):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 1709):        at android.app.ActivityThread.main(ActivityThread.java:4745)
E/AndroidRuntime( 1709):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1709):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 1709):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime( 1709):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 1709):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1709): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 1709):        at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime( 1709):        at java
W/ActivityManager(  157):   Force finishing activity com.pocketwriters/.SettingsActivity

**Comment by Prototik** [comment]
Like anything strange ... And what theme is activity?

**Comment by indieboyalex** [comment]
Right I just took paired the preferencex.xml down to:

<?xml version="1.0" encoding="utf-8"?>
<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:holo="http://schemas.android.com/apk/res-auto" >

```
<PreferenceCategory
    holo:key="pref_about_legal"
    holo:title="@string/legal" >
    <Preference
        holo:key="privacy"
        holo:title="@string/privacy" />
    <Preference
        holo:key="terms"
        holo:title="@string/terms_and_conditions" />
</PreferenceCategory>
```

</PreferenceScreen>

And it still fails to launch - which it did before I moved over to the holo namespace.

The theme is a custom one extending @style/Holo.Theme.Sherlock.Light.DarkActionBar - ahhh, can you give me a couple of minutes I may have an explanation - just want to run a quick test!

**Comment by indieboyalex** [comment]
I think it's a non-error. I have the paired down version working and it was to do with the theme.  Eclipse had helpfully added v-11 and v-14 theme overrides for me which hadn't been updated, so when I changed NS I assume that broke everything.

---

Yep, the Activity will now launch thanks to the theme change.  But we now have an additional error.  I'll post the logcat in a second....

**Comment by indieboyalex** [comment]
OK, so the SPreferenceActivity will now launch - which is a good thing.

However, when I click on either of the ListPreferences I crash again. This is the trace from the first standard ListPreference:

E/AndroidRuntime( 2737): FATAL EXCEPTION: main
E/AndroidRuntime( 2737): android.view.InflateException: Binary XML file line #100: Error inflating class <unknown>
E/AndroidRuntime( 2737):        at android.view.LayoutInflater.createView(LayoutInflater.java:613)
E/AndroidRuntime( 2737):        at com.WazaBe.HoloEverywhere.LayoutInflater.onCreateView(LayoutInflater.java:139)
E/AndroidRuntime( 2737):        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
E/AndroidRuntime( 2737):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
E/AndroidRuntime( 2737):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
E/AndroidRuntime( 2737):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
E/AndroidRuntime( 2737):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
E/AndroidRuntime( 2737):        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
E/AndroidRuntime( 2737):        at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
E/AndroidRuntime( 2737):        at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
E/AndroidRuntime( 2737):        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:256)
E/AndroidRuntime( 2737):        at com.WazaBe.HoloEverywhere.internal.AlertController.installContent(AlertController.java:451)
E/AndroidRuntime( 2737):        at com.WazaBe.HoloEverywhere.app.AlertDialog.onCreate(AlertDialog.java:340)
E/AndroidRuntime( 2737):        at android.app.Dialog.dispatchOnCreate(Dialog.java:351)
E/AndroidRuntime( 2737):        at android.app.Dialog.show(Dialog.java:256)
E/AndroidRuntime( 2737):        at com.WazaBe.HoloEverywhere.preference.DialogPreference.showDialog(DialogPreference.java:275)
E/AndroidRuntime( 2737):        at com.WazaBe.HoloEverywhere.preference.DialogPreference.onClick(DialogPreference.java:147)
E/AndroidRuntime( 2737):        at com.WazaBe.HoloEverywhere.preference.Preference.performClick(Preference.java:535)
E/AndroidRuntime( 2737):        at com.WazaBe.HoloEverywhere.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:105)
E/AndroidRuntime( 2737):        at android.widget.AdapterView.performItemClick(AdapterView.java:298)
E/AndroidRuntime( 2737):        at android.widget.AbsListView.performItemClick(AbsListView.java:1086)
E/AndroidRuntime( 2737):        at android.widget.AbsListView$PerformClick.run(AbsListView.java:2855)
E/AndroidRuntime( 2737):        at android.widget.AbsListView$1.run(AbsListView.java:3529)
E/AndroidRuntime( 2737):        at android.os.Handler.handleCallback(Handler.java:615)
E/AndroidRuntime( 2737):        at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 2737):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 2737):        at android.app.ActivityThread.main(ActivityThread.java:4745)
E/AndroidRuntime( 2737):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2737):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 2737):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime( 2737):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 2737):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 2737): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 2737):        at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime( 2737):        at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
E/AndroidRuntime( 2737):        at android.view.LayoutInflater.createView(LayoutInflater.java:587)
E/AndroidRuntime( 2737):        ... 31 more
E/AndroidRuntime( 2737): Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f010067 a=2}
E/AndroidRuntime( 2737):        at android.content.res.Resources.loadDrawable(Resources.java:1892)
E/AndroidRuntime( 2737):        at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
E/AndroidRuntime( 2737):        at android.view.View.<init>(View.java:3336)
E/AndroidRuntime( 2737):        at android.widget.TextView.<init>(TextView.java:447)
E/AndroidRuntime( 2737):        at android.widget.Button.<init>(Button.java:107)
E/AndroidRuntime( 2737):        at android.widget.Button.<init>(Button.java:103)
E/AndroidRuntime( 2737):        ... 34 more
W/ActivityManager(  157):   Force finishing activity com.pocketwriters/.SettingsActivity

**Comment by Prototik** [comment]
```
E/AndroidRuntime( 1709): at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
E/AndroidRuntime( 1709): at com.WazaBe.HoloEverywhere.preference.Preference.onCreateView(Preference.java:473)
```

Stop, why? Should use com.WazaBe.HoloEverywhere.LayoutInflater

**Comment by indieboyalex** [comment]
I would have thought so.  I've not done anything fancy in the SPreferenceActivity I'm using.  It works on the old versions, just not on Android 4+

**Comment by Prototik** [comment]
@iNdieboyjeff differences in the library contains only one folder - values-v14. try to remove it and say the result.

And another thing: open R.java your application and say that the resource is hidden by id 0x7f010067

**Comment by indieboyalex** [comment]
I assume you mean the v14 folder from the HoloEverywhere library?

In My R.java 0x7f010067 refers to public static final int selectableItemBackground

**Comment by Prototik** [comment]
yes, from library.

**Comment by indieboyalex** [comment]
Yes I remove values-v14 and it works :D

You are a STAR!  :D

**Comment by Prototik** [comment]
i forgot specify attributes selectableItemBackground, borderlessButtonStyle, segmentedButtonStyle for light styles :-/

Thanks for find bug! :D

**Comment by Prototik** [comment]
You may update lib from dev branch, i fix it.

**Comment by indieboyalex** [comment]
Thanks.

It's funny that I found a genuine bug as a result of me being stupid with my use of theme overrides.  Every cloud has a silver lining.

And thanks for the library.  It is amazingly useful.

**Comment by Prototik** [comment]
Say thank Christophe - if not for his project, something like that I would not do that.
Oh and one person from the 4pda forum, who showed me this project.

**Comment by indieboyalex** [comment]
Well a big thanks to Christophe, and everyone involved in the project and it's support.  It's a fine example of what can be done to benefit the community.

**Comment by Prototik** [comment]
Okay, I'm tired today :D I'll sleep for a change...

~~Good night!~~ Thanks everyone for help, test and development!
