### ISSUE TITLE
Dialog crashes when using Light Theme on ICS, JB

### ISSUE THREAD

**Issue by sheharyarn** [Prototik/HoloEverywhere#82]
The Dialog works perfectly for both themes in Android 2.x.x but in Android 4.x.x, the Dialog crashes if we're using Holo.Theme.Sherlock.Light

**Comment by Prototik** [comment]
Fixed in dev version two days ago.

**Comment by Prototik** [comment]
No, it's not fixed, i'm sorry:)

**Comment by Prototik** [comment]
Fixed in current dev version
