### ISSUE TITLE
Transparant status bar on Android Kitkat (4.4.2) platform

### ISSUE THREAD

**Issue by RichardLindhout** [Prototik/HoloEverywhere#821]
These two are not working at the moment?
It would be great if you could make it work in the future!

<item name="windowTranslucentNavigation">true</item>
<item name="windowTranslucentStatus">tre</item>

**Comment by Prototik** [comment]
It's feature of system-ui, not applications.
Impossible.

**Comment by RichardLindhout** [comment]
It is possible with windowstrancslucent or something in your themes (i added it but github removed the markup somehow)

See example apps at ->
http://forum.xda-developers.com/showthread.php?t=2623461

**Comment by RichardLindhout** [comment]
better article
http://forum.xda-developers.com/nexus-4/themes-apps/kitkat-immersive-transparent-mode-apps-t2575236/post48607416

**Comment by RichardLindhout** [comment]
Here you go - http://developer.android.com/about/versions/android-4.4.html#UI

Translucent system bars

You can now make the system bars partially translucent with new themes, Theme.Holo.NoActionBar.TranslucentDecor and Theme.Holo.Light.NoActionBar.TranslucentDecor. By enabling translucent system bars, your layout will fill the area behind the system bars, so you must also enable fitsSystemWindows for the portion of your layout that should not be covered by the system bars.

If you're creating a custom theme, set one of these themes as the parent theme or include the windowTranslucentNavigation and windowTranslucentStatus style properties in your theme.

**Comment by Prototik** [comment]
Again: it's not possible to make a status bar a transparent. Action bar - yes, but not status.

**Comment by RichardLindhout** [comment]
Hmmm? see this app -> https://play.google.com/store/apps/details?id=com.klinker.android.twitter
And one of the screenshots the 6th i think

You really are wrong now it is really possible in android 4.4 could you make it work I mean i don't need backward compitablity but it would be great if you could support the windowtransluscentstatusbar or something to add in your custom theme.

https://lh4.ggpht.com/zm9vwlmeM6d-8lCyWITMl7P2ywEUZNFE7KYzUwqgON7wl29RVEMrAhEtHJbCEMhenNM=h900-rw

**Comment by BraisGabin** [comment]
@RichardLindhout if you want it only for 4.4.2 it's possible but it's not a HoloEverywhere feature. Override the theme in `values-v19` and add `<item name="android:windowTranslucentStatus">true</item>`.

**Comment by Prototik** [comment]
Create your own theme and put attrs windowTranslucentNavigation/windowTranslucentStatus = true.
HoloEverywhere is backward-compitablity library, all features should be available for all versions.

**Comment by RichardLindhout** [comment]
Ah great that was what I ment!! Sorry yeah you're right

I'll look after it when I'm home, I'm at school now.
