### ISSUE TITLE
Could not find property 'configuration' on org.holoeverywhere.plugin.extension.HoloEverywhereExtension

### ISSUE THREAD

**Issue by boonkerz** [Prototik/HoloEverywhere#822]
Error:A problem occurred configuring project ':mec'.

> Could not find property 'configuration' on org.holoeverywhere.plugin.extension.HoloEverywhereExtension_Decorated@26fc1552.

After Update Android Studio

**Comment by Prototik** [comment]
Plugin version?

Try to invoke `./gradlew --refresh-dependencies clean build` first.

**Comment by boonkerz** [comment]
Thx
