### ISSUE TITLE
Drawer using Slider Addon is always open in Tablets

### ISSUE THREAD

**Issue by hichamboushaba** [Prototik/HoloEverywhere#836]
Hi All,

I know that this project is discontinued, but I have a question that I hope I will have some help from you.
The slider is always open in Tablets in landscape mode. Can I configure it to automatically hiding?

Thanks,

**Comment by Prototik** [comment]
Yep, you can change this behavior by providing custom slider layout.
Or just delete `//addons/slider/res/layout-w720dp/slider_default_layout.xml` and rebuild your app, then drawer will have no difference between phone and tablet.

**Comment by hichamboushaba** [comment]
Thank you very much, it's working
