### ISSUE TITLE
Repo down

### ISSUE THREAD

**Issue by croccio** [Prototik/HoloEverywhere#843]
Repository is down. Compilation project failed because cannot find this repo/lib

**Comment by boonkerz** [comment]
Same Issue what can i do?

**Comment by Prototik** [comment]
@boonkerz Nothing, repo is temporary down. You could bind plugin to your own repo with precompiled version of library.

**Comment by Prototik** [comment]
Repo is up.

**Comment by apollo1234** [comment]
@Prototik Thanks.
