### ISSUE TITLE
How to change AutoCompleteTextView border color of default theme in android?

### ISSUE THREAD

**Issue by larrymeng** [Prototik/HoloEverywhere#849]
I am using AutoCompleteTextView in my android application. I am using Theme.Light as my default theme for my application.

Here is how my AutoCompleteTextView look like 
http://stackoverflow.com/questions/14378511/how-to-change-autocompletetextview-border-color-of-default-theme-in-android

Now, I want to change the BLUE color border of that AutoCompleteTextView to some other color ,for different selection, keeping the border style as it as. I dont want full border. How to do that?

**Comment by BraisGabin** [comment]
How is this question related with HoloEverywhere? 

Anyway I just answered this question in SO. You can check it.

**Comment by larrymeng** [comment]
I use HoloEverywhere in my project. 
And I use AutoCompleteTextView in the code.

I want to change the color of border in AutoCompleteTextView from blue to green.
But I have not idea.

So, I explore for help.

**Comment by Prototik** [comment]
@larrymeng AutoCompleteTextView is extended EditText, so all ways for styling basic EditText applicable for ACTV too. You can colorize default blue background and apply new background for widget via styles or layout.

**Comment by larrymeng** [comment]
Thanks Prototik.
I have tried to do that. But there will exists 4 sided border in AutoCompleteTextView.

How to Achieve this effect: 
1) only one bottom border exists.
2) change the color of border.

Thanks.
