### ISSUE TITLE
Error inflating class android.widget.DatePicker

### ISSUE THREAD

**Issue by jonasbark** [Prototik/HoloEverywhere#85]
First of a question about the current Dev version:
When do I have to cast my Views to com.WaZabe... and when to android.widget...? Right now it doesn't make any sense to me as on Android 4 Spinners are inflated as com.WaZabe while EditText are inflated as android.widget. It seems to be very inconsistent and would require a lot of work to adapt the current HoloEverywhere version with my app.

Second: 
Line of code:
`DatePickerDialog datePickDiag=new DatePickerDialog(getActivity(), odsl, maxYear, maxMonth, maxDay);`

Stacktrace:
`09-17 01:08:29.999: E/AndroidRuntime(8719): FATAL EXCEPTION: main
09-17 01:08:29.999: E/AndroidRuntime(8719): android.view.InflateException: Binary XML file line #20: Error inflating class android.widget.DatePicker
09-17 01:08:29.999: E/AndroidRuntime(8719):     at android.view.LayoutInflater.createView(LayoutInflater.java:613)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at com.WazaBe.HoloEverywhere.LayoutInflater.onCreateView(LayoutInflater.java:139)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at android.app.DatePickerDialog.<init>(DatePickerDialog.java:108)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at android.app.DatePickerDialog.<init>(DatePickerDialog.java:79)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at com.jaumo.login.Register_Step2$6.<init>(Register_Step2.java:280)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at com.jaumo.login.Register_Step2.openDatePicker(Register_Step2.java:280)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at com.jaumo.login.Register_Step2.onClick(Register_Step2.java:252)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at android.view.View.performClick(View.java:4084)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at android.view.View$PerformClick.run(View.java:16966)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at android.os.Handler.handleCallback(Handler.java:615)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at android.os.Handler.dispatchMessage(Handler.java:92)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at android.os.Looper.loop(Looper.java:137)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at android.app.ActivityThread.main(ActivityThread.java:4939)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at java.lang.reflect.Method.invokeNative(Native Method)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at java.lang.reflect.Method.invoke(Method.java:511)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at dalvik.system.NativeStart.main(Native Method)
09-17 01:08:29.999: E/AndroidRuntime(8719): Caused by: java.lang.reflect.InvocationTargetException
09-17 01:08:29.999: E/AndroidRuntime(8719):     at java.lang.reflect.Constructor.constructNative(Native Method)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at android.view.LayoutInflater.createView(LayoutInflater.java:587)
09-17 01:08:29.999: E/AndroidRuntime(8719):     ... 22 more
09-17 01:08:29.999: E/AndroidRuntime(8719): Caused by: java.lang.ClassCastException: com.WazaBe.HoloEverywhere.widget.CalendarView cannot be cast to android.widget.CalendarView
09-17 01:08:29.999: E/AndroidRuntime(8719):     at android.widget.DatePicker.<init>(DatePicker.java:212)
09-17 01:08:29.999: E/AndroidRuntime(8719):     at android.widget.DatePicker.<init>(DatePicker.java:145)
09-17 01:08:29.999: E/AndroidRuntime(8719):     ... 25 more`

**Comment by Prototik** [comment]
You should cast view to all contains in package com.WazaBe.HoloEverywhere.widget, exclude TextView and LinearLayout. For TV and LL you can use android.widget._, but com.WazaBe.HE.widget._ also has work;

DatePicker - added to todo list.

**Comment by M1cha** [comment]
I have exactly the same problem. I really need a way to pick date(calendarview or datepicker).
It would be great If you have a working example.

**Comment by Prototik** [comment]
@M1cha CalendarView - com.WazaBe.HoloEverywhere.widget.CalendarView or simply CalendarView. Included in 1.2.3. In 1.2.4 will DatePicker(Dialog)

**Comment by Prototik** [comment]
8cc4a920ec7716eabb7a966c83b901e17e3ed76e

**Comment by M1cha** [comment]
Can you give an example on how to use this?
If I use the code from google, nothing happens.
I I create the DatePickerDialog directly without extending DialogFragment, I get an java.lang.NoSuchMethodException for NumberPicker.

**Comment by Prototik** [comment]
Please wait... i'm update demo and fix a bug in DatePicker :) 1.2.4...

**Comment by Prototik** [comment]
OMG... I find next bug: spinners on DatePicker is working... but drawing state not changing. Spinners a freezes. I will work on that:)

**Comment by Prototik** [comment]
Fixed in current dev version

**Comment by M1cha** [comment]
great work :)
but on android 2.1 the numbers hangs between two after first click.
