### ISSUE TITLE
The project is using an unsupported version of the Android Gradle plug-in (0.9.2)

### ISSUE THREAD

**Issue by zeroarst** [Prototik/HoloEverywhere#850]
Hi I pull the code and tried to build it but got error
The project is using an unsupported version of the Android Gradle plug-in (0.9.2)

Not quite sure how to solve it...

**Comment by Prototik** [comment]
Make sure that you have latest version of Android Studio (0.8.11 for now) and latest version of library sources (b870abb for now). I've been successfully import library into studio.
