### ISSUE TITLE
Maven release 1.2.0

### ISSUE THREAD

**Issue by imminent** [Prototik/HoloEverywhere#88]
Is it possible the version on Maven repository has a bug in it? I have errors like:

> app/target/unpack/apklibs/com.github.christopheversieux_holoeverywhere-library_apklib_1.2.0/res/values/styles.xml:482: error: Resource entry Holo.Theme.Sherlock.Light already has bag item android:listChoiceIndicatorSingle.

I looked into that file and it does in fact have `android:listChoiceIndicatorSingle` defined twice in some of the themes, which I think is what is raising the error when I try to build it with Maven.

**Comment by Prototik** [comment]
yes, in 1.2.0 listChoiceIndicatorSingle defined twice. But 1.2.0 - old version, current stable 1.2.3 don't have this bug.

**Comment by imminent** [comment]
The problem is 1.2.0 is the version on Maven repository, hence if you try to add the dependency through Maven repository you're stuck with that bug. Can the repository be updated?

**Comment by Prototik** [comment]
Responsibility for Maven repo - Neoasket and Christophe. Wait for their comments.

Well, you can manually install the 1.2.3 version to the local repository.

**Comment by imminent** [comment]
I know you can manually do it, but they just finally added it to Maven
repository so I thought I would try to switch. Then unfortunately I get let
down my the bug. Side note: I also have ABS dependency, what exactly has to
change for 1.2.3? I saw a note that seemed to say that you couldn't use
normal ABS with 1.2.3, but then it seemed to say you could, but something
about tabs.

**Comment by Prototik** [comment]
Yes, if you use standart ABS - you lose support tabs.
See https://github.com/ChristopheVersieux/ActionBarSherlock/commit/0584a38a342b9bc95156c56c07304b04f8adedd4

**Comment by neoasket** [comment]
@imminent I've sent request to @JakeWharton asking him to release ABS 4.1.0.1 with Tabs fix
if he accepts we'll update HE's dependency and push it to Maven central

**Comment by imminent** [comment]
@neoasket awesome, I hope he does it soon. Good work getting it on Maven central by the way.

**Comment by neoasket** [comment]
@imminent
I received the answer from @JakeWharton just now:
"4.2 will be released in the next week or so."

let's be patient (:

**Comment by DenisMir** [comment]
What does "you lose tabs support" mean in this context? If we use HE 1.2.3 we lose the support of styled tabs or what does it mean?

**Comment by Prototik** [comment]
@annoma getSupportActionBar().addTab().
In TabListener FragmentTransaction will be null.

**Comment by DenisMir** [comment]
Ok. So we have to wait for ABS 4.2 or fix it ourselves in ABS. (or not updating HE)

**Comment by imminent** [comment]
Yeah @annoma, for the time being I'm going with not updating HE.

**Comment by neoasket** [comment]
https://twitter.com/JakeWharton/status/253878524639854592

**Comment by imminent** [comment]
Nice, @JakeWharton, just a little longer for ABS 4.2 then.

**Comment by imminent** [comment]
I see the preparation for the next release (1.3) looks like it is compatible with ABS 4.2, @neoasket. Are there any last minute issues to resolve before it can be released? Or will the release be pushed soon?

**Comment by Jaumo** [comment]
Will you push the 1.3.1 release to maven? This would be very helpful. The current version there is still 1.2.0 http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22holoeverywhere-library%22

**Comment by Prototik** [comment]
Yes, 1.3.1 will be pushed to maven. Soon. Serious.

**Comment by Jaumo** [comment]
Great, thank you!

**Comment by neoasket** [comment]
1.3.1 will be pushed on Sunday

**Comment by ChristopheVersieux** [comment]
I worked on the push of 1.3.1 today, but had serious issues.
I have to leave now and will try again tomorrow (9AM Belgian time)

Thank a lot to neoasket for his precious help

**Comment by agarwlGaurav** [comment]
Any updates on pushing version 1.3.x to Maven Central.

**Comment by Prototik** [comment]
1.3.3 pushed just now. Will be available in a couple of hours.
