### ISSUE TITLE
Publish HoloEverywhere.apklib's maven repository

### ISSUE THREAD

**Issue by yuki24** [Prototik/HoloEverywhere#9]
I love HoloEverywhere and thank you for the great project. But currently the instruction is only available for Eclipse. Please publish this in a maven repository so that we could leverage the dependency tools in maven/sbt.

**Comment by ChristopheVersieux** [comment]
Hello,

I would be pleased to add a maven repository, but unfortunately, I am 
not familiar at all with this...
I will be honest, I have even no idea about what this is...

I am just a passionate that develops Android after my main job, during 
free time...

Feel free to send me links and/or documentation and I will see what I 
can do.

Regards

Christophe

**Comment by bartoszgadzala** [comment]
Hi,

Maven is a project management tool - http://maven.apache.org/what-is-maven.html. It handles (among other things) dependency resolution. In maven each artifact is stored in maven repository (http://maven.apache.org/guides/introduction/introduction-to-repositories.html). Many Android libraries (for example ActionBarSherlock) are available as maven artifacts which allows to consume them in projects which are maven driven.

To mavenize project you will need to add pom.xml (Project Object Model) which holds all project metadata. If I'll find some free time, I'll try to create apropriate pom.xml and send you a pull request.

Best regards
Bartek

**Comment by yuki24** [comment]
@bartoszgadzala +1, awesome work!

**Comment by ChristopheVersieux** [comment]
Thank a lot!

**Comment by Berglund** [comment]
@ChristopheVersieux are you planning on putting HoloEverywhere in the maven repositories? It'd solve a lot of my problems!

**Comment by bartoszgadzala** [comment]
You can upload it to Sonatype OSSRH - more details at https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide. According to documentation, they're requiring a 'licenses' element (see http://maven.apache.org/pom.html#Licenses for details ), but it should be trivial to add it. I hope it will be helpfull.

**Comment by ChristopheVersieux** [comment]
I am working on it: https://issues.sonatype.org/browse/OSSRH-3390

Will add the license when coming back home this evening...

**Comment by Berglund** [comment]
Great work!

On 24 April 2012 13:48, Christophe Versieux <
reply@reply.github.com

> wrote:
> 
> I am working on it: https://issues.sonatype.org/browse/OSSRH-3390
> 
> Will add the license when coming back home this evening...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/ChristopheVersieux/HoloEverywhere/issues/9#issuecomment-5302671

## 

Joakim Berglund

**Comment by bartoszgadzala** [comment]
Hi,

any news or problems in which we can help?

**Comment by ChristopheVersieux** [comment]
I am still working on it but I paused a little bit the dev last month.
Will go back to this project on saturday..

Would be nice if we could discuss by email rather than chattinge here, can you contact send me an email so I can tell you, Bartosz?

**Comment by imminent** [comment]
Has the project been added to a maven repository yet? It looks like the [sonatype issue](https://issues.sonatype.org/browse/OSSRH-3390?focusedCommentId=156734&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-156734) was resolved

**Comment by stephanenicolas** [comment]
I agree, it would a very nice feature to have holoeverywhere added to the central maven repo. It can look strange not to only provide the lib for the classic ADT+Eclipse, but maven support in android is getting more and more mature and popular. Please support this effort by adding an apklib + jar for maven users.

**Comment by connorbrinton** [comment]
Any update on when/if the HoloEverywhere library is going to be added to the central maven repo? I would love to add HoloEverywhere to a project I contribute to, but we require all of our dependencies to be managed by Maven.

I'm getting a little bit tired of copy-pasting from /opt/android-sdk-linux/platforms/android-16/data/res/drawable-\* into our project :) HoloEverywhere makes it sooooo much easier!

**Comment by ChristopheVersieux** [comment]
+imminent, yes the issue seems closed, but I have no idea what are the next steps. I am not familiar at all with maven world.

**Comment by goober** [comment]
As @bartoszgadzala mention there is a user guide which describes how you deploy your artifacts to the maven repository.

https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide

As of my understanding you have created a ticket and got the credentials. So if you read from section 7 and forward I think you can get an understanding for how you should proceed.

**Comment by stephanenicolas** [comment]
Bonne chance Christophe, ce serait bien que ta lib soit sur maven.

Tu as vu le nouveau site holo colors ? C'est un collègue qui le publie, si
tu VX linker....

S.
 Le 4 sept. 2012 16:21, "Mathias Åhsberg" notifications@github.com a
écrit :

**Comment by Rutton** [comment]
I also would like to see HE in a Maven repository. Its great to use for our own app. And as this app is open source, we host our own HE jar/apklib on github. But a central one would be really great.

**Comment by ChristopheVersieux** [comment]
Thanks to @neoasket I succeed to sync it: https://oss.sonatype.org/content/groups/public/com/github/christopheversieux/

**Comment by neoasket** [comment]
you could add to your poms:

``` bash
            <dependency>
                <groupId>com.github.christopheversieux</groupId>
                <artifactId>holoeverywhere-library</artifactId>
                <version>${holoeverywhere-library.version}</version>
                <type>apklib</type>
            </dependency>
```
