### ISSUE TITLE
Views always rendered with ARGB_8888

### ISSUE THREAD

**Issue by PatteSMO** [Prototik/HoloEverywhere#91]
Changing from using the style Theme.Sherlock.Light.DarkActionBar to Holo.Theme.Sherlock.Light.DarkActionBar causes views to be rendered using ARGB_8888 instead of the default.

On Android 2.2 (< 2.3?), where this would've been something else (ARGB_565?), the performance is decreased largely on some devices. On devices running 2.3 or higher this does not affect anything.

It could also be a question of dithering/no dithering. 

I haven't found the cause of this, but I'd be forever thankful if this could be fixed, so it uses the default value instead.

**Comment by Prototik** [comment]
Well,. It's not HE bug.
May be, ABS or specify ROM...
But I try find root cause.

**Comment by PatteSMO** [comment]
Did some further testing when you said it could be ABS;

Removed ABS from activity -> Same problem.
Removed SlidingMenu from activity -> Same problem.

"@android:style/Theme.Light" was used as the un-dithered theme during testing.

Unfortunately, my only 2.2 testing device is an Optimus 2X, so I can't tell if it's caused by the ROM or something else. I will give it a try in the emulator and see if the problem occurs there too.

EDIT:
After emulator tests including screenshotting I can confirm that using the HoloEverywhere style Holo.Theme.Light instead of the android style Theme.Light makes the whole app dithered. This dithering is resulting in the performance loss.

**Comment by PatteSMO** [comment]
More testing showed that the window background was causing the problem. Commenting the following line solves this issue.

```
<item name="android:windowBackground">@drawable/background_holo_light</item>
```

**Comment by Prototik** [comment]
It bug shows only on light theme?

**Comment by PatteSMO** [comment]
It has to do with the windowBackground property, so I guess that applies for every theme.

**Comment by Prototik** [comment]
Well, may be alpha channel?
Try to replace in background_holo_*.xml next content:

```
        android:endColor="#ff272D33"
        android:startColor="#ff020202"
```

on this:

```
        android:endColor="#272D33"
        android:startColor="#020202"
```

**Comment by PatteSMO** [comment]
Will try that when I get home (in ~ 40 min) and report the results, thank you.

**Comment by PatteSMO** [comment]
Unfortunately, it did not help. Same problem with or without the "fake" alpha.

**Comment by Prototik** [comment]
You may force set pixel format for window:
getWindow().getAttributes().format = PixelFormat.RGB_565; or other PixelFormat

**Comment by PatteSMO** [comment]
However, that creates problem with devices that are capable of rendering ARGB_8888 with high performance. I think I'll just stick to just skipping the background, it's the easiest solution for me ;)

**Comment by Prototik** [comment]
May be... I will be think on this problem.
