### ISSUE TITLE
Update Market Demo

### ISSUE THREAD

**Issue by kevsmt** [Prototik/HoloEverywhere#92]
Please update market demo with current release. please.. with ABS and without ABS, please do release the source of both.

**Comment by Prototik** [comment]
When @ChristopheVersieux has been return from vacation - he is update demo.
But version without ABS is not planned.
May be in future...

**Comment by kevsmt** [comment]
@Prototik w/o ABS is fine.. Do you have a current apk compiled with the current version that we can try right now?

**Comment by Prototik** [comment]
@kevsmt 1.2.3 or dev version? They're different like a chicken and a dinosaur.

**Comment by kevsmt** [comment]
1.2.3 pls :)

**Comment by Prototik** [comment]
... I'm compiled dev version :D
I am reluctant to switch between branches.
http://ubuntuone.com/5V92aLdQkHyS40ndhwiMFo

Before install uninstall the older version, signed by different keys.

**Comment by kevsmt** [comment]
:) Thanks alot @Prototik .. i wish this can be included on each release.

**Comment by Prototik** [comment]
With 1.2.4 project will has a small web-page... And there may well be put demo APK... Everything is possible.

**Comment by kevsmt** [comment]
@Prototik, i will issue some bugs i found. And yes, very much appreciated this effort and to you, big thanks for the updates.. looks great!
