### ISSUE TITLE
[Branch: dev] Calendar

### ISSUE THREAD

**Issue by kevsmt** [Prototik/HoloEverywhere#93]
Randomly, when you flick down on calendar, you cant flick/scroll down, you have to flick down and flick up will work.

Phone Details:

Build: GINGERBREAD
Android: 2.3.6 
Kernel: 2.6.35.7
Device: GT-S5360 Galaxy Y

**Comment by Prototik** [comment]
I don't can repeat this bug. You may make a video?

**Comment by kevsmt** [comment]
Yes i will submit a video for you soon.. i only got 1 phone right now..
