### ISSUE TITLE
[Branch: dev] Date Picker

### ISSUE THREAD

**Issue by kevsmt** [Prototik/HoloEverywhere#94]
Date Picker wont scroll the lists, Month, Day and Year.  Although dialog title changes.

Phone Details:

Build: GINGERBREAD
Android: 2.3.6 
Kernel: 2.6.35.7
Device: GT-S5360 Galaxy Y

**Comment by Prototik** [comment]
Which version of Android used?

**Comment by indieboyalex** [comment]
I'm having the same issue on a DatePicker widget in an ordinary activity layout.

**Comment by Prototik** [comment]
DatePicker is very strange.
I'll rewrite it to maintain compatibility with the old API.
