### ISSUE TITLE
Broken AutoCompleteTextView

### ISSUE THREAD

**Issue by svenporto** [Prototik/HoloEverywhere#95]
At first, I got regular basic Android style AutoCompleteTextView. Then I saw that AutoCompleteTextView in Holo is commented so I uncommented it.

Line 618 `<item name="android:autoCompleteTextViewStyle">@style/Holo.AutoCompleteTextView</item>`

Then everything is ok except I have black text color on dark grey background (barely visible). I tried chaning text color inside `<item name="android:completionHintView">@layout/simple_dropdown_hint</item>` to visible light blue but didn't help. It stayed black.

**Comment by Prototik** [comment]
Is autoCompleteTextViewStyle commented - than it don't supported in this moment.
Wait for full support.

**Comment by svenporto** [comment]
What exactly is not supported yet? For me It's working and looking just fine with little modifications (`simple_dropdown_hint.xml`) on Android 2.2. Is there a approximate date when it should be fully supported?

**Comment by Prototik** [comment]
@svenkapudija A couple of hours appears in dev branch, respectively, will be at Stable 1.2.4
