### ISSUE TITLE
Vertical button divider missing from alert dialogs in Holo light

### ISSUE THREAD

**Issue by ChrisDavis8** [Prototik/HoloEverywhere#96]
No sure if its related but if I open the main.xml of the demo in the layout designer I get the error

java.lang.NumberFormatException: Color value '?dividerVertical' must start with #

**Comment by Prototik** [comment]
1. You should use theme Holo.Theme.*** in designer.
2. Designer can't display the layout for custom elements (at least, that the layout that is in the dev branch.)

**Comment by ChrisDavis8** [comment]
ah yes that fixes the designer sorry got mixed up with Theme.Holo/ Holo.theme.

 Still have the problem with no divider showing on 2.x devices I am wondering do I need to be on the dev branch of actionbarsherlock?

**Comment by PatteSMO** [comment]
I can confirm that the vertical divider isn't showing up on Android 2.x.

**Comment by Prototik** [comment]
We are talking about exactly the same?
If so, I was like you did not understand. Can you take screenshots?

**Comment by PatteSMO** [comment]
Only have a 4.x device with me, but I pointed out the vertical divider with an arrow. This divider is invisible (or probably just some alpha variant of white) on 2.x devices. 

Screenshot: https://docs.google.com/file/d/0B4zruXZsxrs4eDRNd2k4RnJ2YkU/edit

**Comment by PatteSMO** [comment]
Edit: Can't make Drive file public from mobile, please use this dropbox link instead http://db.tt/qvd6sUsX

**Comment by Prototik** [comment]
![Screen](http://ubuntuone.com/31HVeso6iPb4nfD4xCUTih)
Android 2.1.

**Comment by PatteSMO** [comment]
What happens if you're using a two button AlertDialog instead of a three button one?

**Comment by Prototik** [comment]
![Screen](http://ubuntuone.com/74Fc8pNzMqYpU68QAjV50i)

**Comment by PatteSMO** [comment]
Strange, are you using Holo.Theme.White or the ABS equivalent?

**Comment by Prototik** [comment]
ThemeManager resolve theme to Holo.Theme.Sherlock.Light.Fullscreen

**Comment by Prototik** [comment]
Also, it's dev version. May be, this bug only in 1.2.3?

**Comment by PatteSMO** [comment]
Judging by the content of the online styles.xml file there shouldn't be a problem with the divider color. I will do some testing on this again later today.

**Comment by Prototik** [comment]
Well, bug not confirmed. Close.

**Comment by PatteSMO** [comment]
I found that changing this tag to "com.WazaBe.HoloEverywhere.widget.LinearLayout" solved the problem.
https://github.com/ChristopheVersieux/HoloEverywhere/blob/master/library/res/layout/alert_dialog_holo.xml#L94

Note that the end tag must be replaced as well.

**Comment by Prototik** [comment]
@PatteSMO LinearLayout already inflate <LinearLayout> as com.WazaBe.HoloEverywhere.widget.LinearLayout

**Comment by PatteSMO** [comment]
I expected that behaviour too, but the LG Optimus 2X beside me proofs it inflated the default android.widget.LinearLayout instead.

**Comment by ChrisDavis8** [comment]
I have now found this is not a problem if I use the correct sherlock fork. Might be worth mentioning that on the front page as its not obvious

**Comment by PatteSMO** [comment]
@ChrisDavis8 Does that mean I have to change from using ActionbarSherlockActivity directly to using the one in com.WazaBe.HoloEverywhere.sherlock?

**Comment by ChrisDavis8** [comment]
actually I'm not sure about all that I just finally got the demo running as I was linking to standard ABS before and saw that the alert dialog worked. Still need to try doing the same in my own app when time allows.  

At a guess I would think it is something to do with using the holo layout inflater but with all the changes that went into this latest release I am not sure how it all works now. Perhaps a few words from the devs could help clarify things

**Comment by PatteSMO** [comment]
Turns out I had to extend SActivity, but I must agree that it's far from obvious. For my adapters I had to wrap the views around FontLoader.apply(), but that was more obvious once you got into the "replace every possible class" thinking :)

**Comment by Prototik** [comment]
Okay, I supplement the readme in next version, many people have some questions to highlight it.
