### ISSUE TITLE
Cant deselect preselected items on multi choice selection alert dialog

### ISSUE THREAD

**Issue by ChrisDavis8** [Prototik/HoloEverywhere#99]
If you pass in the array of booleans for the already selected items then they are marked as checked correctly. However these items then cannot be unchecked

**Comment by Prototik** [comment]
It's standart behavior of AlertDialog.
You may create android.app.AlertDialog and sure.

**Comment by ChrisDavis8** [comment]
ah so it is, sorry I didn't realise.
